### ISSUE TITLE
如何自定义toolbar按钮并实现功能呢？

### ISSUE THREAD

**Issue by hbynlsl** [imzbf/md-editor-v3#10]
比如，要添加 字体颜色功能，如何添加一个自定义toolbar按钮呢？并扩展实现这个功能呢？

**Comment by hbynlsl** [comment]
多谢了，希望早日加入这个功能。
另一个问题，highlightCss 这个属性（代码高亮），应该传递什么值呢？默认是 atom-one-dark ，我传入 atom-one-light 或者 http://...../atom-one-light.min.css ，都不起作用。

**Comment by imzbf** [comment]
> 多谢了，希望早日加入这个功能。
> 另一个问题，highlightCss 这个属性（代码高亮），应该传递什么值呢？默认是 atom-one-dark ，我传入 atom-one-light 或者 http://...../atom-one-light.min.css ，都不起作用。

这个功能只能修改代码内容的颜色，目前不能修改代码块的背景颜色（黑色），关于`markdown`文档主题，目前正在开发。现在如果需要修改，你需要通过`.md-preview > pre`选择器进行覆盖样式。

**Comment by hbynlsl** [comment]
多谢回复
