### ISSUE TITLE
因为远程文件访问不到 导致 ，渲染失败。

### ISSUE THREAD

**Issue by HaoZhiYing** [imzbf/md-editor-v3#101]
![image](https://user-images.githubusercontent.com/14025507/169843819-06faf290-5e43-4c73-a9ad-66b092ae51d1.png)

**Comment by imzbf** [comment]
2.x已经替换了这些配置，并且1.x、2.x都支持手动配置这些链接的，1.x的文档看一下v1分支

**Comment by HaoZhiYing** [comment]
为啥不将这几个文件配置到本地呢？这样在没有网络情况下也能用

**Comment by imzbf** [comment]
注意看一下文档，1.x和2.x都支持使用本地实例，自行安装配置，就不会请求网络资源。
