### ISSUE TITLE
希望只读模式增加是否点击浏览图片的开关

### ISSUE THREAD

**Issue by abu3389** [imzbf/md-editor-v3#102]
1.0时通过自定义指令写了一个浏览图片的方式，升级2.0后，想保留原有浏览方式，但与目前浏览图片冲突。。。会打开两次，暂时将该样式进行了隐藏。。。

**Comment by imzbf** [comment]
这个这边考虑一下，目前一定需要升级的话，建议先注释一下原来的代码，下一版还需要点时间

**Comment by rp-lab** [comment]
这个功能大赞

**Comment by imzbf** [comment]
2.1.0只会对文章中带`zoom`属性的图片放大，只需要这样调整一下：

```js
MdEditor.config({
  markedRenderer(renderer) {
    renderer.image = (href, title = '', desc = '') => {
      return `<img src="${href}" title="${title}" alt="${desc}" >`;
    };
    return renderer;
  }
});
```

**Comment by 851605063** [comment]
如何修改配置

**Comment by imzbf** [comment]
> 如何修改配置

3.x版本后新增了`noImgZoomIn`来控制是否预览，另外如果需要修改生成的图片标签

第一步禁用内部的图片扩展https://github.com/imzbf/md-editor-v3/issues/374#issuecomment-1764080443
第二步找一个`markdown-it`关于图片的扩展，或者参考扩展的方式自行编写
第三步通过第一步中的`markdownItPlugin`把新的扩展`push`进去
