### ISSUE TITLE
文档及演示demo中，代码高亮失效

### ISSUE THREAD

**Issue by abu3389** [imzbf/md-editor-v3#103]
![image](https://user-images.githubusercontent.com/52814773/169942243-166f1e77-081e-4627-9cc3-0f993f35f6e6.png)

**Comment by imzbf** [comment]
highlight扩展没有加载完就是这个效果

**Comment by abu3389** [comment]
> 

![image](https://user-images.githubusercontent.com/52814773/169942581-5a3cd86d-0d1e-4deb-8770-a417b41b4ba0.png)
貌似是该css样式cdn资源访问失败

**Comment by imzbf** [comment]
这个是旧的链接了，你清下缓存，2.x版本已经把它替换了

**Comment by abu3389** [comment]
> highlight扩展没有加载完就是这个效果

jsdelivr 近期由于被图床滥用 导致国内大批量封杀 一些正常应用受到影响 建议使用unpkg 或者  baomitu
