### ISSUE TITLE
如何在uniapp中使用，或者说能使用吗?

### ISSUE THREAD

**Issue by baymax-arch** [imzbf/md-editor-v3#104]
现在uniapp支持vue3写法，但是用了之后发现只在h5端生效。原因应该是这种形式的组件没法编译成wxml，既然SFC格式的组件都能被编译，那这种应该也有某种方法吧

**Comment by imzbf** [comment]
这个应该不行，组件内部使用了太多的不兼容的逻辑，比如手动新增`script`标签这类。
