### ISSUE TITLE
vue3 会报这个错误  n]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.   

### ISSUE THREAD

**Issue by daidaibg** [imzbf/md-editor-v3#106]
vue3 会报这个错误

n]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.

**Comment by imzbf** [comment]
嗯，这边已经处理了这个问题，需要合到下一个功能版本一起发布

**Comment by hyahm** [comment]
大概什么时候能发布下一个版本

**Comment by imzbf** [comment]
补丁版本可能一两天吧

**Comment by hyahm** [comment]
加油     坐等

**Comment by imzbf** [comment]
`v2.0.1`更新了这个问题

**Comment by hyahm** [comment]
![image](https://user-images.githubusercontent.com/22030094/170907050-a126761c-2221-401d-b22d-037d63d50dbe.png)

插入不进去， 不知道是不是我哪些写错了


![image](https://user-images.githubusercontent.com/22030094/170907109-7ae68857-eae3-47f1-888d-a00466d5a06b.png)


![image](https://user-images.githubusercontent.com/22030094/170907132-348b1a01-d475-46e7-a8f8-85d3764a627f.png)

**Comment by imzbf** [comment]
> ![image](https://user-images.githubusercontent.com/22030094/170907050-a126761c-2221-401d-b22d-037d63d50dbe.png)
> 
> 插入不进去， 不知道是不是我哪些写错了
> 
> ![image](https://user-images.githubusercontent.com/22030094/170907109-7ae68857-eae3-47f1-888d-a00466d5a06b.png)
> 
> ![image](https://user-images.githubusercontent.com/22030094/170907132-348b1a01-d475-46e7-a8f8-85d3764a627f.png)

`callback`的入参是一个数组，改成`callback([resp.data])`这样就可以了

**Comment by daidaibg** [comment]
作者的是个l数组吧

**Comment by hyahm** [comment]
嗯， 是可以了   谢谢
