### ISSUE TITLE
发现几个小问题，反馈一下

### ISSUE THREAD

**Issue by songjianghu** [imzbf/md-editor-v3#108]
1、一级标题和二级标题字体大小一样大，一级标题不应该更大吗
2、previewOnly模式，鼠标放到图片上，稍等几秒，放大镜旁边会显示一个tips提示null，但是上传图片的时候并没有添加图片tips的地方
3、字体加粗，就是那个B，如果选中的文字后面有空格，加粗就失效了，例如(复制到编辑器看预览效果)：**OK****OK****OK **
4、通过三击选中的文字，加粗的话，如果不是最后一行，也会失效，例如：有三行文字，通过三击选中了第二行文字，然后点击加粗(B按钮)，加粗效果没出来。
5、标题都带有a链接，previewOnly模式下，点击标题就跳转到新页面了。我理解这个a链接的作用是，编辑页面通过目录点击对应的标题跳转到对应的锚点位置。但是在previewOnly模式下，这个a链接就没有用了。previewOnly模式下，有办法去掉标题的a链接吗

**Comment by imzbf** [comment]
1. 关于标题，默认主题一级标题时更大的字体，其他主题是作者去找了对应的源码来适配编辑器的，源码在这儿[markdown-theme](https://github.com/imzbf/markdown-theme)
2. 图片hover这是个bug，待优化。当然添加title的方式还是有的，像这样：`![mark and Emoji extension](https://imzbf.github.io/md-editor-v3/imgs/mark_emoji.gif 'title')`
3. 关于加粗空格问题，这个是语法问题，标识符前后最好不要出现这类字符
4. 三级选中问题和上面的类似，选中末尾出现的特殊字符，编译识别序列有误

**Comment by imzbf** [comment]
第五点有点不太明白你的意思，是你的标题像这样：`## 标题[外链](https://xxx.cc)`么

**Comment by songjianghu** [comment]
第五点的意思是：一级标题的前端代码通过F12看是这样的，对吧。
<h1 id="研发团队管理实践分享"><a href="#研发团队管理实践分享">研发团队管理实践分享</a></h1>
因为我用的了vue-router，所以，这个标题在预览窗口一点击，就跳转到了a链接的href属性对应的页面。跳转路径是：#研发团队管理实践分享，但是这并不是个页面。所就显示空白了。所我理解，在预览窗口下，这个a链接的锚点可以去掉，或者说可以直接吧a链接去掉

**Comment by songjianghu** [comment]
贴的一段代码被自动翻译成样式了，可以通过F12看一下上面一行文字对应的代码内容

**Comment by imzbf** [comment]
编辑器支持自定义markdown内的所有结构，包括标题，你看看编辑器的文档`docs`分支中的代码是不是你想要的功能

[docs](https://github.com/imzbf/md-editor-v3/blob/docs/src/main.ts#L17)
