### ISSUE TITLE
粘贴板上传图片问题

### ISSUE THREAD

**Issue by hbynlsl** [imzbf/md-editor-v3#11]
粘贴板上传图片是什么意思呢？复制图片粘贴？还是 复制一段富文本（含图片），粘贴过来时图片上传成功。
这两种方法，我均尝试了，好像都没有成功，并且没有触发 @uploadImg 事件

**Comment by imzbf** [comment]
> 粘贴板上传图片是什么意思呢？复制图片粘贴？还是 复制一段富文本（含图片），粘贴过来时图片上传成功。
> 这两种方法，我均尝试了，好像都没有成功，并且没有触发 @uploadImg 事件

你这边的浏览器、node及系统环境是怎么样的？

方便提供一个在线案例或仓库案例么，这个功能就是在你截图到粘贴板，或者手动复制某张图片时，在编辑器内粘贴可以直接上传。

**Comment by imzbf** [comment]
[https://stackblitz.com/edit/vue-aleajl](https://stackblitz.com/edit/vue-aleajl)，你在这里尝试一下，看`console`有没有输出内容

**Comment by hbynlsl** [comment]
您好，您这个网址也不行呀，复制word文档（带图片）或 网页富文本 ，控制台没有输出 文件信息









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-v3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 中午11:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-v3] 粘贴板上传图片问题 (#11)





 
https://stackblitz.com/edit/vue-aleajl，你在这里尝试一下，看console有没有输出内容
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imzbf** [comment]
只能复制图片，它不会识别文本中带图片的情况。下面这些情况：

- 网页图片右键复制
- QQ等截图
- 文件系统中复制图片

触发条件还需要聚焦编辑框

**Comment by hbynlsl** [comment]
收到，多谢您的回复。希望后续能支持复制文本中的图片
