### ISSUE TITLE
目录跳转问题

### ISSUE THREAD

**Issue by daidaibg** [imzbf/md-editor-v3#111]
一级二级三级等目录id:都是通过 “目录名字”渲染的，如果目录名字相同的话锚点跳转不就只会跳转到第一个。通过js去跳锚点不也只会跳转第一个，是否有解决方式
![image](https://user-images.githubusercontent.com/55817318/171085405-d8bb8e6b-047c-4eb0-b835-666463f97a62.png)

**Comment by daidaibg** [comment]
![image](https://user-images.githubusercontent.com/55817318/171085758-b91c321d-e6c9-4617-91e4-72020657d929.png)

**Comment by imzbf** [comment]
你可以自定义你的目录，查看一下文档里的`config`方法，下个功能版本会优化最开始的以`heading-${num}`的方式的目录，目前这种形式还没办法。

从开始的时候，咱们就默认不会出现定义相同内容目录的这种情况哈。如果有的话，尽量做区别，文章看着也应该会好一些

**Comment by daidaibg** [comment]
我纯预览的先时候通过+索引解决   先这样解决吧
![image](https://user-images.githubusercontent.com/55817318/171108064-ec7aa2f3-2fa1-4efc-8de5-be493254b4af.png)

**Comment by imzbf** [comment]
2.1.0之后新增了`heading-${index}`，做如下修改即可使用

```vue
<template>
  <md-editor :marked-heading-id="generateId" />
</template>

<script setup>
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const generateId = (_text, _level, index) => `heading-${index}`;
</script>
```
