### ISSUE TITLE
2.1.1 highlight.min.js:105 Could not find the language 'vue'

### ISSUE THREAD

**Issue by daidaibg** [imzbf/md-editor-v3#119]
highlight.min.js:105 Could not find the language 'vue', did you forget to load/include a language module?

会报这个错了，highlight没有支持vue语法，然后指定就报错了，上个版本是没问题的

```vue
<router-link tag="a" target="_blank" to="/test">第一种新窗口打开页面</router-link>

```

**Comment by imzbf** [comment]
这个提示会影响其他的内容吗？

**Comment by daidaibg** [comment]
这个提示目前发现不会影响其他功能

**Comment by daidaibg** [comment]
问章片段这样的，上边的```被识别成代码了
```vue
import { useRouter } from 'vue-router' //引入useRouter
const router = useRouter();
 // 注册点击事件
 <button @click="openPage">这是第二种window.href</button>
 const href = router.resolve({ //使用resolve
      name:'test',    //这里是跳转页面的name
      path: '/test',
   })
  // 点击事件 
 const openPage = ()=>{
     window.open(href.href, '_blank')
  }

e ```

**Comment by daidaibg** [comment]
问章片段这样的，上边的```被识别成代码了
`vue
<router-link tag="a" target="_blank" to="/test">第一种新窗口打开页面</router-link>

`

**Comment by imzbf** [comment]
这边找了一下highlight相关的接口，做了相对的优化，类似vue\react之类它没有很好识别，最好替换为jsx

**Comment by daidaibg** [comment]
如果 这块不是开发自己编辑的话，那也没办法控制别人吧vue换成jsx，是不是要highlight有语言识别的话再指定，没有的话highlight自己去判断，或者有更好的解决方案

**Comment by imzbf** [comment]
它识别出不认识的语言一定会输出这个错误，没有提供关闭的接口。下个版本只能说相对的优化了一下，像这类识别不了的改用自动高亮。

**Comment by imzbf** [comment]
现在可是尝试一下`2.1.2-beta.2`的版本。正式版要在这边做完测试才发布

**Comment by imzbf** [comment]
2.1.2已更新
