### ISSUE TITLE
怎么适配移动端呢

### ISSUE THREAD

**Issue by ixdoer** [imzbf/md-editor-v3#12]
我找了很久vue3的markdown编辑器，居然让我发现了这个宝藏，我用了一下，各方面都很不错，但我不知怎么适配移动端：
一行代码很长的话，编辑器宽度就没法缩小了，我尝试用position：absolute来做，宽度是解决了，但是父元素高度就无法被编辑器撑起来了，请问有什么好的方法吗？

**Comment by imzbf** [comment]
方便给个图看看么

**Comment by ixdoer** [comment]
已经解决了，用着还不错，哈哈。[www.idoer.top](url)

**Comment by ixdoer** [comment]
已经解决了，用着还不错，哈哈。http://www.idoer.top
