### ISSUE TITLE
使用highlight.js内链造成的代码块报错

### ISSUE THREAD

**Issue by yanyunling** [imzbf/md-editor-v3#123]
## 1. highlight.js内链引发的问题
- 只贴出了highlight.js的内链配置
```js
import MdEditorV3 from "md-editor-v3";
import "md-editor-v3/lib/style.css";
import highlight from "highlight.js";
import "highlight.js/styles/github.css";

MdEditorV3.config({
  editorExtensions: {
    highlight: {
      instance: highlight,
    }
  },
});
```

- 代码块内容
![image](https://user-images.githubusercontent.com/32293949/174699587-adb90906-bb53-44b4-8569-0cc35ce7cf29.png)

- 目前只测试出 **bat** 和 **cmd** 代码块会报下面这个错误，导致页面无法渲染：
![image](https://user-images.githubusercontent.com/32293949/174699427-6bfcf2f9-b9c1-4097-a2fd-e934d77a4fdf.png)

- 当未使用 **instance** 引入 highlight 时不会报这个错误，引入的版本：`"highlight.js": "11.5.1"`
- 经测试，在highlight.js官网下载包含 **Batch file (DOS)** 语言的自定义js文件时，也会导致这个问题，代码块：dos、bat、cmd

## 2. 同时使用 **markedHeadingId** 和 **renderer.heading** 的冲突问题
- 由于目录可能有重名标题，故添加了 **markedHeadingId** 的配置
- 标题默认用了a标签，我们一般不希望它可以被点击而乱跳转，故添加了 **renderer.heading** 的配置，但这里无法获得 index 属性，导致无法和 **markedHeadingId** 生成的id匹配，目录无法跳转。
```tsx
import { defineComponent } from "vue";
import MdEditorV3 from "md-editor-v3";
import "md-editor-v3/lib/style.css";

MdEditorV3.config({
  markedRenderer(renderer) {
    renderer.heading = (text, level, raw,) => {
      return `<h${level} id="${raw}">${text}</h${level}>`;
    };
    return renderer;
  }
});

export default defineComponent({
  name: "MdEditor",
  setup() {
    const generateId = (text: any, level: any, index: any) => `heading-${index}`;
    return () => {
      return (
        <MdEditorV3
          toolbarsExclude={["github", "fullscreen"]}
          previewTheme="cyanosis"
          codeTheme="github"
          showCodeRowNumber
          markedHeadingId={generateId}
        />
      );
    };
  },
});
```

**Comment by imzbf** [comment]
正在想办法-_-

**Comment by imzbf** [comment]
在`2.2.0`中修复了这些问题
