### ISSUE TITLE
表情和编辑的问题

### ISSUE THREAD

**Issue by hyahm** [imzbf/md-editor-v3#124]
1   怎么显示出表情栏

2 编辑的时候怎么关闭右边的预览

**Comment by imzbf** [comment]
表情的源码在`docs`分支的`components`目录下面

关闭预览有相应的`prop`的哈，`:preview ="false"`

**Comment by hyahm** [comment]
:preview  这个试过， 如果加上这个prop 那么就无法显示了， 不管是true 还是 false
