### ISSUE TITLE
编辑器可以配置行号吗

### ISSUE THREAD

**Issue by web-xp** [imzbf/md-editor-v3#125]
![image](https://user-images.githubusercontent.com/59134195/174965389-6af7ca9d-e42a-46de-a6bd-f64549acdf6f.png)
类似这样的

**Comment by web-xp** [comment]
> 可以呀，编辑器有一个`showCodeRowNumber`的属性

showCodeRowNumber是配置代码块是否显示行号,不是编辑器的行号吧

**Comment by imzbf** [comment]
编辑器的行号textarea这种编辑器做不了，不能完全对应上，所以没有做这个。
