### ISSUE TITLE
目录树选中状态

### ISSUE THREAD

**Issue by Dellear** [imzbf/md-editor-v3#129]
大佬的项目很好，我磕磕绊绊用起来了，现在和其他md产品的唯一缺点就是目录树点击之后没有选中状态，内容滚动时，目录也没有自动定位选中。大佬有时间先优化一下这块吧。thks

**Comment by imzbf** [comment]
OK，后面尝试一下这个功能

**Comment by VIBom** [comment]
确实，大佬请一定要加入 [toc]功能！感谢感谢感谢

**Comment by imzbf** [comment]
`2.3.0`更新了这个问题~
