### ISSUE TITLE
为了你这个编辑器 我要把我的项目升级到nuxt3 测试版

### ISSUE THREAD

**Issue by xdlumia** [imzbf/md-editor-v3#13]
为了你这个编辑器 我要把我的项目升级到nuxt3 测试版  
界面好看

**Comment by imzbf** [comment]
这个编辑器只能在vue3环境中使用，没有开发vue2的版本，所以需要升级。

1.4版本目前还没有着重兼容ssr，`nuxt`中可能会遇到服务端调用浏览器端api的错误哦
