### ISSUE TITLE
发现有关编辑器全屏功能的BUG

### ISSUE THREAD

**Issue by BugOS-ly** [imzbf/md-editor-v3#131]
先点击浏览器全屏, 再点击屏幕全屏, 再按ESC退出屏幕全屏,  这时回到了浏览器全屏, 也就是此时出现了BUG:  关闭浏览器全屏按钮消失, 关闭屏幕全屏按钮依旧存在, 但它的功能变成了开启屏幕全屏, 再次按下ESC回到屏幕全屏, 此时无BUG

下面是BUG截图
执行步骤是: 开启浏览器全屏; 开启屏幕全屏; ESC退出屏幕全屏
![image](https://user-images.githubusercontent.com/85739810/176997812-2d36ff26-7e3b-4b15-8a71-94c462207e7e.png)
![image](https://user-images.githubusercontent.com/85739810/176997838-54c3e4e3-e621-4c6b-bb08-f7ed1b4a0c5e.png)
![image](https://user-images.githubusercontent.com/85739810/176997911-2a52e04f-ae73-44c2-bcd9-d4606cf4e488.png)

**Comment by imzbf** [comment]
试试2.2.1版本
