### ISSUE TITLE
编辑器的标题快捷键无效

### ISSUE THREAD

**Issue by BugOS-ly** [imzbf/md-editor-v3#132]
我将焦点聚集到编辑区, 使用快捷键CTRL + 1~6 , 无效果,  无论是将光标移到该行, 还是选中该行的内容都无法使用快捷键将其标识为标题,

**Comment by imzbf** [comment]
[预览](https://imzbf.github.io/md-editor-v3/)这里可以用么？

**Comment by imzbf** [comment]
不可以的话，麻烦提供一些浏览器类型、版本和系统类型。可用的话参考一下`docs`分支的源码使用。

**Comment by BugOS-ly** [comment]
预览里没效果, Chrome 版本 103.0.5060.66（正式版本） 64 位）电脑版本: Windows 10 专业版  版本号: 21H1

**Comment by BugOS-ly** [comment]
经过排查, 我发现是由于我自定义了工具栏, 导致ctrl + 1~6快捷键无法使用, 但是该如何解决呢? 我是按照官网上给的工具栏, 来自定义的 ,就只是删除了github 和 三个 '-' 

官网: ['bold',  'underline',  'italic',  '-',  'strikeThrough',  'sub',  'sup',  'quote',  'unorderedList',  'orderedList',  '-',  'codeRow',  code',
  'link',  'image',  'table',  'mermaid',  'katex',  '-',  'revoke',  'next',  'save',  '=',  'pageFullscreen',  'fullscreen',  'preview',  htmlPreview',  'catalog',  'github'];
我的: const toolbar = [  'bold',  'underline',  'italic',  'strikeThrough',  'sub',  'sup',  'quote',  'unorderedList',  'orderedList',  codeRow',  'code',  'link',  'image',  'table',  'mermaid',  'katex',  'revoke',  'next',  'save',  '=',  'pageFullscreen',  'preview',  htmlPreview',  'catalog']

我怀疑原因是: 默认工具栏中, 有标题这一选项, 而自定义的工具栏中没有标题选项;  但我查询官网并未发现有关标题的工具栏选项, 请问标题工具栏选项是哪个?

**Comment by BugOS-ly** [comment]
我在VScode中打开项目, 自定义工具栏时, VScode会报错 :  这个报错并不影响运行
![image](https://user-images.githubusercontent.com/85739810/177074365-7067de71-cf61-4530-b459-5035bbe25479.png)

这是我的自定义工具栏
![image](https://user-images.githubusercontent.com/85739810/177074392-df736fec-9226-456f-8388-eb0f9f1c775c.png)

**Comment by imzbf** [comment]
这边抽时间尝试一下先

**Comment by imzbf** [comment]
标题的key是`title`，抱歉，这边时间没来得及安排。这边编辑器的逻辑是没有显示的工具栏对应的快捷键也不可用

**Comment by BugOS-ly** [comment]
大佬你这也太客气了, 开源出来给我用, 我就很开心了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月13日(星期三) 中午1:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imzbf/md-editor-v3] 编辑器的标题快捷键无效 (Issue #132)





 
标题的key是title，抱歉，这边时间没来得及安排。这边编辑器的逻辑是没有显示的工具栏对应的快捷键也不可用
