### ISSUE TITLE
部分markdown内容样式无效

### ISSUE THREAD

**Issue by BugOS-ly** [imzbf/md-editor-v3#133]
粗体, 斜体的样式在预览组件中无效,    还有一个上下角标, 我不确定是我用法错误还是同样的样式无效, 
贴图如下
![image](https://user-images.githubusercontent.com/85739810/177048237-e96ce6e0-a240-4d14-9e32-c2d14a45a8eb.png)

**Comment by imzbf** [comment]
项目里面用了一些UI库，或者你全局定义了样式可能会覆盖这部分，这类问题最好确认一下。

**Comment by BugOS-ly** [comment]
解决了, 前端为防止各个浏览器之间导致的样式差异, 我引入了元素样式的重置css文件, 经过排查 , 问题出在了 重置样式中的
// 斜体, 粗体, 下标, 上标
em,strong, sub, sup {
  font: inherit;
  vertical-align: baseline;

}&nbsp; 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-v3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 上午8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-v3] 部分markdown内容样式无效 (Issue #133)





 
项目里面用了一些UI库，或者你全局定义了样式可能会覆盖这部分，这类问题最好确认一下。
