### ISSUE TITLE
mermaid插入访问实例报undefined

### ISSUE THREAD

**Issue by chuan02162** [imzbf/md-editor-v3#134]
`TypeError: undefined is not an object (evaluating 'window.mermaid.initialize')`
`md-editor-v3.es.js:5756`

**Comment by imzbf** [comment]
这边是否有调整过什么设置，方便的话给一下还原问题的场景代码。这边好做bug还原

**Comment by chuan02162** [comment]
按照文档安装后没有调整过设置。
`edit.vue`
```
<template>
  <md-editor v-model="text" />
</template>
<script setup>
import { ref } from 'vue';
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const text = ref('# Hello Editor');
</script>
```

**Comment by imzbf** [comment]
这个问题是一直出现吗？

在出现这个问题的时候，麻烦给下下面这个`js`的`network`状态看看呢

```
https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.5/mermaid.min.js
```

**Comment by chuan02162** [comment]
问题一直出现。
`network`的状态，您是指这个吗？
```
摘要
URL: https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.13.5/mermaid.min.js
状态: —
来源: —

请求
没有请求标头

响应
没有响应标头
```

**Comment by imzbf** [comment]
看看这个

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37092006/178423128-f42a911f-d097-4806-92f4-32ef8e8333b3.png">

**Comment by chuan02162** [comment]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/50532938/178457062-e0e5492a-3621-4979-925e-cdaad1b3ab96.png">

**Comment by imzbf** [comment]
这边还原不了这个问题，提供两个决绝方案

1. 如果这边对mermaid没有需求，可以设置`no-mermaid`屏蔽相应的库
2. 如果有使用需求，在你的项目中安装`mermaid`后配置，方法如下
  ```js
  import mermaid from 'mermaid';
  import MdEditor from 'md-editor-v3';
  
  MdEditor.config({
    editorExtensions: {
      mermaid: {
        instance: mermaid
      }
    }
  });
  ```

**Comment by chuan02162** [comment]
好的谢谢您
