### ISSUE TITLE
"md-editor-v3": "^2.2.0"

### ISSUE THREAD

**Issue by GoldRong** [imzbf/md-editor-v3#135]
# Heading 1
## Heading 2
这个版本"^2.2.0"   h1 在预览的效果实际比h2 还小
看实际效果  http://sunmier.com/#/MdEditor

**Comment by imzbf** [comment]
被覆盖了，h1默认是2em
<img width="320" alt="image" src="https://user-images.githubusercontent.com/37092006/178645872-324b92b7-4fc5-46a2-8c2e-3daf3b8b98b7.png">
