### ISSUE TITLE
如何将内容展示到任意页面？

### ISSUE THREAD

**Issue by liyu233** [imzbf/md-editor-v3#138]
我这里将md语法保存到数据库中，有取出渲染的需求，如何将取出的md能够和编辑器中的样式一般还原到页面中？

**Comment by imzbf** [comment]
> > 我这里将md语法保存到数据库中，有取出渲染的需求，如何将取出的md能够和编辑器中的样式一般还原到页面中？
> 
> 我想我可能多问了，展示的话开启只读模式即可

是的，`preview-only`属性即可。同时内置的目录组件，可以参考参考`dev-docs`分支的文档项目使用示例
