### ISSUE TITLE
我提几个建议

### ISSUE THREAD

**Issue by xdlumia** [imzbf/md-editor-v3#14]
1. 目前不支持复制粘贴上传图片
2. 上传图片的按钮，能不能是一个下拉 里面包含上传图片和图片链接？ 这样上传图片就少一步操作逻辑

**Comment by imzbf** [comment]
你指的是什么方式复制粘贴图片，`v1.4.2`目前支持下面的几种方式：
- QQ等截图工具粘贴
- 网页等图片右键复制粘贴
- 文件系统中复制粘贴

以上几种是支持的，以下的方式不支持：

- 同时包含文本和图片的内容。

**建议已收集~**

**Comment by imzbf** [comment]
`>1.6.0`支持下拉上传图片菜单
