### ISSUE TITLE
关于自定义工具栏写入数据问题

### ISSUE THREAD

**Issue by wpww1314** [imzbf/md-editor-v3#140]
你好，我最近在项目中引入这个编辑器，
现在想做一个功能，即：打开一个弹窗，搜索结果，然后将结果写入编辑器内容当中

这是一个常见的功能，但是我在文档中没有发现相应的写入内容代码，请问有什么好的方法吗？

**Comment by imzbf** [comment]
参考一下插入[emoji](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/EmojiExtension/index.vue)这个组件

**Comment by wpww1314** [comment]
> 提取单独的文件
```js
<template>
    <ModalToolbar title="linkToDoc" :visible="state.visible" @on-click="onClick" @on-close="onClose">
        <template #overlay>
            <div class="LTD-container">
                <span @click="searchDoc">搜索框</span>
            </div>
        </template>
        <template #trigger>
            😀
        </template>
    </ModalToolbar>
</template>
```

> 引用组件
```js
<md-editor
        class="spark-editor"
        :editor-id="defaultProps.editorId"
        v-model="docForm.md"
        :theme="defaultProps.theme"
        :code-theme="defaultProps.codeTheme"
        :preview-theme="defaultProps.PreviewTheme"
        @onSave="Save"
        @onUploadImg="onUploadImg"
    >
        <template #defToolbars>
            <LinkToDoc />
        </template>
    </md-editor>
```

但是界面并没有显示，组件是`import`过的了，可就是不显示，奈何处于小白阶段，暂时无法找出问题所在

**Comment by imzbf** [comment]
插入后要定义一下`toolbar`，这个参考[文档](https://imzbf.github.io/md-editor-v3/docs#%F0%9F%AA%B6%20defToolbars)

**Comment by wpww1314** [comment]
感谢，已经实现了

**Comment by 954L** [comment]
有没有完整的示例啊，对小白太不友好了。下标填0，填组件名都不生效 @imzbf

**Comment by 954L** [comment]
@imzbf doc分支的代码全找了，没有引入组件的示例代码。文档的Setup 模板没用组件，真看不懂怎么配置

**Comment by wpww1314** [comment]
暂时已经实现了，需要的可以给你发代码示例，github不常看，可以发我邮箱

**Comment by 954L** [comment]
谢谢，昨天已经搞定了，在仓库的preview包里找到了示例代码。感谢感谢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月08日 15:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [imzbf/md-editor-v3] 关于自定义工具栏写入数据问题 (Issue #140) |

暂时已经实现了，需要的可以给你发代码示例，github不常看，可以发我邮箱
