### ISSUE TITLE
在模态框中使用只读模式时，图片点击不会放大

### ISSUE THREAD

**Issue by Jarod-Xie** [imzbf/md-editor-v3#141]
环境：
vue3+vite+antdv

在antdv的模态框中使用只读模式展示markdown，图片点击不会放大

**Comment by imzbf** [comment]
element-plus中 的弹窗会出现这种问题，是他们的组件库有[问题](https://github.com/element-plus/element-plus/issues/8470)。这边测试了antv，没有还原问题，方便的话，麻烦提供一份简单的可运行的代码，这边看看。
