### ISSUE TITLE
markdown 在dialog中样式无法渲染问题

### ISSUE THREAD

**Issue by tollytu** [imzbf/md-editor-v3#143]
<div>
            <el-dialog v-model="dialogVisible" title="漏洞编辑" width="100%">
                <MdEditor class="mgb20" v-model="text">
                </MdEditor>
            </el-dialog>

        </div>

<img width="855" alt="image" src="https://user-images.githubusercontent.com/47838420/180911380-7ccee949-ccae-49a2-9972-11bf38f4a7b4.png">

请问大佬，如何解决这个问题

**Comment by imzbf** [comment]
这看起来是你没有引入编辑器的样式

```js
import 'md-editor-v3/lib/style.css';
```

**Comment by tollytu** [comment]
😂，抱歉，打扰了
