### ISSUE TITLE
生成标题时，不想插入a标签

### ISSUE THREAD

**Issue by tollytu** [imzbf/md-editor-v3#144]
生成标题时，不想插入a标签
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/47838420/180929077-6ee050d1-3d5a-4f87-a74c-2a11fa35fbd5.png">

**Comment by imzbf** [comment]
参考
https://imzbf.github.io/md-editor-v3/docs#%F0%9F%92%B4%20%E9%85%8D%E7%BD%AE%E7%BC%96%E8%BE%91%E5%99%A8
