### ISSUE TITLE
启用previewOnly属性后，部分内容无法渲染

### ISSUE THREAD

**Issue by erhaa233** [imzbf/md-editor-v3#145]
![image](https://user-images.githubusercontent.com/46651798/181679006-0199bebc-4db1-459e-87d7-8a57bf554d52.png)
![image](https://user-images.githubusercontent.com/46651798/181679048-165bf516-7bb5-4beb-bc69-3409b4bd16d6.png)
![image](https://user-images.githubusercontent.com/46651798/181679087-c530020a-2426-4cd2-846d-885eb1e747ce.png)
**下划线，上下标没办法解析**
![image](https://user-images.githubusercontent.com/46651798/181679142-6d1a204d-1e67-4d4c-822e-1500f03f1862.png)
**代码没有高亮显示，行号也没办法显示**
![image](https://user-images.githubusercontent.com/46651798/181679194-1da97cfa-9284-4812-83b2-3965c33f5d0a.png)
**公式无法渲染
请问这些问题怎么解决呀**

**Comment by imzbf** [comment]
两个`$$`要换行哦，语法是这样的

行内的公式：

`$公式代码$`

块级的公式：

```
$$
公式代码
$$
```

**Comment by erhaa233** [comment]
***@***.***）已收到你的邮件。

**Comment by imzbf** [comment]
标签无法渲染，你是不是使用了`sanitize`格式化内容呢

**Comment by erhaa233** [comment]
> 标签无法渲染，你是不是使用了`sanitize`格式化内容呢

没有，都是默认的配置

**Comment by erhaa233** [comment]
> 两个`$$`要换行哦，语法是这样的
> 
> 行内的公式：
> 
> `$公式代码$`
> 
> 块级的公式：
> 
> ```
> $$
> 公式代码
> $$
> ```

这些都是从官方文档里复制过来的，在没有启用previewOnly的时候，这些标签都是可以正常渲染的，启用之后就变成这样了，其他的配置都是默认的

**Comment by imzbf** [comment]
原文提供一下。这边看看

**Comment by erhaa233** [comment]
> 原文提供一下。这边看看

## 😲 md-editor-v3

Markdown 编辑器，vue3 版本，使用 jsx 模板 和 typescript 开发，支持切换主题、prettier 美化文本等。

### 🤖 基本演示

**加粗**，<u>下划线</u>，_斜体_，~删除线~，上标<sup>26</sup>，下标<sub>[1]</sub>，`inline code`，[超链接](https://imzbf.cc)

> 引用：这是一段引用。

![mark and Emoji extension](https://imzbf.github.io/md-editor-v3/imgs/mark_emoji.gif)

## 🤗 代码演示

```vue
<template>
  <md-editor v-model="text" />
</template>

<script setup>
import { ref } from 'vue';
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const text = ref('Hello Editor!');
</script>
```

## 🖨 文本演示

依照普朗克长度这项单位，目前可观测的宇宙的直径估计值（直径约 930 亿光年，即 8.8 × 10<sup>26</sup> 米）即为 5.4 × 10<sup>61</sup>倍普朗克长度。而可观测宇宙体积则为 8.4 × 10<sup>184</sup>立方普朗克长度（普朗克体积）。

## 📈 表格演示

| 昵称 | 猿龄（年） | 来自      |
| ---- | ---------- | --------- |
| 之间 | 4          | 中国-重庆 |

## 📏 公式

$$
\sqrt[3]{x}
$$

## ☘️ 占个坑@！

**Comment by erhaa233** [comment]
## 😲 md-editor-v3 Markdown 编辑器，vue3 版本，使用 jsx 模板 和 typescript 开发，支持切换主题、prettier 美化文本等。 ### 🤖 基本演示 **加粗**，<u&gt;下划线</u&gt;，_斜体_，~删除线~，上标<sup&gt;26</sup&gt;，下标<sub&gt;[1]</sub&gt;，`inline code`，[超链接](https://imzbf.cc) &gt; 引用：这是一段引用。 ![mark and Emoji extension](https://imzbf.github.io/md-editor-v3/imgs/mark_emoji.gif) ## 🤗 代码演示 ```vue <template&gt;   <md-editor v-model="text" /&gt; </template&gt; <script setup&gt; import { ref } from 'vue'; import MdEditor from 'md-editor-v3'; import 'md-editor-v3/lib/style.css'; const text = ref('Hello Editor!'); </script&gt; ``` ## 🖨 文本演示 依照普朗克长度这项单位，目前可观测的宇宙的直径估计值（直径约 930 亿光年，即 8.8 × 10<sup&gt;26</sup&gt; 米）即为 5.4 × 10<sup&gt;61</sup&gt;倍普朗克长度。而可观测宇宙体积则为 8.4 × 10<sup&gt;184</sup&gt;立方普朗克长度（普朗克体积）。 ## 📈 表格演示 | 昵称 | 猿龄（年） | 来自      | | ---- | ---------- | --------- | | 之间 | 4          | 中国-重庆 | ## 📏 公式 $$ \sqrt[3]{x} $$ ## ☘️ 占个坑@！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-v3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 下午5:48
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-v3] 启用previewOnly属性后，部分内容无法渲染 (Issue #145)





 
原文提供一下。这边看看

**Comment by imzbf** [comment]
> 就是https://imzbf.github.io/md-editor-v3/index 里面的演示代码，直接复制的

没能还原，看看你的`blog.content`，这个估计是被转义了
