### ISSUE TITLE
能更换样式的cdn链接吗

### ISSUE THREAD

**Issue by SamuelBin** [imzbf/md-editor-v3#146]
能更换样式的cdn链接吗？想把样式上传，用自己的cdn，之前发现有些网络环境是请求样式是失败的

**Comment by imzbf** [comment]
你在你的项目里面不引用编辑器的css，在node_modules里面找到对应的css文件上传到你的cdn服务器上就可以了。这样是可行的

**Comment by imzbf** [comment]
文档里面也提供了三方的cdn引用链接的，参考一下[cdn引用](https://imzbf.github.io/md-editor-v3/demo#%F0%9F%A4%93%20CDN%20%E9%93%BE%E6%8E%A5)
