### ISSUE TITLE
内置目录没有实时更新

### ISSUE THREAD

**Issue by liyiligang** [imzbf/md-editor-v3#152]
我发现当我在写文档的时候，内置的目录是没有实时更新的。 不知是否是一个bug
![22](https://user-images.githubusercontent.com/25530874/186160508-490a8d62-b0f7-4358-a40d-160fe4dfb161.jpg)

**Comment by imzbf** [comment]
是的，这边也还原了。感谢提醒，后面补丁修复~

**Comment by imzbf** [comment]
`2.3.0`更新了这个问题~
