### ISSUE TITLE
md页面跳转锚点与vue的Hash路由模式有冲突

### ISSUE THREAD

**Issue by wpww1314** [imzbf/md-editor-v3#155]
当我点击预览页面的标题时，直接在地址栏中跳转，覆盖地址栏中的路由：

比如当前路由是`http://localhost:3000/#/document/add`

点击页面标题，跳转锚点地址栏直接变成 `http://localhost:3000/#/测试标题1`

这个问题导致跳转不成功，有没有好的方法。目录跳转是正常的，只是预览窗口跳转不正常

**Comment by imzbf** [comment]
可以设置标题不包含超链接，会导致复制链接无法重新定位到文章指定标题位置。

最好的建议还是不使用hash路由。
