### ISSUE TITLE
单纯预览模式和编辑模式“链接”的解析结果不一致。

### ISSUE THREAD

**Issue by kmlixh** [imzbf/md-editor-v3#159]
例如在编辑预览模式下，<xdxs@xxx.com>链接会正确解析为maito：//xxxx，但是单纯预览模式下却只是一个链接，不会是mailto

**Comment by imzbf** [comment]
请问怎么复现？这边尝试添加邮箱格式内容仅预览模式显示与编辑预览相同
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/37092006/193410820-f6e76a07-8cff-4a22-85e7-7fab055d50e7.png">
