### ISSUE TITLE
这种tip功能样式我觉得可以考虑一下

### ISSUE THREAD

**Issue by heping945** [imzbf/md-editor-v3#16]
[就这种tip样式](http://ckang1229.gitee.io/vue-markdown-editor/zh/theme/vuepress.html#%E5%86%85%E7%BD%AE%E5%8A%9F%E8%83%BD)

还有请问，根据`onGetCatalog`事件，我成功做了一个目录，然后，`element-plus`没有类似`iview`的`Anchor 锚点`组件，该怎么做目录和文章的相互定位。

我现在做了一个文章目录组件，能够根据`onGetCatalog`事件的数据，做成锚点列表，定位到文章，但是不知道怎么在文章浏览滚动的时候，自动地使目录滚动到相应位置active，还有在刷新页面的时候，路由的锚点无法定位，滚动条一直在最上面

> 我太菜了0.0

**Comment by imzbf** [comment]
这个功能可能得在2.x版本后了，现在内设的marked还不够熟悉，很多语法扩展不了，2版本也许会使用markdown-it来扩展。

对于你想做的这个目录，你可以参考一下我在开发的新的文档界面的代码，分支是`dev-docs`，组件封装在这里：https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/Catalog/index.tsx

**Comment by heping945** [comment]
啊，你这个封装，是用了 `ant-design-vue`的` Anchor `组件封装的吗，和我以前博客用的iview的锚点定位一个好像，但是我项目准备是用`element-plus`做的，这个没`Anchor `组件，没有互相滚动定位的实现啊，-.-，我该怎么办，

> 我前端太菜了不会玩啊，scroll滚动相关不会，我太菜了，

**Comment by imzbf** [comment]
害，只有值看看有这个组件的源码吧，慢慢做一个，或者去建议ele-p开发一个，就完美

**Comment by heping945** [comment]
害0.0，好的老哥
