### ISSUE TITLE
Include localisation files in the project

### ISSUE THREAD

**Issue by ajmas** [imzbf/md-editor-v3#161]
I am looking to use this in my project, but it turns out the only localisation available are `zh-CN` and `en-US`. It would be good to be able to contribute other localisations to the project, but it isn't clear the best way?

Wondering whether the project should be structured to make it easier to contribute localisations. Maybe via a `src/i18n` folder, with translations being in their own file or folder, a bit like with vue-i18n, such as:

```
src/i18n/
  en-US.json
  zh-CN.json
  fr-FR.json
```

**Comment by imzbf** [comment]
The language of this component is set as follows

[Extension Language](https://imzbf.github.io/md-editor-v3/demo#%F0%9F%8F%B3%EF%B8%8F%E2%80%8D%F0%9F%8C%88%20Extension%20Language)

Language types：[StaticTextDefault](https://github.com/imzbf/md-editor-v3/blob/master/MdEditor/config.ts#L66)

It may not be used in the same way as vue-i18n.

**Comment by ajmas** [comment]
Certainly, but the point was more to make it easier to contribute new localisations to the project. No need to get every user of the  project to re-translate.

**Comment by imzbf** [comment]
> Certainly, but the point was more to make it easier to contribute new localisations to the project. No need to get every user of the project to re-translate.

You are right. I will refactor this module next time.

**Comment by imzbf** [comment]
I have prepared a public library of extensions: [md-editor-extension](https://github.com/imzbf/md-editor-extension), for there are two versions of editor: vue and react.

Document here will be updated soon.

**Comment by imzbf** [comment]
Document has been added to `2.4.1`. Thanks~
