### ISSUE TITLE
How to enable emoji?

### ISSUE THREAD

**Issue by gennitdev** [imzbf/md-editor-v3#163]
First, thank you for creating this awesome library.

This is not a feature request or a bug report, but a question about the documentation.

I have looked at the emoji extension source code (https://github.com/imzbf/md-editor-v3/tree/docs/src/components/EmojiExtension) and the documentation (https://imzbf.github.io/md-editor-v3/docs) but I am still confused.

Do I need to copy the source code into my code base? Or can I just enable it as a configuration option? In the documentation about editor extensions and configuration options, the emoji is not included as any of the possible options:

```js
import MdEditor from 'md-editor-v3';

interface EditorExtensions {
  highlight?: {
    instance?: any;
    js?: string;
    css?: {
      [key: string]: {
        light: string;
        dark: string;
      };
    };
  };
  prettier?: {
    // >= 2.2.0
    prettierInstance?: any;
    parserMarkdownInstance?: any;

    standaloneJs?: string;
    parserMarkdownJs?: string;
  };
  cropper?: {
    instance?: any;
    js?: string;
    css?: string;
  };
  iconfont?: string;
  screenfull?: {
    instance?: any;
    js?: string;
  };
  mermaid?: {
    instance?: any;
    js?: string;
  };
  katex?: {
    instance?: any;
    js?: string;
    css?: string;
  };
}

```

**Comment by imzbf** [comment]
The emoji extension source code should be copied into your project, it is not a part of editor. And use it like this: https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/pages/Preview/index.vue#L17

**Comment by gennitdev** [comment]
Thank you, that helped. I think there are some additional requirements that need to be documented, though. If anyone else finds this issue and has the same question, this is what you also need to know:

- The extension only works if MdEditor is installed as a plugin, otherwise it throws an error message that says the `<dropdown-toolbar>` is not a component.
- The emoji button will not appear in the dropdown menu unless you have installed the same icon library that is used in the documentation. So if it looks invisible, change the icon used in the #trigger slot.
- You have to manually add styles from `src/pages/Preview/index.less` or else there is one emoji per row.

**Comment by yasserss** [comment]
> 

How did you install MdEditor as plugin ?

**Comment by imzbf** [comment]
Source code is here: 

| Emoji | Usage | Config Toolbar |
| - | - | - |
| [EmojiExtension](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/EmojiExtension/index.vue) | [Preview#L20](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/pages/Preview/index.vue#L20)  | [toolbar#L23](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/pages/Preview/staticConfig.ts#L23) |


And you need install `MdEditor` like it: [main#L43](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/main.ts#L43)

Or import component in `EmojiExtension` like:

```
import MdEditor from 'md-editor-v3';

const { DropdownToolbar } = MdEditor;

...
```

[Document online](https://imzbf.github.io/md-editor-v3/docs#%F0%9F%92%AA%20defToolbars)

> How did you install MdEditor as plugin ?

**Comment by yasserss** [comment]
@imzbf  thanks , can you recommend please a library to purify the output in order to avoid XSS attacks ?

**Comment by imzbf** [comment]
I used `sanitize-html` to test only, and no idea in production env. I'm sorry I can't help you
