### ISSUE TITLE
请问这个 todolist 可以在换行的时候，也还是 todolist 吗？

### ISSUE THREAD

**Issue by Sylor-huang** [imzbf/md-editor-v3#167]
- [ ] 在线的 demo 里 可以测试。比如说 第一次输入了 todolist，但是点击 enter 换行后，就变成 list 了

https://imzbf.github.io/md-editor-v3/index

<img width="745" alt="image" src="https://user-images.githubusercontent.com/26167245/197775437-253bbea9-19d4-428a-94c0-2f514402a9ea.png">

- [ ] 可以做成像 github 输入框这样的吗，第一次输入了 todolist，然后点击 enter 后，还是继续为 todolist。

<img width="275" alt="image" src="https://user-images.githubusercontent.com/26167245/197776254-f3987b48-173a-4e60-8761-019cf6c4601a.png">

我觉得这个 md-editor-v3 写的真好，特别是有暗黑模式，太喜欢了~

**Comment by imzbf** [comment]
这个功能在下个版本优化一下~，感谢支持

**Comment by imzbf** [comment]
`2.4.1`版本更新了任务列表工具栏，同时修复了回车无法新增任务列表的问题，试试吧~

**Comment by Sylor-huang** [comment]
完美！

谢谢  @imzbf  提供这么好用的 md ~

<img width="764" alt="image" src="https://user-images.githubusercontent.com/26167245/200245385-3f9cac9f-b999-411f-9c76-9959a8be3e7b.png">
