### ISSUE TITLE
Does not support block latex display?

### ISSUE THREAD

**Issue by xclss99** [imzbf/md-editor-v3#168]

**Comment by xclss99** [comment]
$$
 latex
$$
这样子写可以显示块级公式
$$ latex $$
这样子就显示不出来

**Comment by imzbf** [comment]
`$ latex $`这样写

**Comment by xclss99** [comment]
> `$ latex $`这样写
不管用 我说的是块级公式，katex  $$ $$ 这样不换行就能显示出块级公式

**Comment by Nomango** [comment]
@imzbf 想要一个和github latex一样的功能，希望作者大大支持呀，像这里一样，https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-expressions-as-blocks

**Comment by imzbf** [comment]
> @imzbf 想要一个和github latex一样的功能，希望作者大大支持呀，像这里一样，https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-expressions-as-blocks

现在就是支持的呀

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/37092006/220548930-6fa26e4b-00b4-4155-8af6-6cf6851080db.png">

**Comment by Nomango** [comment]
@imzbf 我的用户写的latex语法不是很严格，github markdown上是可以识别的，比如 `$$ euclidean_distance(a, b) = \sqrt(\(a-b\)^2)$$`，放到这边就展示不了了

虽然不是什么有用的需求，但是教会用户写latex也挺困难。。XD

**Comment by imzbf** [comment]
我尝试了一下，这边可以优化一下兼容`$$ xxx $$`的写法来渲染块级的数学公式。

但是，组件内部依赖的转换数学公式web库是`katex`，它的内部实现和`github`定制的语法有所差异。像上面这种`$$ euclidean_distance(a, b) = \sqrt(\(a-b\)^2)$$`，`katex`的语法是不需要对`()`转义，所以变成了`$$ euclidean_distance(a, b) = \sqrt((a-b)^2)$$`。

如果是只有类似转义的语法差异可以提交`issue`到`katex`的作者，不过没有办法去发现所有的语法差异。
