### ISSUE TITLE
图标命名建议加上前缀 否则有可能名字冲突，无法单独配置隐藏图片中的上传按钮

### ISSUE THREAD

**Issue by yuntian001** [imzbf/md-editor-v3#172]
图标命名建议加上前缀 否则有可能名字冲突
无法单独配置菜单下的按钮的显隐
建议用`$.vnode.props.onUploadImg`做下判断 ，如果没传入`onUploadImg`事件  则隐藏`上传图片`和`裁剪上传`按钮

**Comment by imzbf** [comment]
对于不上传图片的情景，是项目中必须么

**Comment by yuntian001** [comment]
> 
上传那个只是建议，不过图标冲突遇到了，另一个第三方库svg命名时也没加前缀，你们俩个库一块用结果，图标会被覆盖

**Comment by imzbf** [comment]
> > 
> 
> 上传那个只是建议，不过图标冲突遇到了，另一个第三方库svg命名时也没加前缀，你们俩个库一块用结果，图标会被覆盖

图标和类型都在进行特殊化

**Comment by imzbf** [comment]
`2.4.1`调整了类和图标的公共前缀，通过新增了`noUploadImg`属性来限制显示上传图片的入口，试试吧~
