### ISSUE TITLE
关于previewOnly和保存html的问题

### ISSUE THREAD

**Issue by lhcGinv** [imzbf/md-editor-v3#173]
1. 通过定义响应式的previewOnly,无法切换，或者说切换有问题，比如true切换为false，只多了没有图表的toolbars，从false切换为true，仍然有textarea。

1. 保存的时候只有md内容数据，有没有获取html内容的方法或者组件内可导出的方法

**Comment by imzbf** [comment]
不支持在仅预览和编辑模式之间切换，这个操作是禁止的，一开始就没有设计这个功能。这样做会出现很多不可兼容的事情，需要切换可以添加两个组件，通过切换显示状态来完成。

保存html可以利用`onHtmlChanged`事件

**Comment by lsixi** [comment]
html的还是希望有可以通过ref导出的函数，或者onSave支持第二个参数接收html内容,这个很希望作者支持

**Comment by imzbf** [comment]
转换是异步的，所以确实存在可能在保存时html和markdown的内容不一致。方案还需要尝试，目前建议无法优化这个问题。

目前个人使用建议编写内容后延迟保存操作，非个人建议暂时使用提醒文案提醒，等待这边给出合理的解决方案哈~

**Comment by imzbf** [comment]
`2.4.2`优化了保存获取相对应的`html`得办法

参考：https://imzbf.github.io/md-editor-v3/docs#%F0%9F%92%BE%20onSave
