### ISSUE TITLE
Image clipping and uploading

### ISSUE THREAD

**Issue by ss-sola** [imzbf/md-editor-v3#174]
Why is the md-editor-modal style in version 2.4.1 in the form of inline style

**Comment by imzbf** [comment]
image? or md-editor-modal? Can you give me an example

**Comment by ss-sola** [comment]
![image](https://user-images.githubusercontent.com/102914742/200994429-011fafe5-3421-4954-80d7-77dbb0ed39e5.png)
这个行内样式是自带的，我想要修改它。我使用了vue的:deep()或是js来修改，但效果并不理想。

**Comment by ss-sola** [comment]
好吧，我在非scoped尝试修改样式发现可以。
![image](https://user-images.githubusercontent.com/102914742/200998417-be2be4ac-52d5-426e-bdf8-ee95c68e0a7e.png)
```html
<style>
/* 裁剪图片上传样式修正 */
.md-editor-modal {
    left: 0 !important;
    width: 100% !important;
    height: 60% !important;
}
</style>
```

**Comment by ss-sola** [comment]
期待作者能做成自适应的

**Comment by imzbf** [comment]
有时间我优化一下移动端的表现

**Comment by imzbf** [comment]
`2.4.2`优化了裁剪弹窗在移动端的显示
