### ISSUE TITLE
关于工具栏响应的问题

### ISSUE THREAD

**Issue by PasserAhao** [imzbf/md-editor-v3#175]
在同一个页面用到多个编辑器的时候，在第一个编辑器点击加粗等功能时所有编辑器内容区域都会出现****（每个编辑器绑定的值是不同的）

**Comment by imzbf** [comment]
设置不同的`editorId`了吗

**Comment by PasserAhao** [comment]
> 
好了，我解决了。
之前设置的editor是个数字，不知道为啥设置成数字就不显示了。
我现在设置成了内容之后就好了。
