### ISSUE TITLE
关于editor绑定的问题

### ISSUE THREAD

**Issue by PasserAhao** [imzbf/md-editor-v3#178]
我在使用循环的时候给editor_id 绑定了一个值（这个值是唯一的），然后内容我会定时存储起来，内容没有用到加粗等样式时组件没有出现任何问题，一旦用到加粗等样式时编辑器就渲染不出来了，但是文本展示的内容可以渲染出来。
（我的内容都是从localStorage中取出来然后替换默认内容，单独使用的编辑器没有任何问题怎么加粗都能渲染出来，但是在循环里边的编辑器渲染不出来）
![image](https://user-images.githubusercontent.com/106132965/201567985-0be98a17-db1b-439d-8ef9-54ea344b2883.png)

**Comment by imzbf** [comment]
这个editorId最好符合html的id命名规范，编辑器不好控制这个id

**Comment by PasserAhao** [comment]
> 这个editorId最好符合html的id命名规范，编辑器不好控制这个id
我不理解的是我绑定的是符合命名规范的值，但是不知道为啥他自己给我换成了文本内容。我就很纳闷了

**Comment by PasserAhao** [comment]
> > 这个editorId最好符合html的id命名规范，编辑器不好控制这个id
> > 我不理解的是我绑定的是符合命名规范的值，但是不知道为啥他自己给我换成了文本内容。

**Comment by imzbf** [comment]
这个id好像还是你的markdown源内容，检查一下是不是把v-model的值赋到了editorId上，把绑定到editorId上的值打印出来看看

**Comment by PasserAhao** [comment]
> 这个id好像还是你的markdown源内容，检查一下是不是把v-model的值赋到了editorId上，把绑定到editorId上的值打印出来看看

没有，他的id一直是v-model的内容

**Comment by imzbf** [comment]
id不要用你的mardkown内容

**Comment by PasserAhao** [comment]
> id不要用你的mardkown内容
好的，谢谢你。我知道问题出在哪里了。
我的编辑框没有显示出来，内容是ok的，所以我一直以为是编辑框的id绑定错了。就一直在编辑框哪里纠结。
最后才发现是显示内容的那一块id绑定错了
最后再次感谢你
