### ISSUE TITLE
createWebHashHistory与heading生成的链接锚点冲突

### ISSUE THREAD

**Issue by SalHe** [imzbf/md-editor-v3#18]
作者您好，有幸能够使用上您的MD编辑器组件，他对于我的帮助特别大，我也非常喜欢。

现在有个特殊场景需要使用`createWebHashHistory`创建的`RouterHistory`，这样一来本身页面的链接就会以`#`开头。
同时`md-editor`本身会根据Markdown中的标题生成对应的锚点，然后生成对应的`a`标签元素能够导航到标题处，但是这样一来就与Router冲突了。

这个场景是必须使用`createWebHashHistory`而不能使用其他的`RouterHistory`创建方式，所以可以考虑为开放一个自定义渲染标题的接口或者在内部做出调整吗？

**Comment by imzbf** [comment]
很高兴对组件的认可。

根据你的描述，目前标题的超链接会影响到你的项目。目前自定义渲染插槽不好支持，预览内容组件可以提供一个`prop`用来取消标题上的`<a />`，这样做的话无法获取某个标题的链接，导航目录也需要特殊处理。如果有更好的建议也可以讨论讨论~
