### ISSUE TITLE
noIconfont设置无效

### ISSUE THREAD

**Issue by popdo** [imzbf/md-editor-v3#181]
终于找到一个好用的markdown编辑了。真是太强大了👍🏻

但我[下载](https://at.alicdn.com/t/font_2605852_pqekijay2ij.js)了iconfont.js文件，并正确引入了，props也设置了[noIconfont](https://imzbf.github.io/md-editor-v3/docs#%F0%9F%A4%9E%F0%9F%8F%BC%20noIconfont) 但编辑器始终无法加载icon图标。

**Comment by popdo** [comment]
另外 其它的一些js文件是否支持本地引入。不然经常会加载失败，或者加载慢，造成icon图标有时候10多秒才能显示

Failed to load resource: net::ERR_CONNECTION_CLOSED screenfull.min.js:1 
Failed to load resource: net::ERR_CONNECTION_CLOSED cropper.min.js:1
Failed to load resource: net::ERR_CONNECTION_CLOSED standalone.js:1

**Comment by imzbf** [comment]
- 编辑器在2.4.1更新了所有类和图标的前缀，防止在与其他项目冲突，最新的iconfont链接在这个哈 [https://at.alicdn.com/t/c/font_2605852_4cjr7o5jo0f.js]()

- 所有的扩展均支持自行引入，参考[自行引入扩展库](https://imzbf.github.io/md-editor-v3/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93)

**Comment by popdo** [comment]
非常完美。解决了。特来感谢！
