### ISSUE TITLE
粘贴图片上传为何会发起两次相同的请求

### ISSUE THREAD

**Issue by News777** [imzbf/md-editor-v3#186]
会重复调用两次上传的方法

**Comment by News777** [comment]
![example](https://user-images.githubusercontent.com/57581602/203682182-f17c5f2b-5f8a-4a50-ab74-06e82857b12e.gif)

**Comment by imzbf** [comment]
文档和在线示例上没有发现这个问题，更新一下你的版本或者贴下你的代码看看

**Comment by News777** [comment]
> 文档和在线示例上没有发现这个问题，更新一下你的版本或者贴下你的代码看看

ok，自查了下，是我这边组件引用问题，问题已解决了。感谢
