### ISSUE TITLE
设置noPrettier 之后保存快捷键失效！

### ISSUE THREAD

**Issue by popdo** [imzbf/md-editor-v3#187]
props同时设置

noPrettier
no-mermaid
no-katex

之后。ctrl+s保存快捷键失效！其它快捷键未测试过！

排查之后 发现设置了noPrettier的原因

**Comment by popdo** [comment]
另外 我未使用 fullScreen工具栏也会加载fullScreen.js文件！

**Comment by imzbf** [comment]
2.5.0修复了相关问题
