### ISSUE TITLE
Write javascript or vue code directly in editor?

### ISSUE THREAD

**Issue by abbjetmus** [imzbf/md-editor-v3#188]
Hi! Is it possible to write javascript or vue code in the editor and view results in preview? Something like this:

```html
<div id="body">
<h1>{{name}}</h1>

<script src="https://unpkg.com/petite-vue"></script>

<script>
const data = {
    name: 'Kalle Kula',
    changeName: function () {
        console.log("Testar")
        this.name = "Pelle Kula"
    }
}
PetiteVue.createApp(data).mount("#body")
</script>
</div>
```

Ideally since it is already a vue app, it would be nice to be able to not include petite-vue at all.
Maybe a suggested enhancement.

**Comment by imzbf** [comment]
Sorry, This is not supported. Because there are too many libraries, and no tools to compile template here.

**Comment by imzbf** [comment]
If you want to support vue only.

You can write an extension about [marked](https://marked.js.org/using_pro#extensions), use [MdEditor.config](https://imzbf.github.io/md-editor-v3/docs#%F0%9F%92%B4%20Config%20Editor) and `markedExtensions` api to add it in editor.

I will write an example here later.

**Comment by imzbf** [comment]
And `innerHTML` will not load script, this feature needs to be customized

**Comment by abbjetmus** [comment]
I see thank you. I'm using your awesome component in an app that creates slides-show presentation to a monitor. It would be nice to have dynamic content that's why I wanted JavaScript or Vue as well.
Vue 3 has it's playground enviorment that can be used but not sure about including it as well

https://github.com/vuejs/repl

https://sfc.vuejs.org/#eNo9j71uwzAMhF+F5eIWqCV0NZQA3foGXbikjpw40B9EOR0EvXspp8imu9N9OFb8TEndN4sTGp7zmgqwLVs6Ulh9irlAhWwXaLDk6GGQrwMFCnMMXMDzBQ49fx2+rHMRvmN255fhjYLRD5yARBTrkzsVKwrAXD+Ote7l1owWtbtrSFuB++jj2boDoeSEEhn9bOM7PlaN/pTUjWOQ3bW36T9gwgl2p3uytmvCaymJJ615mfu1N1YxX7S8VN5CWb1Vlv34k+Mv2yxgwo5oFBq2P3/sZE8=

**Comment by imzbf** [comment]
`@vue/repl` is great for designing dynamic component.

But, markdown contents are appended to page through 'v-html', scripts cannot be loaded specially.

I've tried, in `@vue/repl`, we need to analyze the content by module. In component, It's a little difficult.

I'll try to realize this feature again, if there's a better way later.
