### ISSUE TITLE
Cannot use multiple instances of the editor

### ISSUE THREAD

**Issue by alexandre-le-borgne** [imzbf/md-editor-v3#189]
Hi! 

When you click on a toolbar button, it impacts the content of all editors instead of only doing it on the corresponding editor.

```
<template>
  <md-editor v-model="text" />
  <md-editor v-model="text2" />
  <md-editor v-model="text3"  />
  <md-editor v-model="text4" />
</template>

<script>
import { defineComponent } from "vue";
import MdEditor from "md-editor-v3";
import "md-editor-v3/lib/style.css";

export default defineComponent({
  name: "App",
  components: {
    MdEditor,
  },
  data() {
    return {
      text:
        "Select me and click on the button to put me in bold. All other editors are also impacted. For me the button is invisible on codesandbox.io: it is the one in 1st position",
      text2: "2",
      text3: "3",
      text4: "4",
    };
  }
});
</script>
```

1.
![image](https://user-images.githubusercontent.com/10196942/204513975-79c747ca-afbb-4ac4-a141-97471fa56f6b.png)

2.
![image](https://user-images.githubusercontent.com/10196942/204514344-26eb8e00-c730-4324-acc0-742742d50550.png)

3.
![image](https://user-images.githubusercontent.com/10196942/204514566-4acec506-760d-41c2-ba93-16623f53cb5d.png)

Demo:
https://codesandbox.io/s/example-of-md-editor-v3-forked-2nbd8p?from-embed=&file=/src/App.vue

**Comment by imzbf** [comment]
To fix it, set different `editorId` for editor

**Comment by alexandre-le-borgne** [comment]
It works
Could we have a clearer indication in the docs that this property MUST be filled in (and can be indicated at the top of the list of props or in the Usage part)?

Thank you for the quick reply

**Comment by imzbf** [comment]
I'm thinking about how to show analogous problems, intuitively.

Thanks for your suggestion.
