### ISSUE TITLE
关于点击目录定位的问题

### ISSUE THREAD

**Issue by Msg-Lbo** [imzbf/md-editor-v3#191]
![image](https://user-images.githubusercontent.com/63098778/205340331-c22c07fb-3081-411e-9aac-e110c1999618.png)
因为导航栏使用fixed固定后，点击右侧目录跳转会居窗口的最顶部，从而被顶部导航栏挡住。
请问这个有什么办法解决吗

**Comment by imzbf** [comment]
目前建议将内容滚动放到一个html节点中，只在这个中滚动，同时将scrollElement设置为这个html节点。

后面会给目录组件添加一个合并计算标题滚动距离的属性，这不会太久。

**Comment by Msg-Lbo** [comment]
谢谢

**Comment by imzbf** [comment]
已在2.6.0的目录组件中新增了`scrollElementOffsetTop`属性

**Comment by Arke11** [comment]
这个好，不用自己修改代码了
