### ISSUE TITLE
Enable auto code detector

### ISSUE THREAD

**Issue by devopg** [imzbf/md-editor-v3#192]
hello. how can i enable auto code detection then past fromVisual studio code ?

**Comment by imzbf** [comment]
I don't understand what you mean.
Component can't detect the code in the content.

**Comment by devopg** [comment]
example past code from vsc to milkdown editor 
https://user-images.githubusercontent.com/61819835/205444800-5010434b-6e6f-42c3-8434-2ad158cf76c4.mp4

**Comment by imzbf** [comment]
Got it. Thanks for your video. I'm trying to achieve this feature.

**Comment by imzbf** [comment]
Sorry, I've tried, but no way to eliminate differences between code and text. And same with other editors. This feature will be discarded

**Comment by devopg** [comment]
others have been able to do it and you haven't... ((((

**Comment by imzbf** [comment]
> others have been able to do it and you haven't... ((((

Yes, But they have serious problems. Although they could detect the code, but if we copy simple words from vscode and patse to editor, editor still treats it as code. Even for component used in my company.

It's easy to design in API `e.clipboardData.getData('vscose-editor-data')`. But we should consider the availability.

**Comment by imzbf** [comment]
All right, I'll add a state to editor, developer Developers adjust this state to control detecting code or not. Way to adjust state is controlled by the developers

**Comment by imzbf** [comment]
This feature has been added in `>2.6.0`, need to set `autoDetectCode` to `true`.
