### ISSUE TITLE
再这样拿刀了哈

### ISSUE THREAD

**Issue by daidaibg** [imzbf/md-editor-v3#193]
升个级 把编辑器class名都给改了，```md-dark```改成了```md-editor-dark```
![image](https://user-images.githubusercontent.com/55817318/205533001-6223c550-e08b-4106-a31f-a29b1a973825.png)
我全给重置了的🥹

**Comment by imzbf** [comment]
原来的方案存在缺陷，类似内容的语言设置，名称错误、类型`md`与一些UI库的中等同名。

手动狗头
