### ISSUE TITLE
预览模式下是否可以增加前置和后置插槽

### ISSUE THREAD

**Issue by AnyFork** [imzbf/md-editor-v3#194]
有个需求，是否可以在预览模式下增加前置和后置插槽，通过插槽额外定制标题和文章摘要信息，解决不同预览主题下定制标题和文章摘要同文章正文文字样式问题。
![QQ截图20221210123118](https://user-images.githubusercontent.com/49142023/206829220-74294a80-e6cf-4220-9bc7-8bef27ebe2f1.png)

**Comment by imzbf** [comment]
这个功能实现不了，目前编辑器预览的内容是通过marked直接转换出来的，没有分模块拆分。所以没有办法添加插槽。建议把文章标题独立出来。

**Comment by imzbf** [comment]
这个功能实现不了，目前编辑器预览的内容是通过marked直接转换出来的，没有分模块拆分。所以没有办法添加插槽。建议把文章标题独立出来。

**Comment by AnyFork** [comment]
好的，主要是多种主题预览，样式不兼容，也不影响大局，可以使用单独预览主题。
