### ISSUE TITLE
能否增加提示信息扩展，例如warning,info,error,danger 

### ISSUE THREAD

**Issue by AnyFork** [imzbf/md-editor-v3#195]
![微信截图_20221212100646](https://user-images.githubusercontent.com/49142023/206945701-9905f395-7a62-4a83-8f6e-03ce025370b1.png)
像这样的

**Comment by imzbf** [comment]
这个功能会考虑以扩展组件的方式实现，具体的使用方法参考后续的文档更新后的内容

**Comment by AnyFork** [comment]
ok

**Comment by imzbf** [comment]
`2.7.0`在内部支持了这个功能~
