### ISSUE TITLE
当toolbar上不显示save图标时 onSave事件不能触发！

### ISSUE THREAD

**Issue by popdo** [imzbf/md-editor-v3#198]
因为是在modal中使用编辑器，宽度有限，因此一些不必要的工具栏图标会隐藏掉

但隐藏save图标后 onSave事件就不能触发了！

**Comment by imzbf** [comment]
🤔，待梳理一下工具栏和内部事件的关系

**Comment by imzbf** [comment]
`2.7.2`上了补丁
