### ISSUE TITLE
能让内容渲染成vnode吗？

### ISSUE THREAD

**Issue by Groupguanfang** [imzbf/md-editor-v3#199]
```js
editor.config({
  markedRenderer(renderer) {
    renderer.link = (href, title, text) => {
      return h(NA,{ href },{ default: () => text })
    }
    return renderer
  }
})
```
上面把a标签渲染成`<NA></NA>`的虚拟dom，当我尝试在编辑器中插入一个a标签，发现返回的是`[object Object]`而非虚拟节点。

![如图所示](https://user-images.githubusercontent.com/64218589/209467602-85f9fe7c-5988-4707-a72d-943eda8b48cc.jpeg)

下个版本能试试做下这个功能吗？💦😋

**Comment by Groupguanfang** [comment]
补充一下哈，如果直接在编辑器中输入一段html，那么这段代码就生效了：
![image](https://user-images.githubusercontent.com/64218589/209468060-3845b1d6-7d59-4a00-9079-cd747a4e9fe6.png)
这是没匹配到markdown语法嘛？

**Comment by Groupguanfang** [comment]
昨天研究了一晚上。发现vue有个SSR API，`renderToString()`，可以把vnode的`h()`渲染函数渲染成字符串。
这个函数是异步的，这没有什么问题。
于是我就加上async/await看看能不能把它转成同步。
```js

editor.config({
  markedRenderer: (renderer) => {
    const link = async (href,title,text) => {
      return await renderToString(h(NA,{ href },{ default: () => text }))
    }
    renderer.link = link
    return renderer
  }
})

```
![21DEDCA2-25CF-4135-B792-3D95A5DA6FEB](https://user-images.githubusercontent.com/64218589/209495831-3e1b21c7-8d0e-4255-bd8b-c18f6f72c82a.jpeg)

我特么只有一个字：6

再也没撤了。。Promise居然只能返回`[object Promise]`。。彻底傻了

**Comment by imzbf** [comment]
一般不去考虑把已有的静态节点再转换成虚拟节点再挂载一遍，会出来很多消耗。另外编辑器组件是将`html`文本以`v-html`的方式插入到页面中，它默认不会支持对`vue`的虚拟节点进行处理。

如果实在想，可以考虑从源码开始还早你的特别版本哦
