### ISSUE TITLE
图片上传

### ISSUE THREAD

**Issue by Forest-211** [imzbf/md-editor-v3#2]
支持图片粘贴上传吗？

**Comment by imzbf** [comment]
> 支持图片粘贴上传吗？

支持的，截图到粘贴板、直接复制图片、复制网络图片都是可以的，注册一下事件就可以了，参考在线文档里的demo

**Comment by hwy2** [comment]
有没有发现一个问题，在当前页面上传一个文件之后，切换页面，再重新切换回来的时候，再次上传图片时，会上传2张图片，一张是之前的，一张是现在的，而且这个情况会无线叠加，我最多测试过，一次上传10几张，大部分是重复的
![image](https://user-images.githubusercontent.com/40650839/131604958-caac2979-ceff-49d8-9681-246676090588.png)

**Comment by imzbf** [comment]
> 有没有发现一个问题，在当前页面上传一个文件之后，切换页面，再重新切换回来的时候，再次上传图片时，会上传2张图片，一张是之前的，一张是现在的，而且这个情况会无线叠加，我最多测试过，一次上传10几张，大部分是重复的
> ![image](https://user-images.githubusercontent.com/40650839/131604958-caac2979-ceff-49d8-9681-246676090588.png)

路由相关功能的确存在这个问题，还有部分连带问题，正在修复~

**Comment by imzbf** [comment]
该问题已在[v1.4.2]版本中修复。
