### ISSUE TITLE
关于MdCatalog组件的问题

### ISSUE THREAD

**Issue by architectMymine** [imzbf/md-editor-v3#204]
```vue
<script lang="ts" setup>
import { ref, onMounted } from 'vue'
import MdEditor from '@/components/mdEditor/index.vue'
import MdViewer from '@/components/mdViewer/index.vue'
import md from 'md-editor-v3'

const content = ref<string>()
const viewerRef = ref()

const { MdCatalog } = md

onMounted(() => {
  viewerRef.value = document.querySelector('.main')
})
</script>
<template>
  <div>
    <MdEditor v-model:content="content" />
    <div class="main">
      <MdViewer :content="content" editor-id="radiom" />
    </div>
    <MdCatalog editor-id="radiom" :scroll-element="viewerRef" />
  </div>
</template>
<style lang="scss" scoped>
.main {
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
```
我直接给MdCatalog组件给main的时候，组件不生效，但是直接给document.documentElement就可以正常点击跳转。不太懂为什么不生效。

**Comment by imzbf** [comment]
`scrollElement`接收`HTMLElement`和`string`类型。

如果是`string`会直接将它作为选择器使用`document.querySelector`查询，给`.main`是会生效的。

但是要确定`main`类所在的元素是否是真正的滚动元素，还有就是这个元素必须是已经定位的。

**Comment by architectMymine** [comment]
> `scrollElement`接收`HTMLElement`和`string`类型。
> 
> 如果是`string`会直接将它作为选择器使用`document.querySelector`查询，给`.main`是会生效的。
> 
> 但是要确定`main`类所在的元素是否是真正的滚动元素，还有就是这个元素必须是已经定位的。

能具体一点吗，这个是否为真正的滚动元素，还有这个元素已经定位。我在官方文档看到这句话，不太理解什么意思。

**Comment by imzbf** [comment]
定位就是 `css` 的 `position`为除了 `static` 外的值

滚动元素是指

```html
<html>
<body>
<div class="a1">
  <p>文本内容</p>
</div>
</body>
</html>
```
如果`p`的高度有2000，`.a1`的高度和`html`的高度都为1000，但是`.a1`设置了`overflow: auto`，那么这个时候你的滚动元素就是`.a1`而不是`html`

通俗的讲就是靠近文本内容最近的已经设置`overflow`的祖元素

**Comment by architectMymine** [comment]
> 定位就是 `css` 的 `position`为除了 `static` 外的值
> 
> 滚动元素是指
> 
> ```
> <html>
> <body>
> <div class="a1">
>   <p>文本内容</p>
> </div>
> </body>
> </html>
> ```
> 
> 如果`p`的高度有2000，`.a1`的高度和`html`的高度都为1000，但是`.a1`设置了`overflow: auto`，那么这个时候你的滚动元素就是`.a1`而不是`html`
> 
> 通俗的讲就是靠近文本内容最近的已经设置`overflow`的祖元素

我一开始也是这么想的，但是我不想a1标签设置高度，看来这种情况只能用html标签了。

**Comment by architectMymine** [comment]
遇到一个问题，初次渲染的时候，我不知道MdCatalog什么时候渲染完成，导致我获取元素宽高等不准确。我尝试在onMounted,以及nextTick里面获取，一样是获取不到准确数据。

**Comment by imzbf** [comment]
> 遇到一个问题，初次渲染的时候，我不知道MdCatalog什么时候渲染完成，导致我获取元素宽高等不准确。我尝试在onMounted,以及nextTick里面获取，一样是获取不到准确数据。

目录组件的原理是，共享编辑器内部状态，在编辑器发现目录发生改变时才会通知目录组件渲染目录，所以无论是`onMounted`还是`nextTick`都只能拿到没有目录的组件。

因为内容的不确定性，所以目录组件也无法告知你它什么时候是处于渲染完成状态。

如果你目前迫切需要获取目录组件的高度，尝试使用一下[ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)监听目录组件的大小变化情况，变化时执行你的调整逻辑

**Comment by architectMymine** [comment]
> > 遇到一个问题，初次渲染的时候，我不知道MdCatalog什么时候渲染完成，导致我获取元素宽高等不准确。我尝试在onMounted,以及nextTick里面获取，一样是获取不到准确数据。
> 
> 目录组件的原理是，共享编辑器内部状态，在编辑器发现目录发生改变时才会通知目录组件渲染目录，所以无论是`onMounted`还是`nextTick`都只能拿到没有目录的组件。
> 
> 因为内容的不确定性，所以目录组件也无法告知你它什么时候是处于渲染完成状态。
> 
> 如果你目前迫切需要获取目录组件的高度，尝试使用一下[ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)监听目录组件的大小变化情况，变化时执行你的调整逻辑

这个倒是可以试试，目前用的最傻的方法，写的setTimeout延迟获取。
