### ISSUE TITLE
关于在Nuxt3中使用中遇到的问题

### ISSUE THREAD

**Issue by 7836246** [imzbf/md-editor-v3#205]
再使用Nuxt-Link进入页面 代码部分的复制功能图片的放大功能无法出现
使用a链接或刷新页面进去 是正常有功能的

**Comment by imzbf** [comment]
https://codesandbox.io/p/sandbox/cool-jasper-8th3hw

我这边简单尝试了下你的描述，没法发现相关问题。提供一份能还原你的问题的代码，用来获取帮助。

**Comment by 7836246** [comment]
你发的这个就出现了 你点击进去 是没有高亮代码中的复制  刷新页面就出现了

**Comment by 7836246** [comment]
http://www.xukangr.com/  这是我的demo 你从首页点击进去就不显示 你进去之后刷新就有了

**Comment by 7836246** [comment]
<template>
  <div>
    <md-editor v-model="context"  showCodeRowNumber previewOnly />
  </div>
</template>
<script setup lang="ts">
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
const props = defineProps({
  context: {
    type: String,
    default: 'Hello World',
  },
})
const { context } = toRefs(props)
</script>

**Comment by 7836246** [comment]
需要使用Nuxt-Link进去 a链接或者刷新都是正常的

**Comment by imzbf** [comment]
贴一下你从获取`context`的代码，在线实例符合描述的基础，也是用内部的`NuxtLink`，这边需要知道是否和`nuxt`的数据获取方式相关

> ```
> <template>
>   <div>
>     <md-editor v-model="context"  showCodeRowNumber previewOnly />
>   </div>
> </template>
> <script setup lang="ts">
> import MdEditor from 'md-editor-v3';
> import 'md-editor-v3/lib/style.css';
> const props = defineProps({
>   context: {
>     type: String,
>     default: 'Hello World',
>   },
> })
> const { context } = toRefs(props)
> </script>
> ```

**Comment by 7836246** [comment]
```Vue
<script setup lang="ts">
import type { ArticlesPost } from '@/types/articles'
import {UrlIdSub} from '../../utils/SubUtils'
const  path  = useRoute()
const id = UrlIdSub(path.params.id)
const {data: articles} = await useAsyncData('data', () => $fetch(useRuntimeConfig().public.apiBase+'/api/articles?id=' + id), {
  transform: (res: any) => {
    return res.data
  },
})
const data = computed<ArticlesPost>(() => {
  return {
    title: articles.value.title || 'no-title available',
    context: articles.value.context || 'no-title available',
    date: articles.value.date || 'not-date-available',
    tags: articles.value.tags || [],
    views: articles.value.views || 0,
  }
})
```

**Comment by 7836246** [comment]
和数据无关 我已经测试多次 就是Nuxt-link点击进去就会出现这种奇怪的问题 使用a链接或直接进入是正常的

**Comment by 7836246** [comment]
···Vue
 <NuxtLink :to="path">
      <NuxtImg
        class="lg:h-48 md:h-36 w-full object-cover object-center rounded-t-2xl shadow-lg group-hover:scale-[1.05] transition-all duration-500"
        :src="image"
      />
      <div class="p-5">
        <div class="text-black text-sm pt-4 pb-2">
          <div class="flex items-center">
            <LogoDate />
            {{ date }}
          </div>
          <div class="flex items-center ">
            <LogoTag />
            <template v-for="tag in tags" :key="tag">
              <span>{{ tag }} &nbsp;</span>
            </template>
          </div>
          <div class="flex items-center">
            <LogoSort />
            {{ sortName }}
          </div>
        </div>
        <h2 class="text-2xl font-semibold text-black pb-1 group-hover:text-sky-700 overflow-auto h-9">
          {{ title }}
        </h2>
        <p class="text-ellipsis line-clamp-3">
          {{ description }}
        </p>
        <div class="flex group-hover:underline text-sky-700 items-center pt-2">
          <p>Read More</p>
          <LogoArrow />
        </div>
      </div>
    </NuxtLink>
···
但是改为a链接 href 就是正常

**Comment by 7836246** [comment]
```Vue
<NuxtLink :to="path" external="false" >
```
NuxtLink 加上external 是可以正常使用 但是页面是刷新出来的 不是加载出来的 和换a标签的效果一样

**Comment by imzbf** [comment]
我在demo中还原不了你的问题，挺麻烦的，你那边的`nuxt`和`md-editor-v3`的版本是多少

**Comment by imzbf** [comment]
原因就是在`nextTick`中获取文章的内容没有获取到，但是没有找到是`nuxt`的什么具体因素导致你说的`NuxtLink`会这样
