### ISSUE TITLE
selectTextChange monitor event exception！ TypeError: textarea is undefined

### ISSUE THREAD

**Issue by Frenchix** [imzbf/md-editor-v3#206]
Hola!

I have this error that spams the console when I type text in the editor so there is a big slowdown after a while (Firefox last version) :

> IselectTextChange monitor event exception！ TypeError: textarea is undefined
    getSelectionText md-editor-v3.es.js:502
    callback md-editor-v3.es.js:6011
    emit md-editor-v3.es.js:323
    emit md-editor-v3.es.js:321
    keyDownHandler md-editor-v3.es.js:591
    useKeyBoard md-editor-v3.es.js:778
    createHook runtime-core.esm-bundler.js:2739
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    __weh runtime-core.esm-bundler.js:2713
    flushPostFlushCbs runtime-core.esm-bundler.js:343
    flushJobs runtime-core.esm-bundler.js:397
    promise callback*queueFlush runtime-core.esm-bundler.js:282
    queueJob runtime-core.esm-bundler.js:276
    effect runtime-core.esm-bundler.js:5743
    triggerEffect reactivity.esm-bundler.js:397
    triggerEffects reactivity.esm-bundler.js:387
    triggerRefValue reactivity.esm-bundler.js:1003
    set value reactivity.esm-bundler.js:1048
    modifyFlashcards Flashcards.vue:43
    onModifyFlashcards Flashcards.vue:66
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    emit$1 runtime-core.esm-bundler.js:714
    0 Card.vue:22
    callWithErrorHandling runtime-core.esm-bundler.js:157
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:166
    invoker runtime-dom.esm-bundler.js:345
    addEventListener runtime-dom.esm-bundler.js:279
    patchEvent runtime-dom.esm-bundler.js:297
    patchProp runtime-dom.esm-bundler.js:376
    mountElement runtime-core.esm-bundler.js:5204
    processElement runtime-core.esm-bundler.js:5178
    patch runtime-core.esm-bundler.js:5098
    mountChildren runtime-core.esm-bundler.js:5285
    mountElement runtime-core.esm-bundler.js:5195
    processElement runtime-core.esm-bundler.js:5178
    patch runtime-core.esm-bundler.js:5098
    mountChildren runtime-core.esm-bundler.js:5285
    mountElement runtime-core.esm-bundler.js:5195
    processElement runtime-core.esm-bundler.js:5178
    patch runtime-core.esm-bundler.js:5098
    mountChildren runtime-core.esm-bundler.js:5285
    mountElement runtime-core.esm-bundler.js:5195
    processElement runtime-core.esm-bundler.js:5178
    patch runtime-core.esm-bundler.js:5098
    mountChildren runtime-core.esm-bundler.js:5285
    mountElement runtime-core.esm-bundler.js:5195
    processElement runtime-core.esm-bundler.js:5178
    patch runtime-core.esm-bundler.js:5098
    componentUpdateFn runtime-core.esm-bundler.js:5638
    run reactivity.esm-bundler.js:187
    update runtime-core.esm-bundler.js:5745
    setupRenderEffect runtime-core.esm-bundler.js:5759
    mountComponent runtime-core.esm-bundler.js:5541
    processComponent runtime-core.esm-bundler.js:5499
    patch runtime-core.esm-bundler.js:5101
    mountChildren runtime-core.esm-bundler.js:5285
md-editor-v3.es.js:325:18

however no problem on Chrome navigator

**Comment by imzbf** [comment]
I can't reproduce this bug. But tried to fix it and published `2.7.3-beta.0` just now. 

I need your help to have a test.

Install `beta` version:

```bash
npm i md-editor-v3@beta
```

**Comment by Frenchix** [comment]
It solve the problem. Thanks :)
