### ISSUE TITLE
编辑时候自带目录遇到问题

### ISSUE THREAD

**Issue by daidaibg** [imzbf/md-editor-v3#207]
点击目录无法进行锚点,就编辑的时候自带那个目录
![image](https://user-images.githubusercontent.com/55817318/216285578-2c2cb2f7-326f-4ba9-bebc-45b952fad5f2.png)
是同一个方法，如果不写这个方法是可以正常的
![image](https://user-images.githubusercontent.com/55817318/216285759-60c6491f-2e55-46ae-89ce-89286c69464a.png)

**Comment by daidaibg** [comment]
点击触发打印出来的id
![image](https://user-images.githubusercontent.com/55817318/216287516-08aa3991-3169-4031-af89-6aeda6475a92.png)
元素id
![image](https://user-images.githubusercontent.com/55817318/216287577-045031e3-b6c4-42ce-aa3d-efe3706a2eb0.png)

如果滚动滚动条后点击每个会自动回到顶部-..-

**Comment by imzbf** [comment]
https://codesandbox.io/s/md-editor-v3-forked-e2b55r?file=/src/App.vue

我简单尝试了一下，是你描述的这种情况吗，没有出现

**Comment by daidaibg** [comment]
我先再研究下我的代码😫

**Comment by daidaibg** [comment]
找到原因了是我这边代码问题，read组件，里面还有一个编辑器影响到了好像。我自己看看怎么处理吧 谢谢！！！
![image](https://user-images.githubusercontent.com/55817318/216868194-68d8b211-577b-4e86-9992-24d1816b1912.png)

### read 组件 
![image](https://user-images.githubusercontent.com/55817318/216868366-e1f8528e-4f6a-4766-aeed-eae5c12bf05d.png)

**Comment by daidaibg** [comment]
我把这个v-if去掉了,原来不能去的
![image](https://user-images.githubusercontent.com/55817318/216870530-d6ba2f34-edf1-403d-bc8e-c79ba106f4f2.png)

**Comment by imzbf** [comment]
是的，原因是**原编辑器**的预览中也存在一个相同的标题ID，这里预览也会存在一个。但是因为这里只是预览，没有放置目录，所以页面同时存在两个相同ID也没问题。

但是如果这个预览没有在弹窗关闭时移除，同时存在两个相同ID，会导致**目录组件**在获取标题的时候不正确，从而导致定位失败。

如果后续想要在预览组件中添加目录，你需要将编辑器和预览组件的`markedHeadingId`定义得不相同来规避这个问题。

**Comment by daidaibg** [comment]
好的 辛苦了

**Comment by daidaibg** [comment]
文档地址也会出现这个问题 😂😂😂
![image](https://user-images.githubusercontent.com/55817318/219614892-0cb9b085-61ee-4b20-86c0-8074aba8b009.png)

还有就是这个预览功能，原型设计的是预览左侧输入的内容吗
![image](https://user-images.githubusercontent.com/55817318/219615364-d7b62d79-3394-4759-8567-7c3d0cf18849.png)

**Comment by imzbf** [comment]
预览是默认打开的，就是有右侧的内容。

这边发现预览模块和目录之前有点交互错误，预计在`2.8.1`进行修复

**Comment by imzbf** [comment]
官网没有发现，目录导航只有在预览内容开启的时候才能使用。

**Comment by daidaibg** [comment]
好滴


> 预见是默认打开的，就是有右边的内容。
> 
> 这边发现预测模块和目录之前有一点交错，预测`2.8.1`正在进行修复
