### ISSUE TITLE
关于preview-only模式下catelog组件的显示

### ISSUE THREAD

**Issue by TOLIE-OFFICIAL** [imzbf/md-editor-v3#208]
> 问题：可以渲染出catelog组件，但是高度始终为0，无法显示在页面上

下面是组件代码，推测是scroll-element有问题，但无法解决（控制台无报错
```vuejs
<!-- description: blog详细内容页面 -->
<template>
  <div class="content">
    <md-editor
      v-model="state.text"
      :editor-id="state.id"
      ref="editorRef"
      :theme="(state.theme as Themes)"
      preview-theme="cyanosis"
      preview-only
    />
    <md-catalog
      :editor-id="state.id"
      :scroll-element="'#blog-content-preview-wrapper'"
      :theme="state.theme as Themes"
    />
  </div>
</template>

<script lang="ts" setup>
import MdEditor, { type Themes } from "md-editor-v3";
import "md-editor-v3/lib/style.css";

const MdCatalog = MdEditor.MdCatalog;

const state = reactive({
  theme: "light",
  text: `<h1><a href="#Web网络安全">Web网络安全</a></h1>`,
  id: "blog-content",
});

<style scoped lang="less">
.content {
  width: 1000px;
  display: flex;
  flex-direction: row;
  margin: 0 auto;
}
.md-editor {
  position: relative;
  padding: 0 8px;
  border-left: 1px solid var(--el-menu-border-color);
  border-right: 1px solid var(--el-menu-border-color);
  border-radius: 6px;
}
#blog-content-preview-wrapper{
  position: absolute;
}
/* .md-editor-catalog {
  width: 400px;
} */
</style>
```

**Comment by TOLIE-OFFICIAL** [comment]
![image](https://user-images.githubusercontent.com/90889293/216904454-fed41470-cc4e-432f-9184-77fd960880f6.png)

是这个字段的问题，已正常显示

**Comment by TOLIE-OFFICIAL** [comment]
想请问一下编辑完成之后，推荐用什么格式保存在数据库中呢？

如果直接存html取html无法正常使用目录组件，存md就会有符号的转译问题，可以推荐一下解决此问题的npm包吗？感谢🙏🏻

**Comment by imzbf** [comment]
> 想请问一下编辑完成之后，推荐用什么格式保存在数据库中呢？
> 
> 如果直接存html取html无法正常使用目录组件，存md就会有符号的转译问题，可以推荐一下解决此问题的npm包吗？感谢🙏🏻

自己的平台，比如博客、新闻之类的，自己完全可以把控内容的安全问题，就不做任何限制的存md文本。

如果涉及他人编辑的内容，比如评论等，组件提供了`sanitize`属性，可以使用一些普遍使用的库去转移和删除危险的内容。

类似的库，作者没有去花时间对比谁的比较好用，可以尝试一下文档里提过的`sanitize-html`。

html的方式存储的话，就需要通过事件[onGetCatalog](https://imzbf.github.io/md-editor-v3/docs#%F0%9F%97%92%20onGetCatalog)获取完整的目录，在服务端再存一份目录然后用一些UI库的锚点组件来挂载你的目录了。

**Comment by TOLIE-OFFICIAL** [comment]
是个人博客，所以我使用了encodeURI()和decodeURI()对原生markdown进行处理。
锚点组件饿了吗plus没有，antd的样式也不喜欢，就先如此吧
