### ISSUE TITLE
开发页面keepAlive,onSave事件重复多次触发

### ISSUE THREAD

**Issue by duofanCoder** [imzbf/md-editor-v3#210]
博客场景，设置KeepAlive 为TRUE 后，打开多篇文章编辑页面，onsave事件触发多次，次数为打开页面数量的平方。

自检推测：估计是缓存后的多个页面实例，onSave事件都触发了，每个事件触发后都分别调用了每个页面的onSave入参，因此就是平法级别的调用，重复调用的次数不固定，可能跟缓存的实例数量有关
下图展示我bug展示 
![image](https://user-images.githubusercontent.com/49710286/219303509-8d6698f9-f0da-4345-a02b-911c84328bfe.png)

**Comment by duofanCoder** [comment]
也许是底层emit 多次调用的缘故
onActivated(() => {
	// isDisplayRef.value = true;
	// ElMessage.info("activated");
	// onSaveRef.value = onSave;
});
onDeactivated(() => {
	// ElMessage.info("deactivated");
	// isDisplayRef.value = false;
	// onSaveRef.value = (v, h) => {};
});
使用这个办法也不行，希望底层优化好

**Comment by imzbf** [comment]
如果你的编辑页面会同时出现在单页应用里面，建议把`editorId`设置为何你每一篇文章ID相关的值。

出现这个问题就是因为每页的保存事件都注册到了一个集合里面。

调整的时候注意一下，`editorId`不会响应式更新，所以建议你这样做：

假设编辑`ID=100`的文章，地址是`/article/update/100`，你的路由配置`/article/update/:id`

```vue
<template>
  <md-editor :editor-id="editorId" />
</template>

<script setup>
import { useRoute } from 'vue-router';
const route = useRoute();

// editorId只能设置默认值，不能响应式更新
const editorId = route.params.id;
</script>
```

**Comment by duofanCoder** [comment]
3Q
