### ISSUE TITLE
字数统计问题

### ISSUE THREAD

**Issue by architectMymine** [imzbf/md-editor-v3#211]
与同样的博客文章在掘金等平台的字数统计相差比较大，我看了一下，好像是直接统计内容的长度的。有考虑说字数这个做一个获取方式吗，主要是想大概估算阅读时间这些功能。
补充：在某些md文档的统计插件也跟掘金这些平台获取的字数一样。

**Comment by imzbf** [comment]
> 与同样的博客文章在掘金等平台的字数统计相差比较大，我看了一下，好像是直接统计内容的长度的。有考虑说字数这个做一个获取方式吗，主要是想大概估算阅读时间这些功能。 补充：在某些md文档的统计插件也跟掘金这些平台获取的字数一样。

抱歉哈，这个功能最好参考模板自行扩展页脚功能。影响原因是：文章中存在用`svg`构成的图形等，统计方式被指向了不同的方向，公共组件不方便指定业务逻辑。

建议这边参考文档中的[扩展示例](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/pages/Preview/index.vue#L23)，扩展一个想要的统计字数的逻辑

通过`footers`属性设置隐藏默认的统计数字功能~

**Comment by architectMymine** [comment]
我在字节的md库中找到的word-count库，这个应该是比较准确的。作者如果可以的话，可以内置，我现在是直接页脚用这个插件统计
