### ISSUE TITLE
有没有获取焦点时触发的事件？

### ISSUE THREAD

**Issue by dxhuii** [imzbf/md-editor-v3#214]
有没有获取焦点时触发的事件？

比如我想在获取焦点的时候给编辑设置一个高度，默认的时候给一个比较小的高度

或者能默认支持自适应高度，达到最大高的时候，出现滚动条。(http://www.jacklmoore.com/autosize/) 这个库不错

还想问下，有没有把 toolbar 放底部的配置。
想做成类型这样的效果：
![image](https://user-images.githubusercontent.com/2328917/219956533-2cea37bb-b23d-47ea-85ad-68702b8b7888.png)

**Comment by dxhuii** [comment]
![image](https://user-images.githubusercontent.com/2328917/219955082-63c3379b-0588-48f4-81df-013c4618025d.png)
这个样式也不太友好，有时候设置比较少的按钮的时候。他不能自适应宽。

**Comment by imzbf** [comment]
事件和样式这边调整一下，但是点击后的逻辑等`2.9.0`后，需要自行利用对应事件实现。

关于头部工具栏放到底部区域，这个目前不会这样调整。因为页脚的样式和顶部相差较大。需要类似的功能，最好利用底部插槽自行扩展一下。

**Comment by dxhuii** [comment]
嗯，好的，用起来，挺好用的。谢谢大佬开源。

**Comment by imzbf** [comment]
2.9.0已支持该功能
