### ISSUE TITLE
支持调整滚动条位置

### ISSUE THREAD

**Issue by Nomango** [imzbf/md-editor-v3#216]
希望可以支持一下调整滚动条位置的功能，想在 v-model 的值变化时，自动将滚动条重置到顶部

**Comment by imzbf** [comment]
每次输入都置顶，这个好像不切合实际

**Comment by Nomango** [comment]
嗯，所以我想自己 watch 一下 content 变化，调整一下滚动条，但是没有找到调整滚动条的办法

**Comment by imzbf** [comment]
> 我用它做一个preview-only的展示功能，所以会有这种奇怪需求

如果是预览模式下，内容变化想回到顶部，这个组件做不到，因为滚动区域没有是外部设定的，你可以做的是在`onHtmlChanged`内容变化后的`nextTick`中去将你的滚动区域滚动至顶部，滚动方法参考[代码](https://github.com/imzbf/md-editor-v3/blob/develop/MdEditor/utils/index.ts#L151)，或者搜索引擎找`scrollTo`的文档

**Comment by Nomango** [comment]
试了一下，`document.getElementById('md-editor-v3-preview-wrapper')?.scrollTo({ top: 0 });` 是可以做到的，感谢
