### ISSUE TITLE
提个统计输入字数统计的建议： string-length 使用这个库来统计

### ISSUE THREAD

**Issue by dxhuii** [imzbf/md-editor-v3#217]
建议使用这个库：https://github.com/sindresorhus/string-length

参与： https://github.com/elk-zone/elk/blob/29b37e67c7675d65a554aac05f742922771484bf/components/publish/PublishWidget.vue#L69

**Comment by imzbf** [comment]
感谢建议，这个功能只是一个简单的页脚工具，不对业务内容进行关联。

可能有不同的同学会有不同的统计方案，所以，在页脚工具栏中提供了隐藏默认工具和扩展页脚工具的功能。这个建议留给需要参考的同学

**Comment by dxhuii** [comment]
嗯，好，这样也更灵活些。
