### ISSUE TITLE
MdEditor.config是否可以指定某个组件？

### ISSUE THREAD

**Issue by Nomango** [imzbf/md-editor-v3#218]
我有个页面有多个 MdEditor，其中一个需要特殊处理 renderer，但是 MdEditor.config 是全局生效的，是否有办法指定某个组件的 config 呢？

**Comment by imzbf** [comment]
这个做不到

**Comment by imzbf** [comment]
不复杂的，建议外部逻辑化。复杂的建议`fork`源码重构特殊版本

**Comment by Nomango** [comment]
那是否可以给 MdEditor 组件加一个 markedRenderer props 呢？

**Comment by imzbf** [comment]
1.x版本确实是这样做的，2.x将这些公共的部分提取出来。移除了组件的属性。`config`里的内容相当多，会让组件属性臃肿到难以维护。所以这边建议需求能统一最好，实在需要的话，建议`fork`组件后，添加你需要的配置内容。

**Comment by Nomango** [comment]
fork之后升级就变得困难了，我再想想别的办法吧
