### ISSUE TITLE
Support mermaid@10 and more versions

### ISSUE THREAD

**Issue by KanLai** [imzbf/md-editor-v3#219]
[object Promise]

mermaid

**Comment by imzbf** [comment]
what is it?

**Comment by KanLai** [comment]
就是  引入最新版本的 mermaid 10.0.0  不能解析 ，同步显示的结果是 [object Promise]

**Comment by KanLai** [comment]
> what is it?
就是 引入最新版本的 mermaid 10.0.0 不能解析 ，同步显示的结果是 [object Promise]

**Comment by imzbf** [comment]
`2.9.0+`以后会支持`mermaid@10`，但是默认还是`mermaid@9.4.0`，目前`mermaid@10`存在不少问题，包括但不限于[Error: Diagram error not found](https://github.com/mermaid-js/mermaid/issues/4140)，等待官方解决后切换为默认。

**Comment by imzbf** [comment]
2.9.0已发布
