### ISSUE TITLE
发布图片类内容，点击查看大图的时候，有一个BUG，点击空白或者图片，得多次才能关闭。你看下优化一下。

### ISSUE THREAD

**Issue by dxhuii** [imzbf/md-editor-v3#220]
或者增加一个开关，点击不打开大图也可以，再或者像github一样，点击弹出新窗口打开图片。

![image](https://user-images.githubusercontent.com/2328917/221342074-66ef6b98-b1f4-4aff-b1a4-459d1890435c.png)
点击图片，第一次是黑屏：
![image](https://user-images.githubusercontent.com/2328917/221342089-f75a262c-b3fb-4718-b650-4b1ef0fa6fd4.png)
点击一次黑屏：
![image](https://user-images.githubusercontent.com/2328917/221342105-3e9a210d-6224-444d-82d5-50c4b64e0356.png)
然后点很多下，图片才会关闭，
![image](https://user-images.githubusercontent.com/2328917/221342122-0771ca00-9e86-40c1-90d4-ad5dd36ae7f2.png)
![](https://pbs.twimg.com/media/Fpcp-n6X0AImjMn?format=jpg&name=large)
![](https://pbs.twimg.com/media/FpcqHhHWAAAOecl?format=jpg&name=large)
![](https://pbs.twimg.com/media/FpcqNztXsAADIv0?format=jpg&name=large)

**Comment by imzbf** [comment]
目前是支持设置点击图片的行为的。

只需要移除代码中`img`标签的`zoom`属性即可，具体的事件就根据自己的需要定义：

```js
import MdEditor from 'md-editor-v3';

MdEditor.config({
  markedRenderer(renderer) {
    renderer.image = (href, title, desc) => {
      return `<span class="figure"><img src="${href}" title="${title || ''}" alt="${
        desc || ''
      }" zoom><span class="figcaption">${desc || ''}</span></span>`;
    };

    return renderer;
  }
});
```

**Comment by imzbf** [comment]
关于点击图片变黑，这个问题方便提供一下环境吗？

- node版本:
- md-editor-v3版本:
- 创建项目的脚手架及版本:
- 是否ssr: 
- 更多:

**Comment by dxhuii** [comment]
node版本: v18.12.1
md-editor-v3版本: 2.8.1
创建项目的脚手架及版本: Nuxt
是否ssr: 是
chrome: 110.0.5481.177
macos: 13.2.1

**Comment by imzbf** [comment]
> node版本: v18.12.1 md-editor-v3版本: 2.8.1 创建项目的脚手架及版本: Nuxt 是否ssr: 是 chrome: 110.0.5481.177 macos: 13.2.1
> 
> ```js
> <MdEditor v-model="content" bg="!base !dark:#121212" preview-only />
> ```

感谢，这边尝试一下

**Comment by imzbf** [comment]
> 关于点击图片变黑，这个问题方便提供一下环境吗？
> 
> * node版本:
> * md-editor-v3版本:
> * 创建项目的脚手架及版本:
> * 是否ssr:
> * 更多:

我创建了个在线实例，没有发现类似问题，这个问题在旧版本出现过，已经优化过了。注意检查一下缓存和你这边的代码是否有影响，解决不了可以提供一份类似能够还原issue的在线项目，以供查找问题哈。
https://codesandbox.io/p/sandbox/jolly-galois-kiot8d

**Comment by imzbf** [comment]
点击空白问题无法还原，请尝试新版本是否存在问题，该问题将关闭

**Comment by dxhuii** [comment]
https://stackblitz.com/edit/github-swjr7u?file=pages%2Findex.vue  

花了点时间复现出来了，应该是循环了多次引起的，这个是放列表页渲染的。一次点击触发多次。

**Comment by imzbf** [comment]
加一个`editorId`，单页面存在多个编辑器`editorId`需要唯一，最好不是纯数字。
<img width="240" alt="image" src="https://user-images.githubusercontent.com/37092006/222964195-48487afe-8cb0-47f4-a86a-21c3d125507f.png">

**Comment by dxhuii** [comment]
> 

嗯，好了，谢谢。
