### ISSUE TITLE
在editor界面结束编辑后，跳转后页面不渲染

### ISSUE THREAD

**Issue by BeastHoo** [imzbf/md-editor-v3#221]
在editor界面结束编辑后，使用router.push()后跳转到其他页面不会渲染，控制台里面查看其他页面组件的html代码直接无了，必须刷新才能恢复正常

**Comment by imzbf** [comment]
方便提供一份还原问题的代码版本吗？

**Comment by imzbf** [comment]
无法还原描述的问题，该问题将关闭
