### ISSUE TITLE
五万个字符左右 - 渲染卡顿严重

### ISSUE THREAD

**Issue by beiming-tuling** [imzbf/md-editor-v3#222]
渲染卡顿严重

**Comment by beiming-tuling** [comment]
已进行文章拆分，坐等大佬更新 @imzbf

**Comment by imzbf** [comment]
2.9.1版本给`mermaid`添加了缓存，因为测试结果显示这个库编译过程占用了大部分时间，在多图表中测试中已将多次构建秒级等待降到百毫秒级，接近10倍速。但是首次仍然会很慢。

**Comment by imzbf** [comment]
这个问题将关闭，有关问题可以继续讨论
