### ISSUE TITLE
腾讯云上传图片后无法回显

### ISSUE THREAD

**Issue by lihuikun** [imzbf/md-editor-v3#223]
`
const onUploadImg = async (files, callback) => {
  const res = await Promise.all(
    files.map((file) => {
      return new Promise((rev, rej) => {
        const form = new FormData();
        form.append('file', file)
        console.log('form', form, file)
        initCOS(file, import.meta.env.VITE_BUCKET_NAME).then(res => {
          rev(import.meta.env.VITE_IMGURL + res)
        })
      });
    })
  );

  callback(res.map((item) => item));
}`
一定要上传form ？是否考虑支持直接上传file，而且有时上传图片callback没有返回图片链接

**Comment by imzbf** [comment]
上传的方式是开发者自己控制的，这只是一个常规的案例。只需要把上传后的图片可以直接访问的链接通过`callback(['https:/xxx.com/1.png', 'https:/xxx.com/2.jpg'])`这种方式回调就可以了

**Comment by lihuikun** [comment]
![image](https://user-images.githubusercontent.com/83935370/223940657-7b961007-83db-455a-a792-b0ae4ee32603.png)
并没有回显到输入框位置，我callback(['https:/xxx.com/1.png', 'https:/xxx.com/2.jpg'])

**Comment by lihuikun** [comment]
callback(['https:/xxx.com/1.png', 'https:/xxx.com/2.jpg'])这样子最终无法回显到输入框，总不能让用户打开控制台输入吧

**Comment by lihuikun** [comment]
找到原因了，子组件使用props无法回显图片，是否考虑支持一下
const text = computed({ get: () => props.text, set: val => emits('upload:text', val) })
我是进行二次封装，后期有多个页面要使用

**Comment by lihuikun** [comment]
1438828140，加qq细聊一下吧

**Comment by imzbf** [comment]
> 找到原因了，子组件使用props无法回显图片，是否考虑支持一下 const text = computed({ get: () => props.text, set: val => emits('upload:text', val) }) 我是进行二次封装，后期有多个页面要使用

没有看出来你的逻辑和上传图片逻辑的相关性

**Comment by imzbf** [comment]
> 1438828140，加qq细聊一下吧

作者没有太多时间去处理消息，困扰的问题及确认的bug在这里能得到一个准确的回复

**Comment by lihuikun** [comment]
`<template>
  <md-editor v-model="text" @onUploadImg='onUploadImg' />
</template>

<script setup>
import { computed, ref } from 'vue';
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
import { initCOS } from '@/utils/upload';

const props = defineProps({ text: String })
const emits = defineEmits(['upload:text'])
const text = computed({
  get: () => props.text,
  set: val => emits('upload:text', val)
})
console.log('text', text)
const onUploadImg = async (files, callback) => {
  const res = await Promise.all(
    files.map((file) => {
      return new Promise((rev, rej) => {
        initCOS(file, import.meta.env.VITE_BUCKET_NAME).then(res => {
          rev(import.meta.env.VITE_IMGURL + res)
        })
      });
    })
  );
  callback(text.value + res);
}
</script>
`
这里的callback可以拿到图片数组，但是子组件通过父组件props传值就无法回显到输入框，你可以试试v-model:text进行

**Comment by lihuikun** [comment]
![image](https://user-images.githubusercontent.com/83935370/223968792-c22783b0-252f-4a94-a254-e97109e1876c.png)
这是二次封装的子组件代码，图片可以上传，如果是子组件就无法回显到输入框的位置，

**Comment by lihuikun** [comment]
> ![image](https://user-images.githubusercontent.com/83935370/223968792-c22783b0-252f-4a94-a254-e97109e1876c.png) 这是二次封装的子组件代码，图片可以上传，如果是子组件就无法回显到输入框的位置，

如果是直接使用是没有问题，但是想要二次封装（子组件使用props接收），callback上传之后的图片url就无法回显到输入框

**Comment by imzbf** [comment]
应该是`update:text`，
我给写了一个使用`v-model`的demo，你参考一下


CommonEditor.vue

```vue
<template>
  <md-editor v-model="text" @on-upload-img="uploadImg" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import MdEditor from 'md-editor-v3';
import axios from '../../utils/request';

import 'md-editor-v3/lib/style.css';

const emits = defineEmits(['update:modelValue']);

const props = defineProps({
  text: {
    type: String,
    default: ''
  }
});

const text = computed({
  get: () => props.text,
  set: (val) => emits('update:modelValue', val)
});

const uploadImg = async (files: Array<File>, callback: (urls: string[]) => void) => {
  const res = await Promise.all(
    files.map((file) => {
      return new Promise((rev, rej) => {
        const form = new FormData();
        form.append('file', file);

        axios
          .post('/api/img/upload', form, {
            headers: {
              'Content-Type': 'multipart/form-data'
            }
          })
          .then((res) => rev(res))
          .catch((error) => rej(error));
      });
    })
  );

  callback(res.map((item: any) => item.data.url));
};
</script>
```

```vue
<template>
  <CommonEditor v-model="text" />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import CommonEditor from './CommonEditor.vue';

const text = ref('# heading');
</script>
```

**Comment by lihuikun** [comment]
还是有一定几率无法回显，鼠标选择输入框后，点击上传图片，上传成功后有时无法回显

**Comment by imzbf** [comment]
> 还是有一定几率无法回显，鼠标选择输入框后，点击上传图片，上传成功后有时无法回显

这个需要你那边调试看是哪个环节出问题了，这边无法还原问题，该问题将关闭。
