### ISSUE TITLE
Auto scroll not working well

### ISSUE THREAD

**Issue by some-user123** [imzbf/md-editor-v3#229]
First of all, I really like this component and your work! Thanks a lot!

I found one issue though.

The auto scrolling does not seem to work if you include, e.g. large images. Markdown content and preview get out of sync then and you see different parts of the document in the preview than in the editor.

I found a markdown editor that synchronizes the scrolling pretty well even with large images. Unfortunately, it seems unmaintained :-( But maybe you can get some inspiration from this project: https://github.com/code-farmer-i/vue-markdown-editor

**Comment by imzbf** [comment]
This feature has been add in `^3.0.0`. Have a try~
