### ISSUE TITLE
销毁组件的时候 报错 大佬这个是怎么回事啊

### ISSUE THREAD

**Issue by janiokq** [imzbf/md-editor-v3#23]
编辑器功能所有一切都是正常的
当我退出页面的时候时候 就提示这个错误
![image](https://user-images.githubusercontent.com/10770735/138300269-63fd1268-648f-40db-a4f2-de1ab71b2aec.png)
![image](https://user-images.githubusercontent.com/10770735/138300315-15f269ef-f977-45d6-bc12-97e064e2fd69.png)
这个变量是null

**Comment by imzbf** [comment]
> 请问你用的vite还是vue-cli创建的项目，如果是vite的话，尝试一下build生产版本，然后看看生产环境会不会有这个问题呢？
> 
> 这个问题在我开发文档时遇到过，只是开发环境会出现，目前还没有定位到是编辑器还是`开发环境`的问题。
