### ISSUE TITLE
emoji可以设计为连续输入吗

### ISSUE THREAD

**Issue by rheet-dev** [imzbf/md-editor-v3#230]
现在是点击，会修改原来的emoji，可以改为连续输入吗？
比如回复表情的时候，会回复多个。现在只能输入一个，点击emoji光标空白处，才能再输入第二个emoji。

**Comment by imzbf** [comment]
emoji扩展组件返回的[配置](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/EmojiExtension/index.vue#L44)中`select`设置为`false`就可以了

```ts
const emojiHandler = (emoji: string) => {
  const generator: InsertContentGenerator = () => {
    return {
      targetValue: emoji,
      // 这里从true改为false
      select: false,
      deviationStart: 0,
      deviationEnd: 0
    };
  };

  props.onInsert(generator);
};
```

**Comment by RickTe** [comment]
@imzbf 修改`select`的值为false后，选择表情，鼠标光标不见了，有什么解决办法吗？

**Comment by imzbf** [comment]
> @imzbf 修改`select`的值为false后，选择表情，鼠标光标不见了，有什么解决办法吗？

失焦了，我调整了一下，先使用一下`beta`版本

```shell
yarn add md-editor-v3@beta
```
