### ISSUE TITLE
连续4个空格后输入与两次tab键输入空白后再输入任意内容报错

### ISSUE THREAD

**Issue by hjyyang** [imzbf/md-editor-v3#233]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/31732570/226515223-8c2cd9b2-7414-43fd-87a8-8c0445200870.png">

**Comment by imzbf** [comment]
2.10.0的没有发现这个问题，你那边的版本和环境是？

**Comment by hjyyang** [comment]
这边的版本是
md-editor-v3:   v2.10.0
node:  v16.17.0
vue: v3
typescript: 4.5.5

**Comment by hjyyang** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/31732570/226652711-357c7b34-32bc-48e8-8ea0-79f694d210a6.png">
没有配置highlight，是最基本的使用

**Comment by imzbf** [comment]
这边没有想到能导致这个问题的原因，只能给出一个规避这个问题的建议：

1. 在你的项目里安装`highlight.js`

  ```shell
  yarn add highlight.js
  ```

2. 把实例配置到编辑器中

  ```js
  import MdEditor from 'md-editor-v3';
  import hljs from 'highlight.js';
  
  MdEditor.config({
    editorExtensions: {
      highlight: {
        instance: hljs
      }
    }
  });
  ```


这个做法和默认的行为相同，只过不不再添加`highlight.js`的`script`标签到页面中。
