### ISSUE TITLE
disable shortcut keys

### ISSUE THREAD

**Issue by doproperly** [imzbf/md-editor-v3#234]
First, It's a very convenient markdown editor :) 
I always use it gratefully. I like it so much. Thank you !

But I want to know one ..
That's how to disable shortcut  keys.
I looked all over the library, but couldn't find an option or way to disable it. Is it really not there (or are you planning..)?

**Comment by imzbf** [comment]
I'm glad this can help you.

Cannot disable shortcut key at present, but it is only valid for element `textarea`, this may not affect the overall project.

**Comment by imzbf** [comment]
Starting with `3.0.0`, shortcut keys can be customized.

Just wait for it to be released

**Comment by imzbf** [comment]
This feature has been added in version 3.0.0.

And Its example is [here](https://imzbf.github.io/md-editor-v3/en-US/demo#%E2%9C%82%EF%B8%8F%20Delete%20Shortcut%20Key)
