### ISSUE TITLE
希望可以增加个代码块组的语法

### ISSUE THREAD

**Issue by Ocyss** [imzbf/md-editor-v3#236]
类似这种
![image](https://user-images.githubusercontent.com/68412205/227700036-ca715634-a084-4390-aedf-2ebbd5e61894.png)

**Comment by imzbf** [comment]
这边研究下可不可行

**Comment by imzbf** [comment]
这个功能在3.0.0版本中添加了。

这是这个模块的[语法](https://imzbf.github.io/md-editor-v3/zh-CN/grammar#%F0%9F%97%84%20%E4%BB%A3%E7%A0%81%E7%BB%84%E5%90%88)

**Comment by Ocyss** [comment]
非常感谢，但最好颜色上区分一下，做点分界线可能会更好看

**Comment by vneoapb** [comment]
可以有长代码折叠这样的效果吗
