### ISSUE TITLE
请问如何添加视频链接，展示视频组件，如youtube视频之类的

### ISSUE THREAD

**Issue by azhengyongqin** [imzbf/md-editor-v3#238]

**Comment by imzbf** [comment]
目前没有markdown短语法来支持展示视频，但是支持直接使用html标签。所以，你可以这样做：

```html
<video controls="controls" src="/static/屏幕录制2023-03-29.mov">屏幕录制2023-03-29.mov</video>
```

可以了解一下添加工具栏组件，快捷上传后显示的方式，参考[表情扩展](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/EmojiExtension/index.vue)。

在`3.0.0`之后，还可以支持绑定快捷键来支持你的功能（还在开发中）。
