### ISSUE TITLE
請問手機端顯示代碼區塊的問題

### ISSUE THREAD

**Issue by york11122** [imzbf/md-editor-v3#239]
謝謝作者，非常好用的編輯器

previewOnly = true，markdown內容中有代碼區塊，
視窗縮放或者直接用手機開啟網頁，視窗較窄的時候，
網頁會被代碼區塊撐開，並不會像編輯模式時，代碼區塊有水平scroll bar可以滾動內容，
不知道可以如何調整

以下是問題的畫面截圖
![Windripple](https://user-images.githubusercontent.com/21119213/230121961-ea24ce97-f8da-4762-822b-740a96f1e802.gif)

以下是編輯時的效果
![編輯時](https://user-images.githubusercontent.com/21119213/230123914-6a2325f9-dbab-42dc-a0bb-77065d5af67b.gif)

**Comment by imzbf** [comment]
你看看图一中的滚动条是什么元素的呢？文章展示的地方没有固定宽度，它是适应你的外部元素宽度的。出现整页的滚动条可能是外面什么元素固定了最小宽度

**Comment by york11122** [comment]
檢查後確實是我自己的問題，不好意思造成您的困擾。
感謝作者不厭其煩的回答
