### ISSUE TITLE
请问如何控制通过条件才写进markdown

### ISSUE THREAD

**Issue by a99463820** [imzbf/md-editor-v3#243]

**Comment by a99463820** [comment]
我尝试使用 markedRenderer 但是并没有生效只是可以控制渲染出来的文本，markdown文本还是可以显示出来
![图片1](https://user-images.githubusercontent.com/35280797/232714746-1d49f310-4007-4115-8027-261947a0ed24.PNG)
![图片2](https://user-images.githubusercontent.com/35280797/232714766-34733b32-f158-451f-9c63-4f8f953a4334.PNG)

**Comment by imzbf** [comment]
你是想对输入的内容做校验？
