### ISSUE TITLE
输入代码时，那个代码框会一闪一闪的

### ISSUE THREAD

**Issue by vvandk** [imzbf/md-editor-v3#244]
当前我正在写一个打字机功能，会一点一点的输入，会遇到代码黑色背景框一闪一闪的

比如以下代码

```python
print("")
```

每次回车就会闪

请问这个能解决吗

**Comment by imzbf** [comment]
没太明白实际是怎么操作的，是左边的输入框会一点点的输入吗

**Comment by vvandk** [comment]
https://user-images.githubusercontent.com/108704266/233563553-f406ffb7-ec37-496a-b2f2-95a405092405.mp4

**Comment by vvandk** [comment]
就像视频中显示的这样，我是一点一点渲染的，但是到代码那里总是会闪，看起来很不舒服，想问一下这个能改吗

**Comment by imzbf** [comment]
了解，这个问题我在正在开发的`3.0`版本中已经处理了，如果你目前只是想用仅预览模式又着急解决的话，可以尝试一下安装`3.0`的`beta`版本

```sh
yarn add md-editor-v3@beta
```

这个版本还没有正式发布，因为还有编辑相关的问题正在处理，不过仅预览模式应该没有问题。

**Comment by vvandk** [comment]
感谢，更新到3.0版本已解决
