### ISSUE TITLE
previewTheme="default" 是，# 一级标题显示异常，font-size只有16px

### ISSUE THREAD

**Issue by fym0121** [imzbf/md-editor-v3#246]
![image](https://user-images.githubusercontent.com/11145391/233586402-936fa9b0-970a-4be2-b41c-f034cd57e8a9.png)

**Comment by imzbf** [comment]
这个应该是受了你的项目里面的样式影响，你点点这个小按钮，看看是哪里定义的冲突的样式，调整一下优先级就可以了

<img width="348" alt="image" src="https://user-images.githubusercontent.com/37092006/233602576-e586fbf4-fc9f-40f7-b215-a29f855308cc.png">
