### ISSUE TITLE
create-vue创建vue项目导入的默认css会导致工具栏异常

### ISSUE THREAD

**Issue by kele98** [imzbf/md-editor-v3#247]
创建的项目默认导入了@import './base.css';
这里面的position设置会导致编辑器工具栏无法正常显示
*::after {
  box-sizing: border-box;
  margin: 0;
  position: relative;
  font-weight: normal;
}
前端小白，被这个问题折磨了好久，能不能在readme中增加个相关提示

**Comment by imzbf** [comment]
我看这段代码对组件没有影响？

给一下还原这个问题的基础代码，这边协助你看看

**Comment by kele98** [comment]
你好 这是用最新版本vue创建的项目 https://github.com/kele98/md-editor-test
问题在编辑器工具栏中通过opacity和z-index控制显示的地方，比如标题的子菜单，上传图片的子菜单，表格等
我尝试了最新的chrome和edge都能复现这个情况
只要在浏览器调试工具关闭下面的position就能恢复正常
*, *::before, *::after {
    box-sizing: border-box;
    margin: 0;
    position: relative;
    font-weight: normal;
}

**Comment by imzbf** [comment]
看到了，原因就是给所有节点都添加了`position`属性，建议合理设置`css`属性，这种全局性的最好不要在项目中存在（作者也不理解为何要这样给全部节点都设置`relative`，这样设定明显的坏处就是，组件针对`static`设置的逻辑关系直接被破坏了，而我们几乎不会去主动将一个元素的`position`属性设置为`static`），参照各个大厂的基础设置来处理化样式。

感谢你的提示
