### ISSUE TITLE
Toolbar buttons are not visible while using with Astro/vue  

### ISSUE THREAD

**Issue by geminigeek** [imzbf/md-editor-v3#249]
hi,

i am trying to use md-editor-v3 with astro + vue integration , the editor is loading fine, but the icons are not loading , seems like a style issue , here is a reproduction url 

https://stackblitz.com/edit/github-qtxzqs?file=src%2Fcomponents%2FCreatePost.vue,src%2Fpages%2Findex.astro,package.json&on=stackblitz

**Comment by geminigeek** [comment]
Hi,
i figured it out , i need to use client:only for the icons to show , leaving it here for someone who makes silly mistake like me

**Comment by PG-Momik** [comment]
Hi @geminigeek, can u explain your fix. I'm facing the same issue.

**Comment by geminigeek** [comment]
hi,

i am using it with astro , so to load the wrapper vue component which contain the editor component ,i am using it like this in an .astro page

<MdEditorWrapper client:only />

**Comment by PG-Momik** [comment]
I did see `<CreatePostMavon client:only="vue"/>` code in the stackblitz code, so thats what it was. Do you happen to know a workaround for just vue without astro ?

**Comment by geminigeek** [comment]
may be wrap it into some client only component or ignore from ssr
