### ISSUE TITLE
引用外链cdn 在ios系统上总是加载很慢且有一定概率失败  导致空白时间过长

### ISSUE THREAD

**Issue by zhubufang** [imzbf/md-editor-v3#251]
引用外链cdn 在ios系统上总是加载很慢且有一定概率失败  导致空白时间过长，能否提供配置本地引入cdn 资源

**Comment by zhubufang** [comment]
![image](https://user-images.githubusercontent.com/40162775/234335203-d1e71b05-8ebe-465b-86fa-ee9114ee831b.png)
这些事例是个啥 有没有文档

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

这里有一个替换的示例

**Comment by zhubufang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
