### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by luezl** [imzbf/md-editor-v3#252]
如果内容是  "## mermaid"   会出错,请确认

**Comment by imzbf** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/37092006/234499234-e4659a03-bc6b-46bb-967e-c51cd60e3650.png">
试了一下，没有发现你说的？是不是还有其他的操作或者内容？

**Comment by imzbf** [comment]
这个看起来和内容不相关，和环境相关，这边还原不了问题，麻烦你这边协助调试一下，具体像下面这样操作

在`Sources`下面找到你的`index-e808448f.js`文件，搜索`initialize`，然后打上断点，刷新页面进入断点，查看一下`i`这个对象的信息。

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/37092006/234536471-cb96205d-0898-4193-968d-40ad42f6f30f.png">

我这里是`r`，就是`initialize`前的变量名称

**Comment by imzbf** [comment]
建议在你的项目中安装`mermaid`后，通过`MdEditor.config`配置实例来规避类似的问题
