### ISSUE TITLE
icon 无法显示！

### ISSUE THREAD

**Issue by xuzeznb** [imzbf/md-editor-v3#255]
iconfontUrl 无法访问 ，导致工具栏的icon也无法显示！

**Comment by imzbf** [comment]
如果你的网络屏蔽了阿里的矢量图标库，你可以利用别的可能访问的网络把文件下载下来放到你的项目可以直接访问的地方，使用`MdEditor.config`配置iconfont的请求路径为你自己的。

```js
MdEditor.config({
  editorExtensions: { iconfont: /xxx' }
})
```

或者在你的项目里面`import`进入，给编辑器添加`noIconfont`的属性。

[参考](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%A4%9E%F0%9F%8F%BC%20noIconfont)
