### ISSUE TITLE
希望添加html转markdown文本

### ISSUE THREAD

**Issue by hjyyang** [imzbf/md-editor-v3#256]
在存储到数据库的时由于从编辑器拿到的html结构再输入到编辑器中并不能成为markdown文本，导致从数据库中拿到markdown文本还要重新编译为html。能否添加html转为markdown文本功能，这样只需要存储html文本即可

**Comment by imzbf** [comment]
html转markdown这个特性应该不会在编辑器这个组件里植入，它不是编辑器的特性。

这个可以利用`unified`去反编译，可以参考一下
