### ISSUE TITLE
加空格变成代码块

### ISSUE THREAD

**Issue by luckyfloret** [imzbf/md-editor-v3#257]
环境：
   vue3+ts+md-editor-v3: "3.0.0"

加几个空格就变成了代码块，这是bug吗
![image](https://user-images.githubusercontent.com/52860702/235826762-9d421baa-1670-404a-bb1a-938c6b808b75.png)

**Comment by imzbf** [comment]
这个不是，但是作者也不清楚这个是什么规范。

至少我看`marked`，`markdown-it`还有`unified`都是这样做的

**Comment by luckyfloret** [comment]
@imzbf 那我想居中或者右对齐咋办
