### ISSUE TITLE
配置本地mermaid时流程图加载异常

### ISSUE THREAD

**Issue by yanyunling** [imzbf/md-editor-v3#261]
版本：v3.0.0
前提：已正确配置本地mermaid如下：
```
{
  editorExtensions: {
    mermaid: {
      instance: mermaid
    }
  }
}
```
现象：首次加载页面时，或再次通过编辑器修改内容时，可正确显示图形；当切换不同的文档内容时，图形就无法显示了。使用默认cdn时没有此异常情况，且应该和mermaid版本无关。

首次刷新：
![image](https://user-images.githubusercontent.com/32293949/236375122-b8949b6a-8832-459b-8b1e-f0d29b7dadf1.png)

切换内容变量后，再切换回有流程图的内容变量：
![image](https://user-images.githubusercontent.com/32293949/236375217-75fc6eb6-fb67-4b43-b879-3964d74b65c1.png)

**Comment by imzbf** [comment]
切换是怎么实现的？我像下面这样尝试了一下，还能运行
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/37092006/236390336-d563b2be-c40b-4f40-9d1d-3355b6b2ea53.png">

**Comment by imzbf** [comment]
是不是切换的时候切换了路由，文章页面有组件更新

**Comment by yanyunling** [comment]
其实就是 v-model 的值直接改变，不知道我这为什么不行
![动画2](https://user-images.githubusercontent.com/32293949/236391394-667584d5-ff8b-46a9-af61-0891fbd65418.gif)

**Comment by yanyunling** [comment]
> 是不是切换的时候切换了路由，文章页面有组件更新

没有切换路由，也未重新渲染组件

**Comment by imzbf** [comment]
还原不了问题，我尝试在可能的地方调整下逻辑，完成后会发布临时版本，这边需要协助测试一下😃

**Comment by yanyunling** [comment]
> 还原不了问题，我尝试在可能的地方调整下逻辑，完成后会发布临时版本，这边需要协助测试一下😃

好的

**Comment by yanyunling** [comment]
我发现问题了，不好意思，我在更新内容时同时更新了组件的key，导致了组件重新渲染，无法加载出流程图
