### ISSUE TITLE
目录切换主题后，高亮变成第一个

### ISSUE THREAD

**Issue by RickTe** [imzbf/md-editor-v3#262]
**主题切换，目录存在的问题**：
1. 切换后高亮总是跑到第一个。
2. 或，第一个先高亮，然后迅速高亮正确的位置

**官网例子**：
https://imzbf.github.io/md-editor-v3/en-US/index

**操作步骤**：
1. 点击右侧工具栏，调出目录
2. 点击下方任意一个目录
3. 切换主题

**Comment by imzbf** [comment]
在4.0.0里优化了这个问题，注意新版本的引用方式
