### ISSUE TITLE
编辑器内容为空时，点击没有关标

### ISSUE THREAD

**Issue by RickTe** [imzbf/md-editor-v3#264]
**问题描述**：
1. 当编辑器内容为空时，没有光标

**官网例子**：
https://imzbf.github.io/md-editor-v3/en-US/index

**操作步骤**：
1. 清空编辑器内容，光标消失
2. 点击编辑器，没有光标

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/commit/dddd631b661e439651a9f3d89352eeba4743d6eb

在下个大版本修复了，还在写文档测试

**Comment by imzbf** [comment]
这个在4.0.0中优化了
