### ISSUE TITLE
如果存在同名的标题，点击目录定位错误

### ISSUE THREAD

**Issue by RickTe** [imzbf/md-editor-v3#266]
**问题描述**：
如果存在同名的标题，点击目录定位错误，如存在两个“# 1111”，点击第二个“# 1111”，定位到的是第一个

**官网链接**：
https://imzbf.github.io/md-editor-v3/en-US/index

**操作步骤**
输入内容：
```
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
# 1
# 2
```
点击目录，同名的只定位到第一个

**Comment by RickTe** [comment]
希望我描述清楚了

**Comment by imzbf** [comment]
默认的标题的id是你的标题内容，解决这个问题的方法是使用`mdHeadingId`重新定义id，参考文档：https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8E%B1%20mdHeadingId

**Comment by xfstu** [comment]
> 默认的标题的id是你的标题内容，解决这个问题的方法是使用`mdHeadingId`重新定义id，参考文档：https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8E%B1%20mdHeadingId

@imzbf  好的，谢谢作者，搜了一下issue，关键字没覆盖，没找到就提了一个bug，没想到23年就提出来了，不好意思没注意看文档😁
