### ISSUE TITLE
换行问题

### ISSUE THREAD

**Issue by Big0range** [imzbf/md-editor-v3#27]
敲下回车时 并没有实现换行效果

**Comment by imzbf** [comment]
方便给个代码地址还原下问题么，这边没有发现类似的问题

**Comment by Big0range** [comment]
```
<template>
  <div>
    <editor v-model="text" editorClass="editor" :pageFullScreen="false"></editor>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import Editor from 'md-editor-v3'
import 'md-editor-v3/lib/style.css'
export default defineComponent({
  components: {
    Editor
  },
  setup() {
    const text = ref(`# H1`)
    return {
      text
    }
  }
})
</script>

```
运行环境: windows 10 Chrome浏览器

**Comment by imzbf** [comment]
> 运行环境: windows 10 Chrome浏览器

请问编辑器的版本是？

**Comment by Big0range** [comment]
版本 94.0.4606.81（正式版本） （32 位）
我测试了下 回车必须敲两下才可以换行,而有的时候又只需要敲一下
比如说上一行是标题(# xxx) 一次回车就可以换行,
如果是普通段落的话,则需要按两次回车

**Comment by imzbf** [comment]
请问你在[文档](https://imzbf.github.io/md-editor-v3/)页面的编辑器示例中会出现该问题吗？如果没有，最好能提供一个临时的代码仓库供还原问题，这边才能正确的解决你的问题。

**Comment by Big0range** [comment]
![1637117622(1).jpg](https://pic.rmb.bdstatic.com/bjh/b7f1ff80a9ed5968caf6fc08fd74d879.png)
会的呢,情况是一样的

**Comment by imzbf** [comment]
在`v1.7.0`版本后已修复该问题

**Comment by Jack-hyt** [comment]
> 在`v1.7.0`版本后已修复该问题

我用的1.11.0还是不能识别，还是要敲两下回车

**Comment by Jack-hyt** [comment]
vue版本是3.2.13
