### ISSUE TITLE
版本号2.11.3，预览模式本地正常，打包时报错

### ISSUE THREAD

**Issue by 18310035303** [imzbf/md-editor-v3#273]

**Comment by imzbf** [comment]
报什么错，给个能还原问题的基础环境看看

**Comment by 18310035303** [comment]
error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'cloneVNode' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'computed' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'createVNode' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'defineComponent' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'inject' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'isVNode' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'mergeProps' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'nextTick' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'onBeforeUnmount' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'onMounted' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'provide' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'reactive' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'ref' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'toRef' from non EcmaScript module (only default export is available)

 error  in ./node_modules/md-editor-v3/lib/md-editor-v3.mjs

Can't import the named export 'watch' from non EcmaScript module (only default export is available)

**Comment by 18310035303** [comment]
vue版本号3.2.47，我使用的是webpack打包

**Comment by imzbf** [comment]
我尝试使用`vue create demo`创建了webpack的环境，但是开发和构建也无法还原你描述的问题。可能是模板的依赖比你这边的新了。我找了一下相关错误的提示，你参考一下看能修复你的问题不

https://github.com/vuejs/pinia/issues/675
