### ISSUE TITLE
How to install and enable the emoji extension

### ISSUE THREAD

**Issue by StefanFlaschko** [imzbf/md-editor-v3#275]
In the docs there is no description on how to install or enable the emoji extension. Could you please describe how to do that? 
Thanks a lot :)

**Comment by imzbf** [comment]
If you want emoji for the document page, there is the [source code](https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/EmojiExtension/index.vue), and : 

- Usage: https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/pages/Preview/index.vue#L19
- Config: https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/pages/Preview/staticConfig.ts#L26

If you want to use it as a plugin of `markdown-it`, install [markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji), and config like [this](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%92%B4%20Config%20Editor)
