### ISSUE TITLE
使用vite+vue3构建项目的时候，解析md字符有个提示，

### ISSUE THREAD

**Issue by zou-hong-run** [imzbf/md-editor-v3#278]
![image](https://github.com/imzbf/md-editor-v3/assets/65335712/48aee45d-c1dc-4360-992b-17892217728f)
![image](https://github.com/imzbf/md-editor-v3/assets/65335712/ed67d37d-abb2-45c3-95c3-14dec58c1b6c)
看着很难受

**Comment by zou-hong-run** [comment]
解决了，真不错啊啊啊啊啊

**Comment by imzbf** [comment]
嗯，在项目里安装一下这个依赖就可以了，下个版本会在编辑器中统一安装，还没发布，只是修改了

**Comment by imzbf** [comment]
`4.0.3`发布中更新了这个问题
