### ISSUE TITLE
添加sanitize处理之后代码和公式没有正确渲染

### ISSUE THREAD

**Issue by kuige** [imzbf/md-editor-v3#280]
<img width="828" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/8212800/c5aa83d6-b612-48c4-8df5-78c89dacf0d8">

按照这里的处理方式，代码、公式、表格、json和yaml等都没有正确渲染了，

<img width="822" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/8212800/a3e7953c-9834-432b-b1c7-5c6eac707066">
<img width="506" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/8212800/9e47a644-3494-4c5e-ada4-a62750e8c31d">

**Comment by kuige** [comment]
如何不通过把函数传给MdEditor的方式，而是先在外面调用sanitize函数处理好文本，再把文本传给MdEditor是没有问题的

**Comment by imzbf** [comment]
这个没办法保证处理html的库的结果，那个只是使用示例，不是建议直接使用它，最好能根据你的需求处理危险的html，你的反馈中应该是大部分html都被这个库转义了，导致你只能看到文本

**Comment by kuige** [comment]
```
<MdEditor v-model="sanitizeCode" />
const code = '这是代码示例'
const sanitizeCode = ref(sanitizeHtml(code))

```
这样是没问题的，如果改为下面那样就没有正确渲染

```
<MdEditor v-model="code" :sanitize="sanitizeHtml" />
const code = '这是代码示例'

```
所以是不是当做函数传给组件做了其他处理？

**Comment by imzbf** [comment]
> ```
> <MdEditor v-model="sanitizeCode" />
> const code = '这是代码示例'
> const sanitizeCode = ref(sanitizeHtml(code))
> ```
> 
> 这样是没问题的，如果改为下面那样就没有正确渲染
> 
> ```
> <MdEditor v-model="code" :sanitize="sanitizeHtml" />
> const code = '这是代码示例'
> ```
> 
> 所以是不是当做函数传给组件做了其他处理？

`sanitize`是对编译成的`html`做处理，上面的方式是对`markdown`文本处理。所以表现不一样。

刚去找了下`markdown-it`的[文档](https://github.com/markdown-it/markdown-it/blob/master/test/fixtures/markdown-it/xss.txt)，好像内部就有对危险标签做处理，这个功能其实现在不需要自己手动添加了

**Comment by imzbf** [comment]
> > ```
> > <MdEditor v-model="sanitizeCode" />
> > const code = '这是代码示例'
> > const sanitizeCode = ref(sanitizeHtml(code))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样是没问题的，如果改为下面那样就没有正确渲染
> > ```
> > <MdEditor v-model="code" :sanitize="sanitizeHtml" />
> > const code = '这是代码示例'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 所以是不是当做函数传给组件做了其他处理？
> 
> `sanitize`是对编译成的`html`做处理，上面的方式是对`markdown`文本处理。所以表现不一样。
> 
> 刚去找了下`markdown-it`的[文档](https://github.com/markdown-it/markdown-it/blob/master/test/fixtures/markdown-it/xss.txt)，好像内部就有对危险标签做处理，这个功能其实现在不需要自己手动添加了

这个是建立在版本`>=3.0.0`上的

**Comment by kuige** [comment]
> 

这个是指MdEditor的版本`>=3.0.0`吗？我用了MdEditor 3.0.1的版本，如果输入以下字符还是有问题`<code><iframe src=# onload=alert(document.cookie)></code>`

```
<MdEditor v-model="code" />
const code = '<code><iframe src=# onload=alert(document.cookie)></code>'
```

会弹窗显示cookie

**Comment by imzbf** [comment]
编辑器开启了嵌入html的模式，所以没有处理iframe标签，其实这里你可以不使用`sanitize-html`库，单独转义`<iframe`即可。

**Comment by kuige** [comment]
嗯，除了iframe标签之外，a标签也有问题

```
<MdEditor v-model="code" />
const code = '<a href="#" onclick="alert(document.cookie)">test</a>'
```

这个点击也会弹出cookie

这些都只能单独处理吗？

**Comment by kuige** [comment]
> > ```
> > <MdEditor v-model="sanitizeCode" />
> > const code = '这是代码示例'
> > const sanitizeCode = ref(sanitizeHtml(code))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样是没问题的，如果改为下面那样就没有正确渲染
> > ```
> > <MdEditor v-model="code" :sanitize="sanitizeHtml" />
> > const code = '这是代码示例'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 所以是不是当做函数传给组件做了其他处理？
> 
> `sanitize`是对编译成的`html`做处理，上面的方式是对`markdown`文本处理。所以表现不一样。
> 
> 刚去找了下`markdown-it`的[文档](https://github.com/markdown-it/markdown-it/blob/master/test/fixtures/markdown-it/xss.txt)，好像内部就有对危险标签做处理，这个功能其实现在不需要自己手动添加了

`sanitize`是对编译成的`html`做处理的时候可以做到保留转义符号吗？单独使用sanitize函数的时候没有过滤转义符号的

**Comment by imzbf** [comment]
> 嗯，除了iframe标签之外，a标签也有问题
> 
> ```
> <MdEditor v-model="code" />
> const code = '<a href="#" onclick="alert(document.cookie)">test</a>'
> ```
> 
> 这个点击也会弹出cookie
> 
> 这些都只能单独处理吗？

可以了解一下需要转义的部分，因为如果直接处理a标签的话，你文章中的所有超链接都不能用了，这可能并不是期望的，就和使用那个转义的库一样，把不该转义的转义了，应该正常显示的内容都不显示了

**Comment by kuige** [comment]
换成DOMPurify来处理就可以了，https://github.com/cure53/DOMPurify
