### ISSUE TITLE
Insert in the current position?

### ISSUE THREAD

**Issue by ikkysleepy** [imzbf/md-editor-v3#284]
How do I get the current position to Insert my images. I have this, which works but I wanted to insert the images in the current cursor position. I have a custom toolbar button that I am calling to open a new view to select images and then I am processing the images and inserting them.

```
        let selectedImages = '';
        images.map(async (photo) => {
            selectedImages = selectedImages + `\r![](${photo.base_url})\r\n`;
        });

        editorRef.value?.insert(() => {
            return {
                targetValue: `${selectedImages}`,
                select: true,
                deviationStart: 0,
                deviationEnd: 0
            };
        });
```

I didn't see how to get the current cursor position, is this possible?

**Comment by imzbf** [comment]
Yes, it does work. `targetValue` is always inserted into current cursor position.
