### ISSUE TITLE
Error: Dynamic require of "punycode" is not supported

### ISSUE THREAD

**Issue by Ya-hui** [imzbf/md-editor-v3#285]
我尝试这样使用
```vue
<template>
    <div v-for="item in list">
        <MdPreview v-model="item.content" preview-only noHighlight noMermaid noKatex />
    </div>
</template>

<script setup>
import { MdPreview } from 'md-editor-v3';
import 'md-editor-v3/lib/preview.css';
</script>
```

浏览器控制台报错 Error: Dynamic require of "punycode" is not supported

我的工具版本
"md-editor-v3": "^4.0.3",
"vue": "^3.3.4",
"vite": "^4.3.9",

**Comment by imzbf** [comment]
I haven't found  issue, Is there any other special environment? Like browser or something else.
