### ISSUE TITLE
Remove hardcoded CDN libraries and include as dependencies

### ISSUE THREAD

**Issue by 20** [imzbf/md-editor-v3#295]
We would like to use md-editor-v3 for a project that runs on local community servers in rural area where there is no internet. 
We have already included in our frontend but we saw that there are some libraries externally linked to cdnjs.cloudfare... Is it possible to set this libraries as local node modules? 

Thank you for your work!

**Comment by imzbf** [comment]
Please refer to #294.

**Comment by 20** [comment]
Thanks! It's a solution.. Is there some reason to put these packages as external link and don't set as dependency like others?

**Comment by imzbf** [comment]
This is also possible, and there is an example for `screenfull`, [Intranet Link](https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%93%A1%20Intranet%20Link) others are similar to it.

To get Reference for all types, search `EditorExtensions` in this page [Config Editor](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%92%B4%20Config%20Editor)
