### ISSUE TITLE
图片打开会弹出黑色蒙层，看不到图片

### ISSUE THREAD

**Issue by pakarsunny** [imzbf/md-editor-v3#297]

**Comment by imzbf** [comment]
什么版本，旧版本存在这个问题，如果是4.x版本，方便的话提供一个最小的还原问题的环境。

**Comment by pakarsunny** [comment]
> 什么版本，旧版本存在这个问题，如果是4.x版本，方便的话提供一个最小的还原问题的环境。

最新版本4.1.0的，单个使用确实没问题，因为做的类似于chatgpt的，会有多个结果使用markdown展示的（preview-only），用在Vue的v-for里面去渲染的，就会出现这种情况

<div v-for="(item, index) in resArr" :key="index">
      <MdPreview :editorId="id" :modelValue="item" />
      <MdCatalog :editorId="id" :scrollElement="scrollElement" />
  </div>

**Comment by pakarsunny** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/21982431/07c7adcd-7697-4466-99c4-d676ecfffbb3)
这个img应该在fixed的dev里面吧，不然页面看不到弹出来的图片

**Comment by imzbf** [comment]
给循环的`MdPreview`设置不同的`editorId`了吗？像这样设置一下就可以了，`editorId`要是不能重复的

```vue
<template>
  <div v-for="item in list">
    <MdPreview
      :modelValue="item.content"
      :editorId="item.id"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { MdPreview } from 'md-editor-v3';
import 'md-editor-v3/lib/preview.css';

const list = ref([
  {
    id: 'id1',
    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',
  },
  {
    id: 'id2',
    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',
  },
  {
    id: 'id2',
    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',
  },
  {
    id: 'id4',
    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',
  },
  {
    id: 'id5',
    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',
  },
]);
</script>
```

**Comment by imzbf** [comment]
好像确实有点问题

**Comment by pakarsunny** [comment]
https://github.com/imzbf/md-editor-v3/assets/21982431/b6146e67-70c6-4d6d-b2ae-d937fab86531

https://user-images.githubusercontent.com/21982431/245013081-07c7adcd-7697-4466-99c4-d676ecfffbb3.png

主要问题在这里，你把img标签放在了fixed的div的外部，内联样式加了style，position: absolute; top: XXXXpx; 这里的XXX计算的有问题；放大看图片只需要在fix的里面展示一下图片就行了，应该跟弹窗没区别

**Comment by pakarsunny** [comment]
你可以测试一下你这个demo，弹出来的图片absolute之后，top值太高了，只有第一张图能保证没问题，其他的都跑到屏幕下面去了，img不应该放在fixed的div里面吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月12日 17:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [imzbf/md-editor-v3] 图片打开会弹出黑色蒙层，看不到图片 (Issue #297) |

循环的时候给MdPreview设置不同的editorId就可以了

<template>
  <divv-for="item in list">
    <MdPreview
      :modelValue="item.content"
      :editorId="item.id"
    />
  </div>
</template>

<scriptsetuplang="ts">import { ref } from'vue';import { MdPreview } from'md-editor-v3';import'md-editor-v3/lib/preview.css';const list =ref([  {    id: 'id1',    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',  },  {    id: 'id2',    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',  },  {    id: 'id2',    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',  },  {    id: 'id4',    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',  },  {    id: 'id5',    content: '# 哈哈哈\n\n ![](https://imzbf.github.io/md-editor-rt/imgs/normal-toolbar.gif)',  },]);</script>

**Comment by imzbf** [comment]
> 你可以测试一下你这个demo，弹出来的图片absolute之后，top值太高了，只有第一张图能保证没问题，其他的都跑到屏幕下面去了，img不应该放在fixed的div里面吗？

和你说这个没有关系，上面的demo是因为出现了两个相同的`id2`，调整一下就没有这个问题，

**Comment by imzbf** [comment]
每个预览组件会根据自己的`editorId`去获取相应的图片，如果存在相同的，那么同一张图片会被添加两次点击事件，才会出现你发现的问题

**Comment by pakarsunny** [comment]
嗯，是的，我仔细看了一下，确实是重复了导致的，👍🏻



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月12日 20:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [imzbf/md-editor-v3] 图片打开会弹出黑色蒙层，看不到图片 (Issue #297) |

你可以测试一下你这个demo，弹出来的图片absolute之后，top值太高了，只有第一张图能保证没问题，其他的都跑到屏幕下面去了，img不应该放在fixed的div里面吗？

和你说这个没有关系，上面的demo是因为出现了两个相同的id2，调整一下就没有这个问题，
