### ISSUE TITLE
.focus() puts cursor at the start after replacing text

### ISSUE THREAD

**Issue by devedx** [imzbf/md-editor-v3#299]
### Describe the issue

When setting the text of the editor with `text.value = "..."` and then calling `editorRef.value.focus()` the cursor is put at the start of the text instead of the end. This is probably not what most people would want and is also inconsistent with the behavior of a `<textarea>`.

### Version of the editor

node: v18.16.0, vue: 3.3.2, vite: 4.3.5, md-editor-v3: 4.1.0

**Comment by imzbf** [comment]
I'm sorry, element `textarea` works like this.

And, if there is a lot of content, the cursor is put at the end of the text, the scrolling position of the textarea and preview area will scroll continuously to the bottom. This doesn't look nice.

**Comment by devedx** [comment]
Is there some way to manually set the the cursor position?

**Comment by imzbf** [comment]
> Is there some way to manually set the the cursor position?

Only manually set the position after getting element `textarea`.

I have tried, `element.focus()` always sets its position where it left last time.

If you are going to set it to that you want, there is a demo: https://github.com/imzbf/md-editor-v3/blob/9f9e879c5b239ab566bbcd22ce6fce27a0c0d49c/MdEditor/utils/index.ts#L10

**Comment by imzbf** [comment]
I found a more elegant way. It may be possible to add a parameter to `focus` to adjust the cursor position. I'll give it a try

**Comment by imzbf** [comment]
This feature is available in `4.2.0-beta.0`. The latest version will be released soon. Only `editorRef.value.focus()` works.

```shell
yarn add md-editor-v3@beta
```

```js
onMounted(() => {
  editorRef.value?.focus('end');
});
```

**Comment by devedx** [comment]
Works great, thank you!

**Comment by imzbf** [comment]
Latest version has be released
