### ISSUE TITLE
失灵

### ISSUE THREAD

**Issue by luoxibo** [imzbf/md-editor-v3#3]
项目中失灵了，点击任何按钮无反应
我的配置
{
  "name": "vue3-js",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^29.0.0",
    "@ckeditor/ckeditor5-vue": "^2.0.1",
    "axios": "^0.21.1",
    "echarts": "^5.1.2",
    "element-plus": "^1.0.2-beta.55",
    "md-editor-v3": "^1.1.2",
    "vue": "^3.1.5",
    "vue-router": "^4.0.10"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.2.2",
    "@vue/compiler-sfc": "^3.0.5",
    "sass": "^1.32.8",
    "vite": "^2.3.3",
    "vuex": "^4.0.0"
  }
}

**Comment by imzbf** [comment]
@luoxibo 

可以提供一个呈现问题的代码仓库吗？

**Comment by luoxibo** [comment]
> @luoxibo
> 
> 可以提供一个呈现问题的代码仓库吗？

找到原因了，我用的写法问题：<script lang="ts">
