### ISSUE TITLE
MdEditorV3存在安全隐患

### ISSUE THREAD

**Issue by SalHe** [imzbf/md-editor-v3#30]
# MdEditorV3安全隐患

当前的编辑器可能存在被注入JS代码攻击的安全隐患。

可以将本Markdown内容完整的复制到MdEditorV3编辑器中测试。

Markdown完整内容：[链接](https://gist.githubusercontent.com/SalHe/20b558fb6f371ffeaf0faab26d7355d6/raw/b461b031b307fa92645ecc5c68eae20a944326fb/MdEditorV3%25E5%25AD%2598%25E5%259C%25A8%25E5%25AE%2589%25E5%2585%25A8%25E9%259A%2590%25E6%2582%25A3.md)

## 测试信息

- 测试版本：v1.7.3
- 测试时间：2021/12/05

### 示例1

<strong>SCRIPT👉</strong><button onclick='(function(){var s=function(r){return r.toString().replaceAll(/\//g,String());};alert(s(/坏东西/));})()'>Hello</button><strong>👈SCRIPT</strong>

### 示例2

这个代码已经被注入，不过没能被直接调用（个人不是干这块的，不是很懂）。

<strong>SCRIPT👉</strong><script type='text/javascript'>alert('你好');</script><strong>👈SCRIPT</strong>

### 示例3

<iframe src="https://next.vuex.vuejs.org/" width="500" height="300"></iframe>

### 不使用字符串表示字符串(用于支持复杂的字符串)

```javascript
function StringToIntArray(str){
    let arr = [];
    for(let i=0;i<str.length;i++)
        arr.push(str.charAt(i));
    return str;
}
```

```javascript
// IntArrayToString
var str = function (arr){
  var zstr = String();
  return arr.map(x=>String.fromCharCode(x)).join(zstr);
}
```

**Comment by imzbf** [comment]
已在1.8.0中处理，通过`sanitize`处理html内容，[参考](https://imzbf.github.io/md-editor-v3/demo/index#%F0%9F%94%92%20xss)
