### ISSUE TITLE
Instant rendering

### ISSUE THREAD

**Issue by devedx** [imzbf/md-editor-v3#300]
Is it possible to have the preview rendered instantly on every input or at least periodically without having to stop typing?

**Comment by imzbf** [comment]
We can control the timing of starting the rendering, but if there is too much text, there may be a lag

Search `renderDelay` in this page: [Config Editor](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%92%B4%20Config%20Editor)

**Comment by devedx** [comment]
Setting `renderDelay: 0` works fine, thanks!
