### ISSUE TITLE
XSS漏洞

### ISSUE THREAD

**Issue by Mia0a-hi** [imzbf/md-editor-v3#302]
### 描述这个Bug

这个作者说使用你的依赖出发漏洞：
https://github.com/zclzone/vue-naive-admin/issues/30

![image](https://user-images.githubusercontent.com/40627909/203245953-62e87400-3f9f-44c9-b112-05c6f7cf04aa.png)

### 版本号

.

### 问题重现链接

https://github.com/zclzone/vue-naive-admin/issues/30

**Comment by imzbf** [comment]
组件本身不会去处理这方面的事情，但是给了接口让开发者处理，你参考这个https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%A3%20sanitize

**Comment by imzbf** [comment]
参考其他小伙伴使用的库来处理内容https://github.com/imzbf/md-editor-v3/issues/280#issuecomment-1575519737
