### ISSUE TITLE
预览模式下MdCatalog组件点击目录无法定位锚点

### ISSUE THREAD

**Issue by AnyFork** [imzbf/md-editor-v3#303]
### Describe the issue

预览模式下MdCatalog组件点击目录无法定位锚点
![image](https://github.com/imzbf/md-editor-v3/assets/49142023/a6d25420-7427-4de2-a3bd-372f8ec8537f)

### Procedure version

"md-editor-v3": "^4.2.0" node 16.17.4

**Comment by imzbf** [comment]
如果你的滚动元素是documentElement，可以直接const scrollElement = document.documentElement。

因为这个属性是不支持响应式的。

**Comment by AnyFork** [comment]
> const scrollElement = document.documentElement
直接使用const scrollElement = document.documentElement 在nuxt3中报错

**Comment by AnyFork** [comment]
> 如果你的滚动元素是documentElement，可以直接const scrollElement = document.documentElement。
> 
> 因为这个属性是不支持响应式的。

如果不支持响应式，在nuxt3中只能客户端渲染
```vue
  <ClientOnly>
      <MdCatalog editorId="previewEditor" :scrollElement="scrollElement" theme="dark" />
  </ClientOnly>
```
```ts
let scrollElement: string | HTMLElement | undefined = undefined
onMounted(() => {
    scrollElement = document.documentElement
})
```
好像MdCatalog组件也不支持SSR
