### ISSUE TITLE
yjs协同编辑支持

### ISSUE THREAD

**Issue by abluepoint-dev** [imzbf/md-editor-v3#304]
### 一个很棒的想法

yjs协同编辑支持

**Comment by imzbf** [comment]
抱歉，#61 之前有提到过这个功能，但是实现方式过于复杂，偏离了`markdown`编辑器的方向。建议有需要克隆源码单独尝试

**Comment by abluepoint-dev** [comment]
感谢回复

**Comment by mingchiuli** [comment]
> 虽然没有内置这个功能，但是现在在文档中提供了一个基础的示例，参考：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%8E%B3%20%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%AC

之后会考虑单独出一个模块提供协同编辑吗？现在这个实现好像不能动态指定切换房间，因为是在配置里的，只能写死。类似https://github.com/Milkdown/milkdown就提供了一个模块，但是那个编辑器完成度远没有这个高

**Comment by imzbf** [comment]
> > 虽然没有内置这个功能，但是现在在文档中提供了一个基础的示例，参考：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%8E%B3%20%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%AC
> 
> 之后会考虑单独出一个模块提供协同编辑吗？现在这个实现好像不能动态指定切换房间，因为是在配置里的，只能写死。类似https://github.com/Milkdown/milkdown 就提供了一个模块，但是那个编辑器完成度远没有这个高

这确实是个问题，我尝试一下怎么去做合适

**Comment by imzbf** [comment]
> > 虽然没有内置这个功能，但是现在在文档中提供了一个基础的示例，参考：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%8E%B3%20%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%AC
> 
> 之后会考虑单独出一个模块提供协同编辑吗？现在这个实现好像不能动态指定切换房间，因为是在配置里的，只能写死。类似https://github.com/Milkdown/milkdown 就提供了一个模块，但是那个编辑器完成度远没有这个高

我修改了示例，参考：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%8E%B3%20%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%AC

后续会考虑更优雅的方式。
