### ISSUE TITLE
markdown-it渲染规则配置失效

### ISSUE THREAD

**Issue by BlueflameLi** [imzbf/md-editor-v3#305]
### 描述这个Bug

我使用了markdown-it的自定义渲染规则来实现一些自定义的语法，但从4.0.3开始的版本就失效了，并且我使用的是nuxt3，在服务端渲染的时候还会出现许多水合错误，而这在4.0.2版本及以前都没有问题的 
![Snipaste_2023-06-20_20-55-45](https://github.com/imzbf/md-editor-v3/assets/58543957/65479124-1af0-43fa-b8de-758ba66d3496)
![Snipaste_2023-06-20_21-03-20](https://github.com/imzbf/md-editor-v3/assets/58543957/d1056393-dffd-44b4-b3be-f3dcc44fbcfe)

### 版本号

4.0.3及以上

**Comment by imzbf** [comment]
这边在这个[示例](https://github.com/imzbf/md-editor-v3/tree/develop/example/nuxt)中尝试好像没有类似的提示。

方便的提供一下你的扩展代码，和一个还原你问题的环境

**Comment by BlueflameLi** [comment]
我这边是重定义了blockquote_open和blockquote_close的规则，我刚刚测试了一下，似乎是4.0.3版本之后我自定义的blockquote_open规则被覆盖了，而blockquote_close没被覆盖，nuxt的水合错误应该是重定义的blockquote_close规则替换了`</blockquote>`标签，而blockquote_open因为失效没成功替换`<blockquote>`，标签不匹配导致的，可以先忽略nuxt的问题

修改[示例](https://github.com/imzbf/md-editor-v3/tree/develop/example/nuxt)中app.vue的代码如下可以复现
```vue
<template>
    <MdPreview :model-value="text" />
</template>

<script setup>
import { ref } from 'vue';
import { MdPreview, config } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const text = ref('> test');
config({
    markdownItConfig(mdit) {
        mdit.renderer.rules.blockquote_open = (tokens, idx) => {
            console.log("blockquote_open")
            return '<blockquote>'
        }

        mdit.renderer.rules.blockquote_close = (tokens, idx) => {
            console.log("blockquote_close")
            console.log(tokens)
            return '</blockquote>'
        }
    },
})
</script>
```
![Snipaste_2023-06-20_23-26-00](https://github.com/imzbf/md-editor-v3/assets/58543957/6a5e625d-5733-4495-b1a1-2949b1d96e12)
上图为最新版的输出，下图为4.0.2版本时的输出
![Snipaste_2023-06-20_23-27-36](https://github.com/imzbf/md-editor-v3/assets/58543957/d2b0282b-0434-41f4-9d8c-1ec9c808df49)

**Comment by imzbf** [comment]
我在`beta`中修复了这个问题，现在可以通过一下方式尝试

```shell
yarn add md-editor-v3@beta
```

正式版会在其它问题修复后一起更新。

**Comment by BlueflameLi** [comment]
非常感谢，测试版中没问题了
