### ISSUE TITLE
编辑时能不能直接显示 预览的样式

### ISSUE THREAD

**Issue by zzj202** [imzbf/md-editor-v3#306]
### 一个很棒的想法

相当于直接在 预览上编辑
内容编辑更直观一点

![image](https://github.com/imzbf/md-editor-v3/assets/80336416/5add4007-d1a2-4df3-9926-b9a22e2fc8e1)

**Comment by imzbf** [comment]
这种方式在还没有明确的实现方法，短时间还添加不进来。目前保持传统的左边编辑，右边预览的方式。

感谢你的提议，
