### ISSUE TITLE
点击编辑获取焦点后，再进行路由切换时会出现错误

### ISSUE THREAD

**Issue by blubluee** [imzbf/md-editor-v3#308]
### 描述这个Bug

点击编辑获取焦点后，再进行路由切换时会出现如下错误（或者说进行路由切换后，点击任何地方都会出现报错）
![image](https://github.com/imzbf/md-editor-v3/assets/79352776/411f59e1-4f9e-4ef6-b4fa-24b1e094b435)
这是依赖的相关版本（这是我新开的一个项目来测试的，发现也会出现这个问题）
![image](https://github.com/imzbf/md-editor-v3/assets/79352776/6af04cb2-5bfa-4c40-9368-8e4a97d1bbc1)

### 版本号

vscode、node v18.16.0、最新版chrome

**Comment by imzbf** [comment]
能提供一下这个初始项目吗，因为项目的文档也是类似的环境，但是运行着没有类似的问题。

**Comment by blubluee** [comment]
QAQ，我回来之后在跑一遍没报错了，刚刚又新建了一个项目也没出现问题。等明天去公司再跑一遍看看 : )

**Comment by blubluee** [comment]
我在公司再次新建项目还是会报错（昨天建的也会），我把项目放到一个仓库里了（https://github.com/blubluee/md-editor-v3-test.git），我自己拉取下来再跑一遍依旧还是报错，不知道啥原因 QAQ

**Comment by imzbf** [comment]
> 我在公司再次新建项目还是会报错（昨天建的也会），我把项目放到一个仓库里了（https://github.com/blubluee/md-editor-v3-test.git ） ，我自己拉取下来再跑一遍依旧还是报错，不知道啥原因 QAQ

这个仓库的代码我尝试运行了下，也还原不了这个问题。可能你在公司的电脑上的环境有特殊的我们没有注意到的情况。

我根据你提供的信息，尝试调整了一下程序，发布到了`beta`中，需要你这边协助测试看问题是否还存在

```shell
pnpm i md-editor-v3@beta
# or
yarn add md-editor-v3@beta
```

**Comment by blubluee** [comment]
我试了一下，这个beta版本还是会报错。不知道是不是chrome的问题（我用的114.0.5735.134（正式版本），是目前最新版本），因为我换成Edge的时候不会出现这个问题（4.2.0和beta都没有）

**Comment by imzbf** [comment]
挺奇怪的了，这边也复现不了。再观察一下

**Comment by imzbf** [comment]
在访问这个属性的地方添加了拦截，再尝试一下看看会出现类似的问题不。

**Comment by blubluee** [comment]
现在好像报错是没有了，但是有个奇怪的地方是我没有更新依赖，用的还是4.2.0... 我也是好久没去注意这个报错了 > <

**Comment by imzbf** [comment]
> 现在好像报错是没有了，但是有个奇怪的地方是我没有更新依赖，用的还是4.2.0... 我也是好久没去注意这个报错了 > <

可能只是编辑器或者浏览器更新出现了问题，确实按照目前的逻辑这种错误不应该会出现。没有就OK。感谢跟进
