### ISSUE TITLE
首行多出几个空格的话，会导致解析为代码块

### ISSUE THREAD

**Issue by pigIsDuck** [imzbf/md-editor-v3#309]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-v3/assets/63036234/660eb406-7ef1-46af-844f-e0fb2eba3ebf)
如图，我在官方的文档中，也会这样解析，希望可以对于代码块的解析优化一下

    这里会被解析为代码块
 123
 阿松大
   这里又不会
123
  123
啊大苏打

这是对应的文本，可以用于测试

### 版本号

"md-editor-v3": "^2.2.1"

**Comment by imzbf** [comment]
这个语法是保留的，在 #257 有提到。像github这里连续输入空格表现也是这样。

**Comment by pigIsDuck** [comment]
可是，这在于某些情况，会导致显示效果不如人意，代码块我就老老实实按照代码块的编写语法
```  这样就好了

**Comment by pigIsDuck** [comment]
我目前遇到的情况，就是同一个地方，需要同时支持  富文本、markdown、和普通输入框 三种支持，那么在其他输入方式的情况，都是统一使用作者您开发的代码 来解析的，这样的话，别人回来询问，为什么变成了代码块

**Comment by imzbf** [comment]
找了下`markdown`文档，这个好像被大家默认为一个标准了，主要是编辑器的编译库也没有提供相关的设置项。建议给予用户语法提示或者强制对输入内容格式化。

**Comment by pigIsDuck** [comment]
这样鸭，那好吧，我想想要怎么办才好，或者能不能给个 props，选择性开启呢

**Comment by imzbf** [comment]
> 这样鸭，那好吧，我想想要怎么办才好，或者能不能给个 props，选择性开启呢

目前还没有找到能控制这个渲染方式的办法，所以还提供不了能用的api来控制状态，如果有我会第一时间尝试，目前只能给到上面的临时解决方案哈

**Comment by pigIsDuck** [comment]
> 

好嘞，感谢
