### ISSUE TITLE
md-editor-v3 有个严重的bug

### ISSUE THREAD

**Issue by xiaofeipapa** [imzbf/md-editor-v3#31]
bug描述: 当上传了图片, 且输入框出现滚动条, 且开启markdown预览功能时, 在输入框的底部输入文字,  滚动条会自动往上走, 使输入无法再进行. 

bug版本:  v1.7.3

重现条件: 
1) 上传图片. (必须, 否则不能重现)
2) 输入一大段文字, 使输入框出现滚动条. 
3) 开启预览功能. 
4) 在输入框的最底部进行输入.

**Comment by imzbf** [comment]
这边好像无法还原该问题，请问是否存在其他必要操作，或者是在开启预览时会出现重新绑定同步滚动事件，此时滚动条位置会有所变化这个问题？

**Comment by xiaofeipapa** [comment]
我录了2个重现bug的视频, 发到你的邮箱了( zbfcqtl@163.com) 

你的这个开源库对我帮助很大, 祝越做越好.

**Comment by imzbf** [comment]
> 我录了2个重现bug的视频, 发到你的邮箱了( [zbfcqtl@163.com](mailto:zbfcqtl@163.com))
> 
> 你的这个开源库对我帮助很大, 祝越做越好.

非常谢谢。这边再确认一下你提的这个问题

**Comment by imzbf** [comment]
非常感谢您的跟进，根据提供的信息，这边已确定该问题并修复~

问题描述及解决方式：存在图片，同时图片不在可见区域内，向标签插入内容会导致标签滚动条向图片靠近。这种情况只会存在于设置了宽度和滚动标签中。现在（2021-12-28 11:27:59）不清楚这种表现是否是标准行为。类似的问题解决方式是移除需要插入内容的标签上的滚动条，添加`wrapper`并设置滚动条到这里。

希望这能有所帮助。

**Comment by imzbf** [comment]
已在[v1.9.2](https://github.com/imzbf/md-editor-v3/releases/tag/v1.9.2)中修复~
