### ISSUE TITLE
展开目录时挡住了同步滚动按钮

### ISSUE THREAD

**Issue by vikyd** [imzbf/md-editor-v3#310]
### 描述这个Bug

展开目录时挡住了同步滚动按钮

<img width="1273" alt="xxx" src="https://github.com/imzbf/md-editor-v3/assets/2208880/a6c8e48d-d3e0-4603-9024-03b91cc422bc">

### 版本号

4.2.0

**Comment by imzbf** [comment]
正式版优化了这个问题
