### ISSUE TITLE
编辑模式时建议增加隐藏左侧 editor 的模式

### ISSUE THREAD

**Issue by vikyd** [imzbf/md-editor-v3#311]
### 一个很棒的想法

编辑模式时建议增加隐藏左侧 editor 的模式，同时也提供对应切换的 toolbar。

**Comment by imzbf** [comment]
这个问题在以前也提到过，但是因为工具栏的原因，所以这种传统的编辑模式需要一直保持编辑区域可见。如果你在编辑的时候对右侧的预览区域不满意，可以参考文档首页的工具栏上的阅读扩展，源码在`dev-docs`分支

![image](https://github.com/imzbf/md-editor-v3/assets/37092006/14579ccd-218f-4833-aa91-030a5f2976dd)
