### ISSUE TITLE
仅预览时候会创建一个无用 div ，重复点击一个页面会重复添加

### ISSUE THREAD

**Issue by daidaibg** [imzbf/md-editor-v3#312]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-v3/assets/55817318/775568da-e229-4ed1-9042-7026bfa0c8d2)
```html
<div style="width: 1375px; height: 19085px; position: fixed; z-index: -10000;"></div>
```
复现步骤，一直切换文档和示例会无限增加 这样的一个div，这个问题能修复嘛
![image](https://github.com/imzbf/md-editor-v3/assets/55817318/ad041a41-cc80-4b67-a2e0-b63e92a49a9f)

### 版本号

4*

### 问题重现链接

https://imzbf.github.io/md-editor-v3/zh-CN/demo

**Comment by imzbf** [comment]
这是用来转换`mermaid`的容器，生成后可能没有被正确的移除，下个补丁版本优化一下~

**Comment by daidaibg** [comment]
> 这是为了转换`mermaid`的容器，生成后可能没有被正确的移除，接下来的几个版本优化一下~

🆗

**Comment by imzbf** [comment]
正式版优化了这个问题~
