### ISSUE TITLE
MdPreview 当内容改变的时候不断添加新的隐藏的div 

### ISSUE THREAD

**Issue by cgisky1980** [imzbf/md-editor-v3#313]
### 描述这个Bug

MdPreview 当内容改变的时候不断添加新的隐藏div dom

![image](https://github.com/imzbf/md-editor-v3/assets/82481660/e9913222-e890-4785-8351-32e6212aca2d)

### 版本号

 "md-editor-v3": "^4.2.0"  vue3

**Comment by cgisky1980** [comment]
https://github.com/imzbf/md-editor-v3/issues/312  这里已经修复了吧~~我重新安装下

**Comment by imzbf** [comment]
> #312 这里已经修复了吧~~我重新安装下

是的，安装一下`4.2.1`就可以了
