### ISSUE TITLE
Are you planning to WYSIWYG mode?

### ISSUE THREAD

**Issue by neslxzhen** [imzbf/md-editor-v3#316]
### A great idea

Is WYSIWYG mode on your roadmap?
Please refer to: https://github.com/nhn/tui.editor#easy-wysiwyg-mode

**Comment by neslxzhen** [comment]
This is a duplicate issue: https://github.com/imzbf/md-editor-v3/issues/202

**Comment by imzbf** [comment]
Sorry,  almost all of this component is developed in my spare time, I don't have much time to to upgrade this mode. So I gave up on it.
