### ISSUE TITLE
建议增加一些emoji表情

### ISSUE THREAD

**Issue by hjljy** [imzbf/md-editor-v3#32]
建议增加一些emoji表情

这样在进行markdown写作的时候，有些emoji表情进行互动还是挺不错的

**Comment by imzbf** [comment]
这个有点类似评论框呢，类似的功能比较多，后续可能纳入工具栏扩展开发计划中。

**Comment by BigHugeC4** [comment]
+1

**Comment by imzbf** [comment]
在v1.10.1中实现了自定义扩展工具栏，参考[[defToolbars](https://imzbf.github.io/md-editor-v3/docs/index#%F0%9F%92%AA%20defToolbars)](https://imzbf.github.io/md-editor-v3/docs/index#%F0%9F%92%AA%20defToolbars)实现自己的功能，文档中也给出了emoji的完整示例~
