### ISSUE TITLE
编辑器无法自动换行问题

### ISSUE THREAD

**Issue by 2420228300** [imzbf/md-editor-v3#321]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/53279456/5f3cd00d-fc60-4da1-ac98-8583a556a6fc)
如图这一行文字无法自动换行全部挤在一起导致了编辑器显示异常，但是渲染出来还是正常的

### Procedure version

4.2.2

**Comment by imzbf** [comment]
这个是你项目的全局样式限制的，找到这块css覆盖掉
