### ISSUE TITLE
编辑器滚动问题，不同步或无法滚动

### ISSUE THREAD

**Issue by RickTe** [imzbf/md-editor-v3#323]
### 描述这个Bug

在使用改编辑器进行生产时我遇到的滚动问题，内容超出，出现滚动条后：
1. 同步滚动异常，**编辑面板**已经滚动到最底部了，**预览面板**的还在最上面（反之亦然）
2. **预览面板**跟随**编辑面板**滚动一下又瞬间滚动到顶部（反之亦然）
3. 预览面板无法滚动（禁用js后正常）

简易模拟了一下场景：
在官方示例的编辑器输入以下内容：
```js
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
```

### 版本号

v4.2.2

**Comment by imzbf** [comment]
同步滚动的函数写得有点着急，待优化一下，感谢反馈

**Comment by imzbf** [comment]
终于修复了，请在`^4.5.0`中尝试
