### ISSUE TITLE
链接按钮预设上传功能接口

### ISSUE THREAD

**Issue by Gengkaibo** [imzbf/md-editor-v3#324]
### 一个很棒的想法

![mmexport1689813590258](https://github.com/imzbf/md-editor-v3/assets/49260105/c3b2b22a-c6df-430d-a2a5-f9a484fddb70)
作者您好，图片目前除了可以添加链接外同时也是有上传预留接口的，那么对于其他类型文件可不可以在链接按钮那那加一个下拉菜单，做出预设的上传接口，可以把上传的文件地址链接到文档中，点击链接后能够打开新页面，如果上传的文件支持浏览就可以在新页面浏览，不支持浏览就可以直接下载

**Comment by Gengkaibo** [comment]
那个打开新标签页不是重点，可以在config配置markdown-it-link-attributes实现

**Comment by imzbf** [comment]
这个不会在图片类似的位置添加。后续计划单独作为一个扩展，这是一个好想法，也很实用，没有在组件中集成是因为文件的链接展示和下载方式不太好统一。

不过，作者在尝试重构编辑器的扩展组件库了，这类工具组件以后会在扩展库中开发，咱们可以选择性的给编辑器添加一些已经存在的工具，也不会导致不需要的这类工具的项目里有太多的不需要的代码。

目前对于扩展组件库的语言和按需引入的方式还没有完善。

**Comment by Gengkaibo** [comment]
好的，感谢作者回复！我目前项目中前台的文档中心需要链接一个pdf，后台管理界面如果要加入pdf链接没有上传渠道，因此产生的这个想法。我先通过自定义toolbars的方式实现吧
但是还有一个问题，您看一看：
![image](https://github.com/imzbf/md-editor-v3/assets/49260105/9cf0c1f7-937a-4f00-a26b-812c62b29edd)
![image](https://github.com/imzbf/md-editor-v3/assets/49260105/be10b471-4732-4050-8995-ccf796db2233)
我的目的是让自定义toolbars位置按组件入参的index排列，但是目前好像defToolbars slots中的内容只能在一起，是我哪里写的有问题吗？

**Comment by Gengkaibo** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/49260105/c99d71d0-e9b4-4688-a246-a788575b4a82)

![image](https://github.com/imzbf/md-editor-v3/assets/49260105/d1625048-1a9f-4e93-943a-11fe11ec2168)
还有就是我加了 '-'以后两个自定义工具并没有分开

**Comment by imzbf** [comment]
> ![image](https://user-images.githubusercontent.com/49260105/254753971-c99d71d0-e9b4-4688-a246-a788575b4a82.png)
> 
> ![image](https://user-images.githubusercontent.com/49260105/254753878-d1625048-1a9f-4e93-943a-11fe11ec2168.png) 还有就是我加了 '-'以后两个自定义工具并没有分开

`-`是用来显示分割线的，左右实际上是用`=`来分割的，可以你需要设置为`['0', '=', '1']`

**Comment by imzbf** [comment]
> > ![image](https://user-images.githubusercontent.com/49260105/254753971-c99d71d0-e9b4-4688-a246-a788575b4a82.png)
> > ![image](https://user-images.githubusercontent.com/49260105/254753878-d1625048-1a9f-4e93-943a-11fe11ec2168.png) 还有就是我加了 '-'以后两个自定义工具并没有分开
> 
> `-`是用来显示分组分割线的，左右实际上是用`=`来进行左右分割的，可以你需要设置为`['0', '=', '1']`

**Comment by Gengkaibo** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/49260105/e4ad62ce-e03e-417d-8f83-f2899dc2f74f)
![1689834808894](https://github.com/imzbf/md-editor-v3/assets/49260105/99debca5-d3c4-4075-b320-f2cf6891c60a)
依然没有分开...

**Comment by imzbf** [comment]
注意看看对应的位置有没有你项目的样式影响

**Comment by imzbf** [comment]
> > ![image](https://user-images.githubusercontent.com/49260105/254753971-c99d71d0-e9b4-4688-a246-a788575b4a82.png)
> > ![image](https://user-images.githubusercontent.com/49260105/254753878-d1625048-1a9f-4e93-943a-11fe11ec2168.png) 还有就是我加了 '-'以后两个自定义工具并没有分开
> 
> `-`是用来显示分组分割线的，左右实际上是用`=`来左右分割显示的，可以你需要设置为`['0', '=', '1']`

这个有点错误，下标是数字，`[0, '=', 1]`。

**Comment by imzbf** [comment]
还有一个问题，给到编辑器组件的`defToolbars`插槽需要时一个组件数组，你封装的组件可能把你这里插槽里面的组件全放到一起了

**Comment by imzbf** [comment]
<img width="431" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/0cc03912-9d74-4758-a2db-db2b6597c553">
这样z组件不会工作

**Comment by Gengkaibo** [comment]
大佬，我还真是这样写的

CommonMdEditor.vue：

<script setup lang="ts">
import 'md-editor-v3/lib/style.css'
import { ref, unref, useAttrs, watch } from 'vue'
import { MdEditor, config } from 'md-editor-v3'
import markdownItLinkAttributes from 'markdown-it-link-attributes'
import { allToolbars, mdHeadingId } from '../../config'
defineOptions({
  name: 'CommonMdEditor',
})

config({
  markdownItConfig(mdit) {
    // 新标签页打开链接
    mdit.use(markdownItLinkAttributes, {
      pattern: /^http/i,
      attrs: {
        target: '_blank',
        rel: 'noopener',
      },
    })
  },
})

const props = defineProps<{
  modelValue: string
}>()
const emits = defineEmits<{
  (e: 'update:modelValue', text: string): void
}>()

const text = ref('')

// 监听
watch(text, (val: string) => {
  emits('update:modelValue', val)
})
watch(
  () => props.modelValue,
  (val: string) => {
    if (val === unref(text)) return
    text.value = val
  },
  {
    immediate: true,
  },
)
const attrs = useAttrs()
</script>
<template>
  <MdEditor
    v-model="text"
    :md-heading-id="mdHeadingId"
    :toolbars="allToolbars"
    v-bind="attrs"
  >
    <template #defToolbars>
      <slot name="defToolbars" />
    </template>
    <template #defFooters>
      <slot name="defFooters" />
    </template>
  </MdEditor>
</template>
<style lang="less">
/* 目录样式 */
.md-editor-catalog.md-editor-catalog-editor {
  .md-editor-catalog-link {
    line-height: 18px;
  }

  .md-editor-catalog-link span {
    color: inherit;
  }

  .md-editor-catalog-link span:hover {
    color: var(--sat-root-color-primary);
  }

  .md-editor-catalog-active > span {
    color: var(--sat-root-color-primary);
  }
}

/* tollbar样式 */
.md-editor-toolbar-wrapper {
  .md-editor-toolbar-item {
    display: flex;
    align-items: center;
  }
}
</style>


是因为这个写法导致的defToolbars插槽里的内容没有按照脚标索引排列吗？

**Comment by Gengkaibo** [comment]
```ts
<script setup lang="ts">
import 'md-editor-v3/lib/style.css'
import { ref, unref, useAttrs, watch } from 'vue'
import { MdEditor, config } from 'md-editor-v3'
import markdownItLinkAttributes from 'markdown-it-link-attributes'
import { allToolbars, mdHeadingId } from '../../config'
defineOptions({
  name: 'CommonMdEditor',
})

config({
  markdownItConfig(mdit) {
    // 新标签页打开链接
    mdit.use(markdownItLinkAttributes, {
      pattern: /^http/i,
      attrs: {
        target: '_blank',
        rel: 'noopener',
      },
    })
  },
})

const props = defineProps<{
  modelValue: string
}>()
const emits = defineEmits<{
  (e: 'update:modelValue', text: string): void
}>()

const text = ref('')

// 监听
watch(text, (val: string) => {
  emits('update:modelValue', val)
})
watch(
  () => props.modelValue,
  (val: string) => {
    if (val === unref(text)) return
    text.value = val
  },
  {
    immediate: true,
  },
)
const attrs = useAttrs()
</script>
<template>
  <MdEditor
    v-model="text"
    :md-heading-id="mdHeadingId"
    :toolbars="allToolbars"
    v-bind="attrs"
  >
    <template #defToolbars>
      <slot name="defToolbars" />
    </template>
    <template #defFooters>
      <slot name="defFooters" />
    </template>
  </MdEditor>
</template>
<style lang="less">
/* 目录样式 */
.md-editor-catalog.md-editor-catalog-editor {
  .md-editor-catalog-link {
    line-height: 18px;
  }

  .md-editor-catalog-link span {
    color: inherit;
  }

  .md-editor-catalog-link span:hover {
    color: var(--sat-root-color-primary);
  }

  .md-editor-catalog-active > span {
    color: var(--sat-root-color-primary);
  }
}

/* tollbar样式 */
.md-editor-toolbar-wrapper {
  .md-editor-toolbar-item {
    display: flex;
    align-items: center;
  }
}
</style>

```
大佬，这是我的代码，简单封了一下，跟您写的插槽差不多，是因为这个导致了插槽内容无法和脚标索引对应吗？

**Comment by Gengkaibo** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/49260105/5ef3b492-3c79-4511-a892-e9d1d4c396b9)
![image](https://github.com/imzbf/md-editor-v3/assets/49260105/3d4b5d5f-bfa1-4372-a460-bf45dab33a6c)
大佬，确实是直接在MdEditor组件里写插槽就没问题了，那我简单封装的那种写法怎么改进一下才能正常使用呢，因为我把这个封装后的组件作为一个公共组件，需要有一些默认配置，比如新标签打开方式以及自定义的默认样式

**Comment by Gengkaibo** [comment]
好像是Toolbar组件的barRender函数中props没有读到defToolbars引起的，您后续有计划解决一下吗？

**Comment by imzbf** [comment]
```vue
<template>
  <MdEditor>
    <template #defToolbars>
      <slot v-for="slotName of props.slotNames" :name="slotName" />
    </template>
  </MdEditor>
</template>

<script setup lang="ts">
const props = defineProps({
  slotNames: Array,
});
</script>
```

```vue
<template>
  <Common :slotNames="['a', 'b', 'c']">
    <template #a> aaaaa </template>
    <template #b> bbbbb </template>
    <template #c> ccccc </template>
  </Common>
</template>
```

**Comment by Gengkaibo** [comment]
我试了试，还是不能排到对应脚表index的位置上

```ts
<CommonMdEditor
        v-model="currentMdText"
        :read-only="isMdReadonly"
        :slot-names="[
          'toolbarPosition',
          'toolbarEdit',
          'toolbarUploadReport',
        ]"
        :toolbars="
          isMdReadonly
            ? [0, '-', '=', ...readOnlyToolbars, 1]
            : [...allLeftToolbars, 0, '=', ...allRightToolbars]
        "
        placeholder="请选中左侧树叶子节点进行编辑或浏览"
        preview-theme="cyanosis"
        @on-save="onSave"
      >
        <template #toolbarPosition>
          <NormalToolbar v-if="isMdReadonly">
            <template #trigger>
              <div>当前位置：{{ treeBreadcrumd || '无' }}</div>
            </template>
          </NormalToolbar>
        </template>
        <template #toolbarEdit>
          <NormalToolbar v-if="isMdReadonly" title="编辑">
            <template #trigger>
              <Icon icon="ep:edit" :size="18" @click="onEdit" />
            </template>
          </NormalToolbar>
        </template>
        <template #toolbarUploadReport>
          <NormalToolbar v-if="!isMdReadonly" title="上传报告">
            <template #trigger>
              <Icon
                icon="teenyicons:pdf-outline"
                :size="18"
                @click="onUploadReport"
              />
            </template>
          </NormalToolbar>
        </template>
      </CommonMdEditor>
```

**Comment by Gengkaibo** [comment]
我试了试，还是不能排到对应脚表index的位置上

```ts
<CommonMdEditor
        v-model="currentMdText"
        :read-only="isMdReadonly"
        :slot-names="[
          'toolbarPosition',
          'toolbarEdit',
          'toolbarUploadReport',
        ]"
        :toolbars="
          isMdReadonly
            ? [0, '-', '=', ...readOnlyToolbars, 1]
            : [...allLeftToolbars, 0, '=', ...allRightToolbars]
        "
        placeholder="请选中左侧树叶子节点进行编辑或浏览"
        preview-theme="cyanosis"
        @on-save="onSave"
      >
        <template #toolbarPosition>
          <NormalToolbar v-if="isMdReadonly">
            <template #trigger>
              <div>当前位置：{{ treeBreadcrumd || '无' }}</div>
            </template>
          </NormalToolbar>
        </template>
        <template #toolbarEdit>
          <NormalToolbar v-if="isMdReadonly" title="编辑">
            <template #trigger>
              <Icon icon="ep:edit" :size="18" @click="onEdit" />
            </template>
          </NormalToolbar>
        </template>
        <template #toolbarUploadReport>
          <NormalToolbar v-if="!isMdReadonly" title="上传报告">
            <template #trigger>
              <Icon
                icon="teenyicons:pdf-outline"
                :size="18"
                @click="onUploadReport"
              />
            </template>
          </NormalToolbar>
        </template>
      </CommonMdEditor>
```

**Comment by imzbf** [comment]
好像确实是，研究了一下，只有两种办法：

1. 使用`vue setup`模板，固定可能的工具栏插槽

```vue
<template>
  <MdEditor>
    <template #defToolbars>
      <slot name="aaa" />
       <slot name="bbb" />
    </template>
  </MdEditor>
</template>

<script setup lang="ts">
const props = defineProps({
  slotNames: Array,
});
</script>
```

2. 使用`jsx`来封装公共组件，`jsx`比模块更加灵活，可以随意的拆解组件

```jsx
import { MdEditor } from 'md-editor-v3';
import { defineComponent } from 'vue';

export default defineComponent({
  setup(props, ctx) {
    return () => {
      const defaultSolt = ctx.slots.default;

      return (
        <MdEditor toolbars={[0, '=', 1]} defToolbars={defaultSolt()}></MdEditor>
      );
    };
  },
});
```

测试

```vue
<template>
  <Common>
    <span>aaaaa</template>
    <span>bbbbb</template>
    <span>ccccc</template>
  </Common>
</template>
```

**Comment by Gengkaibo** [comment]
好的，谢谢，我用jsx试试

**Comment by Gengkaibo** [comment]
```ts
export default defineComponent({
  name: 'CommonMdEditor',
  props: {
    modelValue: {
      type: String,
      required: true,
    },
  },
  emits: ['update:modelValue'],
  setup(props, ctx) {
    config({
      markdownItConfig(mdit) {
        // 新标签页打开链接
        mdit.use(markdownItLinkAttributes, {
          pattern: /^http/i,
          attrs: {
            target: '_blank',
            rel: 'noopener',
          },
        })
      },
    })

    return () => (
      <MdEditor
        modelValue={props.modelValue}
        onUpdate:modelValue={(value) => ctx.emit('update:modelValue', value)}
        mdHeadingId={mdHeadingId}
        toolbars={allToolbars}
        {...ctx.attrs}
      >
        {{
          defToolbars: () => ctx.slots.defToolbars?.(),
          defFooters: () => ctx.slots.defFooters?.(),
        }}
      </MdEditor>
    )
  },
})
```
大佬 ，这种写法成功了， 但是我有些不明白为什么必须使用这种写法才能成功呢，按说 vue script setup模板写法和这种渲染函数的写法渲染逻辑应该一致才对呀，您能帮我解惑一下吗

**Comment by imzbf** [comment]
因为vue的模版虽然通过for循环出了多个slot，但是组件树种，实际上还是一个组件，只不过这个组件的children是循环出来的slot存放的组件而已。jsx就不一样了，这里拿到的就是children，没有外层的包裹组件
