### ISSUE TITLE
编辑模式下,点击右侧部分中的图片,会黑屏

### ISSUE THREAD

**Issue by zxj1997-java** [imzbf/md-editor-v3#325]
### 描述这个Bug

编辑模式下,点击右侧部分中的图片,会黑屏

### 版本号

4.2.2

**Comment by imzbf** [comment]
文档实例上面会吗？不会的话麻烦提供一个可以还原问题的环境

**Comment by zxj1997-java** [comment]
就第一次发生了,后面没在有了,如果再次出现,我将及时留存代码以及操作视频,谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月23日(星期天) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imzbf/md-editor-v3] 编辑模式下,点击右侧部分中的图片,会黑屏 (Issue #325)





 
文档实例上面会吗？不会的话麻烦提供一个可以还原问题的环境

**Comment by imzbf** [comment]
> 就第一次发生了,后面没在有了,如果再次出现,我将及时留存代码以及操作视频,谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月23日(星期天) 晚上6:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [imzbf/md-editor-v3] 编辑模式下,点击右侧部分中的图片,会黑屏 (Issue #325) 文档实例上面会吗？不会的话麻烦提供一个可以还原问题的环境 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的
