### ISSUE TITLE
 工具栏下面可以直接展示工具文字描述吗  

### ISSUE THREAD

**Issue by Jessica-you** [imzbf/md-editor-v3#327]
### 一个很棒的想法

  工具栏下面可以直接展示工具文字描述吗  我们的需求 需要工具栏展示更直观一点 方便没什么基础的普通用户

**Comment by imzbf** [comment]
是指吧图标替换成文字么？现在还不行，而且工具栏会变得很奇怪哦，比如任务列表四个字会站很宽的长度

**Comment by Jessica-you** [comment]
很高兴能这么快收到作者的回复！！  不是替换噢  是指在图标下面加一行文字  类似csdn发布文章的编辑器

**Comment by imzbf** [comment]
我尝试一下，应该是可以的

**Comment by Jessica-you** [comment]
> 我尝试一下，应该是可以的

哇撒！！！  太棒啦

**Comment by imzbf** [comment]
我在测试版中添加了这个功能，尝试方式：

1. 安装测试版

```shell
yarn add md-editor-v3@beta
```

2. 给编辑器设置`showToolbarName`

预览：

<img width="1603" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/aa23e0e6-e3e5-4a18-964c-ab440d85b0a5">

显示的名称通过语言配置来修改成想要的，使用存在问题希望及时反馈~

**Comment by Jessica-you** [comment]
> 我在测试版中添加了这个功能，尝试方式：
> 
> 1. 安装测试版
> 
> ```shell
> yarn add md-editor-v3@beta
> ```
> 
> 2. 给编辑器设置`showToolbarName`
> 
> 预览：
> 
> <img alt="image" width="1603" src="https://user-images.githubusercontent.com/37092006/256787622-aa23e0e6-e3e5-4a18-964c-ab440d85b0a5.png">
> 显示的名称通过语言配置来修改成想要的，使用存在问题希望及时反馈~

作者你好，我先是更新到测试版本，和之前一样引入，最后加了showToolbarName这个字段， 但是没有文字显示，你看是我哪个步骤不对么
![image](https://github.com/imzbf/md-editor-v3/assets/68042286/a13af637-914d-450a-b8e2-0e6412ce0001)
![image](https://github.com/imzbf/md-editor-v3/assets/68042286/7252a8ae-0650-4fb3-800f-92d35e903ebb)
![image](https://github.com/imzbf/md-editor-v3/assets/68042286/be8cba60-9734-4ee0-9d26-f36123d8d012)
![image](https://github.com/imzbf/md-editor-v3/assets/68042286/c86d6627-5275-45c2-9a03-1d60d7c32946)

**Comment by imzbf** [comment]
我试了几次好像都可以，你换个新项目试试看，可以的话就是你老项目带了依赖的缓存

**Comment by Jessica-you** [comment]
感谢  大神精准定位到了问题  现在成功了！
![image](https://github.com/imzbf/md-editor-v3/assets/68042286/917a0275-2271-4fda-b7cf-be8f5ecb8782)

因为之前是使用npm下载的 这次使用的yarn 大概就冲突引起缓存问题了

**Comment by imzbf** [comment]
4.3.0正式版更新了这个功能

**Comment by imzbf** [comment]
4.3.0正式版更新了这个功能
