### ISSUE TITLE
关于仅预览的目录滚动失效问题

### ISSUE THREAD

**Issue by Trainerchan** [imzbf/md-editor-v3#328]
### Describe the issue

我项目是用户端vue3+setup+ts，现在是文章数据过来，要展示，所以仅预览模式，加一个目录，我看您的文档网站里面也是那样的，我也想要您那样的效果，只是我不知道为什么，我明明按照您所讲的配置了scrollElement还是无法自动滚动，点击目录没有任何效果，下面是我的代码：
```vue
<template>
  <el-row>
    <el-col :span="20">
      <MdPreview class="preview" v-model="text" :editor-id="editorId" :theme="(commonStore.commonTheme as Themes)"></MdPreview>
    </el-col>
    <el-col :span="4">
      <MdCatalog :scroll-element="scrollElement" :editor-id="editorId" :theme="(commonStore.commonTheme as Themes)"></MdCatalog>
    </el-col>
  </el-row>
</template>

<script setup lang="ts">
import { MdPreview, MdCatalog, Themes, HeadList } from 'md-editor-v3';
import { TocItem } from 'md-editor-v3/lib/types/MdCatalog/MdCatalog';
import 'md-editor-v3/lib/style.css';
import { useCommonStore } from '@/store/commonStore';
import request from '@/api/request';
import { onBeforeMount, ref } from 'vue';
import { HttpResponse } from '@/api/http';
import { ArticleObj } from '@/typings/article.config.type'

const commonStore = useCommonStore()

const editorId = 'editorId'
const text = ref<string>()
const scrollElement = document.documentElement

onBeforeMount(async () => {
  try {
    const res = await request({
      url: '/api/v1/article/8',
      method: 'get'
    }) as HttpResponse
    const data = res.data as ArticleObj
    text.value = data.content
  } catch (error) {
    console.log(error)
  }
})
</script>

<style scoped></style>
```
下面是页面中的截图，我点击了没有任何效果：
![image](https://github.com/imzbf/md-editor-v3/assets/88485587/9ce9f1a2-b203-49b2-a9fa-8ec50db5dcd5)
我不知道为什么，难道您内部的滚动不是说，传入一个element元素对象，自动定位对应的高度，然后element滚动到指定位置吗？我的最外层套了个element-plus的滚动条控件，el-scrollbar，他的滚动方法scrollTo名称也是一样的，为什么就是不行呢。。我好难受啊，求求您看看

### Procedure version

4.2.2

**Comment by RickTe** [comment]
看样子你的scrollElement不应该取document.documentElement，从图片中看起来你的根元素是不能滚动的，应该取markdown内容区域那个实际可以滚动的那个元素。个人见解，等作者来回复。

**Comment by Trainerchan** [comment]
我解决了，不能直接设置.el-scrollbar,这个是overflow:hidden的。得是他里面的那个.el-scrollbar__wrap这个才行，点击定位正常哈哈哈哈，成功了我擦，，作者您这里应该具体加点说明在文档里面，要不然很多问题都得github一一回复，我看您的文档里面都没有这个说明。。。。

**Comment by Trainerchan** [comment]
> 

刚刚看到你的回复，我已经解决了，看了看其他已经解决的issues，里面有类似的目录无法滚动的问题，参考下解决了。哈哈哈

**Comment by Trainerchan** [comment]
> 看样子你的scrollElement不应该取document.documentElement，从图片中看起来你的根元素是不能滚动的，应该取markdown内容区域那个实际可以滚动的那个元素。个人见解，等作者来回复。

刚刚看到你的回复，我已经解决了，看了看其他已经解决的issues，里面有类似的目录无法滚动的问题，参考下解决了。哈哈哈

**Comment by DeSireFire** [comment]
> 我解决了，不能直接设置.el-scrollbar,这个是overflow:hidden的。得是他里面的那个.el-scrollbar__wrap这个才行，点击定位正常哈哈哈哈，成功了我擦，，作者您这里应该具体加点说明在文档里面，要不然很多问题都得github一一回复，我看您的文档里面都没有这个说明。。。。

你好，我碰到类似的问题，目录渲染出来以后，点击目录无事发生。
使用的是vue3 cli + vite + element-plus 跟你的情况类似。
看到了你的解决方法，但是我不理解。
"得是他里面的那个.el-scrollbar__wrap这个才行"
我该怎么做？可以给个示例代码嘛？谢谢大佬！

**Comment by imzbf** [comment]
> > 我解决了，不能直接设置.el-scrollbar,这个是overflow:hidden的。得是他里面的那个.el-scrollbar__wrap这个才行，点击定位正常哈哈哈哈，成功了我擦，，作者您这里应该具体加点说明在文档里面，要不然很多问题都得github一一回复，我看您的文档里面都没有这个说明。。。。
> 
> 你好，我碰到类似的问题，目录渲染出来以后，点击目录无事发生。 使用的是vue3 cli + vite + element-plus 跟你的情况类似。 看到了你的解决方法，但是我不理解。 "得是他里面的那个.el-scrollbar__wrap这个才行" 我该怎么做？可以给个示例代码嘛？谢谢大佬！

原理是`scrollElement`是滚动条在自己，而不是子元素或者父元素

**Comment by DeSireFire** [comment]
> > > 我解决了，不能直接设置.el-scrollbar,这个是overflow:hidden的。得是他里面的那个.el-scrollbar__wrap这个才行，点击定位正常哈哈哈哈，成功了我擦，，作者您这里应该具体加点说明在文档里面，要不然很多问题都得github一一回复，我看您的文档里面都没有这个说明。。。。
> > 
> > 
> > 你好，我碰到类似的问题，目录渲染出来以后，点击目录无事发生。 使用的是vue3 cli + vite + element-plus 跟你的情况类似。 看到了你的解决方法，但是我不理解。 "得是他里面的那个.el-scrollbar__wrap这个才行" 我该怎么做？可以给个示例代码嘛？谢谢大佬！
> 
> 原理是`scrollElement`是滚动条在自己，而不是子元素或者父元素


```
<template>
  <div class="container">
    <div class="plugins-tips">
      使用文档(开发中...)
    </div>
    <el-scrollbar class="preview">
      <MdPreview :editorId="id" :modelValue="text" />
      <MdCatalog :editorId="id" :scrollElement="scrollElement" />
    </el-scrollbar>
  </div>
</template>

<script setup lang="ts" name="md">
import { ref, onMounted } from 'vue';
import { MdPreview,MdEditor, MdCatalog } from 'md-editor-v3';
import 'md-editor-v3/lib/preview.css';
// const MdCatalog = MdEditor.MdCatalog;
// 导入静态文本文件，例如 readme.md
// 资源可以使用 ?raw 后缀声明作为字符串引入
import textMarkdown from '~/assets/md/readme.md?raw'; // 根据实际路径调整
const id = 'preview-only';
const text = ref<string>();
const scrollElement = document.querySelector(
    '.container .el-scrollbar .el-scrollbar__wrap'
);
// 检查是否找到元素
if (scrollElement) {
  // 在这里进行你的操作
  console.log("scrollElement",scrollElement)
} else {
  console.log("scrollElement  不存在",scrollElement)
}

// 在组件挂载后加载并渲染 Markdown 内容
onMounted(() => {
  text.value = textMarkdown;
});
</script>

<style scoped>
.preview {
  height: 500px;
}
</style>
```
看了一下其它issue，又网上查了一阵..我已经麻了。
目录能生成出来，但是点击不能跳转..

**Comment by imzbf** [comment]
```diff
- const scrollElement = document.querySelector(
-     '.container .el-scrollbar .el-scrollbar__wrap'
- );
+ const scrollElement = '.container .el-scrollbar .el-scrollbar__wrap'
```

试试

**Comment by Trainerchan** [comment]
> > > > 我解决了，不能直接设置.el-scrollbar,这个是overflow:hidden的。得是他里面的那个.el-scrollbar__wrap这个才行，点击定位正常哈哈哈哈，成功了我擦，，作者您这里应该具体加点说明在文档里面，要不然很多问题都得github一一回复，我看您的文档里面都没有这个说明。。。。
> > > 
> > > 
> > > 你好，我碰到类似的问题，目录渲染出来以后，点击目录无事发生。 使用的是vue3 cli + vite + element-plus 跟你的情况类似。 看到了你的解决方法，但是我不理解。 "得是他里面的那个.el-scrollbar__wrap这个才行" 我该怎么做？可以给个示例代码嘛？谢谢大佬！
> > 
> > 
> > 原理是`scrollElement`是滚动条在自己，而不是子元素或者父元素
> 
> ```
> <template>
>   <div class="container">
>     <div class="plugins-tips">
>       使用文档(开发中...)
>     </div>
>     <el-scrollbar class="preview">
>       <MdPreview :editorId="id" :modelValue="text" />
>       <MdCatalog :editorId="id" :scrollElement="scrollElement" />
>     </el-scrollbar>
>   </div>
> </template>
> 
> <script setup lang="ts" name="md">
> import { ref, onMounted } from 'vue';
> import { MdPreview,MdEditor, MdCatalog } from 'md-editor-v3';
> import 'md-editor-v3/lib/preview.css';
> // const MdCatalog = MdEditor.MdCatalog;
> // 导入静态文本文件，例如 readme.md
> // 资源可以使用 ?raw 后缀声明作为字符串引入
> import textMarkdown from '~/assets/md/readme.md?raw'; // 根据实际路径调整
> const id = 'preview-only';
> const text = ref<string>();
> const scrollElement = document.querySelector(
>     '.container .el-scrollbar .el-scrollbar__wrap'
> );
> // 检查是否找到元素
> if (scrollElement) {
>   // 在这里进行你的操作
>   console.log("scrollElement",scrollElement)
> } else {
>   console.log("scrollElement  不存在",scrollElement)
> }
> 
> // 在组件挂载后加载并渲染 Markdown 内容
> onMounted(() => {
>   text.value = textMarkdown;
> });
> </script>
> 
> <style scoped>
> .preview {
>   height: 500px;
> }
> </style>
> ```
> 
> 看了一下其它issue，又网上查了一阵..我已经麻了。 目录能生成出来，但是点击不能跳转..

el-scroll这个组件，只有内部的wrap是可以滚动的，滚动条也是这个元素敞开的，外部的是overflow:hidden
