### ISSUE TITLE
代码块语言关键字高亮不对，比如：语言设为“routeros”,对应的关键字不亮

### ISSUE THREAD

**Issue by terance1987** [imzbf/md-editor-v3#329]
### Describe the issue

代码块语言关键字高亮不对，比如：语言设为“routeros”,对应的关键字不亮/亮的不对

### Procedure version

4.2.2

**Comment by terance1987** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/29724769/e1e633f4-c7cd-4798-8b18-f8a38578e848)
如上图，框中关键字没有高亮

**Comment by terance1987** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/29724769/17535b05-4d98-4d56-b485-76507431691a)
如上图框中关键字没有高亮显示

**Comment by imzbf** [comment]
`highlight.js`没有支持这种语言，调用`highlightAuto`自动高亮关键词有点不太准确

**Comment by terance1987** [comment]
> `highlight.js`没有支持这种语言，调用`highlightAuto`自动高亮关键词有点不太准确
![image](https://github.com/imzbf/md-editor-v3/assets/29724769/cd384d04-78bc-49c6-9b9f-709810fa59f4)
我看highlight里面是有这个JS的，或着我怎么导入这个JS使用呢

**Comment by imzbf** [comment]
目前还不行，我尝试一下看有没有办法自行扩展

**Comment by terance1987** [comment]
> 目前还不行，我尝试一下看有没有办法自行扩展
🙏

**Comment by imzbf** [comment]
有一个快速解决你问题的办法，像下面这样做，

1. 需要安装`highlight.js`到你本地

```shell
yarn add highlight.js
```

2. 配置使用本地的高亮实例

```js
import { config } from 'md-editor-v3';
import highlight from 'highlight.js';
import routeros from 'highlight.js/lib/languages/routeros';
import 'highlight.js/styles/atom-one-dark.css';

highlight.registerAliases('routeros', routeros);

config({
  editorExtensions: {
    highlight: {
      instance: highlight
    }
  }
});
```
