### ISSUE TITLE
集成到页面上有很多警告问题

### ISSUE THREAD

**Issue by zhc644322** [imzbf/md-editor-v3#331]
### Describe the issue

我在vue3+ts+vite中使用时遇到很多问题
![image](https://github.com/imzbf/md-editor-v3/assets/84365910/63dcc058-bf93-40c7-b410-0f567f537f12)
这是我的依赖
![image](https://github.com/imzbf/md-editor-v3/assets/84365910/8f7393ba-8186-442e-9ab0-cddd2291e0b5)

### Procedure version

16.18.0

### Reproduction link

https://gitee.com/thiszhc/RuoYi-Vue3-UI.git

**Comment by imzbf** [comment]
这个好像不是抛出的与编辑器相关的warning

**Comment by zhc644322** [comment]
是的，我目前换了 编辑器就好了
