### ISSUE TITLE
怎么只显示一个图片上传，去除添加图片链接与裁剪的功能

### ISSUE THREAD

**Issue by xutaoqq** [imzbf/md-editor-v3#332]
### Describe the issue

怎么只显示一个图片上传，去除添加图片链接与裁剪的功能
点击图片icon直接选择图片上传，不需要下拉菜单与其它功能

### Procedure version

18

**Comment by imzbf** [comment]
没有类似的控制器，你可以隐藏编辑器的上传图片这一项，然后通过[NormalToolbar](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%A3%20NormalToolbar)来开发你自己想要的工具
