### ISSUE TITLE
上传图片有些问题

### ISSUE THREAD

**Issue by fazheer** [imzbf/md-editor-v3#333]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/77090621/72d57fee-7d6c-46e8-b112-ec4db4ee0d28)
![image](https://github.com/imzbf/md-editor-v3/assets/77090621/1f8be6eb-dec1-4249-896a-dce51e8b7969)
您好，我使用文档写的函数来上传图片，传递给后端时发现好像没有携带file

### Procedure version

4.2.0

### Reproduction link

no

**Comment by fazheer** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/77090621/c30d9c30-60b3-4603-a6b7-022852171ee4)
传过去表单数据没有

**Comment by fazheer** [comment]
作者哥哥，有能跑通的示例程序吗，我怎么弄都传不了图片

**Comment by peng0928** [comment]
// 图片上传事件
    const onUploadImg = async (files, callback) => {
      const res = await Promise.all(
        files.map((file) => {
          return new Promise((rev, rej) => {
            // 传给后端一个FormData数据，添加键值对，这里我添加了这个文章的ID和file
            const form = new FormData();
            form.append("file", file);
            axios
              // 这里是我的后端接口，请求地址和路径可以自己改
              .post("/api/md/img/upload", form, {
                headers: {
                  "Content-Type": "multipart/form-data",
                },
              })
              .then((res) => {
                console.log(res);
                rev(res);
              })
              .catch((error) => rej(error));
          });
        })
      );

**Comment by peng0928** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/84308519/6626b4a5-148f-49c8-9770-b12d8a501e84)

**Comment by imzbf** [comment]
> ```
> 
>     const onUploadImg = async (files, callback) => {
>       const res = await Promise.all(
>         files.map((file) => {
>           return new Promise((rev, rej) => {
>             // 传给后端一个FormData数据，添加键值对，这里我添加了这个文章的ID和file
>             const form = new FormData();
>             form.append("file", file);
>             axios
>               // 这里是我的后端接口，请求地址和路径可以自己改
>               .post("/api/md/img/upload", form, {
>                 headers: {
>                   "Content-Type": "multipart/form-data",
>                 },
>               })
>               .then((res) => {
>                 console.log(res);
>                 rev(res);
>               })
>               .catch((error) => rej(error));
>           });
>         })
>       );
> ```
> 
> ```python
> @router.post('/md/img/upload', summary='md文档照片上传', description='', )
> async def ApiImdUpload(file: UploadFile = File(...)):
>     try:
>         # 执行文件上传逻辑
>         os.makedirs('static/img', exist_ok=True)
>         name = str(uuid.uuid5(uuid.NAMESPACE_DNS, str(time.time())).hex)
>         contents = await file.read()
>         # 保存文件到静态文件目录
>         with open(f"static/img/{name}.png", "wb") as f:
>             f.write(contents)
> 
>         return {"url": f"/api/static/{name}.png"}
>     except Exception as e:
>         loggers.error(e)
>         return {"msg": "error", "detail": str(e), "status": False}
> ```

你没调用`callback`

```js
callback(res.map((item) => item.data.url));
```
