### ISSUE TITLE
超出字数上限可以加个事件回调吗

### ISSUE THREAD

**Issue by xutaoqq** [imzbf/md-editor-v3#334]
### Describe the issue

超出设定字数上限可以加个事件回调吗

### Procedure version

18

**Comment by imzbf** [comment]
考虑提供`input`事件，输入超限通过该事件判断文字是否已经达到限制来实现

**Comment by xutaoqq** [comment]
> 考虑提供`input`事件，输入超限通过该事件判断文字是否已经达到限制来实现

如果设置字数上限后上传图片，会出现图片没有插入的情况（实际上图片已经上传成功了），这种情况input可以监测到吗

**Comment by imzbf** [comment]
> > 考虑提供`input`事件，输入超限通过该事件判断文字是否已经达到限制来实现
> 
> 如果设置字数上限后上传图片，会出现图片没有插入的情况（实际上图片已经上传成功了），这种情况input可以监测到吗

好像不行，这边再考虑下方案

**Comment by imzbf** [comment]
我在4.3.0版本中添加对`onError`事件新增了`overlength`的类型提示，像下面这样使用

```vue
<template>
  <MdEditor v-model="text" :maxLength="10" @onError="onError" />
</template>

<script setup lang="ts">
import { MdEditor } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const text = ref('# Hello Editor');

const onError = (err) => {
  if(err.name === 'overlength') {
    console.log(err);
  }
};
</script>
```
