### ISSUE TITLE
公式，代码高亮的依赖都是csdn加载的，怎么换成依赖包加载呢

### ISSUE THREAD

**Issue by macmac618** [imzbf/md-editor-v3#337]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/54203031/766debad-0d54-4fdb-b89f-49e912263b23)

### Procedure version

 "md-editor-v3": "^4.2.2",

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20Import%20All%20Library

所有的库都是可以自行安装依赖的哈，参考下文档就可以了

**Comment by macmac618** [comment]
好的，谢谢
