### ISSUE TITLE
有没有原生版本的

### ISSUE THREAD

**Issue by YuYin18** [imzbf/md-editor-v3#339]
### Describe the issue

原生的，不带框架的

### Procedure version

js

**Comment by imzbf** [comment]
木有，目前只有依赖vue3和react两个框架的版本

**Comment by YuYin18** [comment]
> 木有，目前只有依赖vue3和react两个框架的版本
有什么推荐的吗

**Comment by imzbf** [comment]
原生的markdown版本的没怎么接触过，不过好像掘金的那个编辑器时有原生版本的，但是没用过
