### ISSUE TITLE
请问如何单独关闭markdown预览模式滚动条

### ISSUE THREAD

**Issue by rp-lab** [imzbf/md-editor-v3#34]
求大佬指点

**Comment by imzbf** [comment]
组件没有提供主动关闭滚动条的API，若你特别需要不显示滚动条，请通过设置`editorClass`以覆盖默认class的表现，参考[::-webkit-scrollbar](https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar)，他们会有兼容问题。

**Comment by rp-lab** [comment]
thank you !
