### ISSUE TITLE
Styles are not working

### ISSUE THREAD

**Issue by sandranrivas** [imzbf/md-editor-v3#340]
### Describe the issue

Styles are not working at all, all the structure is rendered in browser but the styles won't.
```

<template>
  <MdEditor v-model="content" />
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue'
import { MdEditor } from 'md-editor-v3'
import 'md-editor-v3/lib/style.css'

export default defineComponent({
  name: 'TextEditor',
  components: {
    MdEditor,
  },
  setup() {
    const content = ref('test')

    // ... any other composition functions you want to use

    return {
      content,
    }
  },
})
</script>

```

### Procedure version
I am using, vue composition api, vue 3, vue ts, setup function and vite
.

**Comment by imzbf** [comment]
Sorry, I tried your code and can't find the problem. 

<img width="1726" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/54dad17f-d2ee-4dcb-bb6d-181d2812ddcb">


Perhaps this is a problem with your development environment. Try using an official environment

**Comment by sandranrivas** [comment]
I was using it as a Web component. my problem was that I needed to import the styles on style.
```
<style lang="postcss">
@import 'md-editor-v3/lib/style.css';
</style>
```

**Comment by sandranrivas** [comment]
The only problem now is that I don't see the icons, but the functionality do works
<img width="923" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/48434421/4bf67ab5-9aed-4624-a2ed-524b3785e509">

**Comment by imzbf** [comment]
> [WICG/webcomponents#772](https://github.com/WICG/webcomponents/issues/772)

Thanks, I am trying to provide a replacement solution

**Comment by imzbf** [comment]
> [WICG/webcomponents#772](https://github.com/WICG/webcomponents/issues/772)

I provide icons of `font-class`. have a try

```shell
yarn add md-editor-v3@beta
```

```js
import { config } from 'md-editor-v3';

config({
  iconfontType: 'class'
})
```

**Comment by imzbf** [comment]
Latest version has been released
