### ISSUE TITLE
请大佬帮我看看怎么搞自定义工具栏。搞了好久实在搞不定了

### ISSUE THREAD

**Issue by PasserAhao** [imzbf/md-editor-v3#341]
![image](https://github.com/imzbf/md-editor-v3/assets/106132965/e576e131-5a1f-40fd-abfe-b270898630f6)
![image](https://github.com/imzbf/md-editor-v3/assets/106132965/a6be62bc-b449-468b-96b9-6e7fa1721bbf)

**Comment by imzbf** [comment]
如果版本是`4.x`的话，扩展组件的引用方式不是这样引用的了哦，参考这里的完整实例：

https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%BC%20DropdownToolbar

**Comment by PasserAhao** [comment]
好的，感谢大佬，我今晚回去看看。请问大佬有没有项目的q群或者微群

**Comment by PasserAhao** [comment]
今天更新到4.x之后在引入 insert的时候在type {}这里会一直报错。之前的2.4.1版本自定义工具栏也没有生效

**Comment by imzbf** [comment]
具体是怎样的

**Comment by PasserAhao** [comment]
应该是语法检测那边什么问题估计，主要我不熟悉ts所以整起来有点麻烦。请问博主有2.4.1版本js自定义版本的写法吗？

**Comment by imzbf** [comment]
没有js的，目前只有类型定义，你移除掉就可以了
