### ISSUE TITLE
Scroll problem in preview

### ISSUE THREAD

**Issue by Leonardo-Bo** [imzbf/md-editor-v3#342]
### Describe the issue

Hello everyone.
First, congratulations to the authors for their work. 
I'm having problems with scrolling: if I view the preview I can scroll on both sides (md and preview), but once I scroll on the preview the text on the md side goes back to the beginning and scrolling is no longer possible. 
Also I noticed that the two sides do not scroll synchronously, but are independent. 
I don't know if this is a bug or my configuration error. 
I am using version 4.3.0 and use the component as follows:

```vue
<template>
    <MdEditor v-model="abstract" :editor-id="'mde-abstract'"/>
</template>

<script setup>
import { ref } from 'vue'
import { MdEditor } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const abstract = ref('')
</script>

<style scoped lang="scss">
#mde-abstract {
    height: 250px;    
}
</style>
```
There is also another `MdEditor` on the page with different `:editor-id` and `v-model`.

If it helps, I noticed that adding another identical hidden component solves the problem:

```vue
<template>
    <div v-show=false>
        <MdEditor v-model="abstract" :editor-id="'mde-abstract'"/>
    </div>
    <MdEditor v-model="abstract" :editor-id="'mde-abstract'"/>
</template>
```

### Procedure version

node 18.7.0, tested on chrome and firefox

**Comment by imzbf** [comment]
If there are two or more editor.

Each of them needs to have a different `editorId`

**Comment by Leonardo-Bo** [comment]
Thank you for your answer!

> And if there are more than one editors.
>
> Each of them needs to have a different `editorId`

Yes, the other MdEditor has a different `editorId`. 

About the problem I don't understand: is this a bug or my mistake?

In my project I count to use MdEditor many times and it is not practical to add every time `<div v-show=false>`

**Comment by imzbf** [comment]
Sorry, more business logic needs to be set by you

And if you have set different `editorId`, editor should  not be affected by `v-show`

**Comment by Leonardo-Bo** [comment]
Sorry, I misspoke. Ignore the v-show part.

I tried to recreate from scratch a vue project with vite and installed only `md-editor-v3`. Apart from the synchronous scroll between markdown and preview not working well, the blocked scroll problem does not occur. 

I noticed that the scroll works depending on the text entered and this is really strange

*scroll works*
![scroll_ok](https://github.com/imzbf/md-editor-v3/assets/73877676/24b506d5-b967-4f9f-bda6-adbbe011fc39)

*scroll does not work*
![scroll_no](https://github.com/imzbf/md-editor-v3/assets/73877676/41ad524f-0675-4e7a-a9ed-4ee1c8560486)

Unfortunately, I don't know what else to add to better clarify the problem

**Comment by imzbf** [comment]
> Sorry, I misspoke. Ignore the v-show part.
> 
> I tried to recreate from scratch a vue project with vite and installed only `md-editor-v3`. Apart from the synchronous scroll between markdown and preview not working well, the blocked scroll problem does not occur.
> 
> I noticed that the scroll works depending on the text entered and this is really strange
> 
> _scroll works_ ![scroll_ok](https://user-images.githubusercontent.com/73877676/263021472-24b506d5-b967-4f9f-bda6-adbbe011fc39.gif)
> 
> _scroll does not work_ ![scroll_no](https://user-images.githubusercontent.com/73877676/263021532-41ad524f-0675-4e7a-a9ed-4ee1c8560486.gif)
> 
> Unfortunately, I don't know what else to add to better clarify the problem

About this, I am thinking about ways to handle it. But it may be later because I don't have enough time after work. Progress #323

**Comment by Leonardo-Bo** [comment]
If it helps, I noticed that the scroll works perfectly if the text consists of more than one paragraph.
If the text is a single long paragraph I have the problems described

![scroll_no2](https://github.com/imzbf/md-editor-v3/assets/73877676/7f793727-4d95-4a1b-8952-975c58c18220)

**Comment by slugb0t** [comment]
Was a solution ever resolved for the scroll auto breaking on Chrome? Seems to work fine on Firefox

**Comment by imzbf** [comment]
> Was a solution ever resolved for the scroll auto breaking on Chrome? Seems to work fine on Firefox

Can you provide the width and height of the editor where the issue was found, as well as the text of the content, preferably if there is an online link
