### ISSUE TITLE
更新到4.x之后previewOnly是失效了吗？

### ISSUE THREAD

**Issue by PasserAhao** [imzbf/md-editor-v3#343]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/106132965/dedbff7d-185d-49d0-a1c3-53fac6d73e1a)
![image](https://github.com/imzbf/md-editor-v3/assets/106132965/f725140e-8b23-49d2-b35c-c824b4f2a0ab)

### Procedure version

js

**Comment by PasserAhao** [comment]
我今晚回来尝试自定义的工具栏的时候更新了包到4.x版本，然后发现previewOnly属性失效了，在文档里边没有找到解决方法。请问大佬是换关键词还是什么问题

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/zh-CN/contrast#%F0%9F%AA%A4%20%E5%86%85%E9%83%A8%E7%BB%84%E4%BB%B6

文档的升级对比里面有说明哈
