### ISSUE TITLE
请问一下有自定义语法的方法吗

### ISSUE THREAD

**Issue by 3047819830** [imzbf/md-editor-v3#344]
### A great idea

文档看了很久，没找到相应的方法

**Comment by imzbf** [comment]
什么语法

**Comment by 3047819830** [comment]
自定义markdown语法

**Comment by imzbf** [comment]
内部编译是`markdown-it`库，你只需要参考它的扩展方式写扩展，然后通过下面的方式添加到编辑器就可以了

https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8D%A4%20markdownItConfig
