### ISSUE TITLE
Add customizable icons

### ISSUE THREAD

**Issue by sandranrivas** [imzbf/md-editor-v3#345]
### A great idea

Is there any way to add my own icons? I want to use the icons from font awesome, unfortunately I dont find anything on the guideline.

**Comment by imzbf** [comment]
Sorry, there is no way to replace icons. But I can try providing a covered entrance

**Comment by imzbf** [comment]
Updated in version 4.5.0

And document: https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%98%AC%20customIcon
