### ISSUE TITLE
mdpreview style color属性字体没有显示

### ISSUE THREAD

**Issue by PasserAhao** [imzbf/md-editor-v3#346]
### 描述这个Bug

之前版本使用 :style={color:red}字体会显示红色，现在版本字体不会受到color属性影响，只是工具栏颜色变了

### 版本号

最新版本

**Comment by imzbf** [comment]
> ### 描述这个Bug
> 之前版本使用 :style={color:red}字体会显示红色，现在版本字体不会受到color属性影响，只是工具栏颜色变了
> 
> ### 版本号
> 最新版本
> 
> ### 问题重现链接
> _No response_

`style`不会直接作用于预览区域，因为有很多的主题的样式设置优先级比这个高，请通过内置的`css`变量来设置字体等，源码的readme结尾有标注
