### ISSUE TITLE
点击编辑器报错

### ISSUE THREAD

**Issue by zhc644322** [imzbf/md-editor-v3#347]
### 描述这个Bug

当我点击编辑器的时候会触发一个错误
index.js:3746 Unable to preventDefault inside passive event listener invocation.
![image](https://github.com/imzbf/md-editor-v3/assets/84365910/668b78ef-6512-4895-b6ed-2997558d7019)

我已经将问题代码上传至我的仓库，请查看问题链接，在分支devMdedit

### 版本号

16.18.0

### 问题重现链接

https://gitee.com/thiszhc/RuoYi-Vue3-UI.git

**Comment by zhc644322** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/84365910/63b4ed05-6fcc-41ba-9ce2-10d2a019cacd)

**Comment by zhc644322** [comment]
这个错误信息 "Unable to preventDefault inside passive event listener invocation" 通常发生在尝试在被动事件监听器中调用 `event.preventDefault()` 的情况下。被动事件监听器旨在通过指示监听器不会在事件上调用 `preventDefault()` 来提高滚动性能。这使得浏览器可以优化滚动行为。

要解决这个问题，你有几个选项：

1. 移除 `event.preventDefault()` 调用：如果在你的情况下不需要阻止默认行为，你可以简单地将代码中的 `event.preventDefault()` 移除。

2. 使用非被动事件监听器：如果需要阻止默认行为，你可以将事件监听器从被动改为非被动。通常情况下，你可以在添加事件监听器时作为第三个参数添加 `{ passive: false }`。例如：

   ```javascript
   element.addEventListener('event', listener, { passive: false });
   ```

   需要注意的是，将现有的事件监听器从被动改为非被动可能会对性能产生影响，因此请谨慎使用此选项。

3. 为需要 `preventDefault()` 的事件使用单独的处理函数：如果只需要针对特定情况阻止默认行为，你可以为该情况创建一个单独的事件处理函数，并将其作为非被动事件监听器附加。例如：

   ```javascript
   function start(event) {
     event.preventDefault();
     this.select(event);
   }

   element.addEventListener('event', start, { passive: false });
   ```
   通过创建单独的处理函数，你仍然可以阻止默认行为，而不影响其他被动事件监听器。

**Comment by imzbf** [comment]
感谢你的描述，我在尝试运行了你的项目后，发现是因为`default-passive-events`这个库导致的，不太清楚它对你的具体意义，只是需要移除它才可以
