### ISSUE TITLE
添加设置参数enableEmojiExtension

### ISSUE THREAD

**Issue by liaokaipeng** [imzbf/md-editor-v3#349]
### 一个很棒的想法

设置一个参数enableEmojiExtension，设置为true时，则在preview里加上EmojiExtension。
我添加EmojiExtension的过程中，遇到了些困难，尤其在最后需要配置css时，我发现我搞不定了

**Comment by imzbf** [comment]
抱歉，这个扩展不会被默认添加到编辑组件中，`dev-docs`的源码可以参考。

在后面`md-editor-extension`这个库会添加一些常用的扩展，包括emoji的，目前还在计划中

**Comment by liaokaipeng** [comment]
> 抱歉，这个扩展不会被默认添加到编辑组件中，`dev-docs`的源码可以参考。
> 
> 在后面`md-editor-extension`这个库会添加一些常用的扩展，包括emoji的，目前还在计划中

好的，谢谢。
那能不能将emoji需要用到的css都放在EmojiExtension的index.vue呢？这样可能大家用起来更方便
https://blog.csdn.net/tongkongyu/article/details/126059085这个人也是因为css的缘故而放弃了使用md-editor-v3
我也卡在css了，但我很喜欢md-editor-v3的主题，所以还没放弃

**Comment by imzbf** [comment]
ok，我找时间调整一下`emoji`扩展的代码，大概明天就可以了

**Comment by imzbf** [comment]
`dev-docs`中的emoji组件已经独立出来了

https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/components/EmojiExtension/index.vue

**Comment by liaokaipeng** [comment]
非常感谢，还有两个小问题：
（1）在dark模式下，表情包选择框的背景依旧是白色的
（2）菜单栏的表情包选项，是空白的（点击空白可以正常打开表情包选择框）

**Comment by imzbf** [comment]
> 非常感谢，还有两个小问题： （1）在dark模式下，表情包选择框的背景依旧是白色的 （2）菜单栏的表情包选项，是空白的（点击空白可以正常打开表情包选择框）

第一个你还需要定义css变量，看一下暗夜模式css代码

第二个你没有对应图标，你定义成你喜欢的就可以

**Comment by liaokaipeng** [comment]
ok, thank you
