### ISSUE TITLE
渲染不是实时的吗，为什么会有一秒的延迟？

### ISSUE THREAD

**Issue by funmoji** [imzbf/md-editor-v3#350]
### Describe the issue

  <div class="main">
    <md-editor v-model="text" :toolbarsExclude="['save', 'link', 'github']" autoFocus @onUploadImg="onUploadImg" />
  </div>

左边输入内容后，过了一秒之后才有右边的内容。
![image](https://github.com/imzbf/md-editor-v3/assets/127827790/3a7e2f86-0be7-4f00-b0bc-a8860730b1a2)

### Procedure version

nodejs16&nodejs18

**Comment by imzbf** [comment]
不是实时的，实时的会卡顿，要关闭参考文档中的`config`配置
