### ISSUE TITLE
渲染表格内容的时候不是表格内容也会展示在表格内

### ISSUE THREAD

**Issue by Pan-yongyong** [imzbf/md-editor-v3#351]
### 描述这个Bug

在使用MdPreview的时候如果内容中有表格内容，| 结尾后不是表格内容也会展示在表格内

我为你整理了高尿酸血症的药物治疗表格如下：
|药物类别|药物名称|作用|剂量与使用注意|
|:----:|:----:|:----:|:----:|
|增加尿酸排泄的药物|苯溴马隆|降低血尿酸水平|成人：肌酐清除率45～60 ml/min时，每日50 mg；肌酐清除率＞60 ml/min时，每日50～100 mg。注意使用时可能产生尿酸结石、肝肾结石等副作用。|
|增加尿酸排泄的药物|丙磺舒、磺吡酮|降低血尿酸水平|仅适用于肾功能正常者；使用时需注意肝损较多见。|
|辅助降尿酸药|氯沙坦、非诺贝特|降低血尿酸水平|按照医生的建议和处方使用。|
在使用药物治疗的同时，还需注意改善生活方式（如低嘌呤饮食、多饮水、戒烟酒、坚持运动和控制体重等），同时避免使用可能导致血尿酸升高的药物。具体的药物治疗方案需在医生的指导下进行。

将上面这段内容复制在demo展示处即可复现

### 版本号

4.2.2

**Comment by Pan-yongyong** [comment]
我为你整理了高尿酸血症的药物治疗表格如下：
|药物类别|药物名称|作用|剂量与使用注意|
|:----:|:----:|:----:|:----:|
|增加尿酸排泄的药物|苯溴马隆|降低血尿酸水平|成人：肌酐清除率45～60 ml/min时，每日50 mg；肌酐清除率＞60 ml/min时，每日50～100 mg。注意使用时可能产生尿酸结石、肝肾结石等副作用。|
|增加尿酸排泄的药物|丙磺舒、磺吡酮|降低血尿酸水平|仅适用于肾功能正常者；使用时需注意肝损较多见。|
|辅助降尿酸药|氯沙坦、非诺贝特|降低血尿酸水平|按照医生的建议和处方使用。|
在使用药物治疗的同时，还需注意改善生活方式（如低嘌呤饮食、多饮水、戒烟酒、坚持运动和控制体重等），同时避免使用可能导致血尿酸升高的药物。具体的药物治疗方案需在医生的指导下进行。

（在使用药物治疗的同时，还需注意改善生活方式（如低嘌呤饮食、多饮水、戒烟酒、坚持运动和控制体重等），同时避免使用可能导致血尿酸升高的药物。具体的药物治疗方案需在医生的指导下进行。）应该不在表格内

**Comment by imzbf** [comment]
是的，这种表现是正常的，大家都遵循的规范，只需要在表格和段落之间回车就可以避免

**Comment by Pan-yongyong** [comment]
嗯，我发现这段内容（在使用药物治疗的同时，还需注意改善生活方式（如低嘌呤饮食、多饮水、戒烟酒、坚持运动和控制体重等），同时避免使用可能导致血尿酸升高的药物。具体的药物治疗方案需在医生的指导下进行。）前面实际上是有\n的，但是需要两个\n才可以避免这个问题

**Comment by Pan-yongyong** [comment]
> 是的，这种表现是正常的，大家都遵循的规范，只需要在表格和段落之间回车就可以避免

嗯，我发现这段内容（在使用药物治疗的同时，还需注意改善生活方式（如低嘌呤饮食、多饮水、戒烟酒、坚持运动和控制体重等），同时避免使用可能导致血尿酸升高的药物。具体的药物治疗方案需在医生的指导下进行。）前面实际上是有\n的，但是需要两个\n才可以避免这个问题

**Comment by imzbf** [comment]
对，一个\n仅仅是换行了，多一个才是中间有一个空格的
