### ISSUE TITLE
目录的位置可以选择吗，比如可以放在左侧吗，默认是右侧。

### ISSUE THREAD

**Issue by peng0928** [imzbf/md-editor-v3#352]
### 一个很棒的想法

![image](https://github.com/imzbf/md-editor-v3/assets/84308519/287a0c58-3949-483c-aa47-2edf440c53d3)

**Comment by imzbf** [comment]
抱歉这个暂时不能支持，你可以合理的利用`MdEditor`和`MdPreview`两个组件，来组装你需要的样子

**Comment by peng0928** [comment]
ok
