### ISSUE TITLE
MdEditor 使用v-model 或 modelValue 后，编辑左侧内容，均无法修改右侧的预览数据

### ISSUE THREAD

**Issue by Kiven-Rain** [imzbf/md-editor-v3#353]
![image](https://github.com/imzbf/md-editor-v3/assets/27115233/0ba609e1-50f4-4c27-9eee-280569da356b)

![image](https://github.com/imzbf/md-editor-v3/assets/27115233/4fed7523-f5ea-4d13-bc62-73cea074c35a)

**Comment by imzbf** [comment]
你的onChange绑定的是啥

我写成这样没问题

```js
const onChange = (v) => {
  console.log(v);
};
```
