### ISSUE TITLE
页面有多个编辑器时，开启同步滚动后，无效

### ISSUE THREAD

**Issue by webguosai** [imzbf/md-editor-v3#356]
### 描述这个Bug

在页面上有多个编辑器时，全部开启同步滚动后，只有第一个编辑器正常，第二个编辑器（编辑模式下滚动）没有反映
chrome 和 firefox 都没反映

### 版本号

4.6.1

**Comment by imzbf** [comment]
版本号麻烦描述一下

保证下面的条件满足

1. `editorId`每个编辑器不一样

**Comment by webguosai** [comment]
就是最新版本 4.6.1
我的代码，就是这样使用的（按需引用）
```vue
import { MdEditor } from 'md-editor-v3'

<md-editor v-model="value1" :scrollAuto="true"/>
<md-editor v-model="value2" :scrollAuto="true"/>
```
第二个编辑器，的滚动无效，第一个可以滚动 @imzbf

**Comment by imzbf** [comment]
> 版本号麻烦描述一下
> 
> 保证下面的条件满足
> 
> 1. `editorId`每个编辑器不一样

条件要满足

**Comment by webguosai** [comment]
> > 版本号麻烦描述一下
> > 保证下面的条件满足
> > 
> > 1. `editorId`每个编辑器不一样
> 
> 条件要满足
谢谢，这样就好了，
```vue
<md-editor editorId="e1" v-model="value1" :scrollAuto="true"/>
<md-editor editorId="e2" v-model="value2" :scrollAuto="true"/>
```
