### ISSUE TITLE
可不可以加入导出PDF功能？

### ISSUE THREAD

**Issue by terance1987** [imzbf/md-editor-v3#357]
### 一个很棒的想法

编辑好的markdown内容可以不可以一键导出PDF？现在自已导出很多格式都有问题，期待~

**Comment by imzbf** [comment]
这类功能以后会在[md-editor-extension](https://github.com/imzbf/md-editor-extension)中做，目前还在做项目改造

**Comment by terance1987** [comment]
> 这类功能以后会在[md-editor-extension](https://github.com/imzbf/md-editor-extension)中做，目前还在做项目改造

好的

**Comment by imzbf** [comment]
我在扩展库中添加了这个组件，使用文档：https://github.com/imzbf/md-editor-extension/blob/main/packages/v3/components/ExportPDF/README.md

**Comment by imzbf** [comment]
> 我在扩展库中添加了这个组件，使用文档：https://github.com/imzbf/md-editor-extension/blob/main/packages/v3/components/ExportPDF/README.md

注意如果需要切换主题和语言，请将编辑器升级到`4.7.0`及以上
