### ISSUE TITLE
CDN链接引用的页面在钉钉手机端打不开

### ISSUE THREAD

**Issue by terance1987** [imzbf/md-editor-v3#358]
### 描述这个Bug

我的项目使用的是CDN引入的方式，问题是页面在电脑端以及钉钉电脑端显示都没有问题，但在钉钉手机端打不开，无法正常显示，然后用了示例中的代码，如下图：
![image](https://github.com/imzbf/md-editor-v3/assets/29724769/ff0d716e-473a-48e8-af07-04e861387872)
也是有同样的问题，在钉钉手机端无法正常运行，请看下什么原因，应该如何解决？谢谢！

### 版本号

4.6.1/4.3.0/4.2.2

**Comment by imzbf** [comment]
作者没有钉钉手机端的调试环境，这类问题请求能遇见的伙伴协助你

**Comment by pengqian089** [comment]
不一定是钉钉的问题吧，你用手机访问 unpkg 试试再说吧

**Comment by pengqian089** [comment]
> 不一定是钉钉的问题吧，你用手机访问 unpkg 试试再说吧

如果可以访问，再加上

``` html
<script src="https://unpkg.com/vconsole@latest/dist/vconsole.min.js"></script>
```

打开控制台看看是什么问题
