### ISSUE TITLE
支持文件拖拽上传

### ISSUE THREAD

**Issue by 1714080902120** [imzbf/md-editor-v3#359]
### 一个很棒的想法

大佬能支持文件拖拽上传吗？或者有什么方案可以自行实现的？这样体验感上会好很多，我自己也是个重度使用拖拽上传的用户。

**Comment by imzbf** [comment]
目前版本支持监听拖拽释放的事件。这块监听一下就可以了，https://github.com/imzbf/md-editor-v3/discussions/348

**Comment by 1714080902120** [comment]
好的，谢谢大佬~
