### ISSUE TITLE
4.6.1版本控制台会报错chunk-vendors.ea148b9f.js:1 TypeError: Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by wqcn322** [imzbf/md-editor-v3#361]
### 描述这个Bug

chunk-vendors.ea148b9f.js:1 TypeError: Cannot read properties of null (reading 'addEventListener')

### 版本号

4.6.1

**Comment by imzbf** [comment]
请问怎么复现

**Comment by wqcn322** [comment]
没外网的情况下因为不能烦访问cdn导致图标，prettier等cdn用不了  这种情况下改怎么处理？

**Comment by imzbf** [comment]
> 没外网的情况下因为不能烦访问cdn导致图标，prettier等cdn用不了 这种情况下改怎么处理？

文档示例中有，注意查看。

该问题是因为这个导致的吗？

**Comment by imzbf** [comment]
参考 #362
