### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'view')

### ISSUE THREAD

**Issue by Msg-Lbo** [imzbf/md-editor-v3#362]
### Describe the issue

# 测试环境
### vue3+vite+typescript
# 版本
``` json
{
  "name": "test",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vue-tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "md-editor-v3": "^4.6.1",
    "vue": "^3.3.4"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "typescript": "^5.0.2",
    "vite": "^4.4.5",
    "vue-tsc": "^1.8.5"
  }
}
```
# 错误描述
## 错误相关代码
``` vue
<template>
  <MdEditor v-model="text" />
</template>
<script setup lang="ts">
import { ref } from 'vue';
import { MdEditor } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
const text = ref('Hello Editor!');

</script>

<style scoped></style>
```

### Procedure version

nodejs:20.5.0, vscode, edge

**Comment by Msg-Lbo** [comment]
> ### Describe the issue
> # 测试环境
> ### windows10
> ### vue3+vite+typescript
> # 版本
> ```json
> {
>   "name": "test",
>   "private": true,
>   "version": "0.0.0",
>   "type": "module",
>   "scripts": {
>     "dev": "vite",
>     "build": "vue-tsc && vite build",
>     "preview": "vite preview"
>   },
>   "dependencies": {
>     "md-editor-v3": "^4.6.1",
>     "vue": "^3.3.4"
>   },
>   "devDependencies": {
>     "@vitejs/plugin-vue": "^4.2.3",
>     "typescript": "^5.0.2",
>     "vite": "^4.4.5",
>     "vue-tsc": "^1.8.5"
>   }
> }
> ```
> 
> # 错误描述
> ### 什么都没装的情况下，点击编辑框和预览框会报错
> #### TypeError: Cannot read properties of null (reading 'maybeMeasure')
> #### TypeError: Cannot read properties of null (reading 'view')
> ## 错误相关代码
> ```
> <template>
>   <MdEditor v-model="text" />
> </template>
> <script setup lang="ts">
> import { ref } from 'vue';
> import { MdEditor } from 'md-editor-v3';
> import 'md-editor-v3/lib/style.css';
> const text = ref('Hello Editor!');
> 
> </script>
> 
> <style scoped></style>
> ```
> 
> ### Procedure version
> nodejs:20.5.0, vscode, edge
> 
> ### Reproduction link
> _No response_

这里报错指的是浏览器控制台报错

**Comment by Msg-Lbo** [comment]
> ```shell
> @codemirror/view@6.18.1
> ```

问题已解决，谢过

**Comment by CodingAndSleeping** [comment]
> 依赖的库更新了不兼容的东西，临时解决办法
> 
> ```shell
> yarn add @codemirror/view@6.18.1
> ```
还是没有解决呀

**Comment by imzbf** [comment]
> > 依赖的库更新了不兼容的东西，临时解决办法
> > ```shell
> > yarn add @codemirror/view@6.18.1
> > ```
> 
> 还是没有解决呀

有解决方案了，还在测试，今天晚点就可以安装新版本了

**Comment by imzbf** [comment]
在4.6.2中尝试

**Comment by CodingAndSleeping** [comment]
> 在4.6.2中尝试

    "@codemirror/view": "^6.18.1",
    "md-editor-v3": "^4.6.2",

都安装了还是不行

index.js:1820  TypeError: Cannot read properties of null (reading 'scheduleWork')
    at focus (index.js:647:37)

**Comment by imzbf** [comment]
> > 在4.6.2中尝试
> 
> ```
> "@codemirror/view": "^6.18.1",
> "md-editor-v3": "^4.6.2",
> ```
> 
> 都安装了还是不行
> 
> index.js:1820 TypeError: Cannot read properties of null (reading 'scheduleWork') at focus (index.js:647:37)

`4.6.2`不需要额外安装view，把你的locak文件删掉重新安装
