### ISSUE TITLE
手动调用保存方法不会触发onSave回调

### ISSUE THREAD

**Issue by daixu-cn** [imzbf/md-editor-v3#364]
### 描述这个Bug

使用实例上面的 editorRef.value?.triggerSave()，不会触发onSave事件，或者有什么其他方法可以直接获取到编辑器转换之后的html吗？

### 版本号

"md-editor-v3": "^4.6.1"

**Comment by imzbf** [comment]
<img width="1451" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/84709070-7b4f-443b-991a-96f48a1c740c">

我试了下，好像可以触发`onSave`的回调

**Comment by daixu-cn** [comment]
> <img alt="image" width="1451" src="https://user-images.githubusercontent.com/37092006/268813445-84709070-7b4f-443b-991a-96f48a1c740c.png">
> 我试了下，好像可以触发`onSave`的回调

抱歉，onSave事件回调是正常的，是我代码上的问题导致的异常。
