### ISSUE TITLE
自定义toolbar功能栏下的子功能显示

### ISSUE THREAD

**Issue by puppet-666** [imzbf/md-editor-v3#367]
# 问题描述：
如下图，是否能够允许用户自定义功能是否显示？
目前仅能通过hack的方式对item进行display:none处理，但是由于每个功能bar的class名都为md-editor-menu-item，可能会导致其他功能不可用，能否针对具有下拉功能的列表提供配置化？或者对每个不同功能下的class名称加入子功能prfix区分？
![image](https://github.com/imzbf/md-editor-v3/assets/45839282/7ea52703-de1f-44d5-a5be-df7a104fb373)

**Comment by imzbf** [comment]
如果不需要裁剪上传，那需要移除掉上传图片的功能，有一个`noUploadImg`的api，可以只显示添加链接，如果高度自定义，建议隐藏掉默认的项，通过组件的扩展功能自行扩展你的工具栏

**Comment by puppet-666** [comment]
noUploadImage会整体移除掉上传，考虑到开发成本的话还是会默认选择自带的上传。
其实在这里每个子项功能的class是否能从md-editor-menu-item优化为md-editor-xxx-menu-item(xxx代表功能块，比如imge就是md-editor-image-menu-item)? 这样就算改样式也不会直接影响其他子功能下拉框。如果觉得ok的话，我这边能提供pr

**Comment by imzbf** [comment]
> noUploadImage会整体移除掉上传，考虑到开发成本的话还是会默认选择自带的上传。 其实在这里每个子项功能的class是否能从md-editor-menu-item优化为md-editor-xxx-menu-item(xxx代表功能块，比如imge就是md-editor-image-menu-item)? 这样就算改样式也不会直接影响其他子功能下拉框。如果觉得ok的话，我这边能提供pr

可以考虑给子项添加特有的标识类，不改变原有的类名，比如裁剪上传可以是`md-editor-menu-item md-editor-menu-item-clip`，组件不对特有的标识类提供样式，作为开发者外部调整的根据
