### ISSUE TITLE
上传本地图片报错

### ISSUE THREAD

**Issue by rp-lab** [imzbf/md-editor-v3#37]
![截屏2022-01-02 下午5 58 21](https://user-images.githubusercontent.com/81206614/147872399-012f3574-8551-4a0f-8550-b93cc81b3d2b.png)

**Comment by imzbf** [comment]
你好，方便问下这种情况是怎么出现的吗

**Comment by rp-lab** [comment]
没有其他操作，只是选择了本地一张图片，不过我是用js写的

**Comment by rp-lab** [comment]
h还没有处理业务就出现了这种情况
![image](https://user-images.githubusercontent.com/81206614/147880975-8b496f7f-cbe1-470b-ba52-5088dd0f4b6b.png)

**Comment by rp-lab** [comment]
请问大佬啥时候可以修复，嘿嘿嘿

**Comment by imzbf** [comment]
> 请问大佬啥时候可以修复，嘿嘿嘿

如果很急的话，你暂时取消你的项目中的严格模式，看错误应该是这个导致的。这边暂时来不及去调整哦

**Comment by Deleter-D** [comment]
请问一下，这个问题现在有好的解决途径了吗，我尝试了很多方式都没能关闭严格模式

**Comment by imzbf** [comment]
> 请问一下，这个问题现在有好的解决途径了吗，我尝试了很多方式都没能关闭严格模式

最近时间不太宽裕，所以还没来得及。🙈

**Comment by imzbf** [comment]
> 请问一下，这个问题现在有好的解决途径了吗，我尝试了很多方式都没能关闭严格模式

> ![截屏2022-01-02 下午5 58 21](https://user-images.githubusercontent.com/81206614/147872399-012f3574-8551-4a0f-8550-b93cc81b3d2b.png)

这边看了一下，输出文件对象列表是存在类似的问题，但是可以直接使用`Array.from(files)`转换为数组，并不会影响使用。

**Comment by imzbf** [comment]
参考文档中提供的上传图片示例，是可以完成功能开发的。
