### ISSUE TITLE
你好,codeStyleReverse属性和codeStyleReverseList属性均无效,是我写错了吗

### ISSUE THREAD

**Issue by LiarAndQuan** [imzbf/md-editor-v3#371]
### Describe the issue

我想让mk-blue主题内置的代码块从暗黑的改成亮色
![image](https://github.com/imzbf/md-editor-v3/assets/91007741/b816caea-f898-4954-b425-b7f4cf320403)
![image](https://github.com/imzbf/md-editor-v3/assets/91007741/b1171e40-8c9d-411e-aaae-40547b547ba9)
设置了codeStyleReverse不生效就想替换这个数组,还是不生效

### Procedure version

^4.7.0

**Comment by imzbf** [comment]
<img width="1203" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/674c8b1a-5811-4039-89aa-c4321488a88b">

```
:codeStyleReverseList="['default']"
```

只要这个就可以了
