### ISSUE TITLE
使用 HTML <!-- abc --> 注释时，后续内容都空白了

### ISSUE THREAD

**Issue by vikyd** [imzbf/md-editor-v3#372]
### 描述这个Bug

例如下面内容，在预览中，只渲染出 `up`，看不见 `down` 了：
```md
up

<!-- 这是 html 注释，看不见？ --> 

down
```

参考 GitHub 的注释语法： https://stackoverflow.com/a/46734863/2752670

### 版本号

4.8.0

**Comment by imzbf** [comment]
我在4.8.1中优化了这个问题
