### ISSUE TITLE
MdPreview时导航目录不能跳转

### ISSUE THREAD

**Issue by datawz** [imzbf/md-editor-v3#377]
### 一个很棒的想法

MdPreview时导航目录不能跳转，这个是本来就没有，需要自己写的，还是bug？
目前，我只能手动实现了下。

还有MdEditor只能预览和编辑同时显示，不能关闭掉这个编辑

![image](https://github.com/imzbf/md-editor-v3/assets/39027735/63180b84-6144-4513-ba50-a2fa2df5c47a)

**Comment by imzbf** [comment]
MdPreview自带了功能，注意你的使用方式，核心是`editorId`和`scrollElement`

关于关掉编辑框，这个之前讨论过了，不会支持，因为上面还有工具栏，会出现很多难以预料的事情，如果也不想要工具栏，这个时候你只要使用`MdPreview `组件

**Comment by datawz** [comment]
谢谢，我就是用md preview在导航时不能滚动，才想着用editer时。能不能直接关闭这个编辑功能。。，但是找了一圈没找到preview的导航条为啥不能滚动的原因，没办法，自己手写了点击事件触发了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月22日(周日) 晚上9:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imzbf/md-editor-v3] MdPreview时导航目录不能跳转 (Issue #377)




 
MdPreview自带了功能，注意你的使用方式，核心是editorId和scrollElement
 
关于关掉编辑框，这个之前讨论过了，不会支持，因为上面还有工具栏，会出现很多难以预料的事情，如果也不想要工具栏，这个时候你只要使用MdPreview 组件
