### ISSUE TITLE
代码预览区域超过宽度自动换行

### ISSUE THREAD

**Issue by kuige** [imzbf/md-editor-v3#378]
### 一个很棒的想法

现在代码预览的时候太长会出现横向滚动条
<img width="560" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/8212800/a2623bc9-6760-466e-b948-390b897f8660">
有没有配置选项可以支持代码自动换行呢？

**Comment by imzbf** [comment]
高亮后的代码是分了很多标签和换行符来展示的，这个做不到在样式上换行

**Comment by imzbf** [comment]
> ```
> .code-block {
>   white-space: pre-wrap;
> }
> ```
> 
> 用这个可以换行，但是行号对不上，不用行号是没问题的

是的，因为行号就是假设一行就是一行，没有考虑换行，如果需要换行的话，那每一个代码块就需要添加一个代码块宽度变化的监听事件，觉得不是特别有必要。目前建议这边不使用行号使用代替一下

后面我再试试能不能调整html结构来实现，但也不确定是否可行
