### ISSUE TITLE
浏览器客户端警告：Module "fs" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by Bisstocuz** [imzbf/md-editor-v3#379]
## 问题说明
当使用 Vite 4 进行 `pnpm dev` 预览时，浏览器会弹出标题的警告，这一警告源自 `sanitize-html` 的依赖库。

## 建议
目前看来上游仓库似乎已经缺乏这方面的支持与维护了，是否考虑增加其它 XSS 防范库的支持？ 

## 参考
相关：
- https://github.com/apostrophecms/sanitize-html/issues/560
- https://cn.vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility

### Procedure version

任意

**Comment by imzbf** [comment]
内部没有依赖这类库，在`md-editor-v3^4.0.0`以后，内部编译markdown文本的核心库已经提供了基础了这类功能了,比如输入`<script>console.log(2)</script>`并不会执行日志输出

**Comment by Bisstocuz** [comment]
> 内部编译markdown文本的核心库已经提供了基础了这类功能了,比如输入`<script>console.log(2)</script>`并不会执行日志输出。
> 
> 内部没有依赖这类库，在`md-editor-v3^4.0.0`以后，如果不是特别的情况，默认的就可以了

您的意思是说哪怕不给 `:sanitize` 实例，编辑器也有足够用的默认安全机制？

**Comment by imzbf** [comment]
> > 内部编译markdown文本的核心库已经提供了基础了这类功能了,比如输入`<script>console.log(2)</script>`并不会执行日志输出。
> > 内部没有依赖这类库，在`md-editor-v3^4.0.0`以后，如果不是特别的情况，默认的就可以了
> 
> 您的意思是说哪怕不给 `:sanitize` 实例，编辑器也有足够用的默认安全机制？

是的，这个属性其实是2.0版本使用的，但是考虑到部分小伙伴会有特殊的要求，就保留了这个属性
