### ISSUE TITLE
如何修改 markdown-it 的 highlight 配置？

### ISSUE THREAD

**Issue by Nomango** [imzbf/md-editor-v3#383]
### 描述这个Bug

我有一个自定义的 code block 类型，需要特殊的渲染逻辑，但是通过设置 `markdownItConfig` 的 `highlight` 配置没有生效，打印 log 也没有反应，猜测是被框架配置覆盖了，所以我该怎么实现这种功能呢？

### 版本号

4.8.2

**Comment by imzbf** [comment]
在测试版更新了这个内容

快速尝试

```shell
yarn add md-editor-v3@beta
```
