### ISSUE TITLE
cdn地址优化为可配置，或者优化为外部依赖

### ISSUE THREAD

**Issue by AllenTyf** [imzbf/md-editor-v3#385]
### Describe the issue

问题：
1. 编辑器内有部分依赖使用cdn加载，对于网络和一些内网用户存在一定问题

建议
1. 考虑增加配置，将cdn地址优化为外部可配置？
2. 考虑修改内核，将高级功能改为插件化启用？
3. 依赖外部化？

### Procedure version

v16.15.0

**Comment by imzbf** [comment]
文档有示例

1. 替换链接：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%93%A1%20%E5%86%85%E7%BD%91%E9%93%BE%E6%8E%A5
2. 替换依赖：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

**Comment by guangmingcunliutao** [comment]
> 文档有示例
> 
> 1. 替换链接：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%93%A1%20%E5%86%85%E7%BD%91%E9%93%BE%E6%8E%A5
> 2. 替换依赖：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

大佬厉害
