### ISSUE TITLE
如何获取文本框中光标的位置？

### ISSUE THREAD

**Issue by YemaoLuo** [imzbf/md-editor-v3#387]
### 一个很棒的想法

添加一个api用于获取光标位置。

**Comment by imzbf** [comment]
获取它的作用是什么？

**Comment by imzbf** [comment]
如果你想向光标位置插入内容，目前已经提供完善的方式

**Comment by YemaoLuo** [comment]
更新文本框内容的时候会重置光标到0的位置，所以需要重新修改光标位置？

**Comment by imzbf** [comment]
> 更新文本框内容的时候会重置光标到0的位置，所以需要重新修改光标位置？

不知道你如何操作会导致组件重置光标，方便的话描述下详情我看看会不会是issue

重置光标的api：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8E%AF%20focus

**Comment by YemaoLuo** [comment]
好的谢谢，<MdEditor v-model="text" > let text = ref('hello')。这样当我从服务器拿到最新的内容会执行操作：text.value = newValue;这样MdEditor中的光标会重置到0的位置。

**Comment by imzbf** [comment]
> 好的谢谢， let text = ref('hello')。这样当我从服务器拿到最新的内容会执行操作：text.value = newValue;这样MdEditor中的光标会重置到0的位置。

其实想要的是定位到结尾吧，这样的话就只能调用`focus`方法了，编辑器默认不会去调整位置，因为每个用户的想要的也不同

**Comment by YemaoLuo** [comment]
因为我在做协同编辑的工作，所以会有需要获取光标位置的需求，不过其实也可以通过dom对象拿到知识繁琐了点，可能添加一个api会更加合适，毕竟有focus方法用来设置光标位置，可能再来个获取光标位置的api挺合理。谢谢！

**Comment by imzbf** [comment]
> 因为我在做协同编辑的工作，所以会有需要获取光标位置的需求，不过其实也可以通过dom对象拿到知识繁琐了点，可能添加一个api会更加合适，毕竟有focus方法用来设置光标位置，可能再来个获取光标位置的api挺合理。谢谢！

了解
