### ISSUE TITLE
MdPreview的渲染时机是什么？

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#389]
### Describe the issue

想用这个组件替换下之前用的一个已经不怎么维护的markdown编辑器。

我目前的需求是当MdPreview渲染完以后，通过document.querySelectorAll去拿到内容区的所有h1,h2,h3...标签组装一个树形目录：

```js
...
  blog.nickname = data.nickname
  blog.created = data.created
  loading.value = false
  await nextTick()
  catalogueRef.value?.render()
```

在await nextTick()执行完以后，MdPreview没有渲染出来:
<img width="802" alt="Screenshot 2023-11-19 at 7 34 48 PM" src="https://github.com/imzbf/md-editor-v3/assets/80095372/d50a54cc-9f1b-4ebf-94ea-ae5297bcbb07">

导致我拿不到h1-h6的标签信息。

能否帮忙看下这个问题，感谢

### Procedure version

4.8.3

**Comment by imzbf** [comment]
目前来讲，`onHtmlChanged`事件中可以获取最新的

**Comment by mingchiuli** [comment]
> 目前来讲，`onHtmlChanged`事件中可以获取最新的
<img width="802" alt="Screenshot 2023-11-19 at 7 34 48 PM" src="https://github.com/imzbf/md-editor-v3/assets/80095372/5db3c3cf-381d-4dd3-9ee7-00fd5939542f">
佬，我刚才把目录render的代码写到这个回调里，这次是在第3次执行render的时候拿到了。但是我试了下，大约60%的情况还是拿不到，40%是能拿到但是是经历了多次执行

**Comment by mingchiuli** [comment]
> 目前来讲，`onHtmlChanged`事件中可以获取最新的
<img width="802" alt="Screenshot 2023-11-19 at 9 04 06 PM" src="https://github.com/imzbf/md-editor-v3/assets/80095372/53b8c6f8-a9fc-4eda-b387-e276776886a2">
<img width="802" alt="Screenshot 2023-11-19 at 9 04 11 PM" src="https://github.com/imzbf/md-editor-v3/assets/80095372/e089e6c4-ebf0-434c-aae7-981049d7c3af">

佬，写这个回调里是有点变化，但是变成概率事件了。有时候还是始终拿不到

**Comment by imzbf** [comment]
有两个点，应该在nextTick中执行查询，另外，考虑给`onHtmlChanged`设置防抖函数，因为有些的库是通过插入js链接来访问全局变量，这个过程中会有多次的编译

**Comment by mingchiuli** [comment]
> 有两个点，应该在nextTick中执行查询，另外，考虑给`onHtmlChanged`设置防抖函数，因为有些的库是通过插入js链接来访问全局变量，这个过程中会有多次的编译

试了下好像还有问题，我先手动设置500毫秒延迟执行解决吧

**Comment by imzbf** [comment]
> > 有两个点，应该在nextTick中执行查询，另外，考虑给`onHtmlChanged`设置防抖函数，因为有些的库是通过插入js链接来访问全局变量，这个过程中会有多次的编译
> 
> 试了下好像还有问题，我先手动设置500毫秒延迟执行解决吧

上面这种方式我昨晚尝试过可以获取到，你具体的代码发出来看看

**Comment by mingchiuli** [comment]
> > > 有两个点，应该在nextTick中执行查询，另外，考虑给`onHtmlChanged`设置防抖函数，因为有些的库是通过插入js链接来访问全局变量，这个过程中会有多次的编译
> > 
> > 
> > 试了下好像还有问题，我先手动设置500毫秒延迟执行解决吧
> 
> 上面这种方式我昨晚尝试过可以获取到，你具体的代码发出来看看

刚才我又试了下，`onHtmlChanged`的入参确实可以获取到这个html字符串，从这里出发应该可以实现我的需求。我之前是用CSS选择器找的h1-h6标签

**Comment by mingchiuli** [comment]
> > > 有两个点，应该在nextTick中执行查询，另外，考虑给`onHtmlChanged`设置防抖函数，因为有些的库是通过插入js链接来访问全局变量，这个过程中会有多次的编译
> > 
> > 
> > 试了下好像还有问题，我先手动设置500毫秒延迟执行解决吧
> 
> 上面这种方式我昨晚尝试过可以获取到，你具体的代码发出来看看

但是我又发现一个问题，就是通过`onHtmlChanged`确实可以拿到这个字符串，然后渲染出一个div，通过css选择器可以拿到这个树形结构。但是我之前这个树形结构是支持点击树节点做锚点跳转的，这么一来就拿不到对应的高度没法跳转了

**Comment by mingchiuli** [comment]
我的代码结构大致如下：

```vue 

<script lang="ts" setup>
let data: BlogExhibit
  if (token) {
    data = await GET<BlogExhibit>(`/public/blog/secret/${blogId}?readToken=${token}`)
  } else {
    data = await GET<BlogExhibit>(`/public/blog/info/${blogId}`)
  }
  blog.title = data.title
  document.title = data.title
  blog.avatar = data.avatar
  blog.readCount = data.readCount
  blog.nickname = data.nickname
  blog.created = data.created
  loading.value = false
  blog.content = '>' + data.description + '\n\n' + data.content
  await nextTick()
  catalogueRef.value?.render()
</script>

<template>
    <catalogue-item ref="catalogueRef" />
    <MdPreview editorId="preview-only" v-model="blog.content" />
</template>
```

这样的代码就是存在一开始说的，await nextTick()之后MdPreview还没渲染出来，执行  catalogueRef.value?.render()的时候：

```js
const render = async () => {
  const aLabels = document.querySelectorAll<HTMLElement>('#preview-only-preview h1, #preview-only-preview h2, #preview-only-preview h3, #preview-only-preview h4, #preview-only-preview h5, #preview-only-preview h6')
  const arrs = geneCatalogueArr(aLabels)
  if (arrs.length > 0) {
    data.value = arrs
    await nextTick()
    const anchor = document.getElementById(decodeURI(location.hash.substring(1)))
    window.scrollTo({ top: anchor?.getBoundingClientRect().top, behavior: 'instant' })
    allNodes = treeRef.value!.store._getAllNodes()
  } else {
    loadingCatalogue.value = false
  }
}
```

没办法用CSS 选择器去拿到标签和对应的高度

**Comment by imzbf** [comment]
你这边是不想使用内置的目录导航，想要自己开发一个目录？如果是这样，你不需要去管什么渲染时机了，`onGetCatalog`这个事件总是给你给所有的标题相关的属性

**Comment by mingchiuli** [comment]
> 你这边是不想使用内置的目录导航，想要自己开发一个目录？如果是这样，你不需要去管什么渲染时机了，`onGetCatalog`这个事件总是给你给所有的标题相关的属性

确实是在做目录的定制化。因为我看了下本项目的目录，不太符合我的要求。看了下`onGetCatalog `似乎只能拿到text和level这两个属性，我还要拿到每个标签渲染以后距离浏览器顶端的高度，做点击叶子节点锚点跳转。看来是非得等MdPreview加载出来，catalogueRef.value?.render()才能执行了

**Comment by imzbf** [comment]
> > 你这边是不想使用内置的目录导航，想要自己开发一个目录？如果是这样，你不需要去管什么渲染时机了，`onGetCatalog`这个事件总是给你给所有的标题相关的属性
> 
> 确实是在做目录的定制化。因为我看了下本项目的目录，不太符合我的要求。看了下`onGetCatalog `似乎只能拿到text和level这两个属性，我还要拿到每个标签渲染以后距离浏览器顶端的高度，做点击叶子节点锚点跳转。看来是非得等MdPreview加载出来，catalogueRef.value?.render()才能执行了

每个标题节点都会有一个固定的`id`，你也可以自定义，`id`使用`text`和`level`生成的，所以可以通过`id`去获取元素

**Comment by mingchiuli** [comment]
> > > 你这边是不想使用内置的目录导航，想要自己开发一个目录？如果是这样，你不需要去管什么渲染时机了，`onGetCatalog`这个事件总是给你给所有的标题相关的属性
> > 
> > 
> > 确实是在做目录的定制化。因为我看了下本项目的目录，不太符合我的要求。看了下`onGetCatalog `似乎只能拿到text和level这两个属性，我还要拿到每个标签渲染以后距离浏览器顶端的高度，做点击叶子节点锚点跳转。看来是非得等MdPreview加载出来，catalogueRef.value?.render()才能执行了
> 
> 每个标题节点都会有一个固定的`id`，你也可以自定义，`id`使用`text`和`level`生成的，所以可以通过`id`去获取元素

这样感觉有点不自然呀...我还是宁愿延迟100毫秒加载。佬能大致介绍下为什么await nextTick()无效吗？我前端新手

**Comment by imzbf** [comment]
> 佬能大致介绍下为什么await nextTick()无效吗？我前端新手

因为`onBeforeMount`是在节点挂载前触发的，和`onBeforeUnmount`类似，这是在节点移除前触发

**Comment by mingchiuli** [comment]
> > 佬能大致介绍下为什么await nextTick()无效吗？我前端新手
> 
> 因为`onBeforeMount`是在节点挂载前触发的，和`onBeforeUnmount`类似，这是在节点移除前触发

应该和这个没关系，我把await nextTick()写到onMounted()的回调里也是一样的效果

**Comment by mingchiuli** [comment]
> > 佬能大致介绍下为什么await nextTick()无效吗？我前端新手
> 
> 因为`onBeforeMount`是在节点挂载前触发的，和`onBeforeUnmount`类似，这是在节点移除前触发

我看了下实际上组件是挂载到dom上的，只是挂载了一个空的article标签

**Comment by imzbf** [comment]
> > > 佬能大致介绍下为什么await nextTick()无效吗？我前端新手
> > 
> > 
> > 因为`onBeforeMount`是在节点挂载前触发的，和`onBeforeUnmount`类似，这是在节点移除前触发
> 
> 我看了下实际上组件是挂载到dom上的，只是挂载了一个空的article标签

这是因为这个组件有延迟编译文章内容、多次编译等情况，vue的常规生命周期是不适用的

**Comment by mingchiuli** [comment]
> > > > 佬能大致介绍下为什么await nextTick()无效吗？我前端新手
> > > 
> > > 
> > > 因为`onBeforeMount`是在节点挂载前触发的，和`onBeforeUnmount`类似，这是在节点移除前触发
> > 
> > 
> > 我看了下实际上组件是挂载到dom上的，只是挂载了一个空的article标签
> 
> 这是因为这个组件有延迟编译文章内容、多次编译等情况，vue的常规生命周期是不适用的

好的，谢谢佬，我暂时就设置一个定时器延时加载吧
