### ISSUE TITLE
图片预览不显示

### ISSUE THREAD

**Issue by f754699** [imzbf/md-editor-v3#39]
https://qcfdz2.file.qingfuwucdn.com/file/d8b7070ec51c5f3c_1642426406641.jpg

就是图片上这样

**Comment by imzbf** [comment]
> https://qcfdz2.file.qingfuwucdn.com/file/d8b7070ec51c5f3c_1642426406641.jpg
> 
> 就是图片上这样

尝试过了你的地址，你可能需要调整一下你的cdn设置，现在的返回类型是下载的模式。将地址放到浏览器地址栏中就能发现该问题，正常的表现应该是直接显示在浏览器中。
