### ISSUE TITLE
上传图片

### ISSUE THREAD

**Issue by Oreo-Cookies** [imzbf/md-editor-v3#390]
### Describe the issue

你好，请问onUploadImg可以不立刻上传图片吗？业务需要保存的时候统一上传图片

### Procedure version

4.8.3

**Comment by imzbf** [comment]
这个组件没有限制你什么时候上传，只是如果是最后统一上传，你在`onUploadImg`里调用`callback`时得返回你定义好映射关系的占位符。

最后上传完成后去替换图片临时的占位符。
