### ISSUE TITLE
报错不能使用呢

### ISSUE THREAD

**Issue by xibaoning** [imzbf/md-editor-v3#393]
### Describe the issue

index.vue:3  Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/md-editor-v3.js?v=4e153359' does not provide an export named 'default' (at index.vue:3:8)

### Procedure version

vue3

**Comment by xibaoning** [comment]
可以了,请忽略

**Comment by spianmo** [comment]
> ### Describe the issue
> index.vue:3 Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/md-editor-v3.js?v=4e153359' does not provide an export named 'default' (at index.vue:3:8)
> 
> ### Procedure version
> vue3
> 
> ### Reproduction link
> _No response_

怎么解决的，我也遇到了
