### ISSUE TITLE
如果我的标题有重复的或有多个文档在同一页面切换，目录导航栏的内容有时候会卡死不更新，瞄点跳转就不灵了。

### ISSUE THREAD

**Issue by Dalyn-Liu** [imzbf/md-editor-v3#395]
### Describe the issue

如果我有多个文档再在同一页面，右侧的导航栏更新不及时会卡死。导航栏的内容还是之前的内容，没有变。有没有什么方法支持给导航栏组件传入列表值的

**Comment by Dalyn-Liu** [comment]
我的左侧是多个文档的，如果我切换了另一个文档内容，右侧的导航栏直接点了就没反应了。

![image](https://github.com/imzbf/md-editor-v3/assets/133751618/55cec4c5-2fbc-489a-9e38-6f3f5ec31bb8)

**Comment by imzbf** [comment]
最好设置一下`mdHeadingId`，标题的id区别了，这个就不会没反应了

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8E%B1%20mdHeadingId

**Comment by Dalyn-Liu** [comment]
> 最好设置一下`mdHeadingId`，标题的id区别了，这个就不会没反应了

好的谢谢，我是预览组件的,编辑组件的还没试过，同样的操作吗？我先去试试看。

**Comment by imzbf** [comment]
> > 最好设置一下`mdHeadingId`，标题的id区别了，这个就不会没反应了
> 
> 好的谢谢，我是预览组件的,编辑组件的还没试过，同样的操作吗？我先去试试看。

是的，预览组件有的，编辑组件都有
