### ISSUE TITLE
怎么解决多个富文本编辑器在同个.vue中，上传图片重复问题

### ISSUE THREAD

**Issue by hwy2** [imzbf/md-editor-v3#40]
我在同一个页面的dialog里写了2个MdEditor，分别叫：MdEditor，MdEditor1，同时设置了editorId分别为taskProgress，task，上传图片的方法也修改成不同的名字uploadImg，taskProgressUploadImg
但是在上传图片的时候，我在当前编辑器上传，在另一个编辑器也会出现图片链接，而且还是两条
![image](https://user-images.githubusercontent.com/40650839/150498028-66f49ec3-0cd4-47bd-9f64-e48b7e01290a.png)

**Comment by imzbf** [comment]
请问是`ctrl+v`上传的吗

**Comment by hwy2** [comment]
> 是`ctrl+v`上传的吗

不是，直接点击选择本地文件的

**Comment by imzbf** [comment]
已在v1.10.1中修复

**Comment by hwy2** [comment]
我更新了最新版的编辑器，但是bug还是存在
![image](https://user-images.githubusercontent.com/40650839/153333640-63d972af-2a28-4ede-8073-3bf191326b23.png)

**Comment by imzbf** [comment]
> 我更新了最新版的编辑器，但是bug还是存在 ![image](https://user-images.githubusercontent.com/40650839/153333640-63d972af-2a28-4ede-8073-3bf191326b23.png)

操作仅是点击上传图片，选择图片后确认吗？方便看一下这边的代码吗？这边再看看

**Comment by hwy2** [comment]
操作是点击上传图片，选择图片后确认
![image](https://user-images.githubusercontent.com/40650839/153347256-815b8197-296c-4514-9b3b-344ed8762ad8.png)
![image](https://user-images.githubusercontent.com/40650839/153347306-6f96557e-f94b-4c67-9857-e81b64fef2d2.png)
![image](https://user-images.githubusercontent.com/40650839/153347363-d030ce63-9806-4330-bd21-2895c2b95ceb.png)

**Comment by hwy2** [comment]
我现在是吧这个封装成一个组件，当我在同一个页面二次调用这个组件时，会出现我在上一个输入框点击上传图片，在下一个输入框出现两个图片的情况，我又尝试把两个编辑器放在同一个页面，结果就出现我一开始说的那样，这个bug还是存在，可否尝试用ref试试?

**Comment by rentoumu** [comment]
遭遇同样的问题，版本`1.10.1`。
只要进行两次及以上的vue-router跳转，ctrl+v复制的图片就会重复上传若干次。
刷新当前页面，重复上传现象消失。或者单次跳转的vue-router不会出现此问题。
![image](https://user-images.githubusercontent.com/84778968/153562877-05eb28f0-bfd1-45a6-b180-80e7520a4dc4.png)

**Comment by imzbf** [comment]
> 操作是点击上传图片，选择图片后确认 ![image](https://user-images.githubusercontent.com/40650839/153347256-815b8197-296c-4514-9b3b-344ed8762ad8.png) ![image](https://user-images.githubusercontent.com/40650839/153347306-6f96557e-f94b-4c67-9857-e81b64fef2d2.png) ![image](https://user-images.githubusercontent.com/40650839/153347363-d030ce63-9806-4330-bd21-2895c2b95ceb.png)

之前没注意到，你的代码两个中，两个编辑器绑定的是同一个值，这样上传一次，两个编辑器中都出现是正常的。

**Comment by imzbf** [comment]
这边找了小伙伴始终无法还原这个问题，希望遇到该问题的伙伴提供一下以下信息，帮助还原问题：

- 项目环境；
- 对应页面的项目源码。

**Comment by imzbf** [comment]
或者能够克隆项目中的`dev-router`分支提交包含能够出现问题PR。感谢支持！

**Comment by rentoumu** [comment]
@imzbf 
刚才测试了一下，可能是`vue router`的`<keep-alive>`问题。
### 测试环境
`md-editor-v3@1.10.1`
`typescript@4.5.4`
`vue@3.2.25`
`vite@2.8.0`
`vue-router@4`
`QQ截图 `

---

### 测试代码（[压缩包](https://github.com/rentoumu/test/blob/main/test.zip)）

#### views/Index.vue
```vue
<template>
    <h1>Index Router</h1>
    <button @click="$router.push({name:'FirstRouter'})">跳转至second router</button>
    <router-view v-slot="{ Component }">
        <keep-alive>
            <component :is="Component" v-if="$route.meta.keepAlive"/>
        </keep-alive>
        <component :is="Component" v-if="!$route.meta.keepAlive"/>
    </router-view>
</template>
```

#### views/First.vue
```vue
<template>
    <h1>First Router View</h1>
    <button @click="$router.push({name:'SecondRouter'})">跳转至second router</button>
    <router-view v-slot="{ Component }">
        <keep-alive >
            <component :is="Component" v-if="$route.meta.keepAlive"/>
        </keep-alive>
        <component :is="Component" v-if="!$route.meta.keepAlive"/>
    </router-view>
</template>
```
#### views/Second.vue
```vue
<template>
    <h1>Second Router View</h1>
    <md-editor v-model="ctx.content" @onUploadImg="upload_image"></md-editor>
</template>

<script setup lang="ts">
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
import {reactive} from "vue";

const ctx = reactive({
    content: ''
})

const upload_image = async (files: FileList, callback: (urls: string[]) => void) => {
    console.log("upload files:", files)
    const res = await Promise.all(
        Array.from(files).map((file) => {
            return new Promise((rev, rej) => {
                // ...上传图片
                rev("https://test.com/image.png")
            });
        })
    );
    callback(res.map((item: any) => item));
}
</script>
```

#### plugins/router.ts
```typescript
import {createRouter, createWebHashHistory} from 'vue-router'

export const router = createRouter({
  history: createWebHashHistory(),
  routes: [
    {
      path: '/',
      name: 'Index',
      component: () => import('../views/Index.vue'),
      meta: {
        keepAlive: false,
      },
      children: [
        {
          path: 'first',
          name: 'FirstRouter',
          component: () => import('../views/First.vue'),
          meta: {
            keepAlive: true,
          },
          children: [
            {
              path: 'second',
              name: 'SecondRouter',
              component: () => import('../views/Second.vue'),
              meta: {
                keepAlive: false,
              },
            }
          ]
        }
      ]
    }
  ]
})
```

#### main.ts
```typescript
import {createApp} from 'vue'
import App from './App.vue'
import {router} from "./plugins/router";

const app = createApp(App)
app.use(router)
app.mount('#app')
```

---

### 重复提交
![image](https://user-images.githubusercontent.com/84778968/154405552-f55b0a79-0d48-4606-9a70-b3adb40f001a.png)

**Comment by imzbf** [comment]
@rentoumu 这边发现问题是没有正确使用`router-view`导致的

在`App.vue`中

```
<template>
  <router-view v-slot="{ Component }">
    <keep-alive>
      <component :is="Component" v-if="$route.meta.keepAlive" />
    </keep-alive>
    <component :is="Component" v-if="!$route.meta.keepAlive" />
  </router-view>
</template>
```

这样会导致子路由所有的组件的`onMounted`执行3次，所以在编辑器组件中，同时向eventbus中注册了三个上传事件监听。

调整为下面的写法即可：

```
<template>
  <router-view v-slot="{ Component }">
    <keep-alive v-if="$route.meta.keepAlive">
      <component :is="Component"  />
    </keep-alive>
    <component :is="Component" v-if="!$route.meta.keepAlive" />
  </router-view>
</template>
```

**Comment by imzbf** [comment]
@hwy2 也可以检查一下有没有类似的问题。
