### ISSUE TITLE
a标签打开新标签页

### ISSUE THREAD

**Issue by daixu-cn** [imzbf/md-editor-v3#401]
### 一个很棒的想法

作者是否考虑给添加链接的时候加一个标签页的打开方式？现在默认在本窗口某些情况下有点不方便（如果考虑的话建议MdEditor和MdPreview这两个组建中都加上相应的配置，不然没法兼容之前写出来的内容）；

或者是否提供一个MdPreview渲染完成之后的回调函数，这样的话其他人手动去修改DOM做一些其他操作也对开发者更友好；

个人觉得还是第二点建议比较人性化，这样需要啥让其他开发者自己加就好了。

**Comment by imzbf** [comment]
使用markdown-it编译的markdown文本，这类功能它的生态是有现成的，参考 #274
