### ISSUE TITLE
自定义Toolbar，如何获取到当前选中的文本内容

### ISSUE THREAD

**Issue by thellangel** [imzbf/md-editor-v3#404]
### Describe the issue

请问，自定义Toolbar，如何获取到当前选中的文本内容。

### Procedure version

v4.9.0

**Comment by imzbf** [comment]
参考：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%A3%20NormalToolbar

**Comment by thellangel** [comment]
在调用props.insert((selectedText) => {}时，确实可以拿到，但是有别的方法可以取得当前选中的文本么？因为当前操作并不对选中的文本做操作，而是想为调用其他方法作为输入。

**Comment by imzbf** [comment]
> 在调用props.insert((selectedText) => {}时，确实可以拿到，但是有别的方法可以取得当前选中的文本么？因为当前操作并不对选中的文本做操作，而是想为调用其他方法作为输入。

在`insert`里调用其他方法就可以作为入参了
