### ISSUE TITLE
版本升级后打包体积骤增

### ISSUE THREAD

**Issue by szluyu99** [imzbf/md-editor-v3#405]
### Describe the issue

从 2.11.3 升级到 4.9.0 以后，整个项目的打包体积从 2.7MB 变成了 5.4 MB？能问下为什么会增加这么多吗？粗略看了下统计图，好像是把代码高亮语言都打进去了？

### Procedure version

4.9.0

**Comment by imzbf** [comment]
3.0版本后内置了`codemirror`，多出来的是它的内容

**Comment by tianci-06** [comment]
> 3.0版本后内置了`codemirror`，多出来的是它的内容

就是请问有没有办法可以把包分出来呢，比如我不想默认进行全局加载，不想首屏就加载那么大的js包，而是只在我使用到时才加载相应资源。

**Comment by imzbf** [comment]
> > 3.0版本后内置了`codemirror`，多出来的是它的内容
> 
> 那请问有没有办法可以把包分出来呢，比如我不想默认进行全局加载，不想首屏就加载那么大的js包，而是只在我使用到时才加载相应资源。

你的编辑页面做成懒加载就可以了，和组件没有关系

**Comment by tianci-06** [comment]
> > > 3.0版本后内置了`codemirror`，多出来的是它的内容
> > 
> > 
> > 那请问有没有办法可以把包分出来呢，比如我不想默认进行全局加载，不想首屏就加载那么大的js包，而是只在我使用到时才加载相应资源。
> 
> 你的编辑页面做成懒加载就可以了，和组件没有关系

我的路由是懒加载的，但还是在首屏自动加载了编辑器的一些资源..
![image](https://github.com/imzbf/md-editor-v3/assets/153273926/f91682ea-0b99-48a2-9d9e-48c886177b4b)

**Comment by imzbf** [comment]
> > > > 3.0版本后内置了`codemirror`，多出来的是它的内容
> > > 
> > > 
> > > 那请问有没有办法可以把包分出来呢，比如我不想默认进行全局加载，不想首屏就加载那么大的js包，而是只在我使用到时才加载相应资源。
> > 
> > 
> > 你的编辑页面做成懒加载就可以了，和组件没有关系
> 
> 我的路由就是懒加载的,页面也是的，但还是在首屏自动加载了编辑器的一些资源.. ![image](https://private-user-images.githubusercontent.com/153273926/292129716-f91682ea-0b99-48a2-9d9e-48c886177b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDg2NDAsIm5iZiI6MTcwMzE0ODM0MCwicGF0aCI6Ii8xNTMyNzM5MjYvMjkyMTI5NzE2LWY5MTY4MmVhLTBiOTktNDhhMi05ZDllLTQ4Yzg4NjE3N2I0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwODQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzMwMDQ0ZTBjN2YyNDQwYzExNzU3ZTk2Nzc4YTc4YWNjMTI4YjUxYzRjMWJhMjc4ZDkzNWJkYzYxOWEyYTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S-GZeJNUZnSBoceE7T-h8nD5psjslpKa43Y24np3WIA)

这看起来并没有懒加载，检查你的代码，和你是否在其他页面也使用了编辑器
