### ISSUE TITLE
Component scoped config

### ISSUE THREAD

**Issue by Nomango** [imzbf/md-editor-v3#407]
### 一个很棒的想法

希望可以支持组件的独立配置，而不是全局配置

比如避免这样修改全局配置：

```ts
import { config } from 'md-editor-v3';

config({}) // 修改对所有组件生效
```

而是可以控制单个组件的配置

```vue
<MdEditor :setup="(config) => config({...})" />
```

**Comment by imzbf** [comment]
目前的全局配置内容很大部分是不能单独配置的，当前配置内容里，是有什么是想在不同编辑器中独立的么

**Comment by Nomango** [comment]
是的，想在不同组件中使用不同的markdown-it配置

**Comment by Nomango** [comment]
还有mermaid配置

**Comment by imzbf** [comment]
这样的意义是啥呢，同一个站点两份文章会因为配置不同而展示成不同的样子，阅读的人看起来不会有歧义么

**Comment by Nomango** [comment]
因为不只是用它来展示文章，还有弹窗、聊天框等其他仅展示用的 markdown 场景。Anyway，感觉这个功能是很常见的，只是看是否可以实现以及是否计划实现~

**Comment by imzbf** [comment]
目前看起来，只有`markdown-it`可以支持不同的配置，其他的都是使用同一个实例，例如`mermaid`，多次配置实际上也只是后者覆盖前者，鉴于编辑器的实现方式，我会在`markdownItConfig`和`markdownItPlugins`提供第二参数，可能会回传编辑器的`editorId`用于辨识。具体等实现后更新文档

**Comment by Nomango** [comment]
又遇到了这个问题。文章会使用相对路径链接，比如 `![alt](./xx.png)`，这个路径是相对文章的，所以需要修改 `markdown-it` 配置，将 img 路径替换掉。当一个页面有多篇文章时，`config` 只有一篇能正常生效。

**Comment by imzbf** [comment]
> 又遇到了这个问题。文章会使用相对路径链接，比如 `![alt](./xx.png)`，这个路径是相对文章的，所以需要修改 `markdown-it` 配置，将 img 路径替换掉。当一个页面有多篇文章时，`config` 只有一篇能正常生效。

这个问题很好解决，处理掉你的相对路径，根据你上传的环境，配置路径的前缀，之前有伙伴遇到过这种问题

**Comment by imzbf** [comment]
我在beta中更新`markdownItConfig`和`markdownItPlugins`，文档：https://github.com/imzbf/md-editor-v3/blob/develop/README-CN.md#markdownitconfig

```shell
yarn add md-editor-v3@beta
```
