### ISSUE TITLE
Render mermaid as a png

### ISSUE THREAD

**Issue by Nomango** [imzbf/md-editor-v3#409]
### 一个很棒的想法

mermaid会渲染成 svg，在我的比较狭窄的组件里会看不清svg里面的字，如果可以渲染成 png，就能实现点击放大了。类似飞书文档中 mermaid 的渲染效果。

一个可能的实现：使用 `resvg-js` 将 mermaid html （也就是svg）渲染成 base64 png，插入到 markdown 中

**Comment by imzbf** [comment]
这个应该不会内置。

其实还有更简单的方式，手动监听`.md-editor-mermaid`的点击事件，然后复制节点到你的弹窗中，来实现放大查看。

**Comment by Nomango** [comment]
嗯，这个需求确实不够“通用”，不太适合加到内置功能里。

不过是否可能加一些 hook，比如控制 mermaid （或其他组件）生成的内容如何插入到 editor 中？这样就可以在业务代码中实现 svg to png 的功能，同时使用 editor 的 medium zoom。

**Comment by imzbf** [comment]
嗯，这个是可以提供

**Comment by imzbf** [comment]
我在beta中更新了，文档在readme.md中搜索`sanitizeMermaid`

```shell
yarn add md-editor-v3@beta
```
