### ISSUE TITLE
首先如何缩放图片，还有如何拖动上传图片并且处理一些特定场景

### ISSUE THREAD

**Issue by xxlbb123** [imzbf/md-editor-v3#411]
### Describe the issue

首先如何缩放图片，还有如何拖动上传图片并且处理一些特定场景

### Procedure version

图片上传

**Comment by xxlbb123** [comment]
根据官方提供了拖动的方法，但是对于这种情况，比如我我需要在两端文本中间上传一个图片，请问我该怎么做？这部分官方有无提供，其次，官方有没有提供对于上传图片的一个可以调节的缩放，否则图片太大影响美感

**Comment by imzbf** [comment]
1. 文本之间拖拽插入图片步骤：光标提前定位在需要插入的位置，然后随意拖放即可
2. 没有提供拖放的可视化操作，但是扩展库提供了插入类似`<img width="100%" />`类似的组件，参考：https://github.com/imzbf/md-editor-extension/tree/develop/packages/v3/components/OriginalImg

**Comment by xxlbb123** [comment]
@imzbf 1.针对第一个问题，我看官方中针对拖放是有一个事件，然后我使用的这个onDrop事件，使用了自己的方法，至于你说的把光标放在两端文版直接可以插入我不知道是如何实现的，能否详细说明一下
[/[](url)](url)
![Snipaste_2023-12-30_14-47-24](https://github.com/imzbf/md-editor-v3/assets/103021747/aa5fb959-ef9f-4b7d-94f5-12f533efc5e5)

**Comment by imzbf** [comment]
> @imzbf 1.针对第一个问题，我看官方中针对拖放是有一个事件，然后我使用的这个onDrop事件，使用了自己的方法，至于你说的把光标放在两端文版直接可以插入我不知道是如何实现的，能否详细说明一下 [/](url) ![Snipaste_2023-12-30_14-47-24](https://private-user-images.githubusercontent.com/103021747/293447213-aa5fb959-ef9f-4b7d-94f5-12f533efc5e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTIzMjQsIm5iZiI6MTcwNDExMjAyNCwicGF0aCI6Ii8xMDMwMjE3NDcvMjkzNDQ3MjEzLWFhNWZiOTU5LWVmOWYtNGI3ZC05NGY1LTEyZjUzM2VmYzVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxMjI3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWI4OTVlMmU5ZGQ1YWY2YjA0YjIyODhjMTU1Yjc2NGVhYzMxNjgwZDE0NTk3NGE5ZDAzZGYyNjUyMTRjYTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.clHiUQ_86eQ45DDI29CNjHgxdCSbMZr8o705-NeBAAg)

是在输入的时候，手动将光标放在你想要插入的位置

**Comment by xxlbb123** [comment]
@imzbf 我知道，然后呢？此时我的光标在指定位置，然后我拖动图片的话，图片怎么能在指定光标出现？

**Comment by imzbf** [comment]
监听`onDrop`事件，上传获取到拖拽的文件，再调用编辑器暴露的`insert`方法插入到内容中，自动就会在光标的位置出现

**Comment by xxlbb123** [comment]
@imzbf 感谢，已经解决
