### ISSUE TITLE
Copy code tooltip in code blocks is in chinese when using en-US locale

### ISSUE THREAD

**Issue by Payn** [imzbf/md-editor-v3#413]
### Describe the issue

When using markdown for code blocks, there is a copy button in the top right corner - https://imgur.com/a/PLMTL5T
Even with "language="en-US" it's not in english.

Related HTML:
`<span class="copy-button" data-tips="复制代码"><svg class="md-editor-icon" aria-hidden="true"><use xlink:href="#md-editor-icon-copy"></use></svg></span>`

### Procedure version

Editor version 4.10

**Comment by imzbf** [comment]
I cannot reproduce it, is there any special environment or operation?

<img width="1716" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/f67bb057-0595-4f66-8692-d9e96a1547a8">

**Comment by Payn** [comment]
I'm sorry i found out what was wrong. I have a tabpanel switching between `MdEditor` and `MdPreview` and i had `language="en-US"` only in the MdEditor. Adding it also to MdPreview fixed it.
