### ISSUE TITLE
是否可以添加一个开关，让展示区把用户手动输入的html代码转成普通字符串渲染

### ISSUE THREAD

**Issue by Seven-7i** [imzbf/md-editor-v3#415]
### 一个很棒的想法

比如说：在编辑区不在代码块内写：<a href="www.baidu.com">百度</a> ；  展示区原封不动的按照字符串展示。
但是使用语法的话正常显示，比如：![百度](www.baidu.com) ；解析成一个链接

**Comment by imzbf** [comment]
```js
import { config } from 'md-editor-v3';

config({
  markdownItConfig(md) {
    md.set({
      html: false,
    });
  },
});
```

这样就能满足你的要求

**Comment by Seven-7i** [comment]
这样子做的话，全局就写死了吧，不能通过按钮去动态控制这个

**Comment by imzbf** [comment]
也是可以的，你的按钮事件触发时，执行一次`config`，然后控制你的组件重新渲染即可。`markdownItConfig`的第二参数携带了编辑器的ID，你也可以单独针对某个编辑器进行控制。

组件没有办法内置这个功能，能做到这个行为的只能这样配置，而用户的配置永远是高于内部组件默认的配置的

**Comment by Seven-7i** [comment]
明白了  非常感谢您的答疑解惑！
