### ISSUE TITLE
同步滚动问题

### ISSUE THREAD

**Issue by stillwarter** [imzbf/md-editor-v3#418]
### 描述这个Bug

https://file.fishpi.cn/2024/01/mdbug-79228a64.mp4

### 版本号

"md-editor-v3": "^4.10.0"

**Comment by imzbf** [comment]
这份内容可以提供一下么

**Comment by stillwarter** [comment]
> 这份内容可以提供一下么

你是要对应的md文件吗？还是整个code？
这是和md差不多的链接：https://fishpi.cn/article/1704683636785

**Comment by imzbf** [comment]
> > 这份内容可以提供一下么
> 
> 你是要对应的md文件吗？还是整个code？ 这是和md差不多的链接：https://fishpi.cn/article/1704683636785

主要是markdown文本，用来还原问题的，这种问题有点特殊

**Comment by stillwarter** [comment]
> > > 这份内容可以提供一下么
> > 
> > 
> > 你是要对应的md文件吗？还是整个code？ 这是和md差不多的链接：https://fishpi.cn/article/1704683636785
> 
> 主要是markdown文本，用来还原问题的，这种问题有点特殊

找到问题了，当预览部分出现滚动条，而编辑部分没有滚动条，这个时候，当编辑者继续编辑直到编辑部分也出现滚动条，就会出现bug。
https://file.fishpi.cn/2024/01/mdbug2-9dbe509e.mp4
复现也简单，由于代码框样式产生的高度不一样，所以会出现一个高度差，这就是先后出现滚动条的原因。

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-extension/blob/main/packages/v3/components/ExportPDF/README.md


导出PDF有现成的扩展的哦

**Comment by stillwarter** [comment]
> https://githubfast.com/imzbf/md-editor-extension/blob/main/packages/v3/components/ExportPDF/README.md
> 
> 导出PDF有现成的扩展的哦

ok

**Comment by imzbf** [comment]
4.11.1重构了同步滚动的算法，再尝试一下看看

**Comment by stillwarter** [comment]
> 4.11.1重构了同步滚动的算法，再尝试一下看看

已更新，应该是没问题了
