### ISSUE TITLE
md-editor-v3二次编辑

### ISSUE THREAD

**Issue by stillwarter** [imzbf/md-editor-v3#419]
### Describe the issue

md-editor-v3的save函数上传的是html数据，能不能做一个直接上传md的，方便二次编辑？直接获取的数据是html，放到编辑器了也是html，不方便编辑

### Procedure version

"md-editor-v3": "^4.10.0"

**Comment by imzbf** [comment]
`onSave`既提供md也提供了编译后的html的呀
