### ISSUE TITLE
一个好玩的问题

### ISSUE THREAD

**Issue by tianci-06** [imzbf/md-editor-v3#420]
### Describe the issue

请问一下编辑器语法的提示 ！！！ 是基于哪款编辑器的语法呀，typora不能渲染这个语法

### Procedure version

4.0.10

**Comment by imzbf** [comment]
提示是`codemirror`的

**Comment by imzbf** [comment]
可以搜索`@codemirror/autocomplete`看看

**Comment by tianci-06** [comment]
> 可以搜索`@codemirror/autocomplete`看看

好的，谢谢
