### ISSUE TITLE
4.10.0版本代码块存在多余的行号

### ISSUE THREAD

**Issue by tianci-06** [imzbf/md-editor-v3#421]
### 描述这个Bug

我升级之后发现的，然后我去看文档一看，文档也是出现同样的小问题，作者大大有空可以优化一下，目前只发现vue语言才会出现此问题，多了一行而且行号超出代码块，我自己的还出现了纵向滚动条哈哈哈。
![image](https://github.com/imzbf/md-editor-v3/assets/153273926/6f0d0465-2b9c-46b0-9c66-0f76e4c3207a)

### 版本号

4.10.0

**Comment by tianci-06** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/153273926/23a60854-8a09-4424-9e23-2db964a19250)
现在发现JSON语言也是一样的bug

**Comment by imzbf** [comment]
找到问题了，`highlight.js@11.9.0`存在这个问题，这会在下个大版本中更新，目前对你影响很大的话，你可以手动调整一下你项目的版本，像下面这样

```js
config({
  editorExtensions: {
    highlight: {
      js: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js'
    }
  }
})
```

**Comment by imzbf** [comment]
`4.11.0`更正了该问题
