### ISSUE TITLE
无法扩展工具栏

### ISSUE THREAD

**Issue by promisemey** [imzbf/md-editor-v3#424]
### Describe the issue

    <template #defToolbars>
      <ToolBar />
    </template>

### Procedure version

4.10.0

**Comment by imzbf** [comment]
看文档的示例，还需要把需要展示的组件的下标放到`toolbars`

https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%AA%B6%20defToolbars

**Comment by promisemey** [comment]
原来如此，没注意看，谢谢大佬🫡🫡
