### ISSUE TITLE
自定义导航栏问题

### ISSUE THREAD

**Issue by Roaming-l** [imzbf/md-editor-v3#426]
### 描述这个Bug

我在自定义导航栏中加了这样一些导航栏，分散到了不同位置，但是我发现，顺序为连续的时候在本地npm run dev启动后导航栏部分缺失了，但是npm run build打包以后到服务器中访问是没有丢失的，当把顺序改为从1开始的1，3，5  基数后，本地启动导航栏又没问题，但是在服务器中又出现丢失问题。
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/27dd49bb-a751-4da1-a194-36d6c2f04acb)

### 版本号

4.10.0

**Comment by imzbf** [comment]
方便给个还原这个环境的基础代码仓库吗，这边无法还原问题
