### ISSUE TITLE
是否可以提供个方法重置undoredo队列

### ISSUE THREAD

**Issue by MTTTM** [imzbf/md-editor-v3#427]
### 一个很棒的想法

场景：
打开远程数据，再读取另外个远程数据，结果回退时候，回到了上一个编辑的内容，
我想打开新的远程数据时候，清空之前的undoredo队列

**Comment by imzbf** [comment]
查了下[说明](https://discuss.codemirror.net/t/editor-sethistory-clearhistory-equivalent-in-codemirror-6/6291/2)

可能不会有专门的重置历史的方法，转而使用某个重置整个编辑器状态的方法，间接达到这个目的

**Comment by imzbf** [comment]
`4.11.0`提供了[resetHistory](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%97%91%20resetHistory)来清空输入历史

**Comment by MTTTM** [comment]
谢谢，超级棒的
