### ISSUE TITLE
添加on-change后，v-model双向绑定失效

### ISSUE THREAD

**Issue by kuailemao** [imzbf/md-editor-v3#429]
### 描述这个Bug

我MdEditor添加了:on-change="mdContent"后，导致v-model双向绑定失效，无论我怎么输入内容，页面的内容没问题，但是v-model绑定的变量的值(使用ref())都不会有任何变化，如果我把:on-change="mdContent"去掉，就恢复正常

### 版本号

"md-editor-v3": "^4.7.0",

**Comment by imzbf** [comment]
目前优化为总是触发vue的事件监听。

另外vue模版的话，我们建议使用`@on-change`在注册事件。

**Comment by imzbf** [comment]
4.11.0更正了该问题
