### ISSUE TITLE
关于图片的代码

### ISSUE THREAD

**Issue by wuyu8512** [imzbf/md-editor-v3#43]
请问可以不要figure以及figcaption标签吗

**Comment by imzbf** [comment]
> 请问可以不要figure以及figcaption标签吗

这个建议使用主动css隐藏。

**Comment by wuyu8512** [comment]
请问有考虑某种模式使用户自定义生成代码吗

**Comment by imzbf** [comment]
这个目前没有考虑提供自定义的接口，因为没有办法给md相关的所有内容都提供自定义。常用的像图片会在后续开发中考虑。目前建议覆盖样式来达到你的目的。

**Comment by imzbf** [comment]
在v1.11.0版本后，使用`markedImage`来覆盖默认生成图片的方式。
