### ISSUE TITLE
代码块头部加入自定义按钮

### ISSUE THREAD

**Issue by Nick955** [imzbf/md-editor-v3#430]
### Describe the issue

请教下两个问题
1. 如何在代码块头部右侧区域添加自定义按钮，比如我想在复制代码的按钮旁边加入一个插入按钮应该怎么做
2. 如何在编辑器加载完成以后做一些事情，有钩子可以用吗，我想加载完以后操作dom

### Procedure version

browser

**Comment by Nick955** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/49111166/9df58201-75e6-456c-afc2-f12c94f61889)
这部分可以自定义吗

**Comment by imzbf** [comment]
1. 提示只能修改文字，无法自定义新内容
2. 想在编译完成后获取dom比较稳妥的方式是在`onHtmlChanged`事件中添加`nextTick`

**Comment by Nick955** [comment]
好的，谢谢，已经实现了

**Comment by 79rose** [comment]
> 好的，谢谢，已经实现了
你好 请问可以分享一下实现方式吗
