### ISSUE TITLE
长图无法滚动

### ISSUE THREAD

**Issue by nlbwqmz** [imzbf/md-editor-v3#434]
### 描述这个Bug

- 编辑器只插入一张长图，如下
`![test](https://img.zcool.cn/community/0107a458dc5a04a801219c7733f898.jpg@1280w_1l_2o_100sh.jpg)`
**此时编辑框没有滚动条，预览框有滚动条，但是预览框无法滚动**

### 版本号

- 谷歌浏览器版本 120.0.6099.225
- md-editor-v3 4.11.0

**Comment by imzbf** [comment]
4.11.1优化了该问题
