### ISSUE TITLE
仅预览模式点击图片现在放大缩小的功能

### ISSUE THREAD

**Issue by 851605063** [imzbf/md-editor-v3#436]
### 一个很棒的想法

仅预览模式点击图片现在放大缩小的功能

**Comment by imzbf** [comment]
现在是支持这个功能的

**Comment by 851605063** [comment]
@imzbf 不支持啊，点击图片放大后，鼠标滚轮或者双指操作都不会变大变小

**Comment by imzbf** [comment]
> @imzbf 不支持啊，点击图片放大后，鼠标滚轮或者双指操作都不会变大变小

了解了，这个短期内在组件中不会去更新它了，有一个自定义的步骤

1. 禁用内部的放大图片功能，设置`noImgZoomIn`为`true`
2. 找一个你喜欢的扩展库，例如：https://github.com/fengyuanchen/viewerjs，获取文章内的图片标签添加到扩展即可

**Comment by 851605063** [comment]
@imzbf 嗯嗯，我根据另一位朋友的思路目前实现了需求，使用js获取所有的img标签，然后挨个添加点击事件。您说的获取文章内的图片标签也是这样去做吗，还是有配置支持？

**Comment by imzbf** [comment]
> @imzbf 嗯嗯，我根据另一位朋友的思路目前实现了需求，使用js获取所有的img标签，然后挨个添加点击事件。您说的获取文章内的图片标签也是这样去做吗，还是有配置支持？

嗯，是一样的，包括内部已经实现的放大功能
