### ISSUE TITLE
Model弹出层被遮挡

### ISSUE THREAD

**Issue by An-uking** [imzbf/md-editor-v3#437]
### 描述这个Bug

Model弹出层被遮挡，希望把它追加到BODY后面
![微信截图_20240126065731](https://github.com/imzbf/md-editor-v3/assets/6171187/47e6d95d-cfdb-45a1-b1f1-b2d580f628c9)

### 版本号

v4.11.0

**Comment by imzbf** [comment]
在4.12.0中优化了该问题
