### ISSUE TITLE
作者有没有考虑加入默认字体和字体选择呢

### ISSUE THREAD

**Issue by github-SoMoo** [imzbf/md-editor-v3#438]
### 一个很棒的想法

作者有没有考虑加入默认字体和字体选择呢

**Comment by imzbf** [comment]
这类功能暂时不会默认在组件内部，目前组件支持扩展工具栏组件，相应的[扩展库](https://github.com/imzbf/md-editor-extension)，觉得有意义的工具栏扩展欢迎PR
