### ISSUE TITLE
图片上传之后无法在![]显示图片的名字

### ISSUE THREAD

**Issue by lihuikun** [imzbf/md-editor-v3#440]
### Describe the issue

图片上传之后无法在![]中显示图片的名字，这样多张上传之后显示比较乱

### Procedure version

16.0

**Comment by lihuikun** [comment]
现在得到的是支持![](https://****/a.png)，希望得到![a.png](https://****/a.png),

能否自己定义callback来填充【】中的字符串

调用的代码
```
const onUploadImg = async (files, callback) => {
  const res = await Promise.all(
    files.map((file) => {
      return new Promise((rev, rej) => {
        initCOS(file, import.meta.env.VITE_BUCKET_NAME).then(res => {
          rev(res.url)
        })
      });
    })
  );
  callback(res);
}
```

**Comment by imzbf** [comment]
> 现在得到的是`![](https://****/a.png)`，希望得到`![a.png](https://****/a.png)`,
> 
> 能否自己定义callback来填充【】中的字符串
> 
> 调用的代码
> 
> ```
> const onUploadImg = async (files, callback) => {
>   const res = await Promise.all(
>     files.map((file) => {
>       return new Promise((rev, rej) => {
>         initCOS(file, import.meta.env.VITE_BUCKET_NAME).then(res => {
>           rev(res.url)
>         })
>       });
>     })
>   );
>   callback(res);
> }
> ```

现在还不支持这样做，后面计划对`callback`进行扩展来支持它

**Comment by imzbf** [comment]
4.12.0处理了该问题，[参考](https://github.com/imzbf/md-editor-v3?tab=readme-ov-file#-upload-picture)使用
