### ISSUE TITLE
自定义目录显示级别

### ISSUE THREAD

**Issue by lnbiuc** [imzbf/md-editor-v3#441]
### A great idea

希望可以配置目录显示级别，比如:level=[1,2]，只通过12级标题生成目录。现在有什么办法可以实现只显示12极目录吗

**Comment by imzbf** [comment]
抱歉，这个支持不了，不过你可以不使用内置的目录，通过`onGetCatalog`来保存目录，然后使用类似`element-plus`中的锚点组件来展示目录
