### ISSUE TITLE
添加图片链接的时候能不能也提供一个类似onUploadImg的回调函数

### ISSUE THREAD

**Issue by nlbwqmz** [imzbf/md-editor-v3#442]
### 一个很棒的想法

<span style="color:red">添加图片链接</span>的时候能不能也提供一个类似onUploadImg的回调函数

**Comment by imzbf** [comment]
这个目前做不到，即使向现有的插入图片链接添加了时间，像手动复制粘贴链接这类或者自行扩展的工具栏，是捕获不到的。

建议：通过`toolbars`来隐藏现有的插入图片的工具项，然后通过[弹窗工具栏扩展示例](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%A6%89%20ModalToolbar)来实现你想要的功能。
