### ISSUE TITLE
mdcatalog在预览模式下使用无法把目录文本放到地址栏

### ISSUE THREAD

**Issue by 2556227850** [imzbf/md-editor-v3#443]
### Describe the issue

我在使用mdcatalog在预览模式下使用时功能正常，但是我想通过MdCatalog的click函数把目录文本放到地址栏，这一步出现了问题，
只要我使用navigateTo
`
const onClick = (e, t) => {
    navigateTo({
      hash: '#' + t.text,
      query: {
        ...route.query,
      },
    });
}
`
把t.text放到地址栏就无法实现MdCatalog组件原有属性参数和丝滑的浏览器滚动条功能 
官网功能：无法复现官网上点击文档中目的跳转功能
<img width="1091" alt="1706371464296" src="https://github.com/imzbf/md-editor-v3/assets/71800549/42ad84e0-1fd9-4155-a1d2-87cb0bcd0a40">

### Procedure version

node 20.10.0

**Comment by imzbf** [comment]
不使用`navigateTo`

源码：https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/layouts/Catalog/index.vue#L39
