### ISSUE TITLE
MdCatalog定位高亮显示问题

### ISSUE THREAD

**Issue by 1279813** [imzbf/md-editor-v3#445]
### 描述这个Bug

这是个目录定位不准确的问题，在点击到指定的二级标题位置时，它目录的高亮显示还是在上一个二级标题，在一篇文章内只有两三个二级标题的锚点定位高亮是准确的，望作者修复

### 版本号

node 20.11.0  md-editor-v3 4.11.0

**Comment by imzbf** [comment]
请问如何还原这个问题？

**Comment by 1279813** [comment]
这样明天我将录一个视频上传上来。还原一下描述

**Comment by 1279813** [comment]
Uploading Video_2024-02-01_100450.mp4…

**Comment by 1279813** [comment]
https://github.com/imzbf/md-editor-v3/assets/92716079/bcd5e030-09ef-4b74-8901-b2ffc7b94943

**Comment by 1279813** [comment]
像这样，下面三个跟上面的centeros的都是，页面已经滚动到指定的地方了，可是目录的高亮显示还是在上一个二级标题

**Comment by imzbf** [comment]
看起来有点距离差，你看看能不能通过目录组件的`offsetTop`来调节一下

**Comment by 1279813** [comment]
并不行

**Comment by 1279813** [comment]
还是会有问题

**Comment by 1279813** [comment]
他看起来更像是内容区域的锚点定位不准确

**Comment by 1279813** [comment]
可以了，:scrollElementOffsetTop="55" :offsetTop="10"这样子设置就可以了
