### ISSUE TITLE
暴露一个中文输入法完成的事件

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#446]
### 一个很棒的想法

能否暴露一个中文输入法组合完成的事件，类似于input标签的compositionend。目前暴露的事件没法识别中文输入法组合完成

**Comment by imzbf** [comment]
4.12.0处理了该问题，现在你可以使用[domEventHandlers](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8E%9B%20domEventHandlers)来监听所有的dom事件。
