### ISSUE TITLE
vite打包部署后引用编辑器出现 st.join is not a function

### ISSUE THREAD

**Issue by CDCDA** [imzbf/md-editor-v3#447]
### Describe the issue

本地正常
但打包部署后会出现
![image](https://github.com/imzbf/md-editor-v3/assets/55029247/227d9d95-c1a8-4796-9552-3acf94809812)

### Procedure version

node版本 16.20.2

**Comment by imzbf** [comment]
方便的话，提供一下还原问题的可运行代码，和你的部署方式

**Comment by CDCDA** [comment]
只要引入就会报错




/*
&nbsp;* @Description:打包配置
&nbsp;* @Author: cyd ***@***.***
&nbsp;* @Date: 2023-06-26 16:41:56
&nbsp;* @LastEditTime: 2023-11-28 14:10:40
&nbsp;*/
import { defineConfig } from 'vite';
import vue from ***@***.***/plugin-vue';
import commonjs from ***@***.***/plugin-commonjs';
import requireTransform from 'vite-plugin-require-transform';
import path from 'path';
import viteCompression from 'vite-plugin-compression';
import legacy from ***@***.***/plugin-legacy';
import { createSvgIconsPlugin } from 'vite-plugin-svg-icons';

// https://vitejs.dev/config/
export default defineConfig({
&nbsp; // root: resolve('./'), // &nbsp;入口index.html，注意入口js应该与index.html 同一目录下（只能写到目录，不能写到具体文件）
&nbsp; base: './',
&nbsp; // publicDir: resolve('static'), //静态资源文件夹
&nbsp; plugins: [
&nbsp; &nbsp; commonjs() as any,
&nbsp; &nbsp; legacy({
&nbsp; &nbsp; &nbsp; targets: ['defaults', 'not IE 11']
&nbsp; &nbsp; }),
&nbsp; &nbsp; vue(),
&nbsp; &nbsp; createSvgIconsPlugin({
&nbsp; &nbsp; &nbsp; iconDirs: [path.resolve(process.cwd(), 'src/assets/svg')],
&nbsp; &nbsp; &nbsp; symbolId: '[name]'
&nbsp; &nbsp; }),
&nbsp; &nbsp; requireTransform({
&nbsp; &nbsp; &nbsp; fileRegex: /.js$|.vue$|.png$|.ts$|.jpg$/
&nbsp; &nbsp; }), //配置require
&nbsp; &nbsp; viteCompression({
&nbsp; &nbsp; &nbsp; verbose: true,
&nbsp; &nbsp; &nbsp; disable: false,
&nbsp; &nbsp; &nbsp; threshold: 10240,
&nbsp; &nbsp; &nbsp; algorithm: 'gzip',
&nbsp; &nbsp; &nbsp; ext: '.gz'
&nbsp; &nbsp; })
&nbsp; ],
&nbsp; css: {
&nbsp; &nbsp; preprocessorOptions: {
&nbsp; &nbsp; &nbsp; scss: {
&nbsp; &nbsp; &nbsp; &nbsp; additionalData: ***@***.*** "./src/assets/theme/theme.scss";' // 加载全局样式，使用scss特性
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }
&nbsp; },
&nbsp; resolve: {
&nbsp; &nbsp; alias: {
&nbsp; &nbsp; &nbsp; // 这里就是需要配置resolve里的别名
&nbsp; &nbsp; &nbsp; '@': path.join(__dirname, './src') // path记得引入
&nbsp; &nbsp; &nbsp; // 'vue': 'vue/dist/vue.esm-bundler.js' // 定义vue的别名，如果使用其他的插件，可能会用到别名
&nbsp; &nbsp; }
&nbsp; },
&nbsp; optimizeDeps: {
&nbsp; &nbsp; include: ['@/../lib/vform/designer.umd.js'] //此处路径必须跟main.js中import路径完全一致！
&nbsp; },
&nbsp; build: {
&nbsp; &nbsp; commonjsOptions: {
&nbsp; &nbsp; &nbsp; include: /node_modules|lib/ //这里记得把lib目录加进来，否则生产打包会报错！！
&nbsp; &nbsp; },
&nbsp; &nbsp; outDir: 'JcCloudWeb',
&nbsp; &nbsp; cssCodeSplit: true,
&nbsp; &nbsp; rollupOptions: {
&nbsp; &nbsp; &nbsp; input: 'index.html',
&nbsp; &nbsp; &nbsp; output: {
&nbsp; &nbsp; &nbsp; &nbsp; // 静态资源打包做处理
&nbsp; &nbsp; &nbsp; &nbsp; chunkFileNames: 'static/js/[name]-[hash].js',
&nbsp; &nbsp; &nbsp; &nbsp; entryFileNames: 'static/js/[name]-[hash].js',
&nbsp; &nbsp; &nbsp; &nbsp; assetFileNames: 'static/[ext]/[name]-[hash].[ext]',
&nbsp; &nbsp; &nbsp; &nbsp; manualChunks(id) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (id.includes('node_modules')) {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return id.toString().split('node_modules/')[1].split('/')[0].toString();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; },
&nbsp; &nbsp; minify: 'terser',
&nbsp; &nbsp; terserOptions: {
&nbsp; &nbsp; &nbsp; // 清除console和debugger
&nbsp; &nbsp; &nbsp; compress: {
&nbsp; &nbsp; &nbsp; &nbsp; drop_console: true,
&nbsp; &nbsp; &nbsp; &nbsp; drop_debugger: true
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }
&nbsp; },
&nbsp; server: {
&nbsp; &nbsp; port: 8086,
&nbsp; &nbsp; host: '0.0.0.0',
&nbsp; &nbsp; headers: {
&nbsp; &nbsp; &nbsp; 'Access-Control-Allow-Origin': '*'
&nbsp; &nbsp; },
&nbsp; &nbsp; proxy: {
&nbsp; &nbsp; &nbsp; '/dev-api': {
&nbsp; &nbsp; &nbsp; &nbsp; target: 'http://localhost:5008',
&nbsp; &nbsp; &nbsp; &nbsp; changeOrigin: true,
&nbsp; &nbsp; &nbsp; &nbsp; rewrite: p =&gt; p.replace(/^\/dev-api/, '')


&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }
&nbsp; }
});




打包后部署到服务器使用nginx代理


我打算先用cdn方式，感谢帮忙


陈毅东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-v3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 凌晨0:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-v3] vite打包部署后引用编辑器出现 st.join is not a function (Issue #447)





 
方便的话，提供一下还原问题的可运行代码，和你的部署方式

**Comment by imzbf** [comment]
> 只要引入就会报错 /* &nbsp;* @description:打包配置 &nbsp;* @author: cyd ***@***.*** &nbsp;* @Date: 2023-06-26 16:41:56 &nbsp;* @LastEditTime: 2023-11-28 14:10:40 &nbsp;*/ import { defineConfig } from 'vite'; import vue from ***@***.***/plugin-vue'; import commonjs from ***@***.***/plugin-commonjs'; import requireTransform from 'vite-plugin-require-transform'; import path from 'path'; import viteCompression from 'vite-plugin-compression'; import legacy from ***@***.***/plugin-legacy'; import { createSvgIconsPlugin } from 'vite-plugin-svg-icons'; // https://vitejs.dev/config/ export default defineConfig({ &nbsp; // root: resolve('./'), // &nbsp;入口index.html，注意入口js应该与index.html 同一目录下（只能写到目录，不能写到具体文件） &nbsp; base: './', &nbsp; // publicDir: resolve('static'), //静态资源文件夹 &nbsp; plugins: [ &nbsp; &nbsp; commonjs() as any, &nbsp; &nbsp; legacy({ &nbsp; &nbsp; &nbsp; targets: ['defaults', 'not IE 11'] &nbsp; &nbsp; }), &nbsp; &nbsp; vue(), &nbsp; &nbsp; createSvgIconsPlugin({ &nbsp; &nbsp; &nbsp; iconDirs: [path.resolve(process.cwd(), 'src/assets/svg')], &nbsp; &nbsp; &nbsp; symbolId: '[name]' &nbsp; &nbsp; }), &nbsp; &nbsp; requireTransform({ &nbsp; &nbsp; &nbsp; fileRegex: /.js$|.vue$|.png$|.ts$|.jpg$/ &nbsp; &nbsp; }), //配置require &nbsp; &nbsp; viteCompression({ &nbsp; &nbsp; &nbsp; verbose: true, &nbsp; &nbsp; &nbsp; disable: false, &nbsp; &nbsp; &nbsp; threshold: 10240, &nbsp; &nbsp; &nbsp; algorithm: 'gzip', &nbsp; &nbsp; &nbsp; ext: '.gz' &nbsp; &nbsp; }) &nbsp; ], &nbsp; css: { &nbsp; &nbsp; preprocessorOptions: { &nbsp; &nbsp; &nbsp; scss: { &nbsp; &nbsp; &nbsp; &nbsp; additionalData: ***@***.*** "./src/assets/theme/theme.scss";' // 加载全局样式，使用scss特性 &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; }, &nbsp; resolve: { &nbsp; &nbsp; alias: { &nbsp; &nbsp; &nbsp; // 这里就是需要配置resolve里的别名 &nbsp; &nbsp; &nbsp; '@': path.join(__dirname, './src') // path记得引入 &nbsp; &nbsp; &nbsp; // 'vue': 'vue/dist/vue.esm-bundler.js' // 定义vue的别名，如果使用其他的插件，可能会用到别名 &nbsp; &nbsp; } &nbsp; }, &nbsp; optimizeDeps: { &nbsp; &nbsp; include: ['@/../lib/vform/designer.umd.js'] //此处路径必须跟main.js中import路径完全一致！ &nbsp; }, &nbsp; build: { &nbsp; &nbsp; commonjsOptions: { &nbsp; &nbsp; &nbsp; include: /node_modules|lib/ //这里记得把lib目录加进来，否则生产打包会报错！！ &nbsp; &nbsp; }, &nbsp; &nbsp; outDir: 'JcCloudWeb', &nbsp; &nbsp; cssCodeSplit: true, &nbsp; &nbsp; rollupOptions: { &nbsp; &nbsp; &nbsp; input: 'index.html', &nbsp; &nbsp; &nbsp; output: { &nbsp; &nbsp; &nbsp; &nbsp; // 静态资源打包做处理 &nbsp; &nbsp; &nbsp; &nbsp; chunkFileNames: 'static/js/[name]-[hash].js', &nbsp; &nbsp; &nbsp; &nbsp; entryFileNames: 'static/js/[name]-[hash].js', &nbsp; &nbsp; &nbsp; &nbsp; assetFileNames: 'static/[ext]/[name]-[hash].[ext]', &nbsp; &nbsp; &nbsp; &nbsp; manualChunks(id) { &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (id.includes('node_modules')) { &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return id.toString().split('node_modules/')[1].split('/')[0].toString(); &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; }, &nbsp; &nbsp; minify: 'terser', &nbsp; &nbsp; terserOptions: { &nbsp; &nbsp; &nbsp; // 清除console和debugger &nbsp; &nbsp; &nbsp; compress: { &nbsp; &nbsp; &nbsp; &nbsp; drop_console: true, &nbsp; &nbsp; &nbsp; &nbsp; drop_debugger: true &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; }, &nbsp; server: { &nbsp; &nbsp; port: 8086, &nbsp; &nbsp; host: '0.0.0.0', &nbsp; &nbsp; headers: { &nbsp; &nbsp; &nbsp; 'Access-Control-Allow-Origin': '*' &nbsp; &nbsp; }, &nbsp; &nbsp; proxy: { &nbsp; &nbsp; &nbsp; '/dev-api': { &nbsp; &nbsp; &nbsp; &nbsp; target: 'http://localhost:5008', &nbsp; &nbsp; &nbsp; &nbsp; changeOrigin: true, &nbsp; &nbsp; &nbsp; &nbsp; rewrite: p =&gt; p.replace(/^\/dev-api/, '') &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; } }); 打包后部署到服务器使用nginx代理 我打算先用cdn方式，感谢帮忙 陈毅东 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "imzbf/md-editor-v3" ***@***.***&gt;; 发送时间:&nbsp;2024年2月1日(星期四) 凌晨0:34 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [imzbf/md-editor-v3] vite打包部署后引用编辑器出现 st.join is not a function (Issue #447) 方便的话，提供一下还原问题的可运行代码，和你的部署方式 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

👌，问题还原不了，这多半和你构建项目的环境有关系

**Comment by CDCDA** [comment]
找到问题了
跟require插件冲突


陈毅东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-v3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-v3] vite打包部署后引用编辑器出现 st.join is not a function (Issue #447)





  
只要引入就会报错 /* &nbsp;* @description:打包配置 &nbsp;* @author: cyd @.*** &nbsp;* @Date: 2023-06-26 16:41:56 &nbsp;* @LastEditTime: 2023-11-28 14:10:40 &nbsp;/ import { defineConfig } from 'vite'; import vue from @./plugin-vue'; import commonjs from @./plugin-commonjs'; import requireTransform from 'vite-plugin-require-transform'; import path from 'path'; import viteCompression from 'vite-plugin-compression'; import legacy from @./plugin-legacy'; import { createSvgIconsPlugin } from 'vite-plugin-svg-icons'; // https://vitejs.dev/config/ export default defineConfig({ &nbsp; // root: resolve('./'), // &nbsp;入口index.html，注意入口js应该与index.html 同一目录下（只能写到目录，不能写到具体文件） &nbsp; base: './', &nbsp; // publicDir: resolve('static'), //静态资源文件夹 &nbsp; plugins: [ &nbsp; &nbsp; commonjs() as any, &nbsp; &nbsp; legacy({ &nbsp; &nbsp; &nbsp; targets: ['defaults', 'not IE 11'] &nbsp; &nbsp; }), &nbsp; &nbsp; vue(), &nbsp; &nbsp; createSvgIconsPlugin({ &nbsp; &nbsp; &nbsp; iconDirs: [path.resolve(process.cwd(), 'src/assets/svg')], &nbsp; &nbsp; &nbsp; symbolId: '[name]' &nbsp; &nbsp; }), &nbsp; &nbsp; requireTransform({ &nbsp; &nbsp; &nbsp; fileRegex: /.js$|.vue$|.png$|.ts$|.jpg$/ &nbsp; &nbsp; }), //配置require &nbsp; &nbsp; viteCompression({ &nbsp; &nbsp; &nbsp; verbose: true, &nbsp; &nbsp; &nbsp; disable: false, &nbsp; &nbsp; &nbsp; threshold: 10240, &nbsp; &nbsp; &nbsp; algorithm: 'gzip', &nbsp; &nbsp; &nbsp; ext: '.gz' &nbsp; &nbsp; }) &nbsp; ], &nbsp; css: { &nbsp; &nbsp; preprocessorOptions: { &nbsp; &nbsp; &nbsp; scss: { &nbsp; &nbsp; &nbsp; &nbsp; additionalData: @.* "./src/assets/theme/theme.scss";' // 加载全局样式，使用scss特性 &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; }, &nbsp; resolve: { &nbsp; &nbsp; alias: { &nbsp; &nbsp; &nbsp; // 这里就是需要配置resolve里的别名 &nbsp; &nbsp; &nbsp; '@': path.join(__dirname, './src') // path记得引入 &nbsp; &nbsp; &nbsp; // 'vue': 'vue/dist/vue.esm-bundler.js' // 定义vue的别名，如果使用其他的插件，可能会用到别名 &nbsp; &nbsp; } &nbsp; }, &nbsp; optimizeDeps: { &nbsp; &nbsp; include: ['@/../lib/vform/designer.umd.js'] //此处路径必须跟main.js中import路径完全一致！ &nbsp; }, &nbsp; build: { &nbsp; &nbsp; commonjsOptions: { &nbsp; &nbsp; &nbsp; include: /node_modules|lib/ //这里记得把lib目录加进来，否则生产打包会报错！！ &nbsp; &nbsp; }, &nbsp; &nbsp; outDir: 'JcCloudWeb', &nbsp; &nbsp; cssCodeSplit: true, &nbsp; &nbsp; rollupOptions: { &nbsp; &nbsp; &nbsp; input: 'index.html', &nbsp; &nbsp; &nbsp; output: { &nbsp; &nbsp; &nbsp; &nbsp; // 静态资源打包做处理 &nbsp; &nbsp; &nbsp; &nbsp; chunkFileNames: 'static/js/[name]-[hash].js', &nbsp; &nbsp; &nbsp; &nbsp; entryFileNames: 'static/js/[name]-[hash].js', &nbsp; &nbsp; &nbsp; &nbsp; assetFileNames: 'static/[ext]/[name]-[hash].[ext]', &nbsp; &nbsp; &nbsp; &nbsp; manualChunks(id) { &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (id.includes('node_modules')) { &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return id.toString().split('node_modules/')[1].split('/')[0].toString(); &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; }, &nbsp; &nbsp; minify: 'terser', &nbsp; &nbsp; terserOptions: { &nbsp; &nbsp; &nbsp; // 清除console和debugger &nbsp; &nbsp; &nbsp; compress: { &nbsp; &nbsp; &nbsp; &nbsp; drop_console: true, &nbsp; &nbsp; &nbsp; &nbsp; drop_debugger: true &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; }, &nbsp; server: { &nbsp; &nbsp; port: 8086, &nbsp; &nbsp; host: '0.0.0.0', &nbsp; &nbsp; headers: { &nbsp; &nbsp; &nbsp; 'Access-Control-Allow-Origin': '' &nbsp; &nbsp; }, &nbsp; &nbsp; proxy: { &nbsp; &nbsp; &nbsp; '/dev-api': { &nbsp; &nbsp; &nbsp; &nbsp; target: 'http://localhost:5008', &nbsp; &nbsp; &nbsp; &nbsp; changeOrigin: true, &nbsp; &nbsp; &nbsp; &nbsp; rewrite: p =&gt; p.replace(/^/dev-api/, '') &nbsp; &nbsp; &nbsp; } &nbsp; &nbsp; } &nbsp; } }); 打包后部署到服务器使用nginx代理 我打算先用cdn方式，感谢帮忙 陈毅东 @.** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "imzbf/md-editor-v3" @.&gt;; 发送时间:&nbsp;2024年2月1日(星期四) 凌晨0:34 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [imzbf/md-editor-v3] vite打包部署后引用编辑器出现 st.join is not a function (Issue #447) 方便的话，提供一下还原问题的可运行代码，和你的部署方式 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
👌，问题还原不了，这多半和你构建项目的环境有关系

**Comment by imzbf** [comment]
`vite-plugin-require-transform`这个是吗

**Comment by CDCDA** [comment]
对


陈毅东
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imzbf/md-editor-v3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月1日(星期四) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imzbf/md-editor-v3] vite打包部署后引用编辑器出现 st.join is not a function (Issue #447)





 
vite-plugin-require-transform这个是吗
