### ISSUE TITLE
[Bug] 文本输入后，方法在不断的被调用

### ISSUE THREAD

**Issue by labbomb** [imzbf/md-editor-v3#449]
### 描述这个Bug

<img width="588" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/15062456/b3a61434-8560-4811-b210-4f06f09de87d">

每输入一次，都会触发上面方法调用，而input则不会

### 版本号

4.11.0

**Comment by imzbf** [comment]
`n-input`是什么组件，我使用`element-plus`的`Input`组件，有一样的效果，按照常理来讲，text有变化，组件都会重新render的

**Comment by imzbf** [comment]
<img width="335" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/ef75e241-6e38-40ca-908d-b940346305b0">

![录屏2024-02-03 11 35 51](https://github.com/imzbf/md-editor-v3/assets/37092006/69552905-5531-4801-8996-2c18df90f119)

**Comment by labbomb** [comment]
> `n-input`是什么组件，我使用`element-plus`的`Input`组件，有一样的效果，按照常理来讲，text有变化，组件都会重新render的

naive-ui

**Comment by imzbf** [comment]
![录屏2024-02-03 21 30 00](https://github.com/imzbf/md-editor-v3/assets/37092006/8f5f473f-4333-4a50-81bd-15a43c5cbdb7)

<img width="494" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/e738c5a2-2d91-4d04-a3d5-9e8fcbfdf00e">


不太了解这个库，可能是它的bug，从原理上讲，这个方法一定是需要每次调用猜对的，上面是我的实际使用结果，它的双向绑定根本没有生效
