### ISSUE TITLE
请问可以更改字体颜色吗

### ISSUE THREAD

**Issue by Juken8104** [imzbf/md-editor-v3#45]
1. 请问可以更改字体颜色吗

**Comment by imzbf** [comment]
Markdown编辑器一般不会提供这种对样式的定义哦，不过在v1.10.1版本后，在编辑器中内置了扩展工具栏的组件，你可以模仿着[扩展emoji](https://imzbf.github.io/md-editor-v3/demo/index#%F0%9F%AA%A1%20marked%20extension)实现一下。
