### ISSUE TITLE
cyanosis主题颜色问题

### ISSUE THREAD

**Issue by yanyunling** [imzbf/md-editor-v3#450]
### Describe the issue

cyanosis主题的标题颜色，应该是蓝色的，css相关变量都是以--md起头，未找到--cyanosis变量
![image](https://github.com/imzbf/md-editor-v3/assets/32293949/70dbb8f4-1203-43ca-b0bd-b6c71a6a14e4)
![image](https://github.com/imzbf/md-editor-v3/assets/32293949/49ac5790-a17c-4da5-91db-534d82199554)

### Procedure version

4.11.0

**Comment by imzbf** [comment]
感谢提醒，变量名不对

**Comment by imzbf** [comment]
4.11.2修复了这个问题~
