### ISSUE TITLE
[BUG] 预览图片问题

### ISSUE THREAD

**Issue by tyc0125** [imzbf/md-editor-v3#451]
### 描述这个Bug

![20240203135154_rec_](https://github.com/imzbf/md-editor-v3/assets/77429120/f7d3ddaa-bda7-44fe-ba8e-76beab2ef6a3)

![1gif](https://github.com/imzbf/md-editor-v3/assets/77429120/bf493754-af47-4884-9b0a-2051708fd53e)

在模态框组件中使用，image预览有问题,点击预览会生成两组遮罩层和image，点击一次只能取消一组
复现步骤：
            <MdEditor
              :preview="false"
            />
截图，将图片上传，点击小眼睛图标，预览会生成两组遮罩层和image，点击一次只能取消一组
### 版本号

4.11.1

**Comment by tyc0125** [comment]
![Uploading image.png…]()

**Comment by imzbf** [comment]
这个页面存在多个`MdEditor`和`MdPreview`的话，需要区别一下`editorId`这个属性

**Comment by tyc0125** [comment]
上述页面只用了一个MdEditor。
<MdEditor
              :preview="false"
            />
如上代码，将默认打开的预览模式关闭，去截图，上传图片，然后在编辑器中打开预览模式，点击图片后，会出现上述问题

**Comment by imzbf** [comment]
4.11.2修复了这个问题~
