### ISSUE TITLE
能否提供编辑器的搜索和替换功能？

### ISSUE THREAD

**Issue by nlbwqmz** [imzbf/md-editor-v3#452]
### 一个很棒的想法

**能否提供编辑器的搜索和替换功能？**

**Comment by imzbf** [comment]
我做个技术调研看看

**Comment by nlbwqmz** [comment]
我尝试使用codemirror自带的openSearchPanel()方法打开自带的搜索框，但是它样式不太统一。
我又查询了相关资料，可以使用SearchCursor来实现自定义的搜索替换等，但相关资料确实太少 了，暂时还不知道怎么实现。

**Comment by imzbf** [comment]
调研结果是没有找到合适的自定义搜索方式，这个插件的问题看着有点头痛，作者好像不喜欢提供一些完整的demo。

所以我调整了内置的搜索面板样式，尝试一下吧
