### ISSUE TITLE
编辑器v-model行为和官方不一致的讨论

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#455]
### 一个很棒的想法

https://cn.vuejs.org/guide/essentials/forms.html
官方文档形容

> 对于需要使用 [IME](https://en.wikipedia.org/wiki/Input_method) 的语言 (中文，日文和韩文等)，你会发现 v-model 不会在 IME 输入还在拼字阶段时触发更新。如果你的确想在拼字阶段也触发更新，请直接使用自己的 input 事件监听器和 value 绑定而不要使用 v-model。

但是编辑器v-model绑定的内容是在拼字阶段也会触发更新的，想问下这个功能能和官方建议保持一致吗？

**Comment by imzbf** [comment]
旧版倒是一致，问题出现在使用`codemirror`替换掉`textarea`后，找了下这个编辑器稳定和论坛，

https://discuss.codemirror.net/t/how-to-listen-to-changes-with-ime-support/5737

目前还没有较好的方式，不过，目前正在着手添加输入前后的监听事件，我会注意如果绕过这个问题。

**Comment by imzbf** [comment]
4.12.0优化了该问题
