### ISSUE TITLE
图片无法被正确打开

### ISSUE THREAD

**Issue by Mrkk1** [imzbf/md-editor-v3#460]
### 描述这个Bug

#451 
![2024-02-21 11 15 12](https://github.com/imzbf/md-editor-v3/assets/60224145/f1ff15ad-42e9-46ee-8264-7d8961a5db07)
用户发出后的图片可打开，但是打开先展示了一层纯黑的模态框，然后点击一下会展示放大后的图片，但是没有模态框遮罩层，再点击一下 才可以把他关闭，但是上述任一一个步骤 按esc 可完全关闭，
当刷新页面后，从后端传过来的数据中包含的图片就无法直接点开了，🔍图标都没有了

### 版本号

"@types/node": "^18.15.0",

**Comment by Mrkk1** [comment]
"md-editor-v3": "^4.11.2",

**Comment by imzbf** [comment]
能否提供一份还原这个问题的代码呢，我这边暂时定位不了问题

**Comment by yanyunling** [comment]
官方示例中，切换 preview 后也有这个问题

**Comment by imzbf** [comment]
> 官方示例中，切换 preview 后也有这个问题

OK

**Comment by imzbf** [comment]
该问题在4.11.3中更新了

**Comment by Mrkk1** [comment]
您好，在更新到4.11.3的时候依然存在这样的问题，图片要么无法被打开，要么打开出现先出现全黑的模态框，再点击才出现放大后的图片（此时黑色的模态框就没有了，变成了图片四周全透明）
