### ISSUE TITLE
现在公式只支持  $...$ 和 $$...$$ 的检测， 希望能增加  \(...\) 和  \[...\]  的检测

### ISSUE THREAD

**Issue by joker-duzhong** [imzbf/md-editor-v3#462]
### 一个很棒的想法

现在公式只支持  \\$... \\$ 和 \\$\\$ ... \\$ \$ 的检测， 希望能增加  \\(...\\) 和  \\[...\\]  的检测

**Comment by joker-duzhong** [comment]
现在公式只支持  \$...\$ 和 \$\$...\$\$ 的检测， 希望能增加  \\(...\\) 和  \\[...\\]  的检测

**Comment by imzbf** [comment]
抱歉哈，公式目前的这种标记方式是大部分的在用编辑工具认可的，移植比较方便，特殊的方式这边建议参考`markdown-it`的扩展来实现，移除内部和添加自有的扩展的方式[参考](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8D%A4%20markdownItPlugins)

**Comment by joker-duzhong** [comment]
临时解决：

可以通过正则将  \(...\) 和 \[...\] 转为 \$... \$ 和 \$\$ ... \$\$  

 .replace(/\s*\\\(\s*/g, "$$");
 .replace(/\s*\\\)\s*/g, "$$");
 .replace(/\\\[/g, "$$$$");
 .replace(/\\\]/g, "$$$$");

**Comment by imzbf** [comment]
4.19.0版本开始支持这个标识
