### ISSUE TITLE
支持微信小程序吗？

### ISSUE THREAD

**Issue by Diven-xinhai** [imzbf/md-editor-v3#465]
### Describe the issue

我是用uniapp开发微信小程序时使用此组件报错，浏览器是没问题的，问题如下：
![image](https://github.com/imzbf/md-editor-v3/assets/54425515/f3d991a8-8db9-4250-8708-d8ed45dc7be3)

### Procedure version

4.11.0

**Comment by imzbf** [comment]
抱歉哈，这个组件还不能在uni中使用
