### ISSUE TITLE
Library relys on external CDN without advertising it

### ISSUE THREAD

**Issue by func0der** [imzbf/md-editor-v3#466]
### Describe the issue

IconFonts and "cdnBase" (dunno how that is used) are both hard coded into this library.

The editor should not by default download anything from an external source without informing the user first.

Please include the icon font in the lib or find an alternative solution.

At least inform users about the usage of external cdns with a **big fat warning**

### Procedure version

4.11.3

**Comment by LorkiNikita** [comment]
Same problem for me they are also loaded with alicdn within 25-30 seconds (and by the way, such problem apparently only in Ukraine as i switch to the US vpn and loads much faster).
![image](https://github.com/imzbf/md-editor-v3/assets/69603120/80f6c6f9-c578-4478-9f6d-ec5a27484180)

**Comment by imzbf** [comment]
We have a solution for this. [Download](https://at.alicdn.com/t/c/font_2605852_prouiefeic.js) file and import in your project. 

```vue
<template>
  <MdEditor noIconfont />
</template>

<script setup>
import './assets/font_2605852_prouiefeic';
</script>
```

**Comment by func0der** [comment]
> [Download](https://at.alicdn.com/t/c/font_2605852_prouiefeic.js) file and import in your project.

That should be part of the library and not by default downloaded from a random CDN.

Also mentioning it in an issue far away from the documentation is not a very good option.
You might have loser regulations in JPN, but for the whole European market for example your library is basically a data protection nightmare. 

```
<script setup>
import './assets/font_2605852_prouiefeic';
</script>
```

This solution is also not optimal, since it includes the whole JS on each request even of the MdEditor is not launched/used. More overhead than needed in some cases.
In vite you can use `import fontUrl from './assets/font_2605852_prouiefeic?url';` and then set `fonticonUrl: fontUrl` (not sure about the property name of the config).
Still this needs to be an "upfront information".

**Comment by ajmas** [comment]
Looking at the code this is all coming in via the config:

https://github.com/imzbf/md-editor-v3/blob/ebec2d361a2ad56b44d489d90a9f638017c5d075/packages/MdEditor/config.ts#L9

With snippet here:

```ts
export const cdnBase = 'https://cdnjs.cloudflare.com/ajax/libs';

// 代码高亮cdn链接
export const highlightUrl = `${cdnBase}/highlight.js/11.8.0/highlight.min.js`;

// 美化代码cdn连接
export const prettierUrl = {
  main: `${cdnBase}/prettier/2.8.0/standalone.js`,
  markdown: `${cdnBase}/prettier/2.8.0/parser-markdown.js`
};

export const cropperUrl = {
  css: `${cdnBase}/cropperjs/1.5.13/cropper.min.css`,
  js: `${cdnBase}/cropperjs/1.5.13/cropper.min.js`
};

export const screenfullUrl = `${cdnBase}/screenfull.js/5.2.0/screenfull.min.js`;
```

unfortunately this is non-modifiable:

```
export const cdnBase = 'https://cdnjs.cloudflare.com/ajax/libs';
```

The question is whether the maintainer is open to changing this code?

**Comment by imzbf** [comment]
> Looking at the code this is all coming in via the config:
> 
> https://github.com/imzbf/md-editor-v3/blob/ebec2d361a2ad56b44d489d90a9f638017c5d075/packages/MdEditor/config.ts
> 
> With snippet here:
> 
> ```ts
> export const cdnBase = 'https://cdnjs.cloudflare.com/ajax/libs';
> 
> // 代码高亮cdn链接
> export const highlightUrl = `${cdnBase}/highlight.js/11.8.0/highlight.min.js`;
> 
> // 美化代码cdn连接
> export const prettierUrl = {
>   main: `${cdnBase}/prettier/2.8.0/standalone.js`,
>   markdown: `${cdnBase}/prettier/2.8.0/parser-markdown.js`
> };
> 
> export const cropperUrl = {
>   css: `${cdnBase}/cropperjs/1.5.13/cropper.min.css`,
>   js: `${cdnBase}/cropperjs/1.5.13/cropper.min.js`
> };
> 
> export const screenfullUrl = `${cdnBase}/screenfull.js/5.2.0/screenfull.min.js`;
> ```
> 
> unfortunately this is non-modifiable:
> 
> ```ts
> export const cdnBase = 'https://cdnjs.cloudflare.com/ajax/libs';
> ```
> 
> The question is whether the maintainer is open to changing this code? Not sure this issue should be considered resolved?

Demo: https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%93%A1%20Intranet%20Link
Declared type: https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%A5%A0%20editorExtensions

**Comment by func0der** [comment]
@imzbf I understand where you are coming from. You want this to work out of the box. 
But please **advertise** the use of external CDNs prominently in the specific features using them.

Or maybe we can find a way for people to opt-in to this instead of just assuming everybody **wants** or **can** use CDNs.
