### ISSUE TITLE
粘贴从网页中复制来的内容，包含图片如何上传网页中的图片

### ISSUE THREAD

**Issue by Minhat-GitHub** [imzbf/md-editor-v3#468]
### 一个很棒的想法

粘贴从网页中复制来的内容，包含图片如何上传网页中的图片

我在搜索问题的时候发现有很多人都有这样的需求，但是回复的大多数是没法实现，我在另一款Markdown编辑器Vditor中看到了实现的方式：
https://github.com/Vanessa219/vditor
![image](https://github.com/imzbf/md-editor-v3/assets/35595109/caf7ee40-abbe-40eb-8e37-42d54cd0129c)
希望可以参考一下实现方式；

声明：
本人对这款Markdown编辑器的作者表示尊重；没有其它意思，只是希望这款编辑器能更好

**Comment by imzbf** [comment]
多谢提供Idea，不确定这能实现，需要尝试一下，这个组件渲染内容的原理中没有手动解析图片链接的过程。

**Comment by imzbf** [comment]
正式版发布了，[文档](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%AA%92%20transformImgUrl)
