### ISSUE TITLE
关于编辑器元素渲染完毕的回调

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#469]
### 一个很棒的想法

现在是否有办法拿到编辑器渲染完成以后的回调？

可能有一些诉求是这样的，就是要在元素渲染完以后做一些事，比如拿到元素在页面上的位置数据等，目前处理这个问题我使用`setTimeout`延迟处理，但是这样的实现并不优雅。

现在在代码中编辑器数据回填以后

```js
editor.content = data.content
await nextTick()
//后续操作
```

在`后续操作`的位置编辑器并没有渲染。一般来说，我是用vue时一般都是使用`nextTick()`处理这种问题，但是目前编辑器兼容这个应该并不容易实现。

能否暴露一个编辑器内容dom渲染完成的回调？

**Comment by imzbf** [comment]
在事件`onHtmlChanged`中`nextTick`就可以获取到已渲染的元素

**Comment by mingchiuli** [comment]
> 在事件`onHtmlChanged`中`nextTick`就可以获取到已渲染的元素

试了下可以实现，只是不知为啥这个回调调用了多次，但是不要紧
