### ISSUE TITLE
空行问题

### ISSUE THREAD

**Issue by wuyu8512** [imzbf/md-editor-v3#47]
https://www.zhihu.com/question/20134106
根据这篇文章

MarkDown应该是可以用空格打出空行的，但这个组件似乎不支持
实际上我用的解析库 `turndown` 就会把空行解析成两个空格

**Comment by imzbf** [comment]
marked的表现是需要额外的空行，需要添加`<br>`或者`&nbsp;`，空格换行在编辑器中并不支持，其中使用`prettier`默认规则格式化md文本时，也会将其视为无效的内容。

如果需要可通过`extensions`来扩展编辑器内部的marked，通过识别单行双空格以转为为空行。

**Comment by wuyu8512** [comment]
空格似乎没办法扩展 `extensions` 来实现，暂时通过替换解析库生成的文本搞定了
另外修改本组件生成的html代码则可以通过 `sanitize` 来搞定
希望能尽快自定义生成代码吧

**Comment by imzbf** [comment]
通过匹配单行以空格开始及空格结束，指定将其解析为<br>，后续给一个扩展例子给你
