### ISSUE TITLE
如何知道MdPreview的内容已经渲染完毕，并获取渲染内容的一些元素

### ISSUE THREAD

**Issue by RickTe** [imzbf/md-editor-v3#470]
### Describe the issue

我遇到的问题是我在请求接口数据并对**MdPreview**进行赋值，但是我无法在**nextTick**函数中获取渲染后的内容，目前我只能通过**setTimeout(()=>{}, 1000)**来获取，请问是否有方法可以在渲染结束后马上获取到页面元素？

### Procedure version

v4.11.3

**Comment by RickTe** [comment]
我尝试使用onHtmlChanged，但是它被调用了多次造成额外的开销

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/issues/469#issuecomment-1980317349

确实只有这种方式，可以只执行一次，就是将所有的扩展都通过下面的方式给到编辑器

https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93
