### ISSUE TITLE
Allow triggering editor operations by call

### ISSUE THREAD

**Issue by ajmas** [imzbf/md-editor-v3#471]
### A great idea

We would like to be able to hide the menubar. but still trigger certain operations using a method call.

Given a template

```html
    <md-editor
      v-model="content"
      :mode="mode"
      :preview="false"
      :height="300"
      :toolbars="[]"
      :footers="[]"
      :language="language"
      ref="mdEditor"
      class="v-md-editor"
      @change="onChange"
      >
```

Then have a method call such as:

```ts
this.$refs.mdEditor.execCommand('bold');
```

This may already be possible, but I was not able to see this in the documentation.

Just for the use case, I am trying to implement a editor/preview type, like the one in GitHub for editing comments.

**Comment by imzbf** [comment]
The latest version has been released. [docs](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8E%9B%20execCommand)
