### ISSUE TITLE
Word Count Issue

### ISSUE THREAD

**Issue by khalidbelk** [imzbf/md-editor-v3#472]
### Got character count instead of word count

As you can see here if i write this :
<img width="953" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/72026317/0f0503b6-a8fe-4c1c-86e2-fd85818f477e">

It gives me the **character** count: 
<img width="953" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/72026317/347811e9-ef2b-4d7a-8d55-6eb89fdc766a">

Maybe I missed something and my config still needs a parameter or something
Here's the snippet if it can help, tried to see the docs (saw something about the footer and markdownTotal but I don't know if it has something to do with it). Is there any way to have the actual **word count** ? Thank you in advance :)

```
        <md-editor
          :history-length="50"
          :toolbars="toolbars"
          @on-upload-img="uploadImg"
          language="en-US"
          v-model="postContent"
        />
```

### Procedure version

"md-editor-v3": "^2.5.0"

**Comment by khalidbelk** [comment]
Well I found out where was the issue. Opened a PR :)

**Comment by imzbf** [comment]
Thank you for your participation.

But this might be more appropriately achieved through an extension, since Chinese word counting could become abnormal.

**Comment by imzbf** [comment]
> > Thank you for your participation.
> > But this might be more appropriately achieved through an extension, since Chinese word counting could become abnormal.
> 
> Oh I see, so chinese word’s aren‘t delimited by spaces like ours ? Like it can be 2 words without spacing between them, right ? Then in that case, please if you could fix the word count just for the other languages (this way, or display both chars and words like I said in the Issue’s comments) it would be nice :)

Correct, this cannot be made public due to the vast number of language types. Therefore, I suggest you add your private extension in the same way as shown in the [example](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%A6%BF%20defFooters).
