### ISSUE TITLE
MD标题符号后进行拼字，存在光标位置异常的问题

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#474]
### 描述这个Bug

<img width="507" alt="Screenshot 2024-03-16 at 12 09 44" src="https://github.com/imzbf/md-editor-v3/assets/80095372/03d713e3-64e5-4b86-81fa-4a11db94bcd1">

如图首先打一行字，这个时候光标在c的后面，预期没问题。这个时候按键盘退格把这个字符删除掉，然后再按一下c

<img width="507" alt="Screenshot 2024-03-16 at 12 08 59" src="https://github.com/imzbf/md-editor-v3/assets/80095372/5ed96eeb-faad-45dd-976b-42822b68bed5">

这个时候光标就跑到c左边去了。按下空格，会多出一个c，光标此时位于除和c的中间

<img width="507" alt="Screenshot 2024-03-16 at 12 11 43" src="https://github.com/imzbf/md-editor-v3/assets/80095372/b55717c1-ebc7-49fc-9c52-50f5fd44036e">

### 版本号

4.12.1

**Comment by imzbf** [comment]
我在这边按照你的描述尝试还原不了问题，是否还有其他操作，或者和你的输入法有关系

https://github.com/imzbf/md-editor-v3/assets/37092006/d265da9a-8b2d-4b71-9090-3fd6ddca13b1

**Comment by mingchiuli** [comment]
https://www.zhihu.com/question/490010448/answer/3023768357

**Comment by mingchiuli** [comment]
https://www.zhihu.com/question/490010448/answer/3023768357

看了下疑似是苹果的问题。我设备也是mac，我专门开了个新的编辑器对象去试，会稳定复现这个问题。我去你的线上用例看了下并不存在这个问题。

这问题可以先关掉

**Comment by mingchiuli** [comment]
> 我在这边按照你的描述尝试还原不了问题，是否还有其他操作，或者和你的输入法有关系
> 
>  93_1710669606.mp4

https://www.zhihu.com/question/490010448/answer/3023768357

看了下疑似是苹果的问题。我设备是mac，不是win。为了避免干扰我专门开了个新的页面加了个新的编辑器组件对象去试，还是会稳定复现这个问题，而且只在###这种标题后面复现，普通行是不会出现这种问题的。

但是我去你的线上用例看了下并不存在这个问题，怀疑是mac环境下编译代码出了问题，应该是苹果自身的bug。

**Comment by mingchiuli** [comment]
Uploading imissinstagram 2024-03-03 21.08.26.mp4…

**Comment by mingchiuli** [comment]
https://github.com/imzbf/md-editor-v3/assets/80095372/18fcaaf1-fed1-43a0-b91c-95d22e795a8c

**Comment by imzbf** [comment]
> > 我在这边按照你的描述尝试还原不了问题，是否还有其他操作，或者和你的输入法有关系
> > 93_1710669606.mp4
> 
> https://www.zhihu.com/question/490010448/answer/3023768357
> 
> 看了下疑似是苹果的问题。我设备是mac，不是win。为了避免干扰我专门开了个新的页面加了个新的编辑器组件对象去试，还是会稳定复现这个问题，而且只在###这种标题后面复现，普通行是不会出现这种问题的。
> 
> 但是我去你的线上用例看了下并不存在这个问题，怀疑是mac环境下编译代码出了问题，这项目我一直是本机打包完以后发到线上Nginx里。应该是苹果自身的bug。

可能不是系统问题，我常用的是mac，因为在mac还原不了问题才切到win系统去看的。

麻烦你尝试一下4.11.3版本是否有这类问题，如果仍然有可能就是未知的环境的问题

**Comment by nicolas830316** [comment]
我又仔细研究了下，在  https://imzbf.github.io/md-editor-v3/zh-CN/index 的实例页面里不会有问题，只是在我项目里出的问题。    
"ant-design-vue": "^4.1.2",
"md-editor-v3": "^4.12.2",
所以暂时怀疑可能是 ant-design-vue 或者是我写的代码其它东西干扰到了这个测试

**Comment by mingchiuli** [comment]
> 我又仔细研究了下，在 https://imzbf.github.io/md-editor-v3/zh-CN/index 的实例页面里不会有问题，只是在我项目里出的问题。 "ant-design-vue": "^4.1.2", "md-editor-v3": "^4.12.2", 所以暂时怀疑可能是 ant-design-vue 或者是我写的代码其它东西干扰到了这个测试

我这边用的element plus也出现了这个问题

**Comment by 13165680192** [comment]
> 我又仔细研究了下，在 https://imzbf.github.io/md-editor-v3/zh-CN/index 的实例页面里不会有问题，只是在我项目里出的问题。 "ant-design-vue": "^4.1.2", "md-editor-v3": "^4.12.2", 所以暂时怀疑可能是 ant-design-vue 或者是我写的代码其它东西干扰到了这个测试

我把作者官网的cdn方式复制到html中用浏览器打开windows/mac，然后切换输入法依然有这个问题，然后把cdn的版本改成4.11.3，就没这个问题了。但是通过npm安装这两个版本都有问题，npm如果切换到4.0.0的话，光标位置有问题，不过最终显示反而是正常的

**Comment by mingchiuli** [comment]
@imzbf 这边信息多一些，可以看下这里的信息

**Comment by nicolas830316** [comment]
我的 md-editor-v3 版本是 4.12.2，. 经过折腾发下，当出现这个错误的时候，控制台会打印 compositionstart ，来自文件 md-editor-v3.js 的 18713 行。

然后尝试 将  编辑器核心div 就是 contenteditable="true" 的那个div 的 compositionstart 事件监听移除，没什么用

然后再将 compositionend 事件监听移除，再次输入，仍然能复现1次，再之后 bug 就消失了。所以猜测，从 compositionend 入手应该能更快的排除是什么问题。

- [x ]  chrome 123.0.6312.59  有问题
- [ ]  用  360极速 22.1.1073.64（chromium 内核 119.0.6045.160） 没问题
- [ ]  火狐 121.0 也没有问题
- [ ]  QQ浏览器 12.1.1 （chromium 内核 94.0.4606.71） 没有问题
- [x ]  搜狗浏览 12.2.2 （chromium 内核 94.0.4606.71）有问题
- [x ]  edge 122.0.2365.92 有问题

这个比较奇怪，开始以为浏览器内核有关呢，但是 QQ浏览器 和搜狗的 chromium 内核版本号相同，但是一个有问题，一个没有问题。

**Comment by mingchiuli** [comment]
> 我的 md-editor-v3 版本是 4.12.2，. 经过折腾发下，当出现这个错误的时候，控制台会打印 compositionstart ，来自文件 md-editor-v3.js 的 18713 行。
> 
> 然后尝试 将 编辑器核心div 就是 contenteditable="true" 的那个div 的 compositionstart 事件监听移除，没什么用
> 
> 然后再将 compositionend 事件监听移除，再次输入，仍然能复现1次，再之后 bug 就消失了。所以猜测，从 compositionend 入手应该能更快的排除是什么问题。
> 
> * [x]   chrome 123.0.6312.59  有问题
> * [ ]   用  360极速 22.1.1073.64（chromium 内核 119.0.6045.160） 没问题
> * [ ]   火狐 121.0 也没有问题
> * [ ]   QQ浏览器 12.1.1 （chromium 内核 94.0.4606.71） 没有问题
> * [x]   搜狗浏览 12.2.2 （chromium 内核 94.0.4606.71）有问题
> * [x]   edge 122.0.2365.92 有问题
> 
> 这个比较奇怪，开始以为浏览器内核有关呢，但是 QQ浏览器 和搜狗的 chromium 内核版本号相同，但是一个有问题，一个没有问题。

> [v4.12.0](https://github.com/imzbf/md-editor-v3/releases/tag/v4.12.0)
> 新增特性
> 
> 🌟 为editorId设置不同的默认值（现在存在多个编辑器不需要手动设置该属性，但是使用目录组件时仍然需要相同）。
> 🌟 暴露方法[domEventHandlers](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8E%9B%20domEventHandlers)来监听全部的dom事件(https://github.com/imzbf/md-editor-v3/issues/446)。
> 🌟 上传图片事件onUploadImg现在支持回显alt和title属性了，使用[示例](https://github.com/imzbf/md-editor-v3?tab=readme-ov-file#-upload-picture)。

暴露方法[domEventHandlers](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8E%9B%20domEventHandlers)来监听全部的dom事件(https://github.com/imzbf/md-editor-v3/issues/446)

compositionstart应该是这次更新引入的

**Comment by imzbf** [comment]
日志是组件残留的，我会尽快清除

关于输入的内容，作者目前无法定位问题影响的因素

**Comment by imzbf** [comment]
codemirror的问题，在官方demo中能够复现

https://codemirror.net/try/?example=Markdown%20code%20block%20highlighting

**Comment by imzbf** [comment]
尝试4.12.4

**Comment by mingchiuli** [comment]
> 尝试4.12.4

目前问题应该说阶段性解决了，首先我试了下，光标位于字母左侧这个问题算是没解决，但是这时候按下空格不会再多打出一个字母了

**Comment by imzbf** [comment]
不行的删除一下lock文件重新安装

**Comment by imzbf** [comment]
> > 尝试4.12.4
> 
> 目前问题应该说阶段性解决了，首先我试了下，光标位于字母左侧这个问题算是没解决，但是这时候按下空格不会再多打出一个字母了

是的，不过不影响使用了，后续再跟进这个光标显示位置的问题

**Comment by 13165680192** [comment]
> 不行的删除一下lock文件重新安装

ok 可以了 现在只是光标问题 不影响实际输入 点赞
