### ISSUE TITLE
如何使用CDN连接？我想在老的项目中用，没用vue/react,只是想引用一面。

### ISSUE THREAD

**Issue by itmeicn** [imzbf/md-editor-v3#475]
### Describe the issue

https://imzbf.github.io/md-editor-v3/zh-CN/demo，有个CDN链接，打开页面是空白

### Procedure version

3@4.12.1

**Comment by imzbf** [comment]
4.12好像有点问题，可以先使用4.11.3

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Global Load</title>
    <link
      href="https://unpkg.com/md-editor-v3@4.11.3/lib/style.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="md-editor-v3">
      <md-editor-v3 v-model="text" />
    </div>
    <script src="https://unpkg.com/vue@3.2.47/dist/vue.global.prod.js"></script>
    <script src="https://unpkg.com/md-editor-v3@4.11.3/lib/umd/index.js"></script>
    <script>
      const App = {
        data() {
          return {
            text: 'Hello Editor!!',
          };
        },
      };
      Vue.createApp(App).use(MdEditorV3.MdEditor).mount('#md-editor-v3');
    </script>
  </body>
</html>
```

**Comment by itmeicn** [comment]
预览版本，要引用哪些css和js呢，我弄了一晚上没成功。
  <link rel="stylesheet" href="./preview.css">
   <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js" id="md-editor-hljs"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/atom-one-dark.min.css" id="md-editor-hlCss">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js" id="md-editor-katex"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css" id="md-editor-katexCss">
        <script src="https://at.alicdn.com/t/c/font_2605852_prouiefeic.js" id="md-editor-icon"></script>
这里面没有icon图标好像。请大神帮忙

**Comment by imzbf** [comment]
不需要额外添加，组件会自己添加，像上面的示例就足够了

**Comment by imzbf** [comment]
4.12.2修复了这个问题

**Comment by itmeicn** [comment]
膜拜大神。太谢谢了。

**Comment by tiantiankexiao** [comment]
cdnjs.cloudflare 这个域名能换吗?我也是cdn方式引入的，但是加载比较慢

**Comment by imzbf** [comment]
> cdnjs.cloudflare 这个域名能换吗?我也是cdn方式引入的，但是加载比较慢

依赖安装的方式：https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20Import%20All%20Library

替换cdn的方式：https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%A5%A0%20editorExtensions

**Comment by tiantiankexiao** [comment]
![1713919235741](https://github.com/imzbf/md-editor-v3/assets/34303182/a57eadf9-8615-4287-85cc-fc4f370d9aff)

**Comment by tiantiankexiao** [comment]
![1713919235741](https://github.com/imzbf/md-editor-v3/assets/34303182/061a3129-4ef3-4e90-b670-a143db242ce1)
我是这种方式使用的，要改变域名怎么做？提前感谢大佬

**Comment by imzbf** [comment]
> ![1713919235741](https://private-user-images.githubusercontent.com/34303182/325033152-061a3129-4ef3-4e90-b670-a143db242ce1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MjAzMjIsIm5iZiI6MTcxMzkyMDAyMiwicGF0aCI6Ii8zNDMwMzE4Mi8zMjUwMzMxNTItMDYxYTMxMjktNGVmMy00ZTkwLWI2NzAtYTE0M2RiMjQyY2UxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwNTM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNWJmMjAwMzQ5ZjI2MWY5MDg3MjAyNjEzMTQ4Y2I3ZjNjZGE4ZDVmNmQ4MGU4ZmI4OWRiZGExZWVjNDQxNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okQfolpEVnPu51R1qM2VDmQpCjG5rxdS4ein1oJMnSA) 我是这种方式使用的，要改变cdnjs.cloudflare 域名怎么做？提前感谢大佬

也是调用config就可以了，有点小区别：

```js
MdEditorV3.config({
  editorExtensions: {
    mermaid: {
      js: '123'
    }
  }
});

const App = {
  data() {
    return {
      text: 'Hello Editor!!'
    };
  }
};
Vue.createApp(App).use(MdEditorV3.MdEditor).mount('#md-editor-v3');
```

**Comment by tiantiankexiao** [comment]
明白了

**Comment by kesry** [comment]
> mermaid

这种方式我在预览组件下设置，获取的是新的URL，但是，预览组件下，渲染不了
MdEditorV3.config({
      editorExtensions: {
        mermaid: {
          js: 'https://cdn.jsdelivr.net/npm/mermaid@11.3.0/dist/mermaid.min.js',
          //  instance: window.mermaid
        }
      }
    })
，这样调用后，flowchart仍然无法渲染
