### ISSUE TITLE
Any HTML properties are not reflected.

### ISSUE THREAD

**Issue by Gypsy-H-Takumi** [imzbf/md-editor-v3#476]
### Describe the issue

https://github.com/imzbf/md-editor-v3/issues/257#issuecomment-1532835563
![image](https://github.com/imzbf/md-editor-v3/assets/42290579/18b61c52-3806-44c4-8b1e-b27beb6c9e84)
![image](https://github.com/imzbf/md-editor-v3/assets/42290579/e538021a-e522-43f6-ae8c-22c0334258c0)
Similarly for classes and styles.

### Procedure version

4.12.1

**Comment by imzbf** [comment]
Disable XSS extensions or set supported properties

https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%94%8F%20Modify%20XSS%20configuration

**Comment by Gypsy-H-Takumi** [comment]
Oh, thanks!

**Comment by kuige** [comment]
> Disable XSS extensions or set supported properties
> 
> https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%94%8F%20Modify%20XSS%20configuration

@imzbf 这里可以禁用XSS扩展，只使用下面的sanitize配置吗？

<img width="493" alt="Image" src="https://github.com/user-attachments/assets/ecf73aff-0f23-436e-82cf-4dfee63cde4b" />

**Comment by imzbf** [comment]
> > Disable XSS extensions or set supported properties
> > https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%94%8F%20Modify%20XSS%20configuration
> 
> [@imzbf](https://github.com/imzbf) 这里可以禁用XSS扩展，只使用下面的sanitize配置吗？
> 
> <img alt="Image" width="493" src="https://private-user-images.githubusercontent.com/8212800/441221195-ecf73aff-0f23-436e-82cf-4dfee63cde4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY2ODMwMjIsIm5iZiI6MTc0NjY4MjcyMiwicGF0aCI6Ii84MjEyODAwLzQ0MTIyMTE5NS1lY2Y3M2FmZi0wZjIzLTQzNmUtODJjZi00ZGZlZTYzY2RlNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MDhUMDUzODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWY3MDZjYjk1MzdhMGRjNzExNDFlNmFhYThkMTBjMTg3MzZmOWVkYzkyYTI1MzZkOTdkOWI3ZjI5MGQ4N2NmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.d42oQSofAsDReLwfQUzk9SgJVBbc_IN0mQEQ1z3qDyY">

5版本开始时默认没有使用xss扩展的
