### ISSUE TITLE
预览组件对有序列表的数字bug

### ISSUE THREAD

**Issue by Roywhite** [imzbf/md-editor-v3#477]
### 描述这个Bug

预览组件在对chatgpt返回的md格式文字进行渲染时，有序列表最高只能到9，后续会归0重新计算
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/56d198fb-f0ed-4ab1-9b21-55e612dc53fb)
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/26722d83-21bb-489f-b741-56570f984a96)

### 版本号

vscode版本: 1.86.0 (user setup) Node.js: 18.17.0 浏览器：edge 121.0.2277.106 (正式版本) (64 位)

**Comment by Roywhite** [comment]
找到问题了，对li的渲染，数字其实是正常的，但是前面的数字被覆盖掉了，给li加了一个margin-left，数字就正常展示出来了
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/fb6435a0-bbe4-47c9-8ff0-1cea235b9d83)
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/083c2d64-d6e6-462a-8231-33fa65fff60a)

**Comment by imzbf** [comment]
4.12.2开始默认可以展示3位数的序号了
