### ISSUE TITLE
关于自动补全光标的位置

### ISSUE THREAD

**Issue by qiufuxing** [imzbf/md-editor-v3#478]
### 一个很棒的想法

我使用$自动补全时光标会自动在$$两个美元符号中间，这个是否是要自己通过设置光标位置来实现的
在使用公式模式时，比如我输入一个分数$\dfrac{ #1 }{ #2 }$，那么光标能否直接跑到#1位置，输入后按下tab键盘跑到#2的位置，这样就非常方便的输入公式了，不然要将光标回退到括号里面输入，另外补全的下拉框样式能否设置呢

### 一个小bug
使用行内公式时，如果这一行已经输入了一组公式，再次输入$时不会触发补全
![image](https://github.com/imzbf/md-editor-v3/assets/74224689/5e9209e5-6a85-458d-bf9a-3ec75b484cf3)
![image](https://github.com/imzbf/md-editor-v3/assets/74224689/44158336-aac3-4067-92a7-26cdbf5b3ae5)

### 另一个公式BUG
$ \alpha $，美元符号中间的公式首尾如果有空格就不渲染，没有空格才渲染，一般latex编辑器空格应该会忽略

**Comment by imzbf** [comment]
设置光标位置只能调用`insert`自行插入，内置的无法设置这个

**Comment by imzbf** [comment]
4.12.3修复了不能连续提示的问题

**Comment by imzbf** [comment]
> $$之间首尾有空格不渲染的问题是要自己处理么，这个不算bug还是之前没看到呀

这个不算BUG，设计如此哦
