### ISSUE TITLE
Hydration mismatch when used with SSR

### ISSUE THREAD

**Issue by Lenni009** [imzbf/md-editor-v3#479]
### Describe the issue

When using Server Side Rendering, or when pre-rendering pages with tools like VitePress, there is a hydration mismatch on pages that contain the markdown editor.

This is most notable with the `theme` prop, which is always light on pageload, regardless of what is actually set (when using a dynamic prop).

To reproduce:
1. Go to the reproduction URL noted below
3. If the page is not already dark mode, click on the theme toggle on the top right of the page to make it dark mode
1. Click on another link on that page, for example "community page"
2. Click the "back button" of your browser
3. See the editor being dark
4. Reload the page
5. See the editor turning white, while everything else is dark.
6. Open your browser console -> hydration mismatch error

If there is something that makes this component incompatible with SSR, it would be great to have that noted in the readme.

### Procedure version

md-editor-v3: v4.12.2; NodeJS: 20.11.0; Firefox: 124.0; Chrome: 123.0

### Reproduction link

Website: https://eisvana.github.io/about/community/create
Component Code: https://github.com/Eisvana/eisvana.github.io/blob/main/components/PlayerPageForm.vue

**Comment by Lenni009** [comment]
I can't replicate what you are describing. When I put the `div` you described into the page, it defaults to dark, because that's what my preferences are set to.

However, the MdEditor component does not seem to respect that. Here is the screenshot clearly showing the `div` having the correct theme applied, but the editor doesn't. But as I said, this is just one way you notice the SSR incompatibility, it still exists even if you remove all the props. There is always the hydration mismatch error in the console as long as you have the component in the template. The error only goes away when you completely remove the component. So this is clearly a component issue.

As I said, if you don't know what causes this error or can't fix it, it should at least be noted in the readme that the component is not SSR compatible and should be loaded on the client.

![grafik](https://github.com/imzbf/md-editor-v3/assets/91371655/a166179b-7166-45e3-a11c-793084587454)

**Comment by Lenni009** [comment]
I'll investigate further. Thanks!

**Comment by Lenni009** [comment]
But that only explains the theme issue. It doesn't explain why there's a hydration mismatch error whenever the MdEditor component is present in the template.
The error is always there, regardless of the props passed to the editor. The only way to get rid of the error is to either remove the component, or to load it on the clientside.

So this is clearly a component error.

As I said before, if you can't fix this, it should at least be noted in the readme that the component is not compatible with SSR.

Thanks!

**Comment by imzbf** [comment]
Thank you for your feedback, but the point of the example given earlier is to demonstrate that it's Vue Server-Side Rendering (SSR) which needs to address this issue, rather than it being an issue with the application component itself.
