### ISSUE TITLE
使用特殊标记时，输入中文首字母会进入到输入框，而光标会出现在首字母前面

### ISSUE THREAD

**Issue by 13165680192** [imzbf/md-editor-v3#480]
### 描述这个Bug

比如我使用标题时，输入“## 测” 实际上我的‘测’字拼音还没输完，就显示成‘## c’光标自动显示到c的前面了，

### 版本号

4.11.3以后的版本有这个问题

### 问题重现链接

将示例中的CDN 链接复制出来放在html中打开，就能重现

**Comment by 13165680192** [comment]
补充说明：通过npm安装4.11.3也会有这个问题

**Comment by imzbf** [comment]
这个之前的结论是输入法的问题，#474

**Comment by 13165680192** [comment]
切换了输入法和windows/mac依然有这样的问题，而且4.11.3和4.12.2的cdn表现也不一样

**Comment by mingchiuli** [comment]
看起来确实是一个问题

**Comment by imzbf** [comment]
在 #474 中讨论
