### ISSUE TITLE
如何以cdn的方式显示呢？preview

### ISSUE THREAD

**Issue by tiantiankexiao** [imzbf/md-editor-v3#481]
### Describe the issue

```
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <meta charset="UTF-8" />
    <title>Title</title>
    <link href="https://unpkg.com/md-editor-v3@4.11.3/lib/style.css" rel="stylesheet" />
    <link href="https://unpkg.com/md-editor-v3@4.11.3/lib/preview.css" rel="stylesheet" />
</head>
<script></script>
<body>
    <div id="md-editor-v3">
        <!-- <md-editor-v3 v-model="text" /> -->
        <!-- <MdPreview :editorId="id"  :modelValue="text"></MdPreview>  -->
        <MdPreview :editorId="id" :modelValue="text" />
        <MdCatalog :editorId="id" :scrollElement="scrollElement" />
        <!-- <MdCatalog :editorId="id" :scrollElement="scrollElement" /> -->
    </div>
    <script src="https://unpkg.com/vue@3.2.47/dist/vue.global.prod.js"></script>
    <script src="https://unpkg.com/md-editor-v3@4.11.3/lib/umd/index.js"></script>
    <script>
        const App = {
            data() {
                return {
                    id: 'preview-only',
                    text: '### Hello Editor!!aaaaaa'
                };
            }
        };
        Vue.createApp(App).use(MdEditorV3.MdEditor).mount('#md-editor-v3');
    </script>

</body>
</html>
```

### Procedure version

我这么引用了，但是不起作用

**Comment by imzbf** [comment]
```html
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
  <head>
    <meta charset="UTF-8" />
    <title>Title</title>
    <link
      href="https://unpkg.com/md-editor-v3@4.12.2/lib/preview.css"
      rel="stylesheet"
    />
  </head>
  <script></script>
  <body>
    <div id="md-editor-v3">
      <!-- <md-editor-v3 v-model="text" /> -->
      <!-- <MdPreview :editorId="id"  :modelValue="text"></MdPreview>  -->
      <md-preview :editor-id="id" :model-value="text" />
      <!-- <md-catalog :editor-id="id" :scroll-element="scrollElement" /> -->
      <!-- <MdCatalog :editorId="id" :scrollElement="scrollElement" /> -->
    </div>
    <script src="https://unpkg.com/vue@3.2.47/dist/vue.global.prod.js"></script>
    <script src="https://unpkg.com/md-editor-v3@4.12.2/lib/umd/index.js"></script>
    <script>
      const App = {
        data() {
          return {
            id: 'preview-only',
            text: '### Hello Editor!!aaaaaa',
            scrollElement: 'body',
          };
        },
      };
      Vue.createApp(App)
        .use(MdEditorV3.MdPreview)
        // .use(MdEditorV3.MdCatalog)
        .mount('#md-editor-v3');
    </script>
  </body>
</html>
```

全局模式我没有细琢磨同时渲染两个组件，如果尝试了可以同时展示目录，麻烦在这里贴一下代码

**Comment by tiantiankexiao** [comment]
感谢您的解答

**Comment by NetFlareSuperAdmin** [comment]
> ```
> <!DOCTYPE html>
> <html lang="en" xmlns:th="http://www.thymeleaf.org">
>   <head>
>     <meta charset="UTF-8" />
>     <title>Title</title>
>     <link
>       href="https://unpkg.com/md-editor-v3@4.12.2/lib/preview.css"
>       rel="stylesheet"
>     />
>   </head>
>   <script></script>
>   <body>
>     <div id="md-editor-v3">
>       
>       
>       <md-preview :editor-id="id" :model-value="text" />
>       
>       
>     </div>
>     <script src="https://unpkg.com/vue@3.2.47/dist/vue.global.prod.js"></script>
>     <script src="https://unpkg.com/md-editor-v3@4.12.2/lib/umd/index.js"></script>
>     <script>
>       const App = {
>         data() {
>           return {
>             id: 'preview-only',
>             text: '### Hello Editor!!aaaaaa',
>             scrollElement: 'body',
>           };
>         },
>       };
>       Vue.createApp(App)
>         .use(MdEditorV3.MdPreview)
>         // .use(MdEditorV3.MdCatalog)
>         .mount('#md-editor-v3');
>     </script>
>   </body>
> </html>
> ```
> 
> 全局模式我没有细琢磨同时渲染两个组件，如果尝试了可以同时展示目录，麻烦在这里贴一下代码

我也需要用 CDN 的方式在 HTML 文件中显示预览。我尝试了上面的代码，但是刷新页面后是空白的。

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/issues/481#issuecomment-2589711773

直接运行这段代码没有发现你所描述的问题 @NetFlareSuperAdmin

**Comment by NetFlareSuperAdmin** [comment]
> [#481 (comment)](https://github.com/imzbf/md-editor-v3/issues/481#issuecomment-2589711773)
> 
> 直接运行这段代码没有发现你所描述的问题 @NetFlareSuperAdmin

重试了一下，的确没问题！抱歉误报了。
