### ISSUE TITLE
无法识别回车换行

### ISSUE THREAD

**Issue by Jack-hyt** [imzbf/md-editor-v3#482]
### 描述这个Bug

文本内容，回车无法换行，需要敲两次回车才能换行。vue版本是3.2.13，组件版本是1.11.0，用了最新的版本还是不行。我看这个bug在1.7.0解决了，但是我的电脑上面还是不行

### 版本号

vue版本是3.2.13，组件版本是1.11.0

**Comment by imzbf** [comment]
你试试2的最后一个版本

**Comment by Jack-hyt** [comment]
用了md-editor-v3的2.11.2版本，还是无法换行。我后端把强行把\n替换成\n\n 暂时能用了。不过为啥要回车两次，前端md转html的时候才能识别




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 晚上11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imzbf/md-editor-v3] 无法识别回车换行 (Issue #482)





 
你试试2的最后一个版本

**Comment by imzbf** [comment]
还是还原不了你说的两个\n才能换行，像图中一样，一个可以换行，两个可以中间空行

<img width="1482" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/c24bcfed-430f-40da-8f67-255e0075a325">

**Comment by Jack-hyt** [comment]
我是解析成HTML后&nbsp; 展示在前端的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月1日(周一) 晚上6:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imzbf/md-editor-v3] 无法识别回车换行 (Issue #482)




 
还是还原不了你说的两个\n才能换行，像图中一样，一个可以换行，两个可以中间空行
 image.png (view on web)
