### ISSUE TITLE
.value?.rerender is not a function

### ISSUE THREAD

**Issue by mwz747512353** [imzbf/md-editor-v3#483]
### 描述这个Bug

一直报错这个，我想再MdPreview组件中，内容是实时加载进来的，我想实时渲染，报错.value?.rerender is not a function

### 版本号

vue3

**Comment by imzbf** [comment]
提供一下还原问题的代码

**Comment by mwz747512353** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/19990937/16699888-bbe0-42db-8a44-4a537c6e68b9)
![image](https://github.com/imzbf/md-editor-v3/assets/19990937/3a009e1a-b477-4055-8fd6-28e32b2e893b)
![image](https://github.com/imzbf/md-editor-v3/assets/19990937/5b45b1d2-b8af-4eb6-a717-ebad1b89010c)
![image](https://github.com/imzbf/md-editor-v3/assets/19990937/34f93474-4844-4317-a2a0-70df9147b59a)

**Comment by mwz747512353** [comment]
[imzbf](https://github.com/imzbf)

**Comment by imzbf** [comment]
这个实例上的方法不能再setup阶段执行

**Comment by mwz747512353** [comment]
@imzbf 您好，我看到了，已经解决了，我想请问一下，这个组件能支持数学公式吗？比如
- **A项目研发费用** = \( \frac{100}{600} \times 150 \) = 25万元

**Comment by imzbf** [comment]
> @imzbf 您好，我看到了，已经解决了，我想请问一下，这个组件能支持数学公式吗？比如
> 
> * **A项目研发费用** = ( \frac{100}{600} \times 150 ) = 25万元

看看是不是你期望的

<img width="1104" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/104bcd04-3fb2-4206-955a-2340c955eb8a">
