### ISSUE TITLE
在弹窗上使用,复制一段代码上去，点击块级代码，报错Uncaught TypeError: Cannot read properties 0f undefined (reading 'offsetTop')

### ISSUE THREAD

**Issue by shaokeke** [imzbf/md-editor-v3#484]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-v3/assets/37448773/88dd0b50-95db-4a94-976a-3dfd68c57547)
MdEditor.mjs:1340  Uncaught TypeError: Cannot read properties of undefined (reading 'offsetTop')
    at cEleHandler (MdEditor.mjs:1340:70)

### 版本号

4.12.3

**Comment by imzbf** [comment]
同步滚动的问题，不影响主功能，需要点时间重构

**Comment by imzbf** [comment]
报错的内容修复了
