### ISSUE TITLE
MdEditor粘贴内容、代码块行号样式异常

### ISSUE THREAD

**Issue by BreadWithIdeals** [imzbf/md-editor-v3#489]
## MdEditor粘贴内容异常，如果内容中有图片链接就会将粘贴结果替换为图片的url

例如：在示例 https://imzbf.github.io/md-editor-v3/en-US/index 中，将编辑区的内容复制并粘贴就会出现下面的问题
![image](https://github.com/imzbf/md-editor-v3/assets/105090544/4df37369-d566-4b7f-8b9a-15c408a22777)

## 代码块行号不对齐内容
![image](https://github.com/imzbf/md-editor-v3/assets/105090544/bdff5303-c823-4b40-af00-026603366c22)

### 版本号

vue 3.4.21
edge

**Comment by imzbf** [comment]
感谢参与，复制这个是个缺陷

对不整齐这个可能是你的项目样式影响了，你调试看看

**Comment by imzbf** [comment]
4.13.2优化了粘贴内容的问题
