### ISSUE TITLE
这样使用表情组件怎么全部显示出来？

### ISSUE THREAD

**Issue by Auroraol** [imzbf/md-editor-v3#490]
### Describe the issue

![9N5D}4EFB4836H7RQ W3GC1](https://github.com/imzbf/md-editor-v3/assets/98401567/3b8933d2-aaec-4c18-96d7-6ada96a500bd)

![222](https://github.com/imzbf/md-editor-v3/assets/98401567/870708b8-3762-42e9-aa49-2b261b36fe09)

### Procedure version

vue3  md-editor-v34.12.1

**Comment by imzbf** [comment]
有可以访问的链接或者可以运行的代码吗，这看起来是外部的css设置了hidden

**Comment by Auroraol** [comment]
> 有可以访问的链接或者可以运行的代码吗，这看起来是外部的css设置了hidden

https://codesandbox.io/p/sandbox/md-editor-v3-forked-plkfpr?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clti8ogcv00063j6fyatlri6t%2522%252C%2522sizes%2522%253A%255Bnull%252Cnull%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clti8ogcv00023j6fyorwbsly%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clti8ogcv00033j6fmkvx1qce%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clti8ogcv00053j6f2dimci94%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B49.46068803844553%252C50.53931196155447%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clti8ogcv00023j6fyorwbsly%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti8ogcu00013j6fozenxc53%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clv5bfx7k00513j6fub24j8t4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clti8ogcv00023j6fyorwbsly%2522%252C%2522activeTabId%2522%253A%2522clv5bfx7k00513j6fub24j8t4%2522%257D%252C%2522clti8ogcv00053j6f2dimci94%2522%253A%257B%2522id%2522%253A%2522clti8ogcv00053j6f2dimci94%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clti8ogcv00043j6fqfxs8atc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clti8ogcv00043j6fqfxs8atc%2522%257D%252C%2522clti8ogcv00033j6fmkvx1qce%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clti8ogcv00033j6fmkvx1qce%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by imzbf** [comment]
4.13.3中修复了它
