### ISSUE TITLE
【BUG】公式显示错误

### ISSUE THREAD

**Issue by 1014156094** [imzbf/md-editor-v3#491]
### 描述这个Bug
【BUG】图片内的第一种公式显示有问题
![image](https://github.com/imzbf/md-editor-v3/assets/16074662/d436b93e-c359-4bb2-8567-c82e98754274)

### 版本号

4.13.1

**Comment by imzbf** [comment]
不支持这种标识，如果需要参考：https://github.com/imzbf/md-editor-v3/discussions/487#discussioncomment-9115768
