### ISSUE TITLE
禁用html格式渲染后，如何正确渲染下角标与上角标？

### ISSUE THREAD

**Issue by Seven-7i** [imzbf/md-editor-v3#492]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/67766979/dafc9969-1382-423f-ac00-683d5d70139b)
![image](https://github.com/imzbf/md-editor-v3/assets/67766979/5e614d21-de2b-43f8-8c46-83def33627ae)
目前有需求是禁止渲染用户自己输入的html，以普通字符串渲染。但当我禁用之后由于这个角标规则是渲染html来实现的，所以如何能办到使用markdown-it本身自己的角标渲染规则。

### Procedure version

"md-editor-v3": "4.13.1"

**Comment by Seven-7i** [comment]
找到原因了，markdown核心库没带这个功能，需要自己安装 markdown-it-sub markdown-it-sup。
![image](https://github.com/imzbf/md-editor-v3/assets/67766979/978d7e21-0ded-42a6-84cf-c63903458297)

那么原来的下角标与上角标就要重写了吧？
![image](https://github.com/imzbf/md-editor-v3/assets/67766979/febd8aef-c71c-4246-a6bd-82af22d6bdf3)

**Comment by imzbf** [comment]
用外部扩展，https://www.npmjs.com/package/markdown-it-sub

添加到编辑器：https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%8D%A4%20markdownItPlugins

**Comment by Seven-7i** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/67766979/a6b5f46c-8693-4273-94d8-7a4ce1e42ff0)
![image](https://github.com/imzbf/md-editor-v3/assets/67766979/d7f60a7f-591e-4eb1-8acb-8c60be672b06)
![image](https://github.com/imzbf/md-editor-v3/assets/67766979/245efc48-f9cf-45ff-b6f1-1a0898cf0d2f)
大佬，是不是无论怎么样 编辑器原先的两个角标按钮都要去掉，自己重写

**Comment by imzbf** [comment]
是的，只有隐藏它两，然后自行扩展

**Comment by Seven-7i** [comment]
好的，感谢
