### ISSUE TITLE
获取当前选中的值在自定义工具栏中如何使用？

### ISSUE THREAD

**Issue by Roaming-l** [imzbf/md-editor-v3#494]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/63138633/0bf5a181-137e-4c99-b6ba-45b2ea33e30c)
需要选中这个段文字以后，点击自定义工具栏中的某个功能，将这部分选中的数据待入过去，但是目前 无法实现在工具栏中获取，使用的是
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/a00b7bca-1b02-49db-b9e7-86441bf1bb49)
请问有什么好方法可以将数据带过去吗  console.log(editorRef.value?.getSelectedText());  自定义工具栏中这样获取不到数据，

### Procedure version

1

**Comment by imzbf** [comment]
`getSelectedText`不能获取到值能给个重现的案例吗，我尝试了下还原不了你说的问题
<img width="861" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/7f9c5820-8fc4-44c7-af78-1ead8bfd395c">

**Comment by Roaming-l** [comment]
请问你这种写法是咋样的呢，我是把扩展栏这样挂的 
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/d1d2d399-ad4c-426d-a5e7-b27e404e20d0)
  你这种写法能看下吗，是如何在扩展页面中通过按钮调用本页面的选中内容的？

**Comment by imzbf** [comment]
给扩展加一个父子组件交互，像这样

```
<Extension :getSelectedText="getSelectedText" />

const getSelectedText = () => editorRef.editorRef.value?.getSelectedText();
```

**Comment by tianci-8** [comment]
> 给扩展加一个父子组件交互，像这样
> 
> ```
> <Extension :getSelectedText="getSelectedText" />
> 
> const getSelectedText = () => editorRef.editorRef.value?.getSelectedText();
> ```

editorRef有两个，是打错了嘛（嗯？）

**Comment by Roaming-l** [comment]
我按照您说的方法，
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/c2029b16-6f3b-41a5-baaf-0ac80c9b3393)
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/372f18b8-071c-4e79-a943-58f1c4163ab2)
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/db270459-ebde-49e3-b00c-a929b1a7730c)
在props中该如何定义呢？我试着定义成string,
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/7a85c2aa-de48-4b3b-a562-5049f5fc8136)
可是控制台告诉我他是个function,于是用function接收后 控制台打印出来了
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/b2f66687-5b98-44cb-be5e-9b0eb70a580b)
并没有返回我选中的数据，请问哪里有写错吗

**Comment by imzbf** [comment]
方法需要执行，你只是打印了你这个方法，还有你不应该在created阶段打印

**Comment by Roaming-l** [comment]
谢谢，已经解决了
