### ISSUE TITLE
地址跳转到某一个标题处，如何跳转？

### ISSUE THREAD

**Issue by itmeicn** [imzbf/md-editor-v3#495]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-v3/assets/31679124/92c36653-7080-4b44-bb9b-60c721650b48)
如上，我的地址http://www.itmei.cn/u/index.html#/priviewArticle?id=378 是想跳转到 ‘objectName()获取对象的值’此处，地址要如何写呢

### 版本号

4.13.3

**Comment by imzbf** [comment]
手动去处理，像文档里这样：https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/layouts/Catalog/index.vue#L39
