### ISSUE TITLE
link 链接打开扩展疑问？

### ISSUE THREAD

**Issue by iiuhuy** [imzbf/md-editor-v3#496]
### 一个疑问

背景：我想在 markdown 渲染链接的时候生成的 a 标签加上 `target="_blank"` 属性，但文档中没发现有相关的配置。

翻了一下源码，发现作者原来是有处理的 `TargetBlankExtension.js`，不过注释掉了？想请教下这里注释掉的背景原因是什么
- [TargetBlankExtension.js](https://github.com/imzbf/md-editor-v3/blob/develop/dev/Preview/image/TargetBlankExtension.js#L8-L20)

**Comment by imzbf** [comment]
像这样：https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/main.ts#L29
