### ISSUE TITLE
预览区域

### ISSUE THREAD

**Issue by aehyok** [imzbf/md-editor-v3#497]
### 一个很棒的想法

能否添加一个跟编辑区域一样的placeholder

**Comment by imzbf** [comment]
这个好像没有什么意义？实在想也可以逻辑上实现，判断你的`v-model`是不是空，是的话就给它一个暗色调的标签内容

**Comment by aehyok** [comment]
@imzbf  看着空空的，  好的，你说的方法应该可以 我试试

**Comment by aehyok** [comment]
有个问题，我把v-model 设置好了，编辑区域的placeholder 就不生效了，左侧区域就相当于有编辑文字了
