### ISSUE TITLE
支持类似论文中的参考文献引用？

### ISSUE THREAD

**Issue by hiifong** [imzbf/md-editor-v3#498]
### Describe the issue

```markdown
它的原型基于 [LoveIt 主题](https://github.com/dillonzq/LoveIt)，[KeepIt 主题](https://github.com/Fastbyte01/KeepIt) 和 [LeaveIt 主题](https://github.com/liuzc/LeaveIt)。[^1]


[^1]: 主题名称趣谈：“leave it, keep it，love it，fix it”。出现又离开，爱而不得。这像不像那该死的爱情和 BUG 呢？🤣
```
![image](https://github.com/imzbf/md-editor-v3/assets/89133723/04f457ef-9afe-4d56-9cb9-a099fb9ce7d1)
![image](https://github.com/imzbf/md-editor-v3/assets/89133723/3b9140b2-96ae-445e-84be-fdcfbfd56c6f)

[Fixit](https://github.com/hugo-fixit/FixIt)

### Procedure version

Chrome 24.0.6367.63，md-editor-v3 4.13.0

### Reproduction link

https://imzbf.github.io/md-editor-v3/en-US/index

**Comment by imzbf** [comment]
这个扩展可以实现你的功能：https://github.com/markdown-it/markdown-it-footnote

**Comment by hiifong** [comment]
> 这个扩展可以实现你的功能：https://github.com/markdown-it/markdown-it-footnote

作者你好，请问预览组件什么使用拓展，我没有看到相关文档。

**Comment by hiifong** [comment]
> > 这个扩展可以实现你的功能：https://github.com/markdown-it/markdown-it-footnote
> 
> 作者你好，请问预览组件怎么使用拓展，我没有看到相关文档。

已解决，谢谢
