### ISSUE TITLE
ModalToolbar中使用vue-element-ui组件 比如 el-select 由于ModalToolbar的z-index导致 select选项渲染不出来或者被覆盖

### ISSUE THREAD

**Issue by Roaming-l** [imzbf/md-editor-v3#499]
### Describe the issue

ModalToolbar中使用vue-element-ui组件 比如 el-select 由于ModalToolbar的z-index导致 select选项渲染不出来或者被覆盖
![image](https://github.com/imzbf/md-editor-v3/assets/63138633/16ad016f-f0de-4d72-8301-e2fc64f65411)

### Procedure version

1

**Comment by imzbf** [comment]
element支持调整它的zIndex，https://element-plus.org/zh-CN/component/config-provider.html#config-provider-attributes

**Comment by Roaming-l** [comment]
另外请问，扩展的组件再配置文件中按照123走  这个怎么知道1是哪个组件或者2是哪个呢，，是根据什么条件去渲染的？

**Comment by Roaming-l** [comment]
props.insert(() => {
        return {
          targetValue: `${question}
${e.data} `,
          select: false,
          deviationStart: 0,
          deviationEnd: 0,
        };
      });  这个可以实现打字机那种效果吗  对于返回的数据 像打字机一样渲染上去

**Comment by Roaming-l** [comment]
还有个  我在获取了当前选中的文字后  进行了一个操作，比如说翻译，我想将翻译的结果直接替换成选中的文字，有对应的方法可以走 清空选中文字吗

**Comment by imzbf** [comment]
> props.insert(() => { return { targetValue: `${question} ${e.data} `, select: false, deviationStart: 0, deviationEnd: 0, }; }); 这个可以实现打字机那种效果吗 对于返回的数据 像打字机一样渲染上去

这个不会内置哈，更建议外部实现，可能和你的方案一致，延迟调用`insert`插入每个字符

**Comment by Roaming-l** [comment]
好的，谢谢
