### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by kuailemao** [imzbf/md-editor-v3#500]
### Describe the issue

4.10.0更新到4.13.5报错，请问是为什么
![image](https://github.com/imzbf/md-editor-v3/assets/88065987/1bbf39a3-0194-4e46-8287-b14b754b5b1b)

### Procedure version

4.13.5

**Comment by imzbf** [comment]
移除你的lock文件重新安装，或者先卸载再安装

**Comment by kuailemao** [comment]
好的，感谢！
