### ISSUE TITLE
使用script标签从cdn加载脚本的时候添加integrity校验

### ISSUE THREAD

**Issue by kuige** [imzbf/md-editor-v3#502]
### 一个很棒的想法

现在从cdn加载katex, highlight.js之类的脚本的时候没有设置integrity属性：

`<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js" id="md-editor-hljs"></script>`

希望可以增加integrity属性校验，防止cdn内容被篡改

**Comment by imzbf** [comment]
这种情况可能更建议采用依赖安装的方式，因为链接设计成的是可以自由替换

**Comment by kuige** [comment]
一般没特殊需求不会替换链接，直击使用默认的，这种情况下希望可以添加integrity验证，因为之前也出现过cdn投毒的情况了

**Comment by kuige** [comment]
> 这种情况可能更建议采用依赖安装的方式，因为链接设计成的是可以自由替换

另外替换链接不是这样配置吗？
```
config({
  editorExtensions: {
    katex: {
      js: '/static/katex.min.js',
      css: '/static/katex.min.css',
    },
  },
})
```

依赖安装的方式怎么配置呢？

**Comment by imzbf** [comment]
> 一般没特殊需求不会替换链接，直击使用默认的，这种情况下希望可以添加integrity验证，因为之前也出现过cdn投毒的情况了

我尝试下能否通过config自定义更多的属性来达到这个目的

**Comment by imzbf** [comment]
> > 这种情况可能更建议采用依赖安装的方式，因为链接设计成的是可以自由替换
> 
> 另外替换链接不是这样配置吗？
> 
> ```
> config({
>   editorExtensions: {
>     katex: {
>       js: '/static/katex.min.js',
>       css: '/static/katex.min.css',
>     },
>   },
> })
> ```
> 
> 依赖安装的方式怎么配置呢？

参考这个
https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93

**Comment by imzbf** [comment]
在4.14.0增加了这项功能，但是不是内置的，不过提供了内置的属性值，[参考](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%A5%A0%20editorExtensionsAttrs)使用

**Comment by kuige** [comment]
> 在4.14.0增加了这项功能，但是不是内置的，不过提供了内置的属性值，[参考](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%A5%A0%20editorExtensionsAttrs)使用

更新到了最新版本4.14.1，默认的cdn链接没有加上integrity校验吗？

<img width="637" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/8212800/05e926e3-2264-4965-a448-a70e3b4bf38e">
<br /><br />
只能自己通过config配置的时候才可以指定？

**Comment by imzbf** [comment]
是的，默认是不会加，可以自由修改链接，需要对所有的判断逻辑再加一层ifelse，不是很有必要

**Comment by famousprince** [comment]
cdnjs 官网提供 sri hash，不考虑国内加载速度的话是最推荐的，像 BootCDN 有过投毒前科的就算上 integrity 也不建议再用了

个人感觉比较好用的 CdnBase 有 `https://mirrors.sustech.edu.cn/cdnjs/ajax/libs`和`https://s4.zstatic.net/ajax/libs`

**Comment by kuige** [comment]
```
config({
  editorExtensionsAttrs: {
    katex: {
      js: {
        integrity: 'sha384-111',
        crossOrigin: 'anonymous',
      },
      css: {
        integrity: 'sha384-111',
        crossOrigin: 'anonymous',
      },
    },
  },
});
```

@imzbf 这个配置不起作用，highlight和其他是正常的

**Comment by kuige** [comment]
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/e1368e72-0cee-45f5-9c46-a0f60366ee98">

另外mermaid会加载两个脚本，应该如何配置呢？

```
mermaid: {
      // mermaid.esm.min.mjs
      js: {
        integrity:
          'sha384-zmipzuFBFDAekHS2uY4mN5cvpcSvgUi3aMjMJ2xnVRsU2kDHBtqLOJRnianHJeP1',
        crossOrigin: 'anonymous',
      },
    },
```
这个只是配置mermaid.esm.min.mjs的，还差另一个文件mermaid-d06ecb0d.js的配置

<img width="364" alt="image" src="https://github.com/user-attachments/assets/0548d17c-808f-4cdf-9b9a-911cc72dec3f">

mermaid.esm.min.mjs的内容只是从另一个文件导出内容，可以改为只加载mermaid-d06ecb0d.js吗？这样就只有一个文件了，方便配置

**Comment by imzbf** [comment]
它的其他块很多，没有办法一个个的设置这个属性，建议npm安装它然后导入
