### ISSUE TITLE
MdPreview组件，英文单词换行在移动端Google浏览器不生效

### ISSUE THREAD

**Issue by AudreyHepbur** [imzbf/md-editor-v3#503]
### Describe the issue

MdPreview组件，英文单词换行在移动端Google浏览器不生效，PC端目前都是正常的

import { MdPreview } from 'md-editor-v3';
import 'md-editor-v3/lib/preview.css';
`
<MdPreview
      :editor-id="id"
      :model-value="props.text"
      :no-img-zoom-in="true"
      preview-theme="smart-blue"
      code-theme="github"
 />
`

### Procedure version

版本: "md-editor-v3": "^4.11.2",

**Comment by imzbf** [comment]
![Screenshot_2024-05-07-21-11-39-629_com android chrome](https://github.com/imzbf/md-editor-v3/assets/37092006/bd7caf16-ee27-44ac-98c6-d21f10ed72cd)

如果是这样的话，它应该就是这样的
