### ISSUE TITLE
在el-dialog弹出框里面，MdCatalog 的scrollElement不生效，没办法动态选中目录？怎么解决

### ISSUE THREAD

**Issue by yuxintao6** [imzbf/md-editor-v3#504]
### 一个很棒的想法

在弹出框里面，MdCatalog 的scrollElement不生效，没办法动态选中目录？怎么解决

**Comment by imzbf** [comment]
找不到滚动元素时，设定一个自己的滚动标签，让内容在这个标签滚动

**Comment by imzbf** [comment]
这可能和4.13.5版本的BUG有关，https://github.com/imzbf/md-editor-v3/commit/5ccf28dadb6642babc267e87894be0b719d3aed2 你也可以尝试一下目前的beta版本
