### ISSUE TITLE
是不是可以支持配置 cdn 地址

### ISSUE THREAD

**Issue by guangmingcunliutao** [imzbf/md-editor-v3#514]
### 一个很棒的想法

1. 内部插件用到cdn的地方较多
2. 是否可以直接禁用拓展的情况下，不再加载拓展的资源，比如prettier
3. 对于内容的情况，是不是可以直接直接修改 cdnBase ，看源码是有个基础的 cdnBase 变量的

**Comment by imzbf** [comment]
有对应的控制属性，比如禁用`prettier`对应的是`noPrettier`，每个cdn库都对应一个控制属性

不会提供修改cdnBase的方式，每一个cdn供应站的路径可能不同，所以提供的是修改链接的基础方式

**Comment by guangmingcunliutao** [comment]
> 有对应的控制属性，比如禁用`prettier`对应的是`noPrettier`，每个cdn库都对应一个控制属性
> 
> 不会提供修改cdnBase的方式，每一个cdn供应站的路径可能不同，所以提供的是修改链接的基础方式

好的，麻烦了，那您关了把
