### ISSUE TITLE
如果我想在预览的img标签下添加 referrerpolicy="no-referrer"   的代码，我应该如何调整呢？

### ISSUE THREAD

**Issue by beiming-org** [imzbf/md-editor-v3#516]
### Describe the issue

<img src="xxxx" alt="图片" class="md-zoom medium-zoom-image" referrerpolicy="no-referrer">

### Procedure version

1

### Reproduction link

1

**Comment by imzbf** [comment]
参考这个：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%94%8F%20%E4%BF%AE%E6%94%B9%20xss%20%E9%85%8D%E7%BD%AE

**Comment by ToWaitForTheWind** [comment]
> 参考这个：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%94%8F%20%E4%BF%AE%E6%94%B9%20xss%20%E9%85%8D%E7%BD%AE

你好，链接打开的地址在最新文档里面已经查看不到了，能发一下最新的吗

**Comment by ToWaitForTheWind** [comment]
> > 参考这个：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%94%8F%20%E4%BF%AE%E6%94%B9%20xss%20%E9%85%8D%E7%BD%AE
> 
> 你好，链接打开的地址在最新文档里面已经查看不到了，能发一下最新的吗

更改了一种实现方式，通过sanitize方法正则匹配替换字符串实现了
