### ISSUE TITLE
编辑器内嵌html属性丢失

### ISSUE THREAD

**Issue by JacobSuCHN** [imzbf/md-editor-v3#517]
### Describe the issue

- 我在编辑器里输入如
  - `<div style="width: 200px;height: 200px;background-color: cadetblue;color: #fff;">123</div>`style属性不生效
- 请问这是我选择的主题有问题，还是编辑器默认去除了
- 请问有解决办法吗

### Procedure version

"md-editor-v3": "^4.13.5",

**Comment by imzbf** [comment]
参考：https://github.com/imzbf/md-editor-v3/issues/476#issuecomment-2005686961

**Comment by JacobSuCHN** [comment]
> 参考：[#476 (comment)](https://github.com/imzbf/md-editor-v3/issues/476#issuecomment-2005686961)

ok
