### ISSUE TITLE
MdCatalog目录高亮

### ISSUE THREAD

**Issue by nuomi486** [imzbf/md-editor-v3#520]
### Describe the issue

佬，你好，
我这里拿的是element的滚动条，点击可以到该行，但是一直是亮着的第一个目录
![image](https://github.com/imzbf/md-editor-v3/assets/43416971/aef159e2-7472-44d0-9312-7eff29bdb91f)
比如这里我点了目录的Diagram，他也定位到那个位置了，但是就是目录没高亮
![image](https://github.com/imzbf/md-editor-v3/assets/43416971/859c52bf-0346-47f6-ac04-dcee6d348a3e)

该怎么解决呢？

```vue
 <div style="display: flex">
        <MdCatalog :editorId="state.id"
                   :onClick="toTarget"
                   :scrollElement="scrollElement"
                   :theme="state.theme"
                   :scrollElementOffsetTop="55" :offsetTop="10"
        />
        <el-scrollbar height="85vh">
          <MdPreview style="z-index: 1;"
                     :modelValue="state.text"
                     :editorId="state.id"
                     :theme="state.theme"
                     codeTheme="github"/>
        </el-scrollbar>
      </div>

scrollElement.value = document.querySelector(".el-scrollbar__wrap");
```

### Procedure version

4.13.0 md-editor-v3

### Reproduction link

https://github.com/nuomi486/MyBlog/

_No response_

**Comment by imzbf** [comment]
直接给scrollElement赋值，不要二次赋值，它不是响应式的

**Comment by nuomi486** [comment]
> 直接给scrollElement赋值，不要二次赋值，它不是响应式的

直接赋值的话就没反应了。因为我这个是全局没有滚动条的，然后才使用的element的滚动

**Comment by nuomi486** [comment]
> 直接给scrollElement赋值，不要二次赋值，它不是响应式的

直接把document.querySelector(".el-scrollbar__wrap");给他是null值

**Comment by nuomi486** [comment]
> 直接给scrollElement赋值，不要二次赋值，它不是响应式的

已经放进仓库了，帮我康康呗

**Comment by imzbf** [comment]
```js
const scrollElement = ref('.el-scrollbar__wrap')
```

**Comment by imzbf** [comment]
这样

**Comment by nuomi486** [comment]
> ```js
> .el-scrollbar__wrap
> ```

谢谢佬！
