### ISSUE TITLE
仅预览模式下，图片无法预览

### ISSUE THREAD

**Issue by tianchaoyang** [imzbf/md-editor-v3#522]
### 描述这个Bug

编辑器初始化第一次图片可以点击预览大图，再刷新页面都不能预览图片

### 版本号

node: 20.5.0

**Comment by imzbf** [comment]
这是很久以前的问题了，你更新编辑器了吗

更新了还存在问题的话提供一下源码，最好能给完整还原问题的项目

**Comment by tianchaoyang** [comment]
环境信息：MacOs Sonoma 14.3.1
浏览器版本：Chrome 124.0.6367.93
node版本：20.5.0
vue版本：3.4.19
vite版本：5.1.4
md-editor-v3版本：4.14.1

https://codesandbox.io/p/devbox/github/codesandbox/sandbox-templates/tree/main/vue-vite?file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw5pfy3y00073b6jm1b8dd8f%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw5pfy3x00023b6j4dwpodfc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw5pfy3x00043b6jndr2ijmb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw5pfy3y00063b6je6lw3zhk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw5pfy3x00023b6j4dwpodfc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw5pfy3x00013b6jthlykotx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clw5pho3f006v3b6jo9qf5c1i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clw5pfy3x00023b6j4dwpodfc%2522%252C%2522activeTabId%2522%253A%2522clw5pho3f006v3b6jo9qf5c1i%2522%257D%252C%2522clw5pfy3y00063b6je6lw3zhk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw5pfy3y00053b6jtg76cd52%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw5pfy3y00063b6je6lw3zhk%2522%252C%2522activeTabId%2522%253A%2522clw5pfy3y00053b6jtg76cd52%2522%257D%252C%2522clw5pfy3x00043b6jndr2ijmb%2522%253A%257B%2522id%2522%253A%2522clw5pfy3x00043b6jndr2ijmb%2522%252C%2522activeTabId%2522%253A%2522clw5pfy3x00033b6j5j42ih65%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw5pfy3x00033b6j5j42ih65%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clw5pndsi00n63b6jhp75dqpn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clw5pndzh000adchud4nkbq8w%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D


请问是我哪里的写法不对吗？

**Comment by tianchaoyang** [comment]
<img width="682" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37856785/1e5293cb-ec8e-47dd-b549-90d13b718742">
<img width="839" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37856785/1532c987-44b9-48f3-8446-9635109c7786">

我检查了图片放大这块的代码，发现每次在页面刷新后watch会在onMounted之前触发，zoomHandle就是空函数。

在onMounted中调用一次zoomHandle能解决我的问题

**Comment by imzbf** [comment]
内部的问题，预设modalValue需要在挂载的时候执行一次，调整了，先使用beta版本，后面会发布到正式版中

```
npm i md-editor-v3@beta
```

**Comment by tianchaoyang** [comment]
> 内部的问题，预设modalValue需要在挂载的时候执行一次，调整了，先使用beta版本，后面会发布到正式版中
> 
> ```
> npm i md-editor-v3@beta
> ```

ok，感谢

**Comment by imzbf** [comment]
正式版本已更新
