### ISSUE TITLE
我添加的超链接如果在渲染的是点击打开新页面

### ISSUE THREAD

**Issue by zwkmdj** [imzbf/md-editor-v3#523]
### Describe the issue

如我在md编辑器中添加了超链接，[百度](http://www.baidu.com)。 再预览的时候我想渲染为<a href="http://www.baidu.com" **target="blank"**>百度</a>. 目前的超链接中没有target="blank， 我怎么加上的

### Procedure version

v18.16.0

**Comment by imzbf** [comment]
参考：https://github.com/imzbf/md-editor-v3/issues/496#issuecomment-2076109854
