### ISSUE TITLE
添加 markdown 扩展语法

### ISSUE THREAD

**Issue by wanna-diary** [imzbf/md-editor-v3#525]
### 一个很棒的想法

能不能加一个 Typora 中的高亮语法：
==高亮==
![image](https://github.com/imzbf/md-editor-v3/assets/68955959/4cb612ab-81ed-43e7-b66a-5f81eb9cf492)

**Comment by imzbf** [comment]
用这个：https://github.com/imzbf/md-editor-extension/tree/develop/packages/v3/components/Mark
