### ISSUE TITLE
关于toolstab展示问题

### ISSUE THREAD

**Issue by nuomi486** [imzbf/md-editor-v3#530]
### Describe the issue

按理来说他的展示应该是像首页一样，鼠标停在上方的时候会弹出来一个下拉框
![image](https://github.com/imzbf/md-editor-v3/assets/43416971/d1b31fb3-1362-4d88-bd41-a86e7bbd48fb)
但是我鼠标移到图标时候下拉框并没有显示出来
![image](https://github.com/imzbf/md-editor-v3/assets/43416971/cb4d199c-e1ea-4e47-96ef-d79d96064b16)
当我把他的.md-editor-toolbar-wrapper加一个高度的时候就在里面显示了
![image](https://github.com/imzbf/md-editor-v3/assets/43416971/1a1a1fb6-3051-477b-86e4-f35895acaf43)

这是什么情况？？
<MdEditor v-model="formInline.date"  @onUploadImg="onUploadImg"/>

<style scoped lang="less">
.md-editor{
  z-index: 1;
  .md-editor-toolbar-wrapper{
    z-index: 1;
  }
}
</style>

这么设置也没效果

### Procedure version

4.13.0 md-editor-v3

**Comment by imzbf** [comment]
.md-editor-toolbar-wrapper不能给它定位，因为工具栏是设置了overflow隐藏的，而下拉框又是需要超出展示的，所以它的相对原生需要是编辑器最外层元素

**Comment by imzbf** [comment]
方案1，取消你的全局定位方案

方案2，手动设置内部元素定位（隐藏的问题，可能后续其他功能也使用类似的机制，所以建议采用方案一）

```css
.md-editor-toolbar-wrapper {
    position: initial;
}
```
