### ISSUE TITLE
目录的位置

### ISSUE THREAD

**Issue by ss-sola** [imzbf/md-editor-v3#531]
### 一个很棒的想法

能不能搞个目录渲染到指定位置的功能

**Comment by imzbf** [comment]
有导出目录组件

**Comment by ss-sola** [comment]
我找到了，scrollElement要绑定MdPreview。那为什么不耦合在一起，毕竟editorId是相同的。
你的文档似乎有部分代码并不能显示
![image](https://github.com/imzbf/md-editor-v3/assets/102914742/0da8a2cb-efbb-4d04-9749-640d20b0de6e)

**Comment by imzbf** [comment]
你把目录拿出来用，它的editorId是不知道的

那是收起的代码，点击它就可以展开了
