### ISSUE TITLE
能否实现支持粘贴markdown内容进来?

### ISSUE THREAD

**Issue by kingwrcy** [imzbf/md-editor-v3#532]
### A great idea

能否实现支持粘贴markdown内容进来?
还有自动识别url,比如我输入一个网址,自动就转为markdown的链接.title和href都是url.

**Comment by imzbf** [comment]
> 能否实现支持粘贴markdown内容进来?

这是什么意思？

自行转换url这边找时间尝试看看，可能会与github的方案对齐

**Comment by kingwrcy** [comment]
就是现在把页面上的元素复制进来只有原始文本,没有带上应该有的格式.

有点类似html -> md 的转换过程,比如我复制了一个链接,粘贴进来应该是是md的格式,而并不是原始的链接.

**Comment by imzbf** [comment]
反着来的目前没有足够的时间去处理这个，暂时不会投入
