### ISSUE TITLE
4.5.1修改了 将linkify的默认值设置为true 之后 正常的markdown链接无法正常展示了

### ISSUE THREAD

**Issue by kingwrcy** [imzbf/md-editor-v3#535]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-v3/assets/1247324/6e1b9a56-21e7-42b8-b5f4-c2da66a9671e)

参见上图,不知道跟`将linkify的默认值设置为true`是否有关系?

### 版本号

^4.15.2

**Comment by imzbf** [comment]
这个是正常的吧，你写反了，小括号里面才是链接

**Comment by kingwrcy** [comment]
... 确实写反了...
