### ISSUE TITLE
自定义emoji如何实现选完emoji后关掉弹出框?

### ISSUE THREAD

**Issue by kingwrcy** [imzbf/md-editor-v3#536]
### Describe the issue

[在线demo](https://stackblitz.com/edit/vitejs-vite-jcnxvx?file=src%2Fcomponents%2FEmoji.vue)

自定义emoji如何实现选完emoji后关掉弹出框?
我加了一行
```
state.visibile = false
```
确实隐藏了,但是鼠标在附近晃一下,那个弹出窗口又会出来.

另外这个trigger方式如何改成点击才触发?现在是hover.

### Procedure version

"md-editor-v3": "^4.15.4"

**Comment by imzbf** [comment]
onChange使用组件提供的状态就可以了

```
const onChange = (visibile) => {
  state.visibile = visibile;
};
```

目前没有点击触发的方案，之前好像实现下拉框出现了点麻烦，给移除从简了

**Comment by imzbf** [comment]
> state.visibile = false

这一行要留着

**Comment by kingwrcy** [comment]
神奇,就这么好了,感谢了.
