### ISSUE TITLE
关闭 htmlPreview 失效

### ISSUE THREAD

**Issue by QianShi-ffg** [imzbf/md-editor-v3#537]
### 描述这个Bug

 默认开启,无法关闭 htmlPreview与Preview  并且样式为flex: 1
![image](https://github.com/imzbf/md-editor-v3/assets/56419687/d65ce834-eeda-4e7b-b1c0-493303f5379a)

### 版本号

4.15.4

**Comment by imzbf** [comment]
尝试卸载了重新安装，如果还是不行，提供一下可还原问题的可运行的最小项目
