### ISSUE TITLE
4.15.1标签结构发生了变化

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#539]
### 预览模式

之前内容的标签里，存在一个`data-line`属性，现在升级4.15.1以后这个属性没了
我有一些功能依赖这个属性，现在升级就用不了了
评估下这个属性是不是必须删除，能否兼容下
现在标签长这个样子，属性信息有点不够用（我代码去兼容加一个ID也可行，但4.15.0到4.15.1这个改动是破坏性的，正常开发开源项目不应该这么搞），目前这个id不是页面唯一的，因为标题可能重复。
<img width="836" alt="Screenshot 2024-05-25 at 02 36 57" src="https://github.com/imzbf/md-editor-v3/assets/80095372/cfae845b-95f1-47c8-b434-f542b331b130">

原来是这样的
<img width="836" alt="Screenshot 2024-05-25 at 03 12 43" src="https://github.com/imzbf/md-editor-v3/assets/80095372/fb0d415a-2c8c-4681-b94b-b02c5c1ee820">

产生这个问题的应该是这次提交https://github.com/imzbf/md-editor-v3/commit/30a54dd2f35e08d17a98261061495b3b1a509c34

### Procedure version

4.15.1

**Comment by imzbf** [comment]
我在4.15.5中回调了这个设定，预览组件恢复设定`data-line`属性
