### ISSUE TITLE
编辑器样式错位，比如光标移到图片表格控件时。

### ISSUE THREAD

**Issue by lightsaid** [imzbf/md-editor-v3#540]
### Describe the issue

系统Mac，浏览器Chrome和Firefox
<img width="806" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/26699445/2860b7cd-31b0-4408-a5a3-1d8cadb29e89">
<img width="619" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/26699445/ee8fa626-f4c3-4f55-baec-af4fa474554a">

相关代码
```vue
<template>
  <div>
    <MdEditor v-model="text" />
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { MdEditor } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const text = ref('Hello Editor!');
</script>
```

### Procedure version

4.15.6

**Comment by imzbf** [comment]
示例还原不了这个问题，在https://codesandbox.io/ 上面尝试还原下你的问题

**Comment by lightsaid** [comment]
> 示例还原不了这个问题，在https://codesandbox.io/ 上面尝试还原下你的问题

不知道为啥，重启vscode就好了。

**Comment by imzbf** [comment]
OK，这个问题关闭了
