### ISSUE TITLE
Misleading documentation leads to XSS vulnerabilities

### ISSUE THREAD

**Issue by mspi21** [imzbf/md-editor-v3#541]
### Describe the issue

The readme, and by extension the documentation for the `sanitize` prop, states that:
> After 3.x, dangerous code has been processed by default. Please do not use this attribute unless there are special requirements

But this is simply not true. As stated in #453, the latest XSS vulnerability (an **extremely straightforward and common case** of it, using an `img` tag with the `onerror` attribute) was only fixed in 4.11.3. The documentation is the primary resource for users of the library. If it wrongly states that the library is safe by default, developers will use it that way and introduce vulnerabilities into their applications&mdash;vulnerabilities which the library will be directly responsible for.

On another note, why do you explicitly discourage users from employing XSS protection mechanisms, when those shipped by the library are not much more than an afterthought?

I suggest that you update the documentation for the `sanitize` prop to the following:
> Apply a custom function to sanitize the html to prevent XSS. After **4.11.3**, dangerous code has been processed by default.

I also think it highly appropriate for the readme/documentation to show a warning banner **at the top**, warning users about vulnerable versions, like the following:

> [!CAUTION]
> Versions of this library before 4.11.3 are vulnerable to a straightforward case of cross-site scripting (XSS) attacks. Make sure to use the latest version, or use the `sanitize` prop with a 3rd party library such as `sanitize-html`.

### Procedure version

\*

**Comment by imzbf** [comment]
Yes, I will correct this information in the docs

**Comment by imzbf** [comment]
The documentation has been updated

**Comment by mspi21** [comment]
I'm not convinced that not mentioning XSS as a possible security risk at all solves the issue I described...

**Comment by imzbf** [comment]
You're right, I'll add it again
