### ISSUE TITLE
最新版本代码块的复制按钮变成纯文字了

### ISSUE THREAD

**Issue by cooperGao** [imzbf/md-editor-v3#542]
### 描述这个Bug

最新版本的代码块复制按钮变成纯文字了，我希望切换为原来的图标加hover显示提示的方式，在不降级版本的情况下如何操作呢

### 版本号

4.15.6

**Comment by imzbf** [comment]
目前没有办法，其实之前的版本就是纯文本，由于展示代码语言名设计不当，才尝试使用图标。后面我尝试看能不能切换它们

**Comment by cooperGao** [comment]
> 目前没有办法，其实之前的版本就是纯文本，由于展示代码语言名设计不当，才尝试使用图标。后面我尝试看能不能切换它们

好的，感谢大佬

**Comment by imzbf** [comment]
4.16.0以后可以使用icon的方式展示了，按照文档的示例替换icon即可：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%98%AC%20customIcon

**Comment by cooperGao** [comment]
> 4.16.0以后可以使用icon的方式展示了，按照文档的示例替换icon即可：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%98%AC%20customIcon

好的，非常感谢👍

**Comment by cooperGao** [comment]
> 4.16.0以后可以使用icon的方式展示了，按照文档的示例替换icon即可：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%98%AC%20customIcon

我用pnpm无法安装4.16.0版本，最新版只能安装到4.15.6是怎么回事😳
