### ISSUE TITLE
MdPreview无法禁用图片缩放

### ISSUE THREAD

**Issue by cooperGao** [imzbf/md-editor-v3#544]
### 描述这个Bug

当我在移动端使用MdPreview时问题场景如下：
1. 一个页面存在多个MdPreview组件，我给每个MdPreview设置了唯一ID，但是点击图片的时候会出现两个遮罩层架图片；
2. 此时我想禁用图片缩放功能，设置了属性noImgZoomIn=“true”，然而并没有生效；
3. 在config中增加以下配置:
```
config({
  markdownItPlugins(plugins) {
    return plugins.filter((p) => p.type !== 'image');
  }
});
```
依然没有效果；
4.我在pc端做同样的操作，还是无法禁用图片缩放；

### 版本号

4.15.6

**Comment by imzbf** [comment]
给个还原问题的基础项目看看，理论上只要你没有手动把editorId设置成想同，都没有这个问题

**Comment by cooperGao** [comment]
我是在uniapp中应用的，在检查元素的时候，看起来editorId是唯一的，但是点击却出现了两个遮罩层，这是ID重复才会出现的情况，我晚点创建一个基础项目测试下能否复现。（下面是问题的场景图片，图一为图片放大时的div结构；图二为md渲染场景，editorId是唯一的）
图一：
![企业微信截图_877acf33-363b-4901-98da-42b989b3f9af](https://github.com/imzbf/md-editor-v3/assets/46325343/19af9326-b8e0-4faa-af12-9c56aa5de775)
图二：
![企业微信截图_49e6758a-a417-457b-83f8-ed2e9d4f11cc](https://github.com/imzbf/md-editor-v3/assets/46325343/fdab3339-53f5-46e1-82ed-572c95c4ff95)

**Comment by imzbf** [comment]
方便的话给下可以调试的项目，从图上没有办法定位问题

**Comment by cooperGao** [comment]
> 方便的话给下可以调试的项目，从图上没有办法定位问题

目前我用uniapp自带的API在onHtmlChanged中实现了预览放大功能，出现问题的场景我后面搭建个基础项目测试下能否复现
