### ISSUE TITLE
shell语法完全没有高亮

### ISSUE THREAD

**Issue by kingwrcy** [imzbf/md-editor-v3#545]
### 描述这个Bug

shell语法完全没有高亮,看官网文档上的shell代码也没有高亮,这个如何添加呢?

### 版本号

"md-editor-v3": "^4.15.0"

**Comment by imzbf** [comment]
有些确实无法高亮，比如

```shell
yarn add md-editor-v3
```
可能没有识别到关键词，像下面这个，定义为`bash`，就可以

```bash
echo "13"
```

**Comment by kingwrcy** [comment]
```
docker run --restart=always --name moments -d -v /data/docker/moments:/app/data -p 3000:3000 kingwrcy/moments:0.1.6
```

这个定义为shell和bash 都没有任何语法高亮
有啥好办法吗?毕竟这类脚本还是毕竟多的.

**Comment by imzbf** [comment]
好像没办法，我在[highlight.js](https://highlightjs.org/demo)的demo中试了试。
