### ISSUE TITLE
Firefox and Chrome auto scroll behave differently.

### ISSUE THREAD

**Issue by slugb0t** [imzbf/md-editor-v3#546]
### Describe the issue

I have setup MdEditor on my project and I am testing the auto scroll on both Chrome and Firefox. I'm noticing that on Chrome the auto scroll will break and upon refreshing it won't correct itself. It seems to be random or maybe even depending on the amount of text written out?

### Procedure version

4.13.5

**Comment by imzbf** [comment]
Can you provide the width and height of the editor where the issue was found, as well as the text of the content, preferably if there is an online link
