### ISSUE TITLE
代码块的折叠头

### ISSUE THREAD

**Issue by Roywhite** [imzbf/md-editor-v3#547]
### 一个很棒的想法

代码块自动折叠时，用户第一次使用时很难感知到代码块已经被折叠了或者可以折叠，希望后续能有优化
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/d7fab0db-eaae-4ffd-ad78-7f15cdc5be54)

**Comment by imzbf** [comment]
是的，尝试过用箭头符号提示，但是样式上很奇怪，各位有好的提示方案多指点

**Comment by mingchiuli** [comment]
> 是的，尝试过用箭头符号提示，但是样式上很奇怪，各位有好的提示方案多指点

可以加一个文案提示，如果是折叠状态就显示点击展开之类的

**Comment by imzbf** [comment]
> > 是的，尝试过用箭头符号提示，但是样式上很奇怪，各位有好的提示方案多指点
> 
> 可以加一个文案提示，如果是折叠状态就显示点击展开之类的

应该放哪儿，之前尝试的是折叠后的下面

**Comment by mingchiuli** [comment]
> > > 是的，尝试过用箭头符号提示，但是样式上很奇怪，各位有好的提示方案多指点
> > 
> > 
> > 可以加一个文案提示，如果是折叠状态就显示点击展开之类的
> 
> 应该放哪儿，之前尝试的是折叠后的下面
<img width="631" alt="Screenshot 2024-06-01 at 22 35 24" src="https://github.com/imzbf/md-editor-v3/assets/80095372/2e74a49d-4063-417a-a703-a1e4ce879c4a">

个人感觉就在这里放一个展开代码的按钮就行，不过点击范围触发的区域范围可以和现在保持一致

**Comment by Roywhite** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/0e544571-dd19-47ab-b83d-168deb7af409)
这种展示效果怎么样呢？

**Comment by imzbf** [comment]
1. 在小屏的时候就会挤在一起了，而且会新增多的语言配置，首先考虑icon，但是icon放在这里方向没有友好的指示效果，如果没有合适的再优先考虑这个方案

<img width="631" alt="Screenshot 2024-06-01 at 22 35 24" src="https://github.com/imzbf/md-editor-v3/assets/80095372/2e74a49d-4063-417a-a703-a1e4ce879c4a">

2. 效果是好的，但是这个组件的代码模块的一个特点是左上方会展示三个小圆点，虽然没有实际的用处，如果采用这种方式，就会失去这个视觉效果

![image](https://github.com/imzbf/md-editor-v3/assets/42577687/0e544571-dd19-47ab-b83d-168deb7af409)

**Comment by Roywhite** [comment]
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/e298fe53-3d7d-4bc5-8b00-fb184d55b7b1)
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/4edc1d42-7d13-4830-aaeb-5404e8ff3a33)
https://icones.js.org/collection/all?s=expand
https://icones.js.org/collection/all?s=collapse

可以找同一风格集合的图标试试效果
![image](https://github.com/imzbf/md-editor-v3/assets/42577687/97ddb74d-6edc-40e3-bec3-2151812c153b)

**Comment by imzbf** [comment]
暂定方案：

![录屏2024-06-04 11 39 47](https://github.com/imzbf/md-editor-v3/assets/37092006/490ac7b4-843a-4803-bf8e-baa2b3a4102e)

**Comment by imzbf** [comment]
在`^4.16.0`中尝试
