### ISSUE TITLE
Behavior for links

### ISSUE THREAD

**Issue by mickey58github** [imzbf/md-editor-v3#548]
### Describe the issue

I like md-editor very much. I'm coming from a different Markdown processor, which opens links (in the preview section) in a new browser tab. I have a lot of links in my existing Markdown content. My users got used to opening them by default in a new browser tab.

Would it be possible to have this behavior to open links configurable in md-editor? The default could still be the current behavior, which opens a link in the same browser window. By option, it should be possible to get links opened in a new browser tab. This would require to generate the corresponding HTM for links withL with target="_blank", if this config option is chosen.

Thanks for looking into this.

### Procedure version

Newest version

**Comment by imzbf** [comment]
I have an example that only requires a simple configuration: https://github.com/imzbf/md-editor-v3/blob/dev-docs/src/main.ts#L34

**Comment by mickey58github** [comment]
Thanks a lot! Addressed the issue by using this Link Attributes plugin. Wonderful!
