### ISSUE TITLE
How to customize CSS props in a preview theme

### ISSUE THREAD

**Issue by mickey58github** [imzbf/md-editor-v3#549]
### Describe the issue

Hi, I would like to use the Vuepress theme. However, the word break/word wrap is not working as I need it. The Vuepress theme breaks words arbitrarily in the middle, at the end of lines. I think this is controlled by the CSS prop "word-break", which would have to be customized to "word-break: break-word" for all text displayed by MdPreview.

But I don't know how to override such pre-defined CSS props in the theme. I could not even find the CSS for this "vuepress" theme in the source code of md-editor-v3. 

Do you have an example for changing CSS props in the theme?

### Procedure version

Newest version of md-editor-v3

**Comment by imzbf** [comment]
I think you can do something like this: https://github.com/imzbf/md-editor-v3/issues/511#issuecomment-2103764039

Of course, if you want to target a single theme, the selector should be '.md-editor-preview.vuepress-theme p'

In addition, the theme source code can be https://github.com/imzbf/markdown-theme in the repository

**Comment by mickey58github** [comment]
Thanks, but sorry, I still don't know where to insert the suggested CSS in my code. 

If I understand you correctly, the suggested CSS is this.

```
.md-editor-preview.vue-press-theme p {
    word-break: break-word;
}
```

So I put this at the end of my vue file (in SASS syntax, because I use SASS preprocessor).

But how can I use it with MdEditor?

`<MdEditor class="md-editor-preview.vuepress-theme">` has no effect.

**Comment by mickey58github** [comment]
Update: I found a workaround, by modifying the style.css file that ships with md-editor-v3, and importing that modified version of style.css. Not sure though whether that is the officially supported way of doing this.

**Comment by imzbf** [comment]
不，`.md-editor-preview.vue-press-theme`是编辑器中的类名，当你使用vue-press主题的时候会出现，不需要手动设置

```diff
<MdEditor 
-   class="md-editor-preview"
   previewTheme="vuepress"
>
```
