### ISSUE TITLE
关于于挂载在body上的svg标签

### ISSUE THREAD

**Issue by KeterVM** [imzbf/md-editor-v3#55]
![](https://i.imgur.com/eVI7JZm.png)

如图：当在多个页面中使用的时候（包括modal），来回切换各个页面会不断渲染新的图中的svg dom，请问下没有嘛办法能够优化这一块或者有没有解决方案

**Comment by imzbf** [comment]
这个问题在即将发布的下个版本中已经优化了，不久就会发布。

**Comment by imzbf** [comment]
已在[v1.11.0](https://github.com/imzbf/md-editor-v3/releases/tag/v1.11.0)中优化~
