### ISSUE TITLE
Documentation and translation of find/replace capability

### ISSUE THREAD

**Issue by mickey58github** [imzbf/md-editor-v3#552]
### Describe the issue

Hi, I'm using the find/replace feature which can be opened by Ctrl+ F at the bottom of the editor,.

I can't find that capability in the docs though. Is it described somewhere?

And is there a way to translate its form (find/replace/replace all/next/previous/etc.)? I get it in English, but would need it in German.

### Procedure version

Latest version

**Comment by imzbf** [comment]
Sorry, I couldn't find a way to localize the query functionality in the `codemirror` lib, and we can't handle this at the moment.

**Comment by mickey58github** [comment]
No worries, the functionality itself is great. 

But it took me a couple of days to find out that it exists, by accidentally hitting CTRL + F, as used from other editors.

It would be good to mention the find/replace function in the docs, and get it added to the toolbar.

**Comment by imzbf** [comment]
Indeed, I will add how it is used in the docs, thanks for the reminder.

**Comment by imzbf** [comment]
Document updated
