### ISSUE TITLE
尖括号不知道什么条件下会转译？

### ISSUE THREAD

**Issue by wabshs** [imzbf/md-editor-v3#553]
### Describe the issue

我引入了一个组件叫做MetingJS，可以在HTML页面里面渲染出一个播放器，奇怪的是我一台电脑上的两个项目都是同版本的md-editor，一个会把尖括号转译成例如&lt导致渲染的组件不生效，另一个则正常
![image](https://github.com/imzbf/md-editor-v3/assets/87225821/1e74a465-8469-4ddc-96da-3cd57f6496db)
![image](https://github.com/imzbf/md-editor-v3/assets/87225821/8c0952e1-6fca-4f08-958b-cb0681ea254f)

### Procedure version

4.11.2

**Comment by imzbf** [comment]
在禁用xss的时候不会转义，4.11.3以后禁用参考：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%94%93%20%E7%A7%BB%E9%99%A4%20xss%20%E6%89%A9%E5%B1%95
