### ISSUE TITLE
代码区域样式不能自动换行

### ISSUE THREAD

**Issue by nalandra** [imzbf/md-editor-v3#554]
### Describe the issue

复制一大堆文字到编辑器中，里面有连续4个空格开头的段落，就会被转化成"< pre >" "< code >"
< pre > < code > 区域宽度突破了其他部分的样式宽度，造成页面样式混乱

希望< pre >< code >里面能保持和其他部分同样的宽度，对一行长文字能进行自动换行显示

### Procedure version

node v18.20.2

**Comment by imzbf** [comment]
这看起来是编译的缺陷，会被视为块级代码进行修复，但是不会强制处理掉开头的空格，以及提到的换行问题。

**Comment by imzbf** [comment]
已经统一代码块的样式，在`^4.16.0`中尝试
