### ISSUE TITLE
预览模式点击目录跳转后给一个距离顶部的参数

### ISSUE THREAD

**Issue by Eeasonnnn** [imzbf/md-editor-v3#555]
### Describe the issue

MdCatalog MdPreview  点击目录跳转的时候 可不可以给一个 距离顶部距离的参数

### Procedure version

vue3"md-editor-v3": "^4.15.6","@vitejs/plugin-vue": "^5.0.4",

**Comment by imzbf** [comment]
有这个参数：scrollElementOffsetTop https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%BB%20MdCatalog

**Comment by Eeasonnnn** [comment]
好的 感谢 !
