### ISSUE TITLE
公式为啥渲染不出来函数，例如sqrt等

### ISSUE THREAD

**Issue by HDP2017** [imzbf/md-editor-v3#556]
### Describe the issue

$$\sqrt[3]{x}$$
渲染出来是
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/faa02c41-40c7-4dd7-819d-3bbc2f2d0500)

### Procedure version

vue3项目

**Comment by imzbf** [comment]
你确定你的内容是下面这样？复制到示例页面和预期的一样

```
$$\sqrt[3]{x}$$
```

<img width="1268" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/37092006/9215a7cc-f68f-4aa1-932c-75894a40bc18">

**Comment by HDP2017** [comment]
我的代码基本上就简单的搞了个示例，如下图
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/f3486fca-7650-4f31-a482-cbb7a10a2530)

排查了很久，一直不知道哪里出了问题，我在您的示例里面也是能显示出来预期公式的，但是放到我的代码里就不行。

**Comment by HDP2017** [comment]
如果是不包含sqrt，sum或者frac之类的函数，显示就正常，这些函数会渲染不出来，在dom里面渲染成了这种mathnormal的块
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/5f6ca240-69bc-4fb2-87ec-5be3484cfd09)
而不是像您官网示例里面的sqrt块
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/36f4ccdb-cdd5-41a6-a9b2-ab9c2c388fc1)

**Comment by imzbf** [comment]
你的tttttt内容被转义了，'\\s'

**Comment by HDP2017** [comment]
感谢感谢，我刚刚测试了一下，直接用后端拿到的字符串也没有问题，本来还想着写方法将单反斜杠搞成双反斜杠，目前看应该是不用了，再次感谢
