### ISSUE TITLE
transformImgUrl 属性没效果

### ISSUE THREAD

**Issue by wqcn322** [imzbf/md-editor-v3#557]
### Describe the issue

transformImgUrl 属性没效果

### Procedure version

4.15.6

**Comment by imzbf** [comment]
只会识别复制内容中标准的markdown 图片语法，例如`![](/img/1.png)`，以及在工具栏中添加的图片。直接粘贴图片或者图片链接，是不生效的

**Comment by wqcn322** [comment]
工具栏上传的图片也不生效

**Comment by imzbf** [comment]
从使用角度上，工具栏中的添加链接选项会调用该方法转换，而上传和裁剪上传选项，是可以在上传图片事件中处理，顾不需要转换
