### ISSUE TITLE
新的4.16.0 代码显示这块更新后，和屏幕截图 "html-to-image": "^1.11.11", 冲突了

### ISSUE THREAD

**Issue by cgisky1980** [imzbf/md-editor-v3#559]
### 描述这个Bug

没有报错，但是截不了图了，不加载code 就好的，老版也可以

### 版本号

4.16.0

**Comment by cgisky1980** [comment]
有木有什么开关设置可以把代码折叠关闭的？

**Comment by imzbf** [comment]
使用属性[codeFoldable](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%95%B9%20codeFoldable)来禁用折叠代码
