### ISSUE TITLE
请教一下 预览模式下怎么把目录调出来啊

### ISSUE THREAD

**Issue by aguoxing** [imzbf/md-editor-v3#56]
预览模式下如何把目录调出来呢

**Comment by imzbf** [comment]
用<Editor.Catalog />这个组件就可以了，这里有个简单的[示例](https://imzbf.github.io/md-editor-v3/docs/index#%F0%9F%90%BB%20Catalog)

**Comment by aguoxing** [comment]
> 用<Editor.Catalog />这个组件就可以了，这里有个简单的[示例](https://imzbf.github.io/md-editor-v3/docs/index#%F0%9F%90%BB%20Catalog)

按示例来的，是还要引入嘛
Failed to resolve component: Editor.Catalog
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by imzbf** [comment]
你引入的组件和这个`Editor`名称相同么？正常情况是这样的

![QQ图片20220309164557](https://user-images.githubusercontent.com/37092006/157405486-71d774f0-3c33-4d0a-9ce0-4adea3f495ff.png)
![QQ图片20220309164622](https://user-images.githubusercontent.com/37092006/157405493-c2c30d7a-45a4-4356-a71b-a12e1258cf19.png)
![QQ图片20220309164648](https://user-images.githubusercontent.com/37092006/157405497-0f044f87-8888-4b60-a724-e97cc176140f.png)

**Comment by aguoxing** [comment]
是一样的呀 最新的

我看在线的好像也不行
https://codesandbox.io/s/pedantic-lederberg-i19yoq?file=/src/App.vue

**Comment by imzbf** [comment]
```vue
<template>
  <md-editor editor-id="my-editor" v-model="text" />
  <md-catalog editor-id="my-editor" />
</template>

<script>
import { defineComponent } from "vue";
import MdEditor from "md-editor-v3";
import "md-editor-v3/lib/style.css";

const MdCatalog = MdEditor.Catalog;

export default defineComponent({
  name: "App",
  components: {
    MdEditor,
    MdCatalog,
  },
  data() {
    return {
      text: "# 这是标题",
    };
  },
});
</script>
```

[这样写吧](https://codesandbox.io/s/amazing-williams-fcwdey?file=/src/App.vue)，用vue3的setup模板应该更直观一点，在线那个有时候会抽风

**Comment by imzbf** [comment]
在线报错就点那个Browser下面的刷新按钮
