### ISSUE TITLE
更新新版后，图片下方不再显示标题了

### ISSUE THREAD

**Issue by lei940324** [imzbf/md-editor-v3#560]
### Describe the issue

希望能像之前版本一样  显示下方的标题  就是![]() 中   []里的内容

### Procedure version

最新版

**Comment by imzbf** [comment]
修正了一下语法，参考：https://imzbf.github.io/md-editor-v3/zh-CN/grammar#%F0%9F%90%BC%20%E5%9B%BE%E7%89%87
