### ISSUE TITLE
禁用代码折叠之后不应该显示那个小图标

### ISSUE THREAD

**Issue by cooperGao** [imzbf/md-editor-v3#561]
### 描述这个Bug

禁用代码折叠之后右上角代码折叠的图标仍然存在

### 版本号

4.16.0

**Comment by imzbf** [comment]
在4.16.3中尝试，小于该版本请使用css将其隐藏

**Comment by cooperGao** [comment]
> 在4.16.3中尝试，小于该版本请使用css将其隐藏

好的，谢谢大佬
