### ISSUE TITLE
最新版本由于代码块折叠导致打印bug

### ISSUE THREAD

**Issue by tianci-8** [imzbf/md-editor-v3#563]
### 描述这个Bug

作者大大也可以在你文档的demo试一下，刚才我试了会复现这个。
![截图_20240606145830](https://github.com/imzbf/md-editor-v3/assets/156097200/a5606581-2191-417a-a199-a5f91eb5b24e)

### 版本号

最新版

**Comment by imzbf** [comment]
请不要重复创建，https://github.com/imzbf/md-editor-extension/issues/22
