### ISSUE TITLE
新版本打印bug

### ISSUE THREAD

**Issue by tianci-8** [imzbf/md-editor-v3#564]
### 描述这个Bug

代码折叠出现的打印bug
![截图_20240606145830](https://github.com/imzbf/md-editor-v3/assets/156097200/7ad782e7-76c0-4af1-aa0b-b2fc7cb6796b)

### 版本号

最新版

### 问题重现链接

文档demo即可复现

**Comment by imzbf** [comment]
请不要重新创建问题，该问题已经移到扩展库且已修复，https://github.com/imzbf/md-editor-extension/issues/22
