### ISSUE TITLE
如何将mermaid CDN引入改为本地引入？

### ISSUE THREAD

**Issue by kyalong** [imzbf/md-editor-v3#566]
### Describe the issue

如题， (in promise) TypeError: Failed to fetch dynamically imported module: https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.esm.min.mjs

### Procedure version

vue3

**Comment by imzbf** [comment]
参考这个：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93
