### ISSUE TITLE
打印bug

### ISSUE THREAD

**Issue by tianci-8** [imzbf/md-editor-v3#567]
### 描述这个Bug

应该是由于新功能代码块折叠导致的打印bug
![截图_20240606145830](https://github.com/imzbf/md-editor-v3/assets/156097200/7f978fba-906d-4d98-aee6-6cd41df3e87a)

### 版本号

4.16.0

**Comment by imzbf** [comment]
请你不要再重复提交issue，这个问题不属于这个仓库
