### ISSUE TITLE
关于内存溢出的咨询

### ISSUE THREAD

**Issue by kingwrcy** [imzbf/md-editor-v3#569]
### Describe the issue

用户反应时间长了会内存溢出,我用chrome的开发者工具 随便几次dump,发现这个字符串有7 8万次重复,是这个linkfy里面的.
![image](https://github.com/imzbf/md-editor-v3/assets/1247324/080a9ca2-e553-40e5-a9ac-d54897cd5bf2)

麻烦看看这个有问题吗?初始打开页面内存占用是22m,打开几个页面,刷新,返回正常操作后,这个string就有很多了,内存占用变成了77m

### Procedure version

"md-editor-v3": "^4.16.3"

**Comment by imzbf** [comment]
内存还没有来得及回收，在文档的首页，多次刷新和编辑等操作后确实会增加，在稍后一点时间或者手动垃圾回收，整个页面的稳定在24左右。

导致内存占用增加的原因有内容的增加（其中也包括了mermaid图形缓存），单页应用中页面打开的数量增加等。

至于这个字符串的问题，这是解析程序的正常，我搜出来并没有你描述那么多，貌似只有18次

**Comment by kingwrcy** [comment]
地址在  https://discussion.mblog.club/ ,随便点几个帖子,返回,进入,就出来了,多重复点几次,比如4 5次之后.

![image](https://github.com/imzbf/md-editor-v3/assets/1247324/032fd33e-914c-4df5-b180-92c4905e314f)

**Comment by imzbf** [comment]
展开更多，里面大部分是其他构造字符串。按照你描述的重复进入、刷新等操作，手动清理后也稳定在24左右

**Comment by kingwrcy** [comment]
好吧,那我再看看其它哪里有可能导致内存泄漏.

**Comment by imzbf** [comment]
ddd.html

```html
<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <title>全局引用</title>
    <link href="https://unpkg.com/md-editor-v3@4.16.7/lib/style.css" rel="stylesheet" />
  </head>
  <body>
    <a href="./eee.html">to eee.html</a>

    <div id="md-editor-v3">
      <md-editor-v3
        v-model="text"
        no-katex
        no-mermaid
        no-highlight
        no-prettier
        no-img-zoom-in
      />
    </div>
    <script src="https://unpkg.com/vue@3.2.47/dist/vue.global.prod.js"></script>
    <script src="https://unpkg.com/md-editor-v3@4.16.7/lib/umd/index.js"></script>
    <script>
      const App = {
        data() {
          return {
            text: 'Hello Editor!!'
          };
        }
      };
      Vue.createApp(App).use(MdEditorV3.MdEditor).mount('#md-editor-v3');
    </script>
  </body>
</html>
```


eee.html

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <a href="./ddd.html">to ddd.html</a>
  </body>
</html>
```

我通过最简单的方式对比了下，在包含编辑器的页面跳转到完全空的页面后，内存占用维持在1.2m，而直接打开空的页面维持在482kb，确实存在一些问题，我会持续尝试优化，感谢提醒

**Comment by imzbf** [comment]
> 好吧,那我再看看其它哪里有可能导致内存泄漏.

我会再尝试一下和来回创建编辑器的实例有关系
