### ISSUE TITLE
预览组件不显示有序列表

### ISSUE THREAD

**Issue by c-eqian** [imzbf/md-editor-v3#571]
### Describe the issue

在编辑组件中可以正常显示有序或者无序列表，但是在mdpreview预览组件中不显示，mdpreview预览组件是否还是需要其他额外插件？
![image](https://github.com/imzbf/md-editor-v3/assets/71966808/5f44fea1-c6d6-4004-a4fd-957943ffdf38)

![image](https://github.com/imzbf/md-editor-v3/assets/71966808/0d284c40-b18c-4816-b4d7-029ec7f2b72c)

### Procedure version

"md-editor-v3": "^4.16.7",

**Comment by imzbf** [comment]
编辑器没有强制定义列表的序号显示方式，不显示请检查你的项目中的外部列表样式

**Comment by imzbf** [comment]
#533

**Comment by c-eqian** [comment]
> 编辑器没有强制定义列表的序号显示方式，不显示请检查你的项目中的外部列表样式

感谢您的回复，检查了一下，确实是因为我项目中tailwind 样式覆盖原因
