### ISSUE TITLE
关于全部关闭CDN的问题

### ISSUE THREAD

**Issue by wangdan-fit2cloud** [imzbf/md-editor-v3#572]
### Describe the issue

1、MdEditor和MdPreview两个要分别加config配置才能全部关闭cdn吗，有没有通用配置
2、（升级到4.16.7）在同一个页面里，按照文档配置了config关闭cdn，MdEditor和MdPreview切换的时候，会报错，编辑器就无法显示了（4.12.1正常），目前无法升级

### Procedure version

4.16.7

**Comment by imzbf** [comment]
不需要分别配置，你描述的切换是具体怎么切换操作？

**Comment by wangdan-fit2cloud** [comment]
> 不需要分别配置，你描述的切换是具体怎么切换操作？
```
<template>
  <MdEditor noIconfont noPrettier v-bind="$attrs">
    <template #defFooters>
      <slot name="defFooters"> </slot>
    </template>
  </MdEditor>
</template>

<script setup lang="ts">
import { MdEditor, config } from 'md-editor-v3'

import screenfull from 'screenfull'

import katex from 'katex'
import 'katex/dist/katex.min.css'

import Cropper from 'cropperjs'
import 'cropperjs/dist/cropper.css'

import mermaid from 'mermaid'

import highlight from 'highlight.js'
import 'highlight.js/styles/atom-one-dark.css'
import './assets/iconfont.js'

config({
  editorExtensions: {
    highlight: {
      instance: highlight
    },
    screenfull: {
      instance: screenfull
    },
    katex: {
      instance: katex
    },
    cropper: {
      instance: Cropper
    },
    mermaid: {
      instance: mermaid
    }
  }
})
</script>
```
这个是MdEditor的，但是MdPreview依然会加载，所以MdPreview也要再写一个对吗

**Comment by imzbf** [comment]
不需要的，config是全局的，如果你挂载了多次编辑器组件，或者也是用了预览组件，建议直接在项目入口文件配置。

例如vite创建的项目，建议在`main.ts`中配置。

**Comment by wangdan-fit2cloud** [comment]
上述的是把MdEditor封装成一个叫MarkdownEditor.vue的组件之后
```
    <MarkdownEditor
        v-if="isEdit"
        v-model="form.content"
        placeholder="请输入"
        :preview="false"
        :toolbars="toolbars"
        @onUploadImg="onUploadImg"
        :footers="footers"
      >
      </MarkdownEditor>
      <MdPreview
        v-else
        ref="editorRef"
        editorId="preview-only"
        :modelValue="form.content"
        noIconfont
      />
```
用isEdit的true和false 切换，第一次MdPreview切换到Editor没事，Editor切换MdPreview然后再切换Editor就不行了，错误如下图
![image](https://github.com/imzbf/md-editor-v3/assets/79562285/24a8aa5f-9d3c-4796-a39d-76641c93196f)

**Comment by wangdan-fit2cloud** [comment]
刚刚试了一下把config放到全局main里就好了，封装在组件里不行，单独封装组件是我哪里弄的不合理吗？
还有一个问题就是mermaid.esm.min.mjs和mermaid.js 是什么功能，这个cdn弄不掉，这个如果nomermaid的话是影响什么功能呢？

**Comment by imzbf** [comment]
config在重复渲染的组件是不合适的，毕竟是全局配置，想放在组件里，除非能保证这个组件只会挂载一次，不然它总是会重复的config

mermaid参考https://mermaid.js.org/ ，no-xxx只会禁用相应的编译语法，对别的没有影响

**Comment by wangdan-fit2cloud** [comment]
> config在重复渲染的组件是不合适的，毕竟是全局配置，想放在组件里，除非能保证这个组件只会挂载一次，不然它总是会重复的config
> 
> mermaid参考https://mermaid.js.org/ ，no-xxx只会禁用相应的编译语法，对别的没有影响

好的 非常感谢您解决我的问题，已经没问题了
