### ISSUE TITLE
仅预览模式，’\n‘换行后空了一行出来

### ISSUE THREAD

**Issue by HDP2017** [imzbf/md-editor-v3#574]
### 描述这个Bug

![image](https://github.com/imzbf/md-editor-v3/assets/25113584/0ca28b4b-c668-478d-8a9c-2034d152ca47)

### 版本号

vue3项目，4.16.7

**Comment by imzbf** [comment]
看下你对应的html是怎样的，正常的是这样

```html
<p data-line="0">fas<br>
asd<br>
sasdd</p>
```

**Comment by HDP2017** [comment]
html是这样的
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/3d108794-a2a4-47c0-931b-8bb0aeb2d7d9)
但是我选中里面的文字，这个地方好像前面多了个换行
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/2e8ec60f-2938-461c-bb07-c06c05198102)
但是我得山上应该就是只有一个\n

**Comment by HDP2017** [comment]
或许是因为，在替换为<br>标签的时候，文本里面的\n还存在？

**Comment by imzbf** [comment]
查了下文档，这是有些 Markdown 解析器在生成 HTML 时，为了保持与原始 Markdown 文件的最大兼容性和可读性，选择保留原始的换行符。而 markdown-it 和 marked 在设置 breaks 为 true，有上面相同的行为。

如果不希望使用的话，可以从[这里](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8D%A4%20markdownItConfig)参考设置它的值。

由于`\n`在html中并不会起到真实的换行行为，所以你需要参考下面的语法编写你的内容：

https://github.github.com/gfm/#example-673

**Comment by HDP2017** [comment]
问题是我现在需要在输入框借助\n换行，其实就是输入框默认的换行行为是在字符串添加\n，而我们后端也需要这个来表示换行。渲染的时候就用的咱们的插件，所有下面的markdown语法应该不行。
上面那个配置可以解决这个问题吗，文档看的不是很清晰，可否提供一个示例代码，麻烦大佬

**Comment by imzbf** [comment]
> 问题是我现在需要在输入框借助\n换行，其实就是输入框默认的换行行为是在字符串添加\n，而我们后端也需要这个来表示换行。渲染的时候就用的咱们的插件，所有下面的markdown语法应该不行。 上面那个配置可以解决这个问题吗，文档看的不是很清晰，可否提供一个示例代码，麻烦大佬

如果确实要使用`\n`换行，那不用做任何修改，目前没有办法移除保留的`\n`。

**Comment by imzbf** [comment]
从编译规则上去处理挺麻烦的，通过组件提供的预处理html的方法`sanitize`，你可以把它替换掉，像下面：

```html
<MdPreview sanitize={(h) => h.replace(/<br>\n/g, '<br>')} />
```

**Comment by HDP2017** [comment]
加上这个可以了，感谢老哥
