### ISSUE TITLE
编辑器工具栏消失

### ISSUE THREAD

**Issue by lunckymeet** [imzbf/md-editor-v3#575]
### Describe the issue

当MdEditor组件设置id或editorId时，编辑器工具栏消失，只剩下自定义工具
```vue
<template>
  <div class="editor-containor">
    <MdEditor :editorId="editorId" v-model="text" :toolbars="toolbars" showCodeRowNumber autoDetectCode
      :footers="['markdownTotal', '=', 0, 'scrollSwitch']">
      <template #defToolbars>
        <Mark title="标记" />
        <Emoji :emojis="emojis" title="Emoji表情" />
        <PreviewDialog :mdText="text" :editorId="editorId" />
        <ExportPDF :modelValue="text" height="700px" />
      </template>
    </MdEditor>
  </div>
</template>
<script setup name="MdEditor">
import { ref, reactive } from 'vue'
import { MdEditor } from 'md-editor-v3';
import { Emoji, Mark, ExportPDF } from '@vavt/v3-extension';
import 'md-editor-v3/lib/style.css';
import '@/assets/styles/index';
import PreviewDialog from '@/components/PreviewDialog';
import { toolbars, emojis } from "@/components/XhEditor/config"

const state = reactive({
  text: "",
  modalVisible: false,
  modalFullscreen: false
});

const text = ref("")

defineProps({
  editorId: {
    type: String,
    default: "123"
  },
  themes: {
    type: Array,
    default: []
  },
  emojis: {
    type: Array,
    default: emojis
  }
})

const count = ref(0)
</script>
<style scoped lang="scss">
.emjios {
  width: 370px;
  height: 300px;
  overflow: auto;
}
</style>
```
![image](https://github.com/imzbf/md-editor-v3/assets/63490239/358a2dab-3faa-40fc-95c3-23d602ee2d56)

### Procedure version

nodejs v20.12.0  npm v10.5.0 vue v3.4.21  md-editor-v3 v4.16.7

**Comment by imzbf** [comment]
你是不是不能访问这个地址：https://at.alicdn.com/t/c/font_2605852_cmafimm6hot.js

**Comment by lunckymeet** [comment]
可以的
![image](https://github.com/imzbf/md-editor-v3/assets/63490239/01f95dda-dcc1-44d5-9536-2c2b57d94048)

**Comment by lunckymeet** [comment]
所有弹窗的位置都在左上角了
![image](https://github.com/imzbf/md-editor-v3/assets/63490239/1aa5ee17-5ff7-4337-9697-f96fc5a80bdd)

**Comment by imzbf** [comment]
方便的话，提供一下能还原这个问题的最小项目，这边协助看看

**Comment by lunckymeet** [comment]
可以的
[markdown.zip](https://github.com/user-attachments/files/15862328/markdown.zip)

**Comment by imzbf** [comment]
> 可以的 [markdown.zip](https://github.com/user-attachments/files/15862328/markdown.zip)

我跑了你的项目，是会显示的，如果网络不好会导致它展示的时间延长，你最好考虑[参考](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%A4%9E%F0%9F%8F%BC%20noIconfont)这个示例，来调整一下图标的问题。

**Comment by lunckymeet** [comment]
> 可以的 [markdown.zip](https://github.com/user-attachments/files/15862328/markdown.zip)

这个项目目前的代码是没问题的，在XhEditor这个组件的MdEditor添加`:editorId="editorId"`这个后就不显示了

**Comment by imzbf** [comment]
1. editorId必须是唯一的，按照你的项目，你还把editorId提供给了子组件中的预览组件
2. editorId必须是非空，你的项目中没有提供正确的值

https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8E%B2%20editorId

**Comment by lunckymeet** [comment]
就是编辑器的editorId   预览组件的editorId也不能一样吗？

**Comment by imzbf** [comment]
是的

**Comment by lunckymeet** [comment]
好的，感谢解答
