### ISSUE TITLE
css 问题

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#576]
### Describe the issue

作者您好，当我使用vuetify进行项目构建时，同时引入了下面的style，问题出在emoji组件，显示错误
import 'vuetify/styles'
import 'md-editor-v3/lib/style.css'
import '@vavt/v3-extension/lib/asset/style.css'

如下
当把 vuetify 注释掉后，就又正常了
// import 'vuetify/styles'
有办法兼容吗？

### Procedure version

 "vuetify": "^3.5.8" ；  "md-editor-v3": "^4.16.9",

**Comment by bintheext** [comment]
![Uploading Snipaste_2024-06-17_23-30-28.jpg…]()

**Comment by bintheext** [comment]
![Snipaste_2024-06-17_23-30-28](https://github.com/imzbf/md-editor-v3/assets/155461444/d6503706-2c71-46ca-8557-96eac096c9e9)

**Comment by imzbf** [comment]
默认的盒子模型被覆盖了，手动调整一下吧

```
.emojis li {
  box-sizing: content-box;
}
```

**Comment by bintheext** [comment]
问题解决，感谢作者大大
