### ISSUE TITLE
为什么类似于a.is,这样的字符串会被渲染成<a>标签呀？如图

### ISSUE THREAD

**Issue by HDP2017** [imzbf/md-editor-v3#579]
### Describe the issue

![image](https://github.com/imzbf/md-editor-v3/assets/25113584/449d6c66-08a9-49b2-bd4b-9cc07457a240)
![image](https://github.com/imzbf/md-editor-v3/assets/25113584/41175cda-d8d7-400e-b60d-67b4745d4295)

### Procedure version

vue3项目，4.16.7

**Comment by HDP2017** [comment]
是域名结尾的都这样？比如a.com?如果我只想符合超链接的md语法才渲染成超链接，字符串不去自动匹配这些，有没有配置项呀

**Comment by imzbf** [comment]
可以，参考：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%8D%A4%20markdownItConfig

```
mdit.set({
  linkify: false
})
```

**Comment by HDP2017** [comment]
问题解决了，谢谢谢谢

**Comment by HDP2017** [comment]
不过我还有一个类似的问题，文本里面的1. 2.之类的也会被默认渲染成列表，这个有啥配置项修改不

**Comment by imzbf** [comment]
这个是标准的有序列表语法，不能改变
