### ISSUE TITLE
Ctrl + A Shortcut

### ISSUE THREAD

**Issue by yassinrais** [imzbf/md-editor-v3#58]
When i do press Ctrl + A this add a quotation instead of selecting all editor content 😕 😄

**Comment by imzbf** [comment]
Is it possible that you pressed Ctrl + Q because  this would add a quotation?

**Comment by yassinrais** [comment]
Om using AZERTY keyboard so its A

**Comment by imzbf** [comment]
Can you run the following code and press Ctrl + A to see what happens.

```js
window.addEventListener('keydown', (e) => {
    if(e.ctrlKey) console.log('==e==', e.code);
})
```

I tried it.

![1646920237719](https://user-images.githubusercontent.com/37092006/157675571-cbba9d22-bb9a-44c1-be91-42c3cd4b273f.jpg)

**Comment by yassinrais** [comment]
![image](https://user-images.githubusercontent.com/25354731/157684022-41cb4a8b-667d-404e-8966-3a2cadd5c5dc.png)
![image](https://user-images.githubusercontent.com/25354731/157684117-40ac81c9-cecf-478e-a9f5-aa0849630eaf.png)
weird because im pressing A button

**Comment by yassinrais** [comment]
```js
isTrusted: true
altKey: false
bubbles: true
cancelBubble: false
cancelable: true
charCode: 0
code: "KeyQ"
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: false
detail: 0
eventPhase: 0
isComposing: false
key: "a"
keyCode: 65
location: 0
metaKey: false
```

**Comment by imzbf** [comment]
> better using keyCode instead of code

No, as can be seen from the [document](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), this attribute has been deprecated. 

May I ask about your browser version? I want to try this.

**Comment by yassinrais** [comment]
Oh i see

Versions:
`Google Chrome | 99.0.4844.51`

**Comment by imzbf** [comment]
Seem like, your keyboard is making trouble. I just know, the 'Q' and 'a' of this keyboard are replaced by each other. To fix it, I want more information about

| key | event.code | event.key | event.keyCode |
| - | - | - | - |
| Q |   | | |
| A | | | |
| W | | | |
| Z | | | |

🤓Thanks~

**Comment by yassinrais** [comment]
<html>
<body>


key | event.code | event.key | event.keyCode
-- | -- | -- | --
Q |KeyA|q| 81
A |KeyQ|a| 65
W |KeyZ|w|87  
Z |KeyW|z|90  

</body>
</html>

**Comment by yassinrais** [comment]
Keyboard : English (US) - QWERTY

<html>
<body>


key | event.code | event.key | event.keyCode
-- | -- | -- | --
Q | KeyA  | a | 65
A | KeyQ | q | 81
W | KeyZ | z | 90
Z | KeyW | w | 87


</body>
</html>

**Comment by imzbf** [comment]
Seem like, JavaScript can not fully adapt to this kind of device. I just fixed Francais at weekends, but can not find way to fix US. In order to maintain consistent behavior, we recommend using `Ctrl+Q`and`Ctrl+A`、`Ctrl+W`and`Ctrl+Z` in reverse.

**Comment by yassinrais** [comment]
US one is working good, i just send the table to show you how its look using Azerty and querty by pressing the azerty buttons 🙃🙏

**Comment by yassinrais** [comment]
Im sur the problem come from the upgrade about deprecating the keycode and use code instead 😅😅 browsers dev should fix this soon in future . 
You see in table the keyCode is the onky one who has the same value between azerty and querty even using arabic keyboard 🤦

**Comment by imzbf** [comment]
> US one is working good, i just send the table to show you how its look using Azerty and querty by pressing the azerty buttons 🙃🙏

OK. I got it , then I'll optimize Francais one in the next version. Hope it helps.

**Comment by imzbf** [comment]
`v1.11.2` have been released, have a try~🤓
