### ISSUE TITLE
mermaid instance设置问题

### ISSUE THREAD

**Issue by TzsSpace** [imzbf/md-editor-v3#580]
### 描述这个Bug

已经设置
```config({   editorExtensions: {     mermaid: {       instance: mermaid,     } });```
但是还是请求了https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.6.1/mermaid.esm.min.mjs
![image](https://github.com/imzbf/md-editor-v3/assets/73014454/d15f6858-2660-41f5-b9ec-bd319d3fc429)

### 版本号

last

**Comment by imzbf** [comment]
在4.17.0中修复了该问题
