### ISSUE TITLE
怎么取消点击事件的向上冒泡

### ISSUE THREAD

**Issue by HDP2017** [imzbf/md-editor-v3#581]
### Describe the issue

比如，图片的点击预览的点击，代码段的点击复制以及点击收起等这些事件，因为在组件的父级有其他点击监听，点了这几个事件后，会触发父级的事件，怎么配置可以处理这些？

### Procedure version

vue3项目，4.16.7

**Comment by imzbf** [comment]
无法取消，建议你通过`even.target`判断触发事件的对象后选择是否执行操作

**Comment by HDP2017** [comment]
好的，这样倒也可以解决问题，感谢。
