### ISSUE TITLE
插入`<img>`元素，渲染之后没有了具体的 src 属性

### ISSUE THREAD

**Issue by yoyocraft** [imzbf/md-editor-v3#582]
### Describe the issue

版本信息：
- `"md-editor-v3": "^4.16.7",`

具体代码：
`src/components/MyMdEditorPreview.vue`:
```vue
<template>
    <MdPreview :editorId="id" :modelValue="text" />
    <MdCatalog :editorId="id" :scrollElement="scrollElement" />
</template>

<script setup>
import { ref } from 'vue';
import { MdPreview, MdCatalog } from 'md-editor-v3';

const id = 'preview-only';
const text = ref('<a href="static/emoji/[doge].webp" target="_blank"><img src="static/emoji/[doge].webp" style="width: 2rem; display: inline-block;" /></a>');
const scrollElement = document.documentElement;
</script>
```
<img width="1028" alt="SCR-20240623-orio" src="https://github.com/imzbf/md-editor-v3/assets/99105425/378f0cd9-8098-47f3-917d-e51b151cf911">

### Procedure version

nodejs: v18.16.0

### Reproduction link

https://github.com/yoyocraft/md-editor-demo

**Comment by imzbf** [comment]
内置的xss扩展中的规则会将不带`/`开头的链接移除，所以目前有两种方案

1. 禁用xss扩展，参考：https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%94%93%20Remove%20XSS%20extension

2. 调整标准的链接：

```diff
-<img src="static/emoji/[doge].webp">
+<img src="/static/emoji/[doge].webp">

// 或者
+<img src="http://xxx.com/static/emoji/[doge].webp">
```

**Comment by yoyocraft** [comment]
LGMT

**Comment by yoyocraft** [comment]
LGMT
