### ISSUE TITLE
纯本地环境如何加载第三方类库

### ISSUE THREAD

**Issue by q2316367743** [imzbf/md-editor-v3#584]
### Describe the issue

我在写一个electron的应用，应用是纯本地环境，所以无法加载远程js，我应该如何设置，才可以不使用远程cdn，或者自定义cdn的url

### Procedure version

4.16.7

**Comment by imzbf** [comment]
参考文档：https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20Import%20All%20Library
