### ISSUE TITLE
内容布局选项（居左居中居右）图片尺寸的编辑功能 

### ISSUE THREAD

**Issue by iecube-zhangxiaolong** [imzbf/md-editor-v3#585]
### 一个很棒的想法

现在的内容布局默认居左，是否有可能菜单栏增加布局选项，实现内容的左中右布局。
现在上传图片后，图片的尺寸是无法更改的，是否有可能增加图片的尺寸更改方法（比如可设定固定的宽*高 或 为原尺寸的百分比）。

**Comment by imzbf** [comment]
默认的语法不会改变有一个插入img标签的扩展组件，可以考虑使用这种方式来做，无非是需要向标签增加样式

https://github.com/imzbf/md-editor-extension/tree/develop/packages/v3/components/OriginalImg
