### ISSUE TITLE
katex公式标识符自定义

### ISSUE THREAD

**Issue by jiabochao** [imzbf/md-editor-v3#586]
### A great idea

请问是否支持使用`\[`和`\]` 标识的公式。

例如：
```
\[130万元 \times 15\% = 19.5万元\]
```
<img width="1721" alt="image" src="https://github.com/imzbf/md-editor-v3/assets/16523012/59becfa5-42aa-443d-a155-830ca240d9b6">

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/issues/462#issuecomment-1965702788

之前尝试过，还没有很好的方式，目前保留仅适用`$`符号做标记的方式，针对markdown-it有合适的类似问题解决方案时，会考虑给出
