### ISSUE TITLE
transformImgUrl

### ISSUE THREAD

**Issue by q2316367743** [imzbf/md-editor-v3#587]
### Describe the issue

请问一下，这个配置：transformImgUrl是否如何使用

我现在有个需求，图片上传返回的url不会真正url，需要进行一定的转换，是可以使用这个参数，还是要自己写markdownit拓展

### Procedure version

4.16.7

**Comment by imzbf** [comment]
如果你的图片是要上传的，这个不会起作用，在上传图片事件中处理。

这个属性只有在粘贴标准图片语法和通过工具栏添加图片链接的时候会触发

**Comment by q2316367743** [comment]
好的，我通过重写正则替换的方式解决了
