### ISSUE TITLE
4.17.0存在使用拼字输入法以后输入框乱飘的问题

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#588]
### 描述这个Bug

在https://imzbf.github.io/md-editor-v3/en-US/index
打字，就能复现
<img width="790" alt="Screenshot 2024-06-28 at 00 55 18" src="https://github.com/imzbf/md-editor-v3/assets/80095372/28ce56f1-2998-4f64-ad45-c776b68b6609">
<img width="790" alt="Screenshot 2024-06-28 at 00 55 39" src="https://github.com/imzbf/md-editor-v3/assets/80095372/f798cc14-e120-4fb4-b8c6-16f8796f1a6c">

实际上输入时这个输入框一直在飘一直在移动

### 版本号

4.17.0

### 问题重现链接

https://imzbf.github.io/md-editor-v3/en-US/index

**Comment by imzbf** [comment]
https://github.com/codemirror/dev/issues/1396

编辑器升级引起的，等待修复

**Comment by Arcticn** [comment]
> [codemirror/dev#1396](https://github.com/codemirror/dev/issues/1396)
> 
> 编辑器升级引起的，等待修复

我也发现了这个问题。测试在火狐浏览器上没有问题，但是Chromium系有问题

**Comment by ChrisNi888** [comment]
我遇到的问题是中文输入的时候，不出现选项框，直接跳出中文了。版本号：4.17.3

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/issues/589#issuecomment-2201817674

先参考这个降级处理

**Comment by ChrisNi888** [comment]
> [#589 (comment)](https://github.com/imzbf/md-editor-v3/issues/589#issuecomment-2201817674)
> 
> 先参考这个降级处理

好的，现在看上去可以出来。谢谢！

**Comment by imzbf** [comment]
4.17.4版本禁用了编辑库的实验功能，该issue关闭
