### ISSUE TITLE
拼字时触发compositionstart和compositionend事件失败

### ISSUE THREAD

**Issue by mingchiuli** [imzbf/md-editor-v3#589]
### 描述这个Bug

不知道那个版本开始出问题的，代码是这样

```js
<template>
  <MdEditor ref="editorRef" />
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { MdEditor } from 'md-editor-v3';
import type { ExposeParam } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

const editorRef = ref<ExposeParam>();

onMounted(() => {
  editorRef.value?.domEventHandlers({
  compositionstart: () => {
    console.log('compositionstart');
  }
});
});
</script>
```

<img width="944" alt="Screenshot 2024-06-29 at 21 01 28" src="https://github.com/imzbf/md-editor-v3/assets/80095372/8976853f-121a-4345-b6ff-1c4d8f51770d">
拼字时控制台不会打印compositionstart

回退到4.12.0似乎也不奏效

### 版本号

4.17.0

**Comment by imzbf** [comment]
https://github.com/codemirror/dev/issues/1399

codemirror最近更新出现了不少的拼字输入的bug，等待那边优化

**Comment by mingchiuli** [comment]
> [codemirror/dev#1399](https://github.com/codemirror/dev/issues/1399)
> 
> codemirror最近更新出现了不少的拼字输入的bug，等待那边优化

是的，测试了下firefox是正常的

**Comment by imzbf** [comment]
codemirror在子版本中提交了破坏性的功能，在没有取得替换方案或者恢复的消息时，通过下面的方法对子依赖降级

在package.json中添加

```json
  "resolutions": {
    "@codemirror/view": "6.27.0"
  },
```

**Comment by imzbf** [comment]
4.17.4版本禁用了编辑库的实验功能，该issue关闭
