### ISSUE TITLE
[Docs] use only the preview part to show a rendered markdown

### ISSUE THREAD

**Issue by yassinrais** [imzbf/md-editor-v3#59]
Can o use md editor to only view a markdown ? 

i want to use only the preview part not the editor

**Comment by imzbf** [comment]
Just use `previewOnly`.

**Comment by yassinrais** [comment]
Oh i will try it , thanks 😁

**Comment by francisashley** [comment]
Hello, `previewOnly` appears not to exist. Any other way to do this?

**Comment by imzbf** [comment]
Replace `MdEditor` with `MdPreview` after version `4.0.0`.

References: https://imzbf.github.io/md-editor-v3/en-US/contrast#%F0%9F%94%96%20Props

**Comment by francisashley** [comment]
This worked great, thank you!
