### ISSUE TITLE
代码块换行后，行号的问题现在有办法了吗？

### ISSUE THREAD

**Issue by HDP2017** [imzbf/md-editor-v3#591]
### Describe the issue

我看之前有过讨论https://github.com/imzbf/md-editor-v3/issues/378
不知道现在可有更好的办法？

### Procedure version

vue3项目，4.16.7

**Comment by imzbf** [comment]
不添加js脚本的情况下，还没有让行号和内容能够高度同步的办法

**Comment by HDP2017** [comment]
好吧，目前我不让代码换行了，直接横向滚动吧，暂时就这样，谢谢
