### ISSUE TITLE
保存的内容再次加载内容错乱

### ISSUE THREAD

**Issue by orrest** [imzbf/md-editor-v3#592]
### Describe the issue

1. 我编辑并保存到数据库

![image](https://github.com/imzbf/md-editor-v3/assets/84518085/976b0fba-2838-4106-b02e-a6dfa6807de8)

2. 保存的内容
```
{
    "id": 22,
    "content": "# 123\n\n- hha\n- lla\n- bbla\n\n```\n// some code...\n```\n\n1. 1\n2. 2\n3. 3\n\n> aaa\n\n- 1\n- 2\n- 3\n\n# 234\n"
}
```

3. 预览

![image](https://github.com/imzbf/md-editor-v3/assets/84518085/5345e368-2398-4a18-a6e4-4dcddcc37ab6)

代码的显示有些问题，而且列表是突出的。是我保存内容的方式有问题吗？

### Procedure version

Vue3

**Comment by imzbf** [comment]
你是不是没有引入样式

**Comment by orrest** [comment]
> 你是不是没有引入样式

是的，引入后正常了。感谢~

```
import "md-editor-v3/lib/style.css";
```

![image](https://github.com/imzbf/md-editor-v3/assets/84518085/8671821d-3eb6-4d99-9087-9cdcd40c7626)
