### ISSUE TITLE
onGetCatalog可否返回树形结构数据

### ISSUE THREAD

**Issue by sunaccess** [imzbf/md-editor-v3#595]
### 一个很棒的想法

目前onGetCatalog获取到的是平展title和level,没有父子关系，很难处理成无限树形结构数据，与自定义描点控件绑定
最终要实现的效果就是编辑模式下的层级目录
![image](https://github.com/imzbf/md-editor-v3/assets/4462119/32de9e90-aa8b-48fa-8bc9-73c4ce43dcc5)

**Comment by imzbf** [comment]
是有关系的，前后如果是同一级别的标题，代表是一个子级，如果下一个是更小的标题，就是当前的子级，如果是更大的，那就是下一个父级标题。

这种关系在编辑器中不会有帮助，所以需要你自己处理
