### ISSUE TITLE
关于预览模式在wujie微前端环境下无法高亮当前目录

### ISSUE THREAD

**Issue by Lee12138ljj** [imzbf/md-editor-v3#597]
### Describe the issue

佬，我按照demo写的，放在wujie微前端环境下点击目录，可以定位内容，但是无法高亮标题仍然是第一个，但是单独打开子应用就没问题，请问这是什么情况。
![Snipaste_2024-07-08_11-44-16](https://github.com/imzbf/md-editor-v3/assets/75104260/7194af5b-6273-4436-bf62-e2aee8e8e922)
![Snipaste_2024-07-08_11-44-38](https://github.com/imzbf/md-editor-v3/assets/75104260/d6920db9-0c84-4f3a-8995-51b004f7608c)
![Snipaste_2024-07-08_11-47-59](https://github.com/imzbf/md-editor-v3/assets/75104260/32d2a3ef-b8e1-4259-a94f-ba956105ad6b)

### Procedure version

"md-editor-v3": "^4.17.2"

**Comment by imzbf** [comment]
不能高亮说明滚动容器可能不对，最好给个可以还原问题的地址我们才能查看问题
