### ISSUE TITLE
自动保存

### ISSUE THREAD

**Issue by zengdw** [imzbf/md-editor-v3#6]
没有自动保存功能吗 或者能提供js触发保存的方法吗

**Comment by imzbf** [comment]
> 没有自动保存功能吗 或者能提供js触发保存的方法吗

编辑器监听了`ctrl+s`，以及工具栏上的保存按钮，均会触发`onSave`事件，保存动作由开发者设定。

**Comment by zengdw** [comment]
像过10s自动保存，我怎么在定时器中触发onSave事件啊，没有对应的方法



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imzbf/md-editor-v3] 自动保存 (#6)





  
没有自动保存功能吗 或者能提供js触发保存的方法吗
  
编辑器监听了ctrl+s，以及工具栏上的保存按钮，均会触发onSave事件，保存动作由开发者设定。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by imzbf** [comment]
> 没有自动保存功能吗 或者能提供js触发保存的方法吗

定时器保存只需要你将`modelValue`保存即可，`onSave`会注册一个事件，当你按下`ctrl+s`或点击了保存按钮时，触发你的保存逻辑，下面是一个简单的示例（这里的`onSave`需要写为`on-save`，参与`vue`文档）：

```js
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <title>传统开发模式中使用</title>
    <link href="https://cdn.jsdelivr.net/npm/md-editor-v3@1.3.3/lib/style.css" rel="stylesheet" />
  </head>
  <body>
    <div id="md-editor-v3">
      <md-editor-v3 v-model="text" @on-save="handleSave"/>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3.1.5/dist/vue.global.prod.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/md-editor-v3@1.3.3/lib/md-editor-v3.umd.js"></script>
    <script>
      const App = {
        data() {
          return {
            text: 'Hello Editor!!'
          };
        },
	methods: {
	    handleSave(mdValue) {
                console.log('mdValue', mdValue)
                localStorage.setItem('md-value', mdValue);
            }
	}
      };
      Vue.createApp(App).use(MdEditorV3).mount('#md-editor-v3');
    </script>
  </body>
</html>
```

**Comment by zengdw** [comment]
哦， 忘了是vue写的了 明白了 谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 下午5:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imzbf/md-editor-v3] 自动保存 (#6)





  
没有自动保存功能吗 或者能提供js触发保存的方法吗
  
定时器保存只需要你将modelValue保存即可，onSave会注册一个事件，当你按下ctrl+s或点击了保存按钮时，触发你的保存逻辑，下面是一个简单的示例（这里的onSave需要写为on-save，参与vue文档）：
 <!DOCTYPE html&gt; <html lang="zh-CN"&gt;   <head&gt;     <meta charset="UTF-8" /&gt;     <title&gt;传统开发模式中使用</title&gt;     <link ***@***.***/lib/style.css" rel="stylesheet" /&gt;   </head&gt;   <body&gt;     <div id="md-editor-v3"&gt;       <md-editor-v3 v-model="text" @on-save="handleSave"/&gt;     </div&gt;     <script ***@***.***/dist/vue.global.prod.min.js"&gt;</script&gt;     <script ***@***.***/lib/md-editor-v3.umd.js"&gt;</script&gt;     <script&gt;       const App = {         data() {           return {             text: 'Hello Editor!!'           };         }, 	methods: { 	    handleSave(mdValue) {                 console.log('mdValue', mdValue)                 localStorage.setItem('md-value', mdValue);             } 	}       };       Vue.createApp(App).use(MdEditorV3).mount('#md-editor-v3');     </script&gt;   </body&gt; </html&gt;
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
