### ISSUE TITLE
[bug]@onChange有bug

### ISSUE THREAD

**Issue by 204065248** [imzbf/md-editor-v3#60]
最新版本的onChange失效，通过https://www.jianshu.com/p/ba141529d3c5 链接自己绑定oninput事件可以正常工作，作者麻烦看看。另外我想问问有没有什么函数可以获取当前页面的html呢，我想做markdown导出pdf

**Comment by imzbf** [comment]
1.11.2版本之前没有考虑到vue模板中的onChange，如果一定要在vue模板中要使用该事件，请先通过这种写法防止错误

```vue
<editor
  :modelValue="text"
  :onChange="saveValue"
/>
```

`onHtmlChanged`事件可以获取到正确的html代码。想要导出pdf最好把内容展示出来后通过三方工具导出，不然没有样式。

**Comment by 204065248** [comment]
好的，谢谢作者

**Comment by 204065248** [comment]
另外请问一下有没有 推荐的vue3 html转pdf的插件呢

**Comment by imzbf** [comment]
试试`vue3-print-nb`这个吧，我只用过它的vue2版本。了解下原理自己可以封装一个。

**Comment by 204065248** [comment]
好的，有没有办法自己写一个主题样式呢

**Comment by imzbf** [comment]
给`previewTheme`一个你自己定义的主题的值，像`previewTheme="ddd"`，然后像下面这样写样式，也可以直接通过选择器优先级覆盖内部样式。

```css
.ddd-theme {
  h1: {
    color: red;
  }
}
```

样式参考这个[markdown-theme](https://github.com/imzbf/markdown-theme)

**Comment by 204065248** [comment]
感谢感谢，弄好了，点个赞

**Comment by imzbf** [comment]
1.11.3及后续版本可以正常绑定该事件了~

**Comment by 204065248** [comment]
作者，你有什么好一点的多人协同的方案吗
