### ISSUE TITLE
Disable default Completion

### ISSUE THREAD

**Issue by guidu42** [imzbf/md-editor-v3#603]
### Describe the issue

Hello, 
I'm working on a chat project.
For multiple reasons i decided to use md-editor-v3 with Vue for writting messages.

My users won't specially need to use all the default completions that are defined in the set up of MdEditor.
When i try to override codeMirrorExtensions like this, i got an error because the override key for codeMirrorExtensions is already called during the set up. 

```js
config({
    codeMirrorExtensions(_theme, extensions) {
        return [
            ...extensions,
            autocompletion({
                override: [],
            }),
        ]
    },
})
```

Could it be possible to override the defaultCompletion ?

### Procedure version

Node v16.20.

**Comment by imzbf** [comment]
#604
