### ISSUE TITLE
图片预览存在两个遮罩层

### ISSUE THREAD

**Issue by wqcn322** [imzbf/md-editor-v3#605]
还有这个问题 版本4.17.3

**Comment by wqcn322** [comment]
图片预览还有双遮住曾问题

**Comment by imzbf** [comment]
请描述一下问题的还原方式，如果特殊的话，麻烦提供一下可访问的地址或者项目

**Comment by wqcn322** [comment]
我这边特殊截不了图， 问题就是点击预览的时候会出现两个<div class="medium-zoom-overlay" style="background: rgba(0, 0, 0, 0.45);"></div>

**Comment by imzbf** [comment]
可能的情况是你多个编辑器设置了相同的`editorId`

**Comment by wqcn322** [comment]
editorId我排查过  没有相同的

**Comment by wqcn322** [comment]
是偶尔会出现 考虑是不是浏览器会缓存？

**Comment by wqcn322** [comment]
重复的两个img标签，其中一个类名为class="medium-zoom-image medium-zoom-image--hidden medium-zoom-image--opened"

**Comment by wqcn322** [comment]
medium-zoom-image--hidden medium-zoom-image--opened  感觉是这两个类名同时出现的问题

**Comment by imzbf** [comment]
这类信息定位不了问题。如果你不方便给出问题的项目，麻烦通过创建基础项目，使用这个组件，然后尝试在基础项目中还原这个问题

**Comment by wqcn322** [comment]
[BUG] 预览图片问题 #451   我的问题和这个bug单里面描述的一模一样

**Comment by imzbf** [comment]
是的，但是你还是没有提供还原问题的方法

**Comment by imzbf** [comment]
我尝试优化了潜在的问题，你尝试使用beta版本看是否还存在，如果还存在，就需要你支持一下还原问题了

```
yarn add md-editor-v3@beta
```

**Comment by wqcn322** [comment]
md-editor-v3@beta  我安装了beta版本，问题解决了，感谢
