### ISSUE TITLE
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

### ISSUE THREAD

**Issue by leducgiachoang** [imzbf/md-editor-v3#606]
### Describe the issue

![image](https://github.com/user-attachments/assets/e646ab06-30b7-4be1-807d-43e007429f6e)

Hello library developer. I am encountering some minor errors when using your library within my Chrome extension application. I think you are aware of these errors and can fix them quickly. Thank you."

### Procedure version

^4.17.3

**Comment by leducgiachoang** [comment]
Can you use this library or download and save it locally for your own library? I look forward to your response.

https://github.com/highlightjs/highlight.js

`npm install highlight.js`

**Comment by imzbf** [comment]
You can refer to this example

https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20Import%20All%20Library

**Comment by leducgiachoang** [comment]
![image](https://github.com/user-attachments/assets/e44b9568-f6d2-4e60-9271-0914d1ec2ec6)
I want to tell you: 'YOU ARE AWESOME'. I have fixed my code, and it is now working without any errors. Thank you very much. ❤️
