### ISSUE TITLE
在项目包含 vue-i18n v9.13.1 中会报错，编译后无法使用，开发模式不影响

### ISSUE THREAD

**Issue by hawind** [imzbf/md-editor-v3#607]
### 描述这个Bug

![image](https://github.com/user-attachments/assets/51348b81-5de8-4047-8b6c-b6d1b9803a40)

### 版本号

4.17.4

**Comment by imzbf** [comment]
这个问题和这个库好像没有直接关系？

**Comment by hawind** [comment]
但是我只要不引入这个项目，就是对的，只要引入，就报错了

**Comment by imzbf** [comment]
给一个有这个问题的项目demo看看

**Comment by hawind** [comment]
好的，我试试看看能不能复现。

**Comment by imzbf** [comment]
缺少还原问题的必要步骤，暂停时关闭
