### ISSUE TITLE
title 不生效

### ISSUE THREAD

**Issue by RonaldinhoL** [imzbf/md-editor-v3#608]
### 描述这个Bug

![image](https://github.com/user-attachments/assets/01c75caf-663e-4608-93d6-3d9601df4935)
我和 quasar 一起用，不懂为啥 标题不生效，不同级别的标题渲染出来都是同一个大小

### 版本号

md editor: 4.17.4 node 20.10 chrome 126

**Comment by imzbf** [comment]
这属于css冲突，自行调试即可
