### ISSUE TITLE
yjs在线协同

### ISSUE THREAD

**Issue by 204065248** [imzbf/md-editor-v3#61]
作者，可以加一些yjs在线协同的函数吗，我研究了几天yjs库，发现他还是需要一些光标位置 之类的函数支持的

**Comment by imzbf** [comment]
这种比较特殊了，这个项目只会作为普通md编辑存在。你试试clone编辑器的源码，直接在内部扩展看看吧

**Comment by imzbf** [comment]
虽然没有内置这个功能，但是现在在文档中提供了一个基础的示例，参考：https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%8E%B3%20%E5%8D%8F%E5%90%8C%E5%8A%9E%E5%85%AC
