### ISSUE TITLE
completions not working in v4.17.4

### ISSUE THREAD

**Issue by tidusvn05** [imzbf/md-editor-v3#610]
### 描述这个Bug

i just updated to v4.17.4, and check completions not working.
for previous stable version, v4.17.0, it working ok.
and now i change to v4.17.4, it still work too.
so i think the issue for only v4.17.4.

please check it.
Thank You!

### 版本号

nuxt3, node 20, md-editor-v3 4.17.4

**Comment by tidusvn05** [comment]
fyi, i use 4.17.4 with specific codemirror/view version, it worked.
```
"resolutions": {
    "@codemirror/view": "6.27.0"
  },
 ```

**Comment by imzbf** [comment]
I cannot reproduce this issue. Can you provide a demo that can restore it?

<img width="1723" alt="image" src="https://github.com/user-attachments/assets/1ef544ee-8017-48f0-a481-319efa9beac8">

**Comment by imzbf** [comment]
Lacking examples, temporarily closed.
