### ISSUE TITLE
Saving Markdown Source from the MdEditor to a Local File

### ISSUE THREAD

**Issue by kermitmei** [imzbf/md-editor-v3#612]
### Describe the issue

Thank you for developing this library.

I am trying to save the Markdown source from the editor to a local file. However, the save button on the MdEditor does not seem to trigger any response.

Could you please guide me on how to achieve this?

Alternatively, is there another method to implement this functionality?

Thank you very much!

### Procedure version

4.17.4

**Comment by imzbf** [comment]
1. For the way to save content, you will need to use [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)-related technologies.
2. If you need to place a button on the toolbar, you can refer to this [example](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%92%AA%20defToolbars).

**Comment by kermitmei** [comment]
> 1. For the way to save content, you will need to use [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob)-related technologies.
> 2. If you need to place a button on the toolbar, you can refer to this [example](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%92%AA%20defToolbars).

Thank you for your response.

Based on point 2 of your reply, does this mean that I cannot use the default save button and would need to place a new save button on the toolbar, bind a corresponding handler to it, and then use Blob-related technologies to implement the saving functionality?

**Comment by imzbf** [comment]
No, you can use the default save button and save the text in the [onSave](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%92%BE%20onSave) event
