### ISSUE TITLE
输入多个括号内的空格，预览时只展现一个空格

### ISSUE THREAD

**Issue by webguosai** [imzbf/md-editor-v3#615]
### 描述这个Bug

![image](https://github.com/user-attachments/assets/f335cfb4-fbef-4307-bca6-58560b2bd6d9)

### 版本号

md-editor-v3@4.16.9    node v18.15.0

**Comment by imzbf** [comment]
规则是这样的，多个会合并成一个，实在想要多个的话，用`&nbsp;`代替

**Comment by webguosai** [comment]
好的
