### ISSUE TITLE
Bug with placeholder

### ISSUE THREAD

**Issue by Procrustes5** [imzbf/md-editor-v3#617]
### Describe the issue

When the placeholder is shown, there is cursor that has 2 line height. 

There is possibility it's just my mistake, but if not, I'd be willing to work on a solution !

### Example

https://github.com/user-attachments/assets/a1699e1e-7b15-4733-8e6d-797e41c8c4f0

### Procedure version

4.15.6

**Comment by imzbf** [comment]
Fixed in 4.18.1
