### ISSUE TITLE
MdEditor组件的preview属性不支持响应式数据吗？

### ISSUE THREAD

**Issue by huxiaofeng1983** [imzbf/md-editor-v3#621]
### Describe the issue

我定义了一个布尔类型的ref响应式数据，并使用ResizeObserver监听编辑器父容器的宽度变化，期望随着编辑器宽度变化决定是否展示预览界面，但当我用该ref数据设置preview属性时，通过打印日志可以看到ref数据可以实时更新，但编辑器界面的预览状态没有变化（我的ref数据初始值是false，编辑器的预览状态也一直是没有）

### Procedure version

4.17.4

**Comment by imzbf** [comment]
是的，需要手动切换参考这里的demo：https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%93%96%20togglePreview
