### ISSUE TITLE
MdCatalog组件目录点击没有反应

### ISSUE THREAD

**Issue by linyuanjie** [imzbf/md-editor-v3#623]
### Describe the issue

代码示例，麻烦帮忙看一下，谢谢
![image](https://github.com/user-attachments/assets/5d313cd5-9a61-4ebe-bba1-dd265deec86c)

### Procedure version

"md-editor-v3": "^4.15.2",

**Comment by linyuanjie** [comment]
版本更新到最近版本"md-editor-v3": "^4.18.0",
点击目录也是没有反应；

**Comment by linyuanjie** [comment]
滑动dom元素
![image](https://github.com/user-attachments/assets/7e04e5bd-fec0-4d00-afc1-bdb7b1c599ef)

**Comment by imzbf** [comment]
`editorId`就是基础`id`，这样设置冲突了，移除`id`属性

**Comment by linyuanjie** [comment]
移除id属性还是不行，我翻看了所有的MdCatalog issue,理解了不滚动还是scrollElement的绑定不对，每个人写的滚动条绑定可能会不一样，所以才会出现没有反应，我的这个这样给赋值之后就可以了，const scrollElement = ref('.h-full .n-scrollbar .n-scrollbar-container')
感谢楼主。
