### ISSUE TITLE
MdEditor组件数据回显响应式不支持嘛？

### ISSUE THREAD

**Issue by linyuanjie** [imzbf/md-editor-v3#625]
### Describe the issue

数据保存数据库，查询回显二次编辑再保存，发现查询到的数据回显组件不显示，不是双向绑定嘛？
需要怎么处理，回显数据如图中赋值后，在组件buxians不显示，
![image](https://github.com/user-attachments/assets/bf970c03-d01b-494e-b537-66c323ee95ee)

### Procedure version

    "md-editor-v3": "^4.18.0",

**Comment by imzbf** [comment]
是响应式的，你需要确定你的内容是否正确

**Comment by linyuanjie** [comment]
> 是响应式的，你需要确定你的内容是否正确

返回内容是这样的，应该是正确的。
markDownCn
: 
"# Hello Start Editor"

**Comment by linyuanjie** [comment]
这应该是有值的吧，
![image](https://github.com/user-attachments/assets/579b8644-d551-4f1f-83b0-bc75f0e716f2)

**Comment by linyuanjie** [comment]
找到问题了，得MDvalue.value才行，感谢感谢
