### ISSUE TITLE
增加音视频扩展模块

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#627]
### A great idea

希望增加音mp3/视频mp4扩展模块，模块功能可以跟图片上传模块类似

**Comment by imzbf** [comment]
这个没有内置的原因是音、视频格式不统一，可能需要专用的播放组件，而非直接使用video标签就可以播放

目前支持嵌入iframe视频，例如youtube、bilibili等的分享嵌入代码，在多数情况这种方式比较方便一点。

如果确实需要的话，建议参考[NormalToolbar](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%A3%20NormalToolbar)的扩展示例，按需实现

**Comment by bintheext** [comment]
> 这个没有内置的原因是音、视频格式不统一，可能需要专用的播放组件，而非直接使用video标签就可以播放
> 
> 目前支持嵌入iframe视频，例如youtube、bilibili等的分享嵌入代码，在多数情况这种方式比较方便一点。
> 
> 如果确实需要的话，建议参考[NormalToolbar](https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%A3%20NormalToolbar)的扩展示例，按需实现

好的，感谢回答
