### ISSUE TITLE
关闭输入提示 # 后的弹框 和 全屏问题

### ISSUE THREAD

**Issue by maoruibin** [imzbf/md-editor-v3#629]
### Describe the issue

1. 默认输入#后会自动弹框，我如何可以关闭这个，因为我想输入#后弹出我自己的辅助窗口。
2. 点击全屏后，整个页面都是编辑器页面，此时工具栏上我自定义了一个按钮，点击按钮需要显示一个 element-UI 中的 对话框，发现被挡住了，我可以限制全屏后的展示区域吗，或者你有什么好的方案 推荐吗？
感谢 🙏

### Procedure version

4.17.3

### Reproduction link

https://inbox.gudong.site/#/

**Comment by maoruibin** [comment]
补充一个问题，我现在想在 toolabr 和 输入区域之间插入一个输入框，这个是不是目前也不支持，对此你有什么好的建议吗？

**Comment by imzbf** [comment]
- [ ] 目前禁用默认的，然后启用自己的输入提示操作比较麻烦，作者尝试调整后给出文档。

关于第二点，样式的问题，你只需要提高相应的UI组件的z-index。

**Comment by imzbf** [comment]
在toolbar与输入框之间是没有插槽可以使用的，目前还没有拆分组件的计划，所以建议你考虑在布局上调整一下

**Comment by maoruibin** [comment]
ok  感谢解答，我准备自己调整样式
