### ISSUE TITLE
vue3 + vite

### ISSUE THREAD

**Issue by laoliya** [imzbf/md-editor-v3#63]
vue3 + vite可以使用吗

**Comment by imzbf** [comment]
这个项目就是`vue3`环境下的，它不挑构建工具，像`vite`、`webpack`等等。同时除了`vue3`的模板语法外，还是支持`jsx`的写法以及相当友好的`ts`。

**Comment by laoliya** [comment]
pnpm i md-editor-v3  出现需要先安装webpack
![0 `APOM4FVNA%UO(II)I)$P](https://user-images.githubusercontent.com/48370618/159836711-846af387-fa0a-4611-ace6-a8df2e2cebbc.png)

**Comment by imzbf** [comment]
这个不是这个组件需要的依赖项，你看他的提示。这个编辑器组件开发环境不依赖任何东西。

**Comment by laoliya** [comment]
好，我在排查下
