### ISSUE TITLE
代码组合渲染异常

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#633]
### 描述这个Bug

行号和文本内容没有对齐
![图片](https://github.com/user-attachments/assets/b2ac4456-d6d1-4f3a-855d-4439a0f2e2d9)

### 版本号

4.18.1

### 问题重现链接

https://imzbf.github.io/md-editor-v3/zh-CN/grammar#%F0%9F%97%84%20%E4%BB%A3%E7%A0%81%E7%BB%84%E5%90%88

**Comment by imzbf** [comment]
在这次[提交](https://github.com/imzbf/md-editor-v3/commit/42bf2ace9827f84aa9b989b8527d7fca3dbc6091)中修复了，已更新beta版本。

**Comment by bintheext** [comment]
> 在这次[提交](https://github.com/imzbf/md-editor-v3/commit/42bf2ace9827f84aa9b989b8527d7fca3dbc6091)中修复了，已更新beta版本。

4.19.0-3 还存在问题

**Comment by imzbf** [comment]
4.19.0中修复了这个问题

**Comment by bintheext** [comment]
![image](https://github.com/user-attachments/assets/ba4f86bc-42c5-4fc4-99af-2d662efd9cec)
官网示例，依旧没有解决

**Comment by imzbf** [comment]
这看起来只会在firefox中出现

**Comment by imzbf** [comment]
尝试4.19.1
