### ISSUE TITLE
onHtmlChanged onGetCatalog 会多次回调

### ISSUE THREAD

**Issue by wuhan-coder** [imzbf/md-editor-v3#635]
### 描述这个Bug

MdPreview 初始化的时候，会多次调用 onHtmlChanged onGetCatalog

### 版本号

4.18.0

**Comment by imzbf** [comment]
这是正常的，在异步获取到某些模块的编译库后哦，会重新渲染

**Comment by wuhan-coder** [comment]
好嘞，作者回复这么快，已经加了个临时变量，通过临时变量是否初始化解决了。
