### ISSUE TITLE
自定义扩展应用选中异常

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#636]
### 描述这个Bug

工具栏的自定义扩展选中时，阴影效果是比自带的扩展要高的
<img width="275" alt="image" src="https://github.com/user-attachments/assets/f8ad5bd2-02e8-47a5-803e-294565fea914">
<img width="126" alt="image" src="https://github.com/user-attachments/assets/76833ce3-a68b-4572-96b7-74b423fd6434">

### 版本号

4.19.0-3

**Comment by imzbf** [comment]
两者使用的图标方式不同，font的方式，也就是自定义扩展组件的图标，是通过限制宽高的，组件提供了图标的替换接口，可以考虑替换为svg的形式
