### ISSUE TITLE
目录锚点异常

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#637]
### Describe the issue

目录锚点，在只显示编辑器状态下，点击目录无任何响应，不确定这是bug还是特意设计。
<img width="1173" alt="image" src="https://github.com/user-attachments/assets/20a399fc-2c96-40fb-9cfd-c4567ddc9bdd">
上图是关闭预览情况下，点击目录，无滚动

### Procedure version

4.19.0-3

**Comment by imzbf** [comment]
目录只对预览内容区域有效，左右分栏时，是预览区域带动编辑区域滚动的
