### ISSUE TITLE
增加占位符

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#638]
### 一个很棒的想法

希望在从粘贴板复制上传图片时，能够显示占位符（就像github那样），这样写内容时也能知道有在上传图片

**Comment by imzbf** [comment]
这个暂时建议你在上传的事件中触发上传进度的提示，因为目前还没有很好的处理上传多个图片的方法以及在用户修改内容后，怎么匹配顺序的情况。
