### ISSUE TITLE
Use md-editor in offline server without cdn

### ISSUE THREAD

**Issue by geedys** [imzbf/md-editor-v3#639]
### Describe the issue

您好， 按照https://github.com/imzbf/md-editor-v3/discussions/294
中的方法，确实解决了问题，
但是当我使用ExportPDF插件时，打开编辑器依然会读取以下文件
> https://at.alicdn.com/t/c/font_2605852_cmafimm6hot.js

另外我的项目集成在Electron中，而且开启了CSP。
在切换主题dark->light,或者light->dark时也会去加载以下文件
> https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/atom-one-dark.min.css'

### Procedure version

Node：v22.5.1

**Comment by imzbf** [comment]
组件保留了动态切换代码主题时，动态加载highlight.js的样式的特性，这看起来不太正常，我会尝试丢弃这个特性

**Comment by imzbf** [comment]
4.19.0中修复了这个问题

**Comment by geedys** [comment]
> 4.19.0中修复了这个问题

感谢，解决了问题！

**Comment by geedys** [comment]
> 4.19.0中修复了这个问题

感谢，解决了问题！
