### ISSUE TITLE
应用在 vscode webview中不显示

### ISSUE THREAD

**Issue by gogangsta** [imzbf/md-editor-v3#64]
哈喽，我在vscode插件webview开发过程中（vscode webview也是使用chrome内核），使用md-editor-v3，页面不显示也不报错，打开调试工具-> Elements 找到对应地方显示 “<--v-if-->”，尝试使用过其他markdown编辑组件都是这样的情况，麻烦问一下大概是什么原因呢？ 

md-editor-v3版本: 1.11.3
vue版本: 3.2.31
webpack版本:  5.69.1

**Comment by imzbf** [comment]
这边写了一个简单的示例，发现可以显示编辑器组件，但在`1.11.5`版本之前图标链接不正常，计划在`1.11.6`中优化。附件是demo（dist内容使用`vite`或者`vue-cli`创建基础项目再安装编辑器组件，打包即可）。

![QQ图片20220406161512](https://user-images.githubusercontent.com/37092006/161928918-e1d31894-ff71-4986-a983-15a18794e128.png)

[md-editor-v3-vscode-extension.zip](https://github.com/imzbf/md-editor-v3/files/8425018/md-editor-v3-vscode-extension.zip)

**Comment by gogangsta** [comment]
感谢大佬，可能是我其他地方配置有问题，后面有时间我再找找原因，十分感谢！
