### ISSUE TITLE
可以把PDF文件导入编辑器，生成对应的编辑内容嘛？？？

### ISSUE THREAD

**Issue by linyuanjie** [imzbf/md-editor-v3#643]
### Describe the issue

现在组件有了导出ExportPDF文件功能，如果我们现在有一个PDF文件，我可以直接把PDF文件导入到md-editor-v3进行编辑修改调整文件内容嘛？

### Procedure version

"md-editor-v3": "^4.18.0",

**Comment by bintheext** [comment]
显然是不可以的，md-editor-v3不支持反向解析PDF

**Comment by linyuanjie** [comment]
> 显然是不可以的，md-editor-v3不支持反向解析PDF

那可以把PDF在导入的时候解析成html文件，再把文件内容再插入到编辑器里面可以嘛？

**Comment by imzbf** [comment]
html是支持的，但是内置了xss处理扩展，如果必须要这样做，你最好确认根据文档中的xss相关说明，去放开相应的html标签

**Comment by linyuanjie** [comment]
> html是支持的，但是内置了xss处理扩展，如果必须要这样做，你最好确认根据文档中的xss相关说明，去放开相应的html标签

Ok. thanks
