### ISSUE TITLE
mermaid 增加缩放按键/滚轮

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#644]
### 一个很棒的想法

mermaid 渲染的图片，我没有发现关于缩放的说明，在图片特别复杂、区域又特别小的情况下，渲染出来的图片很难看清，如果可以，增加一个缩放按键功能，会是个实用的提升。
![image](https://github.com/user-attachments/assets/ca72168a-1dbf-41d6-bd9a-b54ba9ed33b9)
就例如这幅图，基本很难看清

**Comment by imzbf** [comment]
这个需要找时间尝试一下，不确定一定能很好实现

**Comment by bintheext** [comment]
> 这个需要找时间尝试一下，不确定一定能很好实现
类似这样的实现
https://mermaid.live/edit#pako:eNptkT1vgzAQhv-Kc2sAOYD58JCqUoemUqduFYsFB1gCO3VstRTx32ug2eLp7HueV_LdDLVuEDjc8MuhqvFFis6IsVLEn-dB1hiez8c33StOXnEYNFnrgPT6mwiDZNLu6SG8Y7VQK0J6FIaM-I-uvdCj4eb4YLnbAblsxkZ77fAYv5AWcSCdQWEPEMCIZhSy8b-YV6EC2-OIFXBfNtgKN9gKKrV4VDirPyZVA7fGYQBGu64H3orh5m_u2gh7H8EduQoFfIYf4HFCozIu45yxU5yVLAlg8q80jQqWZwlLy4KmWVEsAfxq7QNolNM0oZTlZVbEeXZiW9zn1tzTsZFWm_d9CbVWrexg-QMhH3yC

**Comment by imzbf** [comment]
优秀的示例确实可以参考，单独拎出来是很好实现的，只是混合在markdown中，就不太一样了

**Comment by bintheext** [comment]
> 优秀的示例确实可以参考，单独拎出来是很好实现的，只是混合在markdown中，就不太一样了

emm，应该是可以在preview里面实现，隔离开markdown

**Comment by imzbf** [comment]
这个意思是只是单独的mermaid模块的话，可以采用组件化的思维封装一个缩放查看的功能。

可是这个编辑器的编译过程虽然有采用模块编译的方式，但是这种方式无法和各大前端框架的组件关联起来，这样就不得不让我们去对页面上已存在的内容做一些改变，比如本来没有的放大、缩小以及调整位置的按钮，我们就得采用原生方式把这些按钮添加进去，然后再考虑绑定事件，改变内容的位置等。

理论上是可以实现的，只是看要多久，要是有现成的，肯定就捡现成的用了

**Comment by bintheext** [comment]
或者说，为了降低难度；可以针对document.querySelectorAll('p.md-editor-mermaid') 这个标签的元素，增加滚轮缩放的功能

**Comment by imzbf** [comment]
比起使用滚轮和拖拽的话，按钮技术成本好像又更小一些，考虑在移动端的时候

**Comment by imzbf** [comment]
不过这种方式可以的话，倒是可以考虑直接导出一个util

**Comment by bintheext** [comment]
> 不过这种方式可以的话，倒是可以考虑直接导出一个util

看技术难度吧，如果太复杂的话，就没必要了，由用户个人实现就行

**Comment by bintheext** [comment]
> 比起使用滚轮和拖拽的话，按钮技术成本好像又更小一些，考虑在移动端的时候

移动端可以像图片一样，点击后悬浮框，支持双指缩放

**Comment by imzbf** [comment]
已在beta版本更新

**Comment by imzbf** [comment]
这个我也发现了，比较棘手，现在还没有解决方案，先beta着
