### ISSUE TITLE
目录加一个折叠？

### ISSUE THREAD

**Issue by xytx000** [imzbf/md-editor-v3#645]
### 一个很棒的想法

有些专栏类的，里面的内容可能会很多章节，多层标题的话有点显示的太多了，不显示还不太好，目录是不是能加个折叠功能的值，比如默认展开到第几层，其他都自动折叠进去

**Comment by imzbf** [comment]
抱歉，这个暂时不会去实现，目录组件只是一个协助使用的基础组件，更好的是方式通过事件获取目录列表，采用更优秀的导航组件来实现它，例如element-plus的锚点组件等，他们能够更好融入你的页面去
