### ISSUE TITLE
编辑器内部标题锚点点击异常

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#648]
### 描述这个Bug

官网示例可以复现：
点击目录正常跳转并滚动；点击编辑器内部预览标题，编辑区域滚动异常，并且编辑器外部会向上滚动-浏览器会出现外部滚动条（浏览器高度变化了）

https://github.com/user-attachments/assets/50411e4c-5546-46f2-a856-a9635e0509b8

### 版本号

4.19.1

### 问题重现链接
谷歌、火狐浏览器都可以复现
https://imzbf.github.io/md-editor-v3/zh-CN/index

**Comment by imzbf** [comment]
文档为了演示能够标题作为瞄点，点击标题会给路径加上hash，和vue的路由模块有点冲突。如果你需要类似的功能，自行处理一下就可以，这不是编辑器的问题
