### ISSUE TITLE
[Feature Request] 希望增加在新标签打开外部链接的功能

### ISSUE THREAD

**Issue by yzqdev** [imzbf/md-editor-v3#65]
默认情况下渲染出来的html都是在当前页打开外部链接.但有时候需要新开一个tab来显示链接内容,同时保留当前渲染的内容  
可以用一个`openLinkInNewTab`来控制是否在新标签页打开外部链接(默认在当前页打开外部链接)

**Comment by imzbf** [comment]
marked的扩展的开发计划后续统一，不再另外新增编辑器的prop属性，预计在下个功能版本中体现

**Comment by yzqdev** [comment]
收到,感谢大佬做出这么好用的工具

**Comment by imzbf** [comment]
2.0版本现在可以完全自行扩展类似的功能了，可以参考下文档的示例，有新窗口打开页面的示例

**Comment by yzqdev** [comment]
好的,谢谢大佬
