### ISSUE TITLE
添加禁用某个markdown特性的设置

### ISSUE THREAD

**Issue by kuige** [imzbf/md-editor-v3#656]
### 一个很棒的想法

markdown的渲染，可以支持禁用某项特性吗？例如不想渲染删除线，~~ test ~~ 这种要原样展示，可以支持吗？

有个`markdownItConfig`的配置，但不起作用
```
markdownItConfig(mdit) {
    mdit.renderer.rules.del = function (tokens, idx, options, env, self) {
      return self.renderInline(tokens[idx].children || [], options, env);
    };
  },
```

**Comment by imzbf** [comment]
方式不对。

```
mdit.disable(['strikethrough']);
```

不清楚你的具体需求，建议不禁用，使用行内代码来保留文本。

下个版本会使用`~~`来替换下标，可能你需要同时禁用它才能完全展示`~~~~`

**Comment by kuige** [comment]
> 方式不对。
> 
> ```
> mdit.disable(['strikethrough']);
> ```
> 
> 不清楚你的具体需求，建议不禁用，使用行内代码来保留文本。
> 
> 下个版本会使用`~~`来替换下标，可能你需要同时禁用它才能完全展示`~~~~`

可以了，行内代码保留文本的方式是怎样的？使用~~来替换下标之后要怎么处理？

**Comment by imzbf** [comment]
参考文档中的行内代码说明
