### ISSUE TITLE
mermaid 中无法使用数学公式 

### ISSUE THREAD

**Issue by shadowmas** [imzbf/md-editor-v3#657]
### 描述这个Bug

https://mermaid.js.org/config/math.html 中的示例

```mermaid
sequenceDiagram
    autonumber
    participant 1 as $\alpha$
    participant 2 as $$\beta$$
    1->>2: Solve: $$\sqrt{2+2}$$
    2-->>1: Answer: $$2$$
    Note right of 2: $$\sqrt{2+2}=\sqrt{4}=2$$
```
无法正常渲染其中的公式
![image](https://github.com/user-attachments/assets/c6b85fb5-bd7c-4608-af71-a8f99dfae6da)

### 版本号

4.17.4

**Comment by imzbf** [comment]
这种写法是不受支持的
