### ISSUE TITLE
MdCatalog 中标题中的公式无法显示

### ISSUE THREAD

**Issue by shadowmas** [imzbf/md-editor-v3#658]
### 描述这个Bug

![image](https://github.com/user-attachments/assets/2df54473-338e-4da3-bd7f-33889209dc29)

![image](https://github.com/user-attachments/assets/ff82c7c7-243e-4c33-8241-cfe3a2c3d4c4)

### 版本号

4.17.4

**Comment by imzbf** [comment]
复杂的内容在目录中是无法回显，我会统一为纯文本展示标题

**Comment by imzbf** [comment]
4.20.0调整了该问题，现在会正确显示未编译的标题内容
