### ISSUE TITLE
mermaid 增加短暂边框

### ISSUE THREAD

**Issue by bintheext** [imzbf/md-editor-v3#660]
### 一个很棒的想法

现在的mermaid，在进行缩放时，没有一个边框作为区域指示，希望在进行缩放、拖动操作时，出现一个指示边框（浅色），框住当前的mermaid区域，在停止操作后，自动隐藏

https://github.com/user-attachments/assets/3865a2fa-47ef-4f88-a062-8bb745f6faf3

**Comment by imzbf** [comment]
在实现的时候也有考虑这个问题，但是取消掉了，原因是尽可能保留原来的阅读样子。如果我单独加上，有伙伴也会提出异议，所以这类样式问题，建议根据自己的喜好来覆盖。
