### ISSUE TITLE
如何自定义目录的样式

### ISSUE THREAD

**Issue by kuailemao** [imzbf/md-editor-v3#661]
### Describe the issue

请问我想自定义目录的各种样式，该怎么实现

### Procedure version

^4.18.1

**Comment by imzbf** [comment]
自带的比较基础，这种情况的话就不建议你用了。通过[onGetCatalog](https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%97%92%20onGetCatalog)事件去获取目录，再使用你喜欢的锚点组件去渲染

**Comment by kuailemao** [comment]
哦哦好的，我前面试了一下用:deep()修改自带的元素样式也可以修改一些基本的样式，只不过自定义样式还是有不少限制，使用onGetCatalog显然可以更大程度的自定义，我去尝试一下，感谢回复！！！
