### ISSUE TITLE
文档的点击标题和右侧的导航有自带嘛

### ISSUE THREAD

**Issue by Danyhug** [imzbf/md-editor-v3#663]
### Describe the issue

软件文档中的点击标题和右侧的导航有自带嘛
![image](https://github.com/user-attachments/assets/537921bf-91bb-4896-a9bd-1b0357d6917d)

### Procedure version

4.19.2

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%90%BB%20MdCatalog

有，参考文档使用
