### ISSUE TITLE
无法支持这种mdit插件

### ISSUE THREAD

**Issue by ijry** [imzbf/md-editor-v3#665]
### 描述这个Bug

默认use只支持传递plugin和options，实际上mdit.use支持这种3参数用法，典型的是这个插件https://github.com/markdown-it/markdown-it-container。

### 版本号

4.12.9

**Comment by imzbf** [comment]
markdownItPlugins虽然不满足使用，但是这种特殊情况，可以直接使用markdownItConfig，第一个入参就是md-it实例，直接调用md.use方法

**Comment by ijry** [comment]
markdownItConfig这个是哪里的方法，文档查不到？
