### ISSUE TITLE
可以支持代码块选项组功能吗，code-group

### ISSUE THREAD

**Issue by xutao-o** [imzbf/md-editor-v3#666]
### 一个很棒的想法

不同语言的代码块组进行tab切换
![image](https://github.com/user-attachments/assets/a98a527a-d8f4-4235-a0f6-24b6607a0747)

**Comment by imzbf** [comment]
现在支持的，语法参考：https://imzbf.github.io/md-editor-v3/zh-CN/grammar#%F0%9F%97%84%20%E4%BB%A3%E7%A0%81%E7%BB%84%E5%90%88

**Comment by xutao-o** [comment]
> 现在支持的，语法参考：[https ://imzbf.github.io/md-editor-v3/zh-CN/grammar#%F0%9F%97%84%20%E4%BB%A3%E7%A0% 81%E7%BB%84%E5%90%88](https://imzbf.github.io/md-editor-v3/zh-CN/grammar#%F0%9F%97%84%20%E4%BB%A3%E7%A0%81%E7%BB%84%E5%90%88)

好的，感谢！
