### ISSUE TITLE
I am having performance issues

### ISSUE THREAD

**Issue by thaycacac** [imzbf/md-editor-v3#670]
### Describe the issue

Currently my performance score on PageSpeed ​​Insights is very low, and I am using the library with nuxt
As I upgrade to new version, it becomes heavier.
Do we have a plan to have a version to optimize performance?
Or can you suggest me ways to optimize performance?

### Procedure version

nodejs 20.5.1

**Comment by imzbf** [comment]
The analysis page should provide optimization suggestions for you. I used it on my site to analyze two article URLs. By comparing the results it provided, we can see that what mostly affects the score are images and unused large JavaScript libraries (such as Mermaid). My suggestion is to optimize the size of the images or implement lazy loading for them, as well as disable libraries you're not using via `noXXX`.

![image](https://github.com/user-attachments/assets/d904e7aa-442c-4b2c-9c0d-9edf8c7a8cbf)
![image](https://github.com/user-attachments/assets/db80a64b-be0d-4b1c-99a7-352abe5c03fb)
