### ISSUE TITLE
It seems to be a style bug

### ISSUE THREAD

**Issue by Magic44** [imzbf/md-editor-v3#671]
### 描述这个Bug

# Env
Acro Design Pro
Node v18.19.1
Vue 3

# Desc
  When the editor component is put in a modal, the bug happens like the following pic
![image](https://github.com/user-attachments/assets/42efde5f-706e-462b-b3ae-8c672ae3bb30)
![image](https://github.com/user-attachments/assets/b34e12a8-2442-44cd-8bd8-4ac50e4457f6)

### 版本号

Acro Design Pro ; Node v18.19.1; Vue 3

**Comment by imzbf** [comment]
I don't think this is an issue with the component.

<img width="1391" alt="image" src="https://github.com/user-attachments/assets/83d6b850-351f-4f16-8b3d-b60fc49b61ab">
