### ISSUE TITLE
如何获取cursor

### ISSUE THREAD

**Issue by Qingluan** [imzbf/md-editor-v3#674]
### 一个很棒的想法

建议加一个getCursor

**Comment by imzbf** [comment]
你可以通过`getEditorView`获取到`codemirror`的实例，之后调用它的api都可以获取到

**Comment by Qingluan** [comment]
谢谢，但是我试了getEditorView.getCursor() 没有这个方法

zbf ***@***.***> 於 2024年9月24日 週二 下午2:45寫道：

**Comment by imzbf** [comment]
codemirror获取光标位置的api不是叫这个名字，可以尝试`editorRef.value?.getEditorView()?.state.selection`，更具体的你需要查阅它的文档。
