### ISSUE TITLE
请问 如何开启 mermaid 的缩放、拖动效果

### ISSUE THREAD

**Issue by webguosai** [imzbf/md-editor-v3#675]
### Describe the issue

我看到 https://imzbf.github.io/md-editor-v3/zh-CN/index 的 mermaid 有缩放、拖动效果
而我本地没有缩放、拖动效果

### Procedure version

md-editor-v3@4.16.9

**Comment by imzbf** [comment]
更新一下就可以了，这个是[v4.19.2](https://github.com/imzbf/md-editor-v3/releases/tag/v4.19.2)的功能
