### ISSUE TITLE
文本里面包含超链接时，a标签转化有误,具体可查看下方图片

### ISSUE THREAD

**Issue by hanruigit** [imzbf/md-editor-v3#679]
### 描述这个Bug

![企业微信截图_20240925092021](https://github.com/user-attachments/assets/bc2976e4-5027-464c-9b8d-fc8a6f32edde)
文案：
河北师范大学的教师教学发展中心是一个独立设置的机构，挂靠在人事处。该中心致力于教师的专业发展，提供全方位的培训和支持。中心的组织架构包括刘艳房，作为常务副主任和主任，负责全面工作；张旭云作为副主任，负责具体工作；董凯静，作为高级经济师，负责河北师范大学的教师培训；刘宁，助理研究员，也负责教师培训工作；此外，还有郝艳梅，作为副教授，主要负责中心的办公室工作。

中心的工作内容围绕教师发展需求，通过整合校内外资源，提供交流平台，促进教师职业发展的各个阶段，包括新入职教师的多维度培训，青年教师的进阶式培养，中青年教师的教学创新和综合素质提升，以及全校教师的专项培训。他们实施了“三全两建一研究”的培养体系，旨在提升教师的教学和科研能力，以及人才培养质量。

河北师范大学教师教学发展中心的网址是https://jsfzzx.hebtu.edu.cn/，同时他们还有一个教师发展或培训平台，网址是https://fd.enetedu.com/hebtu/portal/，供教师们访问和使用。

如果你需要更详细的信息或者有具体的问题，可以访问上述提供的网址，或者直接联系中心的工作人员。

### 版本号

4.20.1

### 问题重现链接

官网首页即可复现问题https://imzbf.github.io/md-editor-v3/en-US/index

**Comment by imzbf** [comment]
如果你的超链接后面不是非空文本（符号、文字等），是会被视为链接的一部分的，只需要链接后面打一个空格。

如果你无法让写文章的人能够遵循链接后面打个空格的规则，建议关闭自动是被超链接的功能，将非标准语法（`[xxx](xxx)`这种）的链接显示为普通文本，禁用方式参考：https://github.com/imzbf/md-editor-v3/issues/651#issuecomment-2311422751
