### ISSUE TITLE
上传图片时的callback回传失效

### ISSUE THREAD

**Issue by kaichundaily** [imzbf/md-editor-v3#680]
### 描述这个Bug

上传图片时，已经成功上传并且已经打印出图片链接，但callback并没有把图片显示在编辑器上取而代之的是![](Underfine)
![image](https://github.com/user-attachments/assets/fc7106e8-9424-451d-88bc-74aab6c7be7f)
这是我的上传代码
![image](https://github.com/user-attachments/assets/dcd9a90e-4e37-4fbd-9c87-723162fec247)
这是一些配置

### 版本号

^4.19.1

**Comment by kaichundaily** [comment]
console.log是可以成功打印出图片链接的

**Comment by imzbf** [comment]
回调入参是数组才行

**Comment by kaichundaily** [comment]
入参是数组回参也是数组，感觉就很奇怪

**Comment by imzbf** [comment]
result.data.imgUrl是个数组？

**Comment by kaichundaily** [comment]
是个字符串

**Comment by kaichundaily** [comment]
![image](https://github.com/user-attachments/assets/9fd955d3-2c0a-437d-86f6-9f92a266fd74)
我给改了套了一个[]
