### ISSUE TITLE
代码块长的时候默认收起了，这个可不可以默认不收起啊？

### ISSUE THREAD

**Issue by aQ-TuTu** [imzbf/md-editor-v3#681]
### Describe the issue

代码块长的时候默认收起了，这个可不可以默认不收起啊？

### Procedure version

4.17.4

**Comment by imzbf** [comment]
参考https://imzbf.github.io/md-editor-v3/en-US/docs#%F0%9F%95%B9%20codeFoldable

**Comment by aQ-TuTu** [comment]
ok 感谢
