### ISSUE TITLE
工具栏显示中文时不居中和

### ISSUE THREAD

**Issue by aQ-TuTu** [imzbf/md-editor-v3#682]
### Describe the issue

工具栏显示中文时不居中和
<img width="322" alt="1727258900617" src="https://github.com/user-attachments/assets/32f0474c-92e4-4a46-8875-bb390f3c2c70">

### Procedure version

4.17.4

**Comment by aQ-TuTu** [comment]
更新到4.3.0版本问题解决了

**Comment by imzbf** [comment]
fixed in 4.20.3
