### ISSUE TITLE
Cursor position becomes fixed when scrolling

### ISSUE THREAD

**Issue by Procrustes5** [imzbf/md-editor-v3#685]
## Description
When using the text editor library, the cursor's position becomes fixed (like `position: fixed` in CSS) when scrolling the page. This causes the cursor to appear in an incorrect position relative to the text, rather than staying aligned with the actual text position.

## Steps to Reproduce
1. Open the text editor
2. Place the cursor at any position within the text
3. Scroll the page up or down
4. Observe that the cursor remains fixed on the screen instead of moving with the text

## Expected Behavior
The cursor should remain aligned with its position in the text, moving along with the text as the page is scrolled.

## Actual Behavior
The cursor remains fixed in its screen position, becoming misaligned with its actual position in the text.

## Environment
- Library version: v4.18.1
- Browser: Firefox
- Operating System: Windows 10
 (it also occurs on Mac M3 and Chrome)

## Additional Information
https://github.com/user-attachments/assets/b5b41656-8eff-4461-b60b-86f4db741d68

## Possible Causes
This issue might be related to how the cursor positioning is calculated or updated during scroll events. It appears that the cursor's position is not being properly recalculated relative to the scrolled content.

### Procedure version

4.18.1

**Comment by imzbf** [comment]
Can you reproduce this issue on your browser and on [this page](https://imzbf.github.io/md-editor-v3/en-US/index)? If not, I  need you to provide an example that fully replicates the problem.

**Comment by Procrustes5** [comment]
@imzbf 
Thank you for reply!

I apologize, this might not be directly related to the library. I was able to reproduce this bug when setting max-height with CSS on the editor component. Are there any other ways to specify max-height?

**Comment by imzbf** [comment]
Hmm there are no other ways to set it up
