### ISSUE TITLE
`mermaid@11.x`图表无法正常显示文字

### ISSUE THREAD

**Issue by nijinekoyo** [imzbf/md-editor-v3#688]
### 描述这个Bug

在使用外部依赖引入`mermaid`后，图表无法正常显示文字
![image](https://github.com/user-attachments/assets/61a14f3c-c8cb-4d95-b352-196521b047cc)

``` vue
<template>
        <md-editor v-model="text" autoDetectCode noIconfont :toolbars="toolbar" :style="{ height: height }">
        </md-editor>
</template>

<script setup lang="ts">
...
import { config, MdEditor } from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
import mermaid from 'mermaid';

config({
    // 替换扩展库
    editorExtensions: {
        mermaid: {
            instance: mermaid
        }
    }
    ...
});

...
</script>
```

### 版本号

node: v20.5.1
md-editor-v3: 4.20.2
mermaid: 11.2.1

**Comment by imzbf** [comment]
`mermaid@11`存在问题，参考这个 https://github.com/mermaid-js/mermaid/issues/5904 解决，等等`mermaid`官方修复。没有特殊要求的话，建议使用`mermaid@10`

**Comment by nyancatda** [comment]
原来如此
非常感谢

**Comment by nijinekoyo** [comment]
原来是这样，我在mermaid的ieeues搜no text没搜到所以还以为是这边的问题（
