### ISSUE TITLE
如何修改 编辑区域 标题样式

### ISSUE THREAD

**Issue by shadowmas** [imzbf/md-editor-v3#690]
### Describe the issue

如何修改 编辑区域 标题样式
![image](https://github.com/user-attachments/assets/bb051e6a-69e7-4050-9459-33f07201041a)
打包后类名发生了变化

### Procedure version

4.17.4

**Comment by imzbf** [comment]
只有写css覆盖，用codemirror主题的方式很繁琐。

**Comment by imzbf** [comment]
给个项目demo看看
