### ISSUE TITLE
如何插入自定义样式的html代码

### ISSUE THREAD

**Issue by adrianlx** [imzbf/md-editor-v3#696]
### Describe the issue

在model-value中传入markdown字符串中如果包含自定义的html代码片段，比如```<div class='myclass'>text</div> ```那么在最终的呈现阶段div的class会被丢弃，我无法根据class在其中注册事件或者自定义样式。也许是我方法有误，请指导我该如何做。

### Procedure version

latest

**Comment by imzbf** [comment]
xss问题，参考这个：https://github.com/imzbf/md-editor-v3/issues/476#issuecomment-2005686961
