### ISSUE TITLE
Label missing on Input for Modal Clip

### ISSUE THREAD

**Issue by ikkysleepy** [imzbf/md-editor-v3#697]
### Describe the issue

Thanks for fixing the ADA Issues with the inputs. I have one more in the clip modal

```
/packages/MdEditor/layouts/Modals/Clip.tsx
```

Here is a possible fix, but please adjust, if necessary:

line 201:
```
        <label
          for={`${editorId}_clip_label`}
          style={{ display: 'none' }}
          aria-label={ult.value.imgTitleItem?.upload}
        ></label>
        <input
          id={`${editorId}_clip_label`}
          ref={uploadRef}
          accept="image/*"
          type="file"
          multiple={false}
          style={{ display: 'none' }}
        />
```

### Procedure version

4.21.0

**Comment by imzbf** [comment]
Okay, I'll find the time to check it again. I've been quite busy lately.

**Comment by imzbf** [comment]
Basic attributes have been added in version 4.21.1, including those for menus.
