### ISSUE TITLE
路由切换后引入的 CDN 资源并未移除

### ISSUE THREAD

**Issue by shadowmas** [imzbf/md-editor-v3#698]
### 描述这个Bug

预览组件中使用了 highlight.js、Katex 等 cdnjs.cloudflare.com 上的资源。路由切到其它页面后 , 这些资源依然在 header 内

### 版本号

4.20.4

**Comment by imzbf** [comment]
特意保留了这个特性，考虑到多个组件可能会同时使用到编辑器组件，重复嵌入会产生麻烦。如果这个对你造成很大的困扰的话，建议参考这个[示例](https://imzbf.github.io/md-editor-v3/zh-CN/demo#%F0%9F%99%8D%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20%E8%87%AA%E8%A1%8C%E5%BC%95%E5%85%A5%E6%89%A9%E5%B1%95%E5%BA%93)取消使用CDN，采用本地依赖的方式去添加这些库。
