### ISSUE TITLE
TOC以及工具栏

### ISSUE THREAD

**Issue by vains-Sofia** [imzbf/md-editor-v3#7]
请问是否可以添加 TOC 生成目录的功能？工具栏是否可以自定义图标与回调事件？

**Comment by imzbf** [comment]
> 请问是否可以添加 TOC 生成目录的功能？工具栏是否可以自定义图标与回调事件？

生成目录功能在dev中已开发，使用`onGetCatalog`获取内容扁平结构的标题，工具栏目前没有所描述的功能，会考虑在下一个版本之前添加进来。
