### ISSUE TITLE
关于预览设置的控制台报错

### ISSUE THREAD

**Issue by Wlssn** [imzbf/md-editor-v3#70]
为了一开始不显示右边的预览界面就设置了 preview="false" ，然后点击工具栏的预览图标，能正常展示预览界面，但是控制台会报错（继续输入的时候也会报这个错）
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'removeEventListener')
    at md-editor-v3.js?v=565c72b1:893:12
    at md-editor-v3.js?v=565c72b1:4939:9`

会不会有什么影响

**Comment by imzbf** [comment]
在`v1.11.5`中修复了该问题，试试看~
