### ISSUE TITLE
video 标签支持问题

### ISSUE THREAD

**Issue by Peng1203** [imzbf/md-editor-v3#704]
### Describe the issue

我记得之前的版本 渲染是支持 video 标签的
最近更新了版本 发现渲染 video 标签有问题了
当前使用的是 **v4.16.3** 
![c9f93d1c308778b76934bc4974bd42b](https://github.com/user-attachments/assets/16f28448-ea56-475a-a6c9-238677a97f4d)

### Procedure version

md-editor-v3 4.16.3 node 18.13.0

**Comment by Peng1203** [comment]
<video
      loop
      autoplay
      controls
      src="xxx"
    ></video>
  改成这样没问题了 看了一下渲染 source 标签的内容被渲染成字符串了

**Comment by imzbf** [comment]
内置了xss扩展，参考：https://imzbf.github.io/md-editor-v3/en-US/demo#%F0%9F%94%93%20Remove%20XSS%20extension
