### ISSUE TITLE
MDPreview如何transformImgUrl ？

### ISSUE THREAD

**Issue by kagg886** [imzbf/md-editor-v3#708]
### Describe the issue

目前只在官网的MDEditor看到了这个属性，仍然不清楚MDPreview如何转换这种Image，
恳求解答，感激不尽！

### Procedure version

4.21.2

**Comment by imzbf** [comment]
预览组件不能转换，这个属性是提供给编辑的时候，替换外部链接使用的，我们默认在预览的时候就已经是正确的了。

如果你实在无法替换，你可以尝试替换markdown-it的图片扩展，通过markdownItPlugins找到type=image的扩展替换，内部使用的markdown-it-image-figures
