### ISSUE TITLE
如何禁用输入区AutoCompletion的弹窗

### ISSUE THREAD

**Issue by Rhaegal0411** [imzbf/md-editor-v3#710]
### Describe the issue

![image](https://github.com/user-attachments/assets/66588f43-4458-4f80-b650-7e9d9fdf6cab)
这个tooltip怎么禁用, 找了很久没有找到配置项

### Procedure version

4.11.1

**Comment by imzbf** [comment]
https://imzbf.github.io/md-editor-v3/zh-CN/docs#%F0%9F%A6%AA%20codeMirrorExtensions

提供的extensions最后一项就是输入提示的扩展，移除掉再返回

**Comment by Rhaegal0411** [comment]
感谢解答!!
