### ISSUE TITLE
单行 `$$` 行尾若有更多字符，显示失败，MathJax 则没问题。

### ISSUE THREAD

**Issue by vikyd** [imzbf/md-editor-v3#712]
### 描述这个Bug

能正常显示：
```
$$v \approx 900$$
```

未能正常显示：
```
$$v \approx 900$$ abcdef
```

⬇️ md-editor-v3 不能渲染后者：
<img width="907" alt="image" src="https://github.com/user-attachments/assets/1eef4783-dfb1-4a7b-bad0-a80e0eae11b3">

Github 官方使用的 MathJax 能渲染后者：

<img width="159" alt="image" src="https://github.com/user-attachments/assets/620740de-7097-44c5-95e0-6c792c3db98f">

https://markdown.com.cn/editor/ 也能渲染一部分：
<img width="717" alt="image" src="https://github.com/user-attachments/assets/ccb88727-2312-4374-9e7a-3b9923f35a96">

### 版本号

4.21.3

**Comment by vikyd** [comment]
@imzbf  目的是渲染大模型的回答，而非我们自己拼接出来的 Markdown 内容。

**Comment by vikyd** [comment]
字节的豆包 https://www.doubao.com/chat/ 也能相对正常的渲染出来。

**Comment by imzbf** [comment]
在5.0.1中修复了这个问题，请尝试

**Comment by vikyd** [comment]
试了下 5.0.1。

可以：
```
a
$$v \approx 900$$
a
```


但下面依然不行（结尾 $$ 后有【空格+字符】）：
```
a$$v \approx 900$$ a
```

**Comment by imzbf** [comment]
试试beta版是否还有问题，`npm i md-editor-v3@beta`

**Comment by vikyd** [comment]
@imzbf good, 可以了。

**Comment by vikyd** [comment]
但 `md-editor-v3@beta` 即 `5.0.2-0` 有另外的问题：顶部工具栏高度变得很小、图标也很小。

<img width="569" alt="image" src="https://github.com/user-attachments/assets/8f8febbe-d72d-45ac-966e-cfab63552da3">

**Comment by imzbf** [comment]
你检查一下你的图标和文档页面的图标css设置是否一致，不一致的话可能你项目有别的给覆盖了
