### ISSUE TITLE
可否支持一下mention 

### ISSUE THREAD

**Issue by liniu** [imzbf/md-editor-v3#713]
### 一个很棒的想法

是否可以支持mention @功能，并且可以自定义提示符，最好能同时支持多个，类似[tribute](https://github.com/zurb/tribute)。

使用场景，如在编辑过程中 输入":y",可以触发函数从后台中药库过滤药品下拉选择，  输入":z" 可以触发函数从后台症状库过滤症状下拉选择。

**Comment by imzbf** [comment]
从描述中感觉你可以参考 autocomplete 实现

https://imzbf.github.io/md-editor-v3/zh-CN/api#%F0%9F%93%9D%20completions
