### ISSUE TITLE
【Question】作为表单使用？

### ISSUE THREAD

**Issue by fu050409** [imzbf/md-editor-v3#719]
### Describe the issue

感谢您对于`md-editor-v3`的出色工作。

我将`md-editor-v3`与`primevue`结合使用，我希望能将`MdEditor`作为表单以将数据推送到服务器。但是文档中没有提及类似的方案，我尝试设置`name = "exmaple"`但没有奏效。

我们有考虑过作为表单使用的方法吗？或者这是由于我的某些疏漏？

### Procedure version

nodejs lts | Chrome latest

**Comment by imzbf** [comment]
编辑器没有可用的表单标签，你可以设置一个隐藏的input标签，将编辑的值与input标签绑定能实现

**Comment by fu050409** [comment]
啊……很抱歉这么晚回复。PrimeVue这边设置一个`type="hidden"`的标签（甚至不是`hidden`）并绑定同一个引用，这无法被识别，想来他们可能依赖于`name`参数，因为`MdEditor`与`input`共存时，我对`input`（未隐藏的）进行修改能够触发PrimeVue的事件，但是对绑定了同样数据的`MdEditor`不奏效。

我翻阅了`md-editor-v3`的源码，实现表单确实不是一个简单的事情，我现在放弃了使用[PrimeVue Forms](https://primevue.org/forms/#formfield-resolver。

总的来说感谢您的耐心回复 ：）

**Comment by gentingincubus** [comment]
你好 请问这个需求最终实现了吗 我现在也有这样的需求 要在AI回答里面插入表单项 让用户选了之后带到下一轮对话里

**Comment by imzbf** [comment]
> 你好 请问这个需求最终实现了吗 我现在也有这样的需求 要在AI回答里面插入表单项 让用户选了之后带到下一轮对话里

这功能似乎不需要表单支持？类似用户引用了AI某次的回答，这个引用动用你通过会话ID就能获取到对话内容，在下次对话携带上即可？

**Comment by gentingincubus** [comment]
> > 你好 请问这个需求最终实现了吗 我现在也有这样的需求 要在AI回答里面插入表单项 让用户选了之后带到下一轮对话里
> 
> 这功能似乎不需要表单支持？类似用户引用了AI某次的回答，这个引用动用你通过会话ID就能获取到对话内容，在下次对话携带上即可？

比如某个人需要出差 AI回答一份模板需要他填表格(可自行增删) 通过接口动态获取选项 填输入框 填数字等等表单的交互  这些表单项都嵌入在AI的回答中 用户填完后 只需要回答填好了就行 或者需要更详细的引导 AI再给出更详细的选项让用户选择

**Comment by imzbf** [comment]
> > > 你好 请问这个需求最终实现了吗 我现在也有这样的需求 要在AI回答里面插入表单项 让用户选了之后带到下一轮对话里
> > 
> > 
> > 这功能似乎不需要表单支持？类似用户引用了AI某次的回答，这个引用动用你通过会话ID就能获取到对话内容，在下次对话携带上即可？
> 
> 比如某个人需要出差 AI回答一份模板需要他填表格(可自行增删) 通过接口动态获取选项 填输入框 填数字等等表单的交互 这些表单项都嵌入在AI的回答中 用户填完后 只需要回答填好了就行 或者需要更详细的引导 AI再给出更详细的选项让用户选择

这种确实没有实现，目前只有把当前组件作为表单单项的方案，而在markdown中使用表单，可以考虑直接定义合适的表单的html源码嵌入到AI 回答的内容中，因为直接渲染html是受支持的
