### ISSUE TITLE
Slot inside the actual editor

### ISSUE THREAD

**Issue by DerSimeon** [imzbf/md-editor-v3#725]
### A great idea

It would be good to have a slot inside the editor, so we make changes to the actual text-input.
something like:
```vue
<template #editor class="bg-gray-600">
</editor>```

In my use-case we need to add a custom context menu that is only available inside the editor.

**Comment by imzbf** [comment]
The editing area is created using CodeMirror, and it's not possible to embed HTML into it via slots. The content area of the editor is managed by CodeMirror, so any custom HTML elements, such as a context menu, should be defined outside of the editor in other locations. You can adjust the position of your menu according to the following example to ensure it displays correctly where you need it.

```js
editorRef.value?.domEventHandlers({
  contextmenu(e) {
    // Consider displaying the menu or adjusting its position here.
    console.log('===', e);
  },
});
```

**Comment by DerSimeon** [comment]
Hmm That won't work for me unfortunately, I will have to find a different way then :/

**Comment by DerSimeon** [comment]
@imzbf would it be possible to add a slot around the CodeMirror div?
I am talking about this div: https://github.com/imzbf/md-editor-v3/blob/6de07c0790c6b24404e6478c12d91cc5c505ad65/packages/MdEditor/layouts/Content/index.tsx#L48

That way I can use my contextmenu properly as the domevent way won't work for me.
I need to prevent it from being triggered from the preview.

**Comment by imzbf** [comment]
https://github.com/imzbf/md-editor-v3/issues/725#issuecomment-2515897305

Event `contextmenu` in this code example will only be triggered in the editing area only; they will not be triggered during preview. 

What difficulties exist in obtaining the mouse position within event `contextmenu` to display a context menu?

**Comment by DerSimeon** [comment]
I am using a Component from Nuxt UI (https://ui3.nuxt.dev/components/context-menu) which handles the context menu on its own, including triggering the context menu.

**Comment by imzbf** [comment]
Even if there are slots, it seems that `input-wrapper` cannot be used as the default slot content for the `ContextMenu` component. Does this issue exist?

If the editor is used as the default slot content, it would be useful to have an API that allows setting which elements are inactive.
