### ISSUE TITLE
连续换行预览区无法正常渲染连续换行

### ISSUE THREAD

**Issue by ningmeng0503** [imzbf/md-editor-v3#726]
### Describe the issue

编辑区连续换行，在预览区却不会连续换行

### Procedure version

最新版

**Comment by ningmeng0503** [comment]
在文档的首页体验时出现这个问题：https://imzbf.github.io/md-editor-v3/zh-CN
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/8e663dee-dae6-467a-8ece-b1bac2019f1c">

**Comment by ningmeng0503** [comment]
<img width="1411" alt="image" src="https://github.com/user-attachments/assets/03bc631a-1508-4ab0-aeb7-1c91252c5d05">

**Comment by imzbf** [comment]
这个语法是正常的，多个回车只会保留一个换行

**Comment by ningmeng0503** [comment]
是否有扩展插件解决这个问题

**Comment by ningmeng0503** [comment]
> 这个语法是正常的，多个回车只会保留一个换行

有插件可以解决吗

**Comment by imzbf** [comment]
没有，只有考虑添加<br>作为额外的换行

**Comment by jagdtiger9** [comment]
> No, only consider adding `<br>`as extra line breaks

Hi, mate!
Are there any recomended way to do this, to keep multiple carriage returns as <br>s

**Comment by imzbf** [comment]
There's no elegant way to do, so we can only think about styling HTML tags for this purpose
