### ISSUE TITLE
自定义'collapse-tips'的图标没起作用

### ISSUE THREAD

**Issue by hengrong1** [imzbf/md-editor-v3#727]
### Describe the issue

在代码里自定义collapse-tips这个图标好像还是默认的

![image](https://github.com/user-attachments/assets/bfe37e06-e307-4d5f-b660-04ad7c055592)
![image](https://github.com/user-attachments/assets/09a107ed-a148-465c-8e89-1d57584e9444)

### Procedure version

5.0.2

**Comment by imzbf** [comment]
它是字符型的图标，我把类型定义错了， 不好意思

`'collapse-tips': 'eee'`

**Comment by imzbf** [comment]
在5.1.0中优化了提示
