### ISSUE TITLE
怎么判断Catalog能否生成目录

### ISSUE THREAD

**Issue by JayFans2000** [imzbf/md-editor-v3#728]
### Describe the issue

如果Catalog抓取的内容没有标题来生成目录，就会显得空荡荡的，有没有什么方法能够知道是否能生成目录呢，这样我可以隐藏掉目录。

现在的问题：
![image](https://github.com/user-attachments/assets/02fc19b8-78c8-4bac-b9d2-2da7e1091ded)
![image](https://github.com/user-attachments/assets/46658ed3-6e58-412d-8c64-90d4dce85f8b)

### Procedure version

4.18.1

**Comment by imzbf** [comment]
有额外的事件可以获取到目录列表，onGetCatalog
