### ISSUE TITLE
我使用vite构建后，提示错误

### ISSUE THREAD

**Issue by itmeicn** [imzbf/md-editor-v3#732]
### 描述这个Bug

 ➜  press h + enter to show help
X [ERROR] No matching export in "node_modules/.pnpm/vue@3.4.38_typescript@5.5.4/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "useId"

    node_modules/.pnpm/md-editor-v3@5.1.0_@codemirror+view@6.35.3_@lezer+common@1.2.3_vue@3.4.38_typescript@5.5.4_/node_modules/md-editor-v3/lib/es/chunks/index.mjs:1:155:
      1 │ import { inject, onMounted, watch, toRef, nextTick, shallowRef, ref, computed, onBeforeUnmount, defineComponent, createVNode, Fragment, reactive, provide, useId } from "vue";
        ╵                                                                                                                                                            ~~~~~

17:24:33 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/md-editor-v3@5.1.0_@codemirror+view@6.35.3_@lezer+common@1.2.3_vue@3.4.38_typescript@5.5.4_/node_modules/md-editor-v3/lib/es/chunks/index.mjs:1:155: ERROR: No matching export in "node_modules/.pnpm/vue@3.4.38_typescript@5.5.4/node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "useId"
    at failureErrorWithLog (D:\company_python\aiTools1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1472:15)
    at D:\company_python\aiTools1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:945:25
    at D:\company_python\aiTools1\node_modules\.pnpm\esbuild@0.21.5\node_modules\esbuild\lib\main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### 版本号

5.1.0

**Comment by imzbf** [comment]
5.0.0开始需要安装vue3.5.3以上
