### ISSUE TITLE
Reload Page Error Katex Rendering

### ISSUE THREAD

**Issue by 0xPuddi** [imzbf/md-editor-v3#733]
### 描述这个Bug

I am correctly importing and initializing the Markdown plugin for my vue3 project, so much so that the markdown initializes correctly the latex string when i open the page for the first time, as an example:

```html
		<p data-line="2">
			You are given positive integers
			<span class="md-editor-katex-inline" data-processed=""
				><span class="katex"
					><span class="katex-mathml"
						><math xmlns="http://www.w3.org/1998/Math/MathML"
							><semantics
								><mrow><mi>N</mi></mrow
								><annotation encoding="application/x-tex"
									>N</annotation
								></semantics
							></math
						></span
					><span class="katex-html" aria-hidden="true"
						><span class="base"
							><span class="strut" style="height: 0.6833em"></span
							><span
								class="mord mathnormal"
								style="margin-right: 0.10903em"
								>N</span
							></span
						></span
					></span
				></span
			>
			...
```

but then when i refresh the markdown does not render the latex correctly anymore, it seems that it does not try to render it at all:

```html
<p data-line="2">
			You are given positive integers
			<span class="md-editor-katex-inline">N</span> and
			<span class="md-editor-katex-inline">K</span>, and a sequence of
			length <span class="md-editor-katex-inline">N</span>,
			<span class="md-editor-katex-inline">A=(A_1,A_2,\ldots,A_N)</span>.
			Extract all elements of
			<span class="md-editor-katex-inline">A</span> that are multiples of
			<span class="md-editor-katex-inline">K</span>, divide them by
			<span class="md-editor-katex-inline">K</span>, and print the
			quotients.
</p>
```

how can i make the markdown re-run manually the rendering? so that i can trigger a re-render when it does not render properly?

I cannot provide you with the repo as it is private and its visibility out of my reach
Thank you.

### 版本号

md-editor-v3: ^5.0.2, vue: ^3.5.12, @vitejs/plugin-vue: ^5.1.4, vite: ^5.4.10, and as component I am using MdPreview

**Comment by imzbf** [comment]
The editor provides a [rerender](https://imzbf.github.io/md-editor-v3/en-US/api#%E2%9C%92%EF%B8%8F-rerender) method to forcibly re-render the content. You can try using this method to see if it works for you.
