### ISSUE TITLE
传递一个目录高度，目录可以根据内容自动滚动么

### ISSUE THREAD

**Issue by yuxintao6** [imzbf/md-editor-v3#737]
### 一个很棒的想法

具体效果参考此篇博客的文章目录效果：https://blog.51cto.com/tntxia/12573824

上传图片功能，可以像WangEditer一样，图片可以拉伸大小么？

**Comment by imzbf** [comment]
目录那个是可以的，并且文档页面就是这种效果，你可以参考一下我的实现代码：https://github.com/imzbf/md-editor-v3/blob/dev-docs/layouts/Catalog/index.vue#L59

关于图片这个问题，这个组件无法支持，你可以考虑自定义扩展，上传后插入img标签，通过width和height手动去调整大小
