### ISSUE TITLE
最新版（5.1.1）里面关于列表项的::marker标签缺失

### ISSUE THREAD

**Issue by q564240849** [imzbf/md-editor-v3#740]
### 问题描述
在 md-editor-v3 的 新版本中，列表项渲染后的 HTML 中缺少了 ::marker 标签，而在 4.0.0 版本中是存在的。并且官网首页预览的地方，和在线尝试案例的https://codesandbox.io/p/sandbox/epic-bird-2znqo都是存在的。目前这个变化影响了列表项的样式展示。

### 版本信息
- 正常版本：4.0.0（有 ::marker 标签）
- 问题版本：5.1.1（无 ::marker 标签）

### 复现步骤
1. 创建使用 md-editor-v3 的 Vue 项目
2. 添加如下 markdown 列表：
```markdown
> 引用：《I Have a Dream》

1. So even though we face the difficulties of today and tomorrow, I still have a dream.
2. It is a dream deeply rooted in the American dream.
3. I have a dream that one day this nation will rise up.
- 项目1
- 项目2
- 项目3
```
3.在浏览器开发者工具中检查渲染后的 HTML
### 预期行为
列表项应该像 4.0.0 版本一样包含 ::marker 标签 在显示的地方，文字左侧有1.2.3.或者●占位
### 实际行为
4.1.1 版本中列表项缺少 ::marker 标签，文字左侧为空白

### 版本号

vue3 vite

**Comment by q564240849** [comment]
具体测试是从[v4.13.5](https://github.com/imzbf/md-editor-v3/releases/tag/v4.13.5)开始这个bug就存在了，是特意删除的吗

**Comment by kaneha** [comment]
我也是5.1.1版本, 无序列表不显示黑点,  有序列表不显示序号

**Comment by imzbf** [comment]
现在编辑器的样式中不再强制定义列表标签的序号类型了，一般出现这种情况是由于你的全局样式统一定义了该类型的标签，参考上面伙伴的方式进行调整

**Comment by q564240849** [comment]
> 我也是5.1.1版本，无序列表不显示黑点，村庄列表不显示序号。 原因看起来是样式被不知道什么东西覆盖成没有 我的解决方法：
> 
> ```vue
> <style scoped>
> :deep(ul li) {
>   list-style-type: disc;
> }
> :deep(ul li li) {
>   list-style-type: circle;
> }
> :deep(ul li li li) {
>   list-style-type: square;
> }
> :deep(ol li) {
>   list-style-type: decimal;
> }
> </style>
> ```

这个方法有用！谢谢！问题解决了
