### ISSUE TITLE
上传图片如果选择base64

### ISSUE THREAD

**Issue by Z-xiaoxuan** [imzbf/md-editor-v3#743]
### 一个很棒的想法

上传图片如果选择base64，可以只保留一行转译后的长度嘛

**Comment by imzbf** [comment]
保留一行的行只有让编辑区域出现横向滚动条才行，这样并不太美观，我试过折叠功能对这个不起作用。

显示横向滚动条的方式是通过`codeMirrorExtensions`移除第二入参`extensions`中下标为3的扩展项
