### ISSUE TITLE
上传图片的路径建议增加相对路径 动态设置图片的基础路径

### ISSUE THREAD

**Issue by xpfan** [imzbf/md-editor-v3#76]
上传图片的路径建议增加相对路径 动态设置图片的基础路径：
原因：上传的图片是本地后端服务器，后端服务器可能变更地址，那么难题来了，所有的文档都带的绝对路径，都无法显示图片了。
解决方案：
  给编辑器设置个图片的基础路径属性，可以动态绑定，所有上传的路径可以设置成基础路径也可以是绝对路径；如果上传后的图片路径为绝对路径，就不需要拼接基础路径；如果是相对路径，就将基础路径拼接上。
这样后端服务器图片上传服务器变动后，修改下基础路径，就能将图片渲染出来了。

**Comment by imzbf** [comment]
上传图片功能编辑器只提供选择的图片文件，上传成功后的地址，是开发者自行设置的，你需要把你想要的路径通过`onUploadImg`的回调函数返回

**Comment by xpfan** [comment]
知道onUploadImg这个是没有问题，上传时用这个函数。但是编辑文档里面我不想用绝对路径(如：http://xxxx/images/1)，我想用相对路径(如：/images/1)。对于前后端分离的项目，相对路径下，如果不使用nginx是无法显图片的。

**Comment by imzbf** [comment]
```js
async onUploadImg(files: FileList, callback: (urls: string[]) => void) {
  const res = await Promise.all(
    Array.from(files).map((file) => {
      return new Promise((rev, rej) => {
        const form = new FormData();
        form.append('file', file);

        axios
          .post('/api/img/upload', form, {
            headers: {
              'Content-Type': 'multipart/form-data'
            }
          })
          .then((res) => rev(res))
          .catch((error) => rej(error));
      });
    })
  );

  // =====这里的item.data.url返回相对路径就行了吧=====
  callback(res.map((item: any) => item.data.url));
}

```

**Comment by imzbf** [comment]
> 用的是相对地址, 但是如果调试阶段前后端分离, 域名和端口不一样,无法请求图片. 前端地址: localhost:5050 后端地址: localhost:8080
> 
> 所以建议添加设置图片资源请求基础路径

你在callback的时候，会批量处理图片

这样就解决了
```
callback(res.map((item: any) => `localhost:8080/${item.data.url}`));
```

现在的前端环境基本都有配置环境变量的，在环境中增加一个`IMG_PREFIX`的环境变量

```
const IMG_PREFIX = process.env.IMG_PREFIX; // 开发环境就是localhost:8080, 生产环境就是别的域名

callback(res.map((item: any) => `${IMG_PREFIX}/${item.data.url}`));
```

**Comment by lascyb** [comment]
遇到了同样的问题，前后端分离的项目，之前编辑文章时保存的图片都是 `http://example.com/img1.png` 形式的路径，现在计划所有图片迁移上CDN， 但是原来文章中的图片需要统一替换域名到`http://cdn.example.com`，编辑器能不能提供一个渲染图片时，图片src预处理的接口，这样我在保存图片的时候只需要保存图片的相对地址`/img1.png`，域名可以在渲染时自行拼接，就不用担心图片域名迁移的问题了

**Comment by lascyb** [comment]
> 遇到了同样的问题，前后端分离的项目，之前编辑文章时保存的图片都是 `http://example.com/img1.png` 形式的路径，现在计划所有图片迁移上CDN， 但是原来文章中的图片需要统一替换域名到`http://cdn.example.com`，编辑器能不能提供一个渲染图片时，图片src预处理的接口，这样我在保存图片的时候只需要保存图片的相对地址`/img1.png`，域名可以在渲染时自行拼接，就不用担心图片域名迁移的问题了

我研究了下markdown-it的插件，然后把问题解决了，详细信息可以看下这篇文章 [md-editor-v3 渲染时实现图片src预处理
](http://itfly.xyz/blog/article/read-12
)
