### ISSUE TITLE
vue 上引入后文字不能居左，一直居中显示

### ISSUE THREAD

**Issue by wzj760130613** [imzbf/md-editor-v3#78]
请问怎么将其设置成居左，当前一直默认居中，没有加任何配置

**Comment by imzbf** [comment]
你的全局样式影响了吧，debug看看你居中的样式哪儿来得

**Comment by wzj760130613** [comment]
感谢感谢，找到原因了，就是#App{}下的全局样式影响的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imzbf/md-editor-v3] vue 上引入后文字不能居左，一直居中显示 (Issue #78)





 
你的全局样式影响了吧，debug看看你居中的样式哪儿来得
