### ISSUE TITLE
目录跳转失败

### ISSUE THREAD

**Issue by 204065248** [imzbf/md-editor-v3#79]
我在gin-vue-admin 框架下使用这个组件 点击页面跳转没有任何反应，请问应该怎么解决呢

**Comment by imzbf** [comment]
看看你的代码怎么写的

**Comment by 204065248** [comment]
```js
<template>
  <div>
    <el-row :gutter="24">
      <el-col :span="21">
        <editor 
          v-model="state.context" 
          :editor-id="state.id"
          :theme="state.theme"
          previewOnly 
          previewTheme="default" 
          class="editor"
        >
        </editor>
      </el-col>
      <el-col :span="3">
        <el-affix :offset="120">
          <el-scrollbar height="500px">
            <Editor.Catalog
              :editor-id="state.id"
              :theme="state.theme"
              class="editor-catalog"
              :scrollElement="scrollElement"
            />
          </el-scrollbar>
        </el-affix>
      </el-col>
    </el-row>
  </div>
</template>
    
<script>
export default {
  name: 'AppList'
}
</script>

<script setup>
import { reactive } from 'vue'
import Editor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';
import apiDoc from ".\\apiDoc.md?raw"

const state = reactive({
  theme: 'light',
  context: '',
  id: 'my-editor'
});

const scrollElement = document.documentElement;

const initPage = async() => {
  state.context = apiDoc
}

initPage()

</script>
    
<style>
  .editor {
    padding: 50px 50px
  }

  .editor-catalog {
    padding: 10px 10px;
    background-color: white;
    min-height: 500px;
  }
</style>
```

**Comment by 204065248** [comment]
会不会是因为 gin-vue-admin是有路由的问题，滚动条滚动的目标不对

**Comment by imzbf** [comment]
设置为`document.documentElement`的时候，是需要你的内容滚动条是全局的，你尝试把`scrollElement`设置为文本真正的滚动区域元素试试，选择器和标签元素实例都可以

**Comment by imzbf** [comment]
> 会不会是因为 gin-vue-admin是有路由的问题，滚动条滚动的目标不对

可能是，一般来讲`admin`项目都只有中间内容区域在滚动

**Comment by 204065248** [comment]
不太行啊，我设置为父元素 还是 富文本编辑框还是 给他套一个div都跳转不了

**Comment by imzbf** [comment]
`scrollElement`的元素，要求是，要设置了`overflow`，并且改元素必须是已定位的元素

**Comment by 204065248** [comment]
我现在用element ui的 Scrollbar把编辑器包裹起来 然后scrollElement就是 Scrollbar 这个元素，也是没成功，
![image](https://user-images.githubusercontent.com/17307843/163337620-6da776a6-b93e-4830-b1da-67d43e8ce776.png)

**Comment by 204065248** [comment]
![image](https://user-images.githubusercontent.com/17307843/163338231-332c2437-9b21-4ff5-a946-1d81203f08a0.png)
这样是可以控制滚动条滚动的

**Comment by imzbf** [comment]
> 我现在用element ui的 Scrollbar把编辑器包裹起来 然后scrollElement就是 Scrollbar 这个元素，也是没成功， ![image](https://user-images.githubusercontent.com/17307843/163337620-6da776a6-b93e-4830-b1da-67d43e8ce776.png)

很明显ele的组件滚动的不是`.el-scrollbar`，需要设置了`overflow`为滚动的元素

**Comment by 204065248** [comment]
![image](https://user-images.githubusercontent.com/17307843/163339392-f408bb62-f23b-4602-bb6b-5a18aafbb19f.png)
这个也是不行的

**Comment by imzbf** [comment]
方便的话给一份可以运行的问题的代码，这边给看看

**Comment by 204065248** [comment]
环境是 gin-vue-admin 最新版本，在内容区域放了富文本编辑框，右侧是目录。源码不太方便给，抱歉了。目前我利用js解决了跳转，但是没有用到富文本的方法
