### ISSUE TITLE
输入链接及描述，点击确定，直接刷新页面是什么鬼

### ISSUE THREAD

**Issue by hwy2** [imzbf/md-editor-v3#8]
我使用的是vue3.0+el UI+ts,
md-editor的版本是1.4.1

用文档默认导入方法导入的md-editor，出现两个问题

1.点击链接，输入描述及链接，点击确定时确实在输入框显示相应的描述信息，但是过多一会就自动刷新当前页面，model也没有关闭

2.点击上传文件的时候，在选择文件时原本的弹出层，自动关闭

**Comment by imzbf** [comment]
能提供一下源码方便这边看一下问题吗

**Comment by hwy2** [comment]
页面：
   <md-editor
                v-model="content"
                @onHtmlChanged="methods.saveHtml"
                @onSave="methods.saveValue"
                @onUploadImg="methods.uploadImg"
                :preview="false"
              />
ts:
import MdEditor from "md-editor-v3";
import "md-editor-v3/lib/style.css";

const methods = {
      saveHtml(html: string) {
        console.log(html);
        state.article.content = html;
      },
      saveValue(v: string) {
        console.log(v);
        ElNotification({
          title: "成功",
          message: "保存成功",
          type: "success",
        });
      },
      async uploadImg(files: FileList, callback: (urls: string[]) => void) {
        const res = await Promise.all(
          Array.from(files).map((file) => {
            return new Promise((rev, rej) => {
              proxy.$axios
                .post("/common/enclosure", {
                  files: file,
                })
                .then((resp: any) => rev(resp))
                .catch((error: any) => rej(error));
            });
          })
        );
        callback(res.map((item: any) => item.result.url));
      },
    };

**Comment by hwy2** [comment]
> 能提供一下源码方便这边看一下问题吗

我在下一条写了，但是格式化没有了
![image](https://user-images.githubusercontent.com/40650839/131304325-1cd569fb-fe76-44a1-be6d-3a2e77f676d9.png)
![image](https://user-images.githubusercontent.com/40650839/131304396-f9ee8e17-d9de-49bf-b641-2d88ccc8a52f.png)

**Comment by imzbf** [comment]
方便提供一下一份项目的copy么，一个可以`clone`的仓库地址，这边直接尝试无法还原问题。还想了解一下你这边的`node`、系统及浏览器版本

**Comment by hwy2** [comment]
> 方便提供一下一份项目的copy么，一个可以`clone`的仓库地址，这边直接尝试无法还原问题。还想了解一下你这边的`node`、系统及浏览器版本

https://github.com/hwy2/blog.git 这个是我的项目地址，在 front-end\blog\src\views\backstage\writingArticles里面的vue文件是这次引用当前项目的地方

**Comment by imzbf** [comment]
> https://github.com/hwy2/blog.git 这个是我的项目地址，在 front-end\blog\src\views\backstage\writingArticles里面的vue文件是这次引用当前项目的地方

这边启动尝试了一下，但页面存在一些错误，没有后端服务，在把相应的错误代码注释后，就可以使用了，下面是调试代码，你那边看看项目中是不是有错误项没有修正。

```
<template>
  <md-editor
    v-model="content"
    @onHtmlChanged="methods.saveHtml"
    @onSave="methods.saveValue"
    @onUploadImg="methods.uploadImg"
  />
</template>
<script lang="ts">
import {
  defineComponent,
  reactive,
  toRefs,
  onMounted,
  onBeforeMount,
} from 'vue';
import MdEditor from 'md-editor-v3';
import 'md-editor-v3/lib/style.css';

export default defineComponent({
  name: 'home',
  components: {
    MdEditor,
  },
  setup: () => {
    const state = reactive({
      // vue2.x的data参数
      content: '', // 富文本编辑框
      checkboxGroup: ['默认'],
      article: {
        title: '',
        content: '',
        photo: '',
        state: '1',
        abstract: '',
        pageview: 0,
        ishot: false,
      },
      rulesArticle: {
        title: [
          { required: true, message: '请输入标题', trigger: 'blur' },
          {
            max: 255,
            message: '最长为 255 个字符',
            trigger: 'blur',
          },
        ],
        content: [
          { required: true, message: '请输入文章内容', trigger: 'blur' },
        ],
        photo: [{ required: false, message: '请输入链接', trigger: 'blur' }],
        abstract: [
          { required: true, message: '请输入摘要', trigger: 'blur' },
          {
            max: 255,
            message: '最长为 255 个字符',
            trigger: 'blur',
          },
        ],
      },
    });

    const methods = {
      saveHtml(html: string) {
        console.log(html);
        state.article.content = html;
      },
      saveValue(v: string) {
        console.log(v);
      },
      async uploadImg(files: FileList, callback: (urls: string[]) => void) {
        const res = await Promise.all(
          Array.from(files).map((file) => {
            return new Promise((rev, rej) => {
              //
            });
          })
        );
        callback(res.map((item: any) => item.result.url));
      },
    };
    onBeforeMount(() => {
      // 挂载之前
      document.title = '撰写文章';
    });
    onMounted(() => {
      // 挂载之后
    });

    return {
      ...toRefs(state),
      methods,
    };
  },
});
</script>

```

**Comment by hwy2** [comment]
> <template>
>   <md-editor
>     v-model="content"
>     @onHtmlChanged="methods.saveHtml"
>     @onSave="methods.saveValue"
>     @onUploadImg="methods.uploadImg"
>   />
> </template>
> <script l

我好像发现原因了，是不是我在el-form中嵌套了md-editor，点击确定的时候el-form默认认为是提交，但是又没有提交链接，导致的页面刷新

**Comment by imzbf** [comment]
> 我好像发现原因了，是不是我在el-form中嵌套了md-editor，点击确定的时候el-form默认认为是提交，但是又没有提交链接，导致的页面刷新

嗯，选择图片后，上传后默认行为是关闭弹窗，显示编辑内容哈

**Comment by hwy2** [comment]
解决办法：在原码的Link.tsx、Clip.tsx中的<button > 添加 type="button"

**Comment by imzbf** [comment]
> 解决办法：在原码的Link.tsx、Clip.tsx中的 button 添加 type="button"，添加上类型，不影响其他form的提交，希望下一版本能加上

嗯，会在下版本兼容这类问题的，感谢支持~
