### ISSUE TITLE
图片上传的菜单，在触摸屏幕上无效，只有鼠标指针的hover有效

### ISSUE THREAD

**Issue by pengqian089** [imzbf/md-editor-v3#83]
在触摸屏幕上，比如手机、触屏显示器上，不管是touch、click，上传图片的菜单都不会显示。
关于这个能优化一下吗？

![markdown-touch](https://user-images.githubusercontent.com/13491546/164335456-88729444-c07f-4e87-943e-0a108d764941.png)

![markdown-hover](https://user-images.githubusercontent.com/13491546/164335472-fd541df0-4f57-4a67-a66e-57d5e817ad54.png)

提个建议，分屏预览很重要，但是能不能增加一个编辑和预览的切换模式呢？
emmm，不知道怎么表达，就类似github上的write和preview一样。

**Comment by imzbf** [comment]
这边做下移动端的测试。

关于分屏，在之前的issue中有提到，这个编辑器默认就是一边编辑一边预览，相对来讲，比github的这个模式更好。而在编辑的时候提供仅预览，会造成工具栏上的大部分错误，该编辑提供了工具栏扩展，所以不考虑在编辑的时候，不显示编辑框只显示预览内容的情况。

想要这块的功能，我去看了一些以前优秀的编辑器例子，你可以自行扩展一个工具栏项，通过点击这个项，使用弹窗或者其他方式显示一个`previewOnly=true`模式的编辑器，可以实现你的这个需求。这样两个独立的编辑器不会破坏编辑器内部的逻辑。

**Comment by imzbf** [comment]
这边针对`iphone`、`pad`、`android`设备和可触碰的`windows`设备进行测试，发现文档预览页状态栏的下拉框都可以正常触摸显示，请问你是否是这些设备之外的设备？

**Comment by pengqian089** [comment]
> 这边针对`iphone`、`pad`、`android`设备和可触碰的`windows`设备进行测试，发现文档预览页状态栏的下拉框都可以正常触摸显示，请问你是否是这些设备之外的设备？

感谢回复，我在查看了DOM节点之后，发现下拉菜单有出现，只是定位不准确。
因为在很窄的屏幕下，需要左右拖拽移动才能看到完整的工具栏。

![](https://images.dpangzi.com/free/image/626140ad1f1fe2c42da1fdff)



![drop-menu-DOM](https://user-images.githubusercontent.com/13491546/164449852-b685575f-f8e8-42f4-9587-5850eb9e8235.png)

我目前临时的解决办法是：

```javascript
export default{
  data() {
    return {
      toolbars: [
        'bold',
        'underline',
        'italic',
        'image',  // 
        'strikeThrough',
       // todo ..
      ]
    }
  },
}

```

把图片上传的按钮排在工具栏靠前的位置。

![markdown-editor-now](https://user-images.githubusercontent.com/13491546/164450147-d625e3f6-2798-4f72-97e4-0f14bd3044ee.png)

😂，目前在这样用着，还有其它解决方式吗？

**Comment by pengqian089** [comment]
https://images.dpangzi.com/free/image/626140ad1f1fe2c42da1fdff

移动工具栏的动图，github不显示

**Comment by imzbf** [comment]
大致明白了，这个需要重新设计下拉菜单，在完成之前暂时将需要的下拉工具栏放前面吧

**Comment by imzbf** [comment]
试试新版

**Comment by pengqian089** [comment]
> 试试新版

好，我更新一下
