### ISSUE TITLE
1.11.11全屏BUG：Cannot read properties of null (reading 'isEnabled')

### ISSUE THREAD

**Issue by 204065248** [imzbf/md-editor-v3#84]
仍然有报错bug。。。蚌埠住了
![image](https://user-images.githubusercontent.com/17307843/164881207-a28be657-026f-4ddf-8460-4edcd78611e5.png)

**Comment by imzbf** [comment]
看起来是扩展加载太慢了，在操作的时候，js还没加载完造成的，后面优化一下。

**Comment by imzbf** [comment]
在1.11.12以后，扩展网络请求未完成，点击操作不会有反应。如果期望用户体验更佳，最后给编辑器传入本地实例，避免再在生产中再去请求CDN。

在编辑器全屏状态下，不建议使用上传图片以及`f11`退出全屏。主程序无法区分操作对象是哪个编辑器实例。建议使用页面内全屏。
