### ISSUE TITLE
Editor preview ignores custom vuetify theme variables

### ISSUE THREAD

**Issue by hwgn** [imzbf/md-editor-v3#86]
I'm using the Editor both to render Editors as well as the final markdown text, and it seems like the editor has its own styling which clashes with styling set using custom themes:

![image](https://user-images.githubusercontent.com/19843204/166100876-aca13b62-c2c2-4ee4-964d-9d7edca814dc.png)
![image](https://user-images.githubusercontent.com/19843204/166100885-0b19ae37-cdd6-40db-b662-a1eaa849126c.png)

For reference, the themes are defined as such: 
```
import {ThemeDefinition} from "vuetify/dist/vuetify";
 ...
export const darkTheme: ThemeDefinition = {
    dark: true,
    colors: {
        background: '#212121',
        surface: '#282828',
        ...
```

and for the preview window, I'm calling the component like this: 

```
<Editor :theme="theme" previewOnly class="text-left" language="en-US" :modelValue="content"/>
```

Is there some ability to disable the style override in these cases? Or could one pass own CSS arguments to fix this?

**Comment by hwgn** [comment]
Unrelated question, but is there some way to use the code block externally? I'm currently using another package to display code, but it would be nice if I could use yours outside of Markdown text as well.

**Comment by imzbf** [comment]
Preview styles are all defined under the `default-theme`(`github-theme` and `vuepress-theme` ) class. To remove the default style, just change the name of the preview theme(ignore ts error, this will be done at v2.0.0)

**Comment by imzbf** [comment]
> Unrelated question, but is there some way to use the code block externally? I'm currently using another package to display code, but it would be nice if I could use yours outside of Markdown text as well.

There is no way to directly display code blocks, but if a section of content is only composed of code, you may use another editor to display it.

**Comment by hwgn** [comment]
> Preview styles are all defined under the `default-theme`(`github-theme` and `vuepress-theme` ) class. To remove the default style, just change the name of the preview theme(ignore ts error, this will be done at v2.0.0)

How would I go about that? Do I need to change the packages code or can I override it somehow?

**Comment by imzbf** [comment]
> > Preview styles are all defined under the `default-theme`(`github-theme` and `vuepress-theme` ) class. To remove the default style, just change the name of the preview theme(ignore ts error, this will be done at v2.0.0)
> 
> How would I go about that? Do I need to change the packages code or can I override it somehow?

Set `preview-theme="your theme name except for the three above`.

**Comment by hwgn** [comment]
Thank you very much! In the end, I opted for a simple `style="background: none"`, since your default themes based on light/dark are great already.
