### ISSUE TITLE
两个编辑器，会相互影响

### ISSUE THREAD

**Issue by ranran310** [imzbf/md-editor-v3#88]

**Comment by ranran310** [comment]
点击菜单区域两个编辑器，会同时更改

**Comment by imzbf** [comment]
区别了每个编辑器的`editor-id`属性了么？

**Comment by ranran310** [comment]
> 那每个编辑器的`editor-id`属性了么？
多谢，多谢，一致感觉有个属性能控制，可是差不到

**Comment by imzbf** [comment]
> > 那每个编辑器的`editor-id`属性了么？
> > 多谢，多谢，一致感觉有个属性能控制，可是差不到

是的，这个属性非常重要，特别是在同一个页面多个编辑器，和使用内部的目录等组件的时候。
