### ISSUE TITLE
能不能增加vuepress那个主题啊

### ISSUE THREAD

**Issue by heping945** [imzbf/md-editor-v3#9]
rt

**Comment by imzbf** [comment]
建议已收集，将在下一个版本中开发~

**Comment by heping945** [comment]
> 那，能不能再增加個 vuepress主題啊  0.0

**Comment by heping945** [comment]
> 代碼的行號，建議一并解決了 

我覺得這個項目的vue3開發可以的，我找了很久，一個另外的項目說的支持vue3，但是源碼不是用ts寫的，安裝了引入都是報錯0.0

**Comment by hwy2** [comment]
能不能增加图片限制宽高功能，大图片剪裁之后还是占满全部

**Comment by imzbf** [comment]
> 能不能增加图片限制宽高功能，大图片剪裁之后还是占满全部

具体是什么需求，如果是显示图片页面，目前可以将`![]()`语法修改为`<img width="10px" height="10ox" >`来实现，这个行为交给用户手动实现。

**Comment by imzbf** [comment]
主题在v1.4.3中已实现，只包括`markdown`基础样式
