### ISSUE TITLE
显示的宽度再某一范围内才能显示

### ISSUE THREAD

**Issue by hyahm** [imzbf/md-editor-v3#90]
![图片](https://user-images.githubusercontent.com/22030094/167822838-5344b500-1255-44a4-a0be-a92622ae4ada.png)

![图片](https://user-images.githubusercontent.com/22030094/167822870-e334baf5-24f1-4ac8-b050-9eab5a52b007.png)

![图片](https://user-images.githubusercontent.com/22030094/167823546-30f0c3d0-dc26-4704-b1ce-21f8504198c6.png)

**Comment by hyahm** [comment]
算了， 我再编辑器 加 
`style="display: block !important"` 就好了

**Comment by imzbf** [comment]
编辑器没有做`media`相关设置，这个应该是你的项目里的哦
