### ISSUE TITLE
想做 “Preview only ”无法调用到 Catalog

### ISSUE THREAD

**Issue by yarnk** [imzbf/md-editor-v3#91]
谢谢你的开源，请问有没有 vue3 template+setup “Preview only ”写法的例子，我想在浏览的时候展示目录但是，我无法调用到Catalog。

**Comment by imzbf** [comment]
参考一下[这个](https://github.com/imzbf/md-editor-v3/blob/dev-docs-ssg/src/pages/Doc/index.vue)

**Comment by yarnk** [comment]
好的谢谢
