### ISSUE TITLE
依赖的 https://cdn.jsdelivr.net 全部挂了，有什么解决方案

### ISSUE THREAD

**Issue by itshizhan** [imzbf/md-editor-v3#93]
好像 公式和样式了使用 `https://cdn.jsdelivr.net/` 的cdn
最近 **jsdeliver** 全部挂了，可以替换为自身的cdn吗

**Comment by imzbf** [comment]
1.x版本都提供了替换的api的哦，找到对应的设置一下就可以了

**Comment by itshizhan** [comment]
感谢。已经配置好
