### ISSUE TITLE
编辑和预览不是实时同步的

### ISSUE THREAD

**Issue by IUaenaSong** [imzbf/md-editor-v3#94]
一卡一卡的，好难受

**Comment by IUaenaSong** [comment]
能不能加个实时渲染的开关

**Comment by imzbf** [comment]
> 能不能加个实时渲染的开关

如果没输入一个字就渲染一个，内容比较长，你输入的时候会明显感觉到输入框卡顿，延迟渲染就是为了解决这个问题。像掘金等网站的编辑器，都是做了这个优化的，后面的大版本能给延迟的配置，等待一下文档吧

**Comment by imzbf** [comment]
2.x版本支持设置渲染延迟，见文档
