### ISSUE TITLE
cdn无法访问

### ISSUE THREAD

**Issue by baymax-arch** [imzbf/md-editor-v3#95]
cdn.jsdelivr.net 挂了，高亮没了，然后好像会导致ios上出现白屏，具体原因未知，目前只排查出这一个原因

**Comment by imzbf** [comment]
使用[https://unpkg.com](https://unpkg.com)的链接替换一下，1.x所有的扩展都有对应的`api`可替换。2.x版本会多备用一两个cdn站供切换（文档还没写完）。

**Comment by imzbf** [comment]
2.x版本已替换
