### ISSUE TITLE
设置图片大小

### ISSUE THREAD

**Issue by SuperLy1999** [imzbf/md-editor-v3#96]
![image](https://user-images.githubusercontent.com/58931828/169330275-683d1896-64f0-46eb-adf0-5b203808f221.png)
如题，能否支持修改图片大小，我看到有一个编辑器是这样的语法实现的，目前我是每个图片都用 img标签，然后使用 style 来控制样式，图片多的时候太累了...

**Comment by imzbf** [comment]
抱歉，暂时没有考虑支持这样的写法。2.x版本现已完全支持对内部的`marked renderer`、`option`和`extension`进行扩展，你可以考虑编写一个扩展来支持这个功能。扩展语法参考[marked](https://marked.js.org/using_pro#extensions)
