### ISSUE TITLE
css和 js怎么设置使用本地的

### ISSUE THREAD

**Issue by hyahm** [imzbf/md-editor-v3#98]
https://cdn.jsdelivr.net   这个cdn在国内访问经常访问不到

![图片](https://user-images.githubusercontent.com/22030094/169633472-662e1d7f-4800-4624-bc6b-b9e94d892603.png)

**Comment by imzbf** [comment]
1.x有对应的api可以替换，看一下[v1](https://github.com/imzbf/md-editor-v3/tree/v1#props)的文档，2.x已经替换了这些链接

**Comment by hyahm** [comment]
看到了  感谢
